### ISSUE TITLE
an issue with CSS clamp() and calculating units.

### ISSUE THREAD

**Issue by sturobson** [sass/dart-sass#1007]
This issue is taken up from this article – https://adactio.com/journal/16887 – sadly the author doesn't tell us what version or implementation of Sass they are using. 

I have tried this in Sassmeister which runs Dart Sass v1.18.0 - https://www.sassmeister.com/gist/e675fe1769d2ebbb87fc0d692832512e

I have also created a quick CodePen to show it works in plain CSS - 
https://codepen.io/sturobson/pen/4bf3502b785e03a09fa13622a90e5cb4

note: for this to work you'd need. to run the CodePen url in Firefox or Chrome (I've tested on both Nights releases to see the text changes size)

I'm not sure what else I can do to help move this along - let me know if you want me to try anything else

**Comment by sturobson** [comment]
it looks like my Sassmeister link is broken a little and it doesn't seem to want to save a gist for Sass that doesn't compile properly.

The code that doesn't work in Dart Sass v1.18.0 is 
```
:root {
  font-size: clamp(100%, 50% + 0.666vw, 150%);
}
```

**Comment by Awjin** [comment]
This is not a `clamp()` error. It is caused by adding numbers with incompatible units—`50%` and `0.666vw`. The following will work:

```scss
:root {
  font-size: clamp(100%, calc(50% + 0.666vw), 150%);
}
```

**Comment by sturobson** [comment]
As shown in the codepen. It works without the calc. Try it with the calc and the code doesn’t actually effect the text.

**Comment by Awjin** [comment]
> As shown in the codepen. It works without the calc. Try it with the calc and the code doesn’t actually effect the text.

The codepen shows me code written in plain CSS: `font-size: clamp(100%, calc(50% + 0.666vw), 150%)`. The code styles the text properly, both with and without `calc`.

Can you clarify the issue you are having with Sass?

**Comment by sturobson** [comment]
Nah, you're alright. From your initial reply perhaps Jeremy is right – "Do people even use Sass any more?"

**Comment by Awjin** [comment]
My mistake—you are correct here. [Clamp](https://www.w3.org/TR/css-values-4/#funcdef-clamp) supports plain CSS math and has been shipped by major browsers now, so we'll have to modify the Sass language to parse it correctly.

This will need a language proposal. I've submitted an issue https://github.com/sass/sass/issues/2860 to track the progress.
