### ISSUE TITLE
Incorrect / no reference in CONTRIBUTING.md

### ISSUE THREAD

**Issue by albert-github** [sass/dart-sass#1017]
In the file CONTRIBUTING.md we see the output:

>Changing the Node API

>Most of Dart Sass's code is shared between Dart and Node.js, but the API that's exported by the sass npm package is Node-specific. It's defined using Dart's [JS interop package][], and it's tested by compiling the Dart package to JS and loading that JS using JS interop to best simulate the conditions under which it will be used in the real world.

The "strange" part is `[JS interop package][]` on line 164, so I suspect that something is missing here. Most likely it should read `[JS interop package][JS]`

**Comment by Awjin** [comment]
Good eye, thanks.
