### ISSUE TITLE
Support @supports selector()

### ISSUE THREAD

**Issue by brookjordan** [sass/dart-sass#1023]
[The supports selector syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#selector) has been implemented in most modern browsers and it would be great if SASS could support it.

That is:
```css
@supports selector(:focus-visible) {
```

Right now this error is thrown:
```shell
Expected "not".
  ╷
1 │ @supports selector(:focus-visible) {
  │           ^
  ╵
```

### Work around
Right now there is a work-around, (but it feels like it should be natively supported):
```scss
@supports #{"selector(:focus-visible)"} {
```

**Comment by jathak** [comment]
This should be covered by #894 / sass/sass#2780. Follow those issues for the status of support for this in Dart Sass and in Sass as a whole.

**Comment by brookjordan** [comment]
Apologies, I totally missed this while searching.
Thank you for the update!
