### ISSUE TITLE
using @use and @forward

### ISSUE THREAD

**Issue by saltnpixels** [sass/dart-sass#1027]
We are trying to use @use and @forward instead of @import, but is proving to be extremely difficult.

We cannot get forwarding working. Maybe we do not understand how it works. 
There is very little avaiable online on how to use it in a real practical situation.

We have a structures like so:

Base/
_base.scss
_bundle.scss
_variables.scss
_layout.scss
_something.scss
_something-else.scss

Other Styles/
_front-page.scss

main.scss

Everything needs to be compiled into main. We used to @import all files in Base into _base.scss

So inside _base.scss we forwarded all the files in that folder. (bundle, variables...)
Then, in main we used @use _base as *;

This does not work. 

We have not even gotten to the part where we need the variables and one or two other files available inside front-page.

**Comment by saltnpixels** [comment]
Ok.... I think I'm understanding.

The @forward makes it so that when I @use a file, it and any forwards are now available in the _immediate_ file I am in.
I cannot chain forwards from file to file.

**Comment by jathak** [comment]
That's correct. You'd need to add a `@use` makes members from a dependency available in the current file, while `@forward` makes them available in files that *directly* depend on the current file. You can forward members through multiple layers of dependencies, but you'll need to explicitly `@forward` at each layer.
