### ISSUE TITLE
Panic for large number in dart2js

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1031]
For the following input `dart-sass` will raise an exception, but only when compiled through `dart2js`.
```scss
a {
    color: 1e999;
}
```
```
Unexpected exception:
Unsupported operation: Infinity.round()


~/npm/node_modules/sass/sass.dart.js 1166:17   Object.wrapException
~/npm/node_modules/sass/sass.dart.js 21141:15  Interceptor.round$0
~/npm/node_modules/sass/sass.dart.js 3087:43   Object.round$0$n
~/npm/node_modules/sass/sass.dart.js 57368:44  _SerializeVisitor._writeNumber$1
~/npm/node_modules/sass/sass.dart.js 57355:13  _SerializeVisitor.visitNumber$1
~/npm/node_modules/sass/sass.dart.js 46419:22  SassNumber.accept$1$1
~/npm/node_modules/sass/sass.dart.js 46422:19  SassNumber.accept$1
~/npm/node_modules/sass/sass.dart.js 57870:36  _SerializeVisitor_visitCssDeclaration_closure0.call$0
~/npm/node_modules/sass/sass.dart.js 45526:23  NoSourceMapBuffer.forSpan$1$2
~/npm/node_modules/sass/sass.dart.js 45529:19  NoSourceMapBuffer.forSpan$2
```
```
~ >sass --version 
1.26.5 compiled with dart2js 2.7.2
```

**Comment by avinash-dewangan** [comment]
Hi @connorskees ,
I got same error 

I found error in my css 

**scss file**

.current-fund {
            color: 1e407c;;
}

in color property assign value without # tag that is why got error then correct color code propitiates with # Tag

.current-fund {
            color: #1e407c;;
}

successfully compile

I think compiler couldn't understand that code and throw the exception dart.js

**Comment by connorskees** [comment]
@avinash-dewangan without the leading `#`, that value is being recognized as a number using [scientific notation](https://chortle.ccsu.edu/java5/Notes/chap11/ch11_5.html#:~:text=In%20scientific%20notation%2C%20the%20letter,101%20which%20is%2013.14%20.&text=When%20a%20double%20is%20converted,large%20or%20very%20small%20values.) (with a unit of `c`). 

If you wish to have that value emitted literally (and without the `#`), you could make it into an unquoted string,

```scss
.current-fund {
  color: unquote("1e407c");
}
```

which should give you

```scss
.current-fund {
  color: 1e407c;
}
```
