### ISSUE TITLE
package_resolver is now discontinued - sass seems to still depend on it

### ISSUE THREAD

**Issue by daniel-v** [sass/dart-sass#1036]
Please see: https://github.com/dart-archive/package_resolver/issues/30

Not sure what the upgrade path should be about it but I thought I'd drop an issue just to make note of it in case this has skipped the attention of the maintainers. I know it didn't notice it till recently.

**Comment by nex3** [comment]
Since `PackageResolver` is part of Dart Sass's public API, we can't get rid of it until we release a major version.

**Comment by daniel-v** [comment]
Thanks for the info, @nex3 ! If you need some contribution, maybe a wiki on how to move away from `PackageResolver`, I could write some based on my experiences. Can't promise a feature-for-feature migration guide but the most important pieces I can cover.

Also, feel free to close this issue should you not want it to linger, since the intent of the issue has been fulfilled - you obviously know about it :)
