### ISSUE TITLE
variables in css vars not replaced

### ISSUE THREAD

**Issue by mokraemer** [sass/dart-sass#1039]
having the following example:
$test: #777777; :root{ --body: $test; } body{ color: $test; }

$test is not replaced after --body

**Comment by mokraemer** [comment]
someone pointed me to this [section](https://sass-lang.com/documentation/breaking-changes/css-vars)
You should really have an example inside the variables  [section](https://sass-lang.com/documentation/variables)

But still I don't see any explanation why this syntax breaks css:
--accent-color-wrong: $accent-color;

**Comment by jathak** [comment]
CSS custom properties (aka CSS variables) allow almost any string of characters to be used. Even for values that have no meaning in plain CSS, they could still have some arbitrarily-defined meaning when accessed from JavaScript.
