### ISSUE TITLE
Throw warnings when using internal functions without @use?

### ISSUE THREAD

**Issue by dvlden** [sass/dart-sass#1043]
Hello,

I was wondering if I could somehow get errors in the terminal, whenever I use internal Sass functions, such as: `map-get`, etc.

Because I want to stick with the new syntax, such as:

```
@use 'sass:map';

map.get('...');
```

I went through entire Sass CLI docs and I don't see any flag/argument for this, nor was I able to find anything regarding this. Any kind of assistance is appreciated, thanks!

**Comment by nex3** [comment]
We recommend using [stylelint-scss](https://github.com/kristerkari/stylelint-scss#stylelint-scss) for verifying style issues like this. In particular, it has a [no-global-function-names](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/no-global-function-names/README.md) lint that checks for exactly this.
