### ISSUE TITLE
sass command line install not working MacOS 

### ISSUE THREAD

**Issue by rushilrama** [sass/dart-sass#1044]
Hello, when installing the sass command line "npm install -g sass" it comes up with this error. 
<img width="660" alt="Screenshot 2020-07-17 at 14 48 22" src="https://user-images.githubusercontent.com/56439220/87787836-96187680-c83c-11ea-9e99-174d85f3fd11.png">

**Comment by jathak** [comment]
This is an npm error, not anything specific to Sass.

From the looks of it, your Node installation is installing modules to a directory that requires root to write to, so adding `sudo` might help. You could also try reinstalling/reconfiguring node to install global packages to a different directory, or just use a different installer for Sass, like `brew`.

**Comment by rushilrama** [comment]
Thanks, and I am getting a error when running a npm command it says sh: sass./sass/style.scss: no such file or directory

Thank you for your help
