### ISSUE TITLE
Compilation failures with new string_scanner version

### ISSUE THREAD

**Issue by whesse** [sass/dart-sass#1048]
Language changes like "throw" returning the "Never" type are causing compilation failures of dart-sass when upgrading string_scanner.

This should be fixed ASAP.

The following have been reported:
ERROR: third_party/dart/sass/lib/src/parse/parser.dart:447
  Dead code. #dead_code

ERROR: third_party/dart/sass/lib/src/parse/parser.dart:487
  Dead code. #dead_code

ERROR: third_party/dart/sass/lib/src/parse/sass.dart:343
  Dead code. #dead_code

ERROR: third_party/dart/sass/lib/src/parse/selector.dart:265
  Dead code. #dead_code

ERROR: third_party/dart/sass/lib/src/parse/stylesheet.dart:182
  Dead code. #dead_code

ERROR: third_party/dart/sass/lib/src/parse/stylesheet.dart:2147
  Dead code. #dead_code

**Comment by nex3** [comment]
I can't reproduce this:

```shellsession
$ dartanalyzer-2.10.0-1.0.dev lib/
Analyzing lib...
No issues found!
```

What version of Dart produces these errors?

---

Looking at the code, it seems like the errors are triggering on `return null` lines that come after function calls that always throw errors. I believe at some point in the past, those returns were required to avoid missing-return errors. Did those missing-return errors get removed? If so, in which Dart version?

**Comment by whesse** [comment]
This failure was fixed on the Dart end, issue https://github.com/dart-lang/sdk/issues/42797.
I believe this was caused by a mixture of a library enabling null safety and a library not using it, but it is fixed in the analyzer now.
