### ISSUE TITLE
Consistent command-line arguments

### ISSUE THREAD

**Issue by idleberg** [sass/dart-sass#105]
It would be easier to switch between different Sass compilers, if each of them would use the exact same command-line arguments. While `dart-sass` doesn't (yet) offer all of the same features as its brothers, there are already some differences.

For example, in `dart-sass` the shorthand for `--style` is `-s`, while  it's `-t` in both,`sass` and `sassc`. In `dart-sass` the shorthand for `--color` is `-c`, while`-c` is used as the shorthand for `--check` in `sass`.

I understand that there might be no plans to bring all the features of `sass` (or `sassc`) to `dart-sass`, yet I think the advantages of consistent arguments are obvious.

**Comment by xzyfer** [comment]
FWIW this has come up with node-sass and I've generally been against it. There are many LibSass front-ends i.e sassc, perl-sass, python-sass, libsass-net, node-sass, etc...

Trying to standardise the CLI arguments across all these implementations is reasonable IMHO. Adding to this some language ecosystems and/or OSes have their own conventions for CLI flags.

**Comment by nex3** [comment]
After talking to @chriseppstein, I think the plan here is to match the command-line API with Ruby Sass where it's easy to do, but not to promise total compatibility. We'll probably add `-t` as an alias for `--style`, but I think we'll keep `-c` as `--color` since I don't think we intend to support `--check` regardless.

Leaving this open until we figure out which flags we want to correspond and implement them.

**Comment by nex3** [comment]
I think the options we'll match are:

* `-I`/`--load-path`
* `-t` (although we'll also support `-s`)
* `--scss`
* `--stdin` (but not `-s`; we'll also support `-` as an alias for `stdin`)
* `-q`/`--quiet`

**Comment by nex3** [comment]
> `-t` (although we'll also support `-s`)

Dart's arg parser doesn't support multiple short names for the same argument, and I don't think this is a compelling enough reason to add support, so this is no longer planned.

> `--scss`

We probably want the executable to default to SCSS, so this should actually be `--sass`.
