### ISSUE TITLE
JS release errors on Windows

### ISSUE THREAD

**Issue by airda2895** [sass/dart-sass#1052]
So, I'm having this error when I try to watch my styles.scss file:
![image](https://user-images.githubusercontent.com/45570407/89284032-6a73f980-d64e-11ea-9ffc-13e474d16932.png)

I have installed sass with node.js: `npm install -g sass`

In my styles.scss I have a @use, so I can load styles from other .scss files, but unfortunately and apparently, I have a version of Dart which doesn't support this feature.

I have installed Dart from [this website](https://dart.dev/get-dart) and I have tried to upgrade it after the installation was complete, but I get this error each time I try to upgrade it:
![image](https://user-images.githubusercontent.com/45570407/89284589-4c5ac900-d64f-11ea-9f6d-95496cadc501.png)

What should I do in order to be able to use @use in sass?

### Edit: 
Sorry, I'm not able to delete my post, but I've just fixed the issue! Now I can use @use.
Instead of installing sass with `npm install -g sass` as I firstly did, now I've tried with `choco install sass`, because apparently choco also installs the compatible version of Dart:
![image](https://user-images.githubusercontent.com/45570407/89287484-5d5a0900-d654-11ea-9c52-53d8168fd7a9.png)

Then, I've upgraded sass to the latest version with `choco upgrade sass`

I just don't understand why in [https://sass-lang.com/install](https://sass-lang.com/install), the npm command is the first one if then installing Dart is required and has issues with versions. Wouldn't be better to put the choco command as the preferred command as it installs the proper version of Dart?

**Comment by jathak** [comment]
FYI: The version of Sass on Chocolatey is outdated (we aren't currently able to deploy there; we should probably change those instructions).

The NPM version of Sass doesn't require Dart because we compile it to JS for that release. It should have the latest version available, so I'm not sure why it wasn't working for you. What version of Node are you using? It's possible you have an old version of Node that's only compatible with an old version of the Sass package.

We list the NPM install first because that's the easiest method for most web developers to use.

**Comment by airda2895** [comment]
> FYI: The version of Sass on Chocolatey is outdated (we aren't currently able to deploy there; we should probably change those instructions).
> 
> The NPM version of Sass doesn't require Dart because we compile it to JS for that release. It should have the latest version available, so I'm not sure why it wasn't working for you. What version of Node are you using? It's possible you have an old version of Node that's only compatible with an old version of the Sass package.
> 
> We list the NPM install first because that's the easiest method for most web developers to use.

Ok, thanks for letting me know... but firstly, I installed Sass with npm, and I had this error:

![image](https://user-images.githubusercontent.com/45570407/89446529-ec4e4a80-d754-11ea-83cc-bdcd7f7ae9dc.png)

Sorry, it's in Spanish because of my Windows language, but it means:

"dart.exe" is not recognized as an internal or external command, operable program or batch file.

And I had the latest version of Sass:
![image](https://user-images.githubusercontent.com/45570407/89446564-fa9c6680-d754-11ea-9b54-c074a863b24b.png)

So, it does require Dart.

**Comment by jathak** [comment]
That seems like a path misconfiguration where `sass` is not actually pointing to the NPM installation. That error message would only appear when using the batch script in the standalone release if it were separated from its dependencies.

Try `where sass` (I think that's the Windows equivalent of Unix's `which`) to see what Sass executable is actually being used.

An NPM installation would report `1.26.10 compiled with dart2js 2.8.4` (or something similar) when `sass --version` is run.

**Comment by airda2895** [comment]
> That seems like a path misconfiguration where `sass` is not actually pointing to the NPM installation. That error message would only appear when using the batch script in the standalone release if it were separated from its dependencies.
> 
> Try `where sass` (I think that's the Windows equivalent of Unix's `which`) to see what Sass executable is actually being used.
> 
> An NPM installation would report `1.26.10 compiled with dart2js 2.8.4` (or something similar) when `sass --version` is run.

Alright, I have just uninstalled my current sass version with `choco uninstall sass -y --remove-dependencies` and I have installed it again with `npm install -g sass`:

![image](https://user-images.githubusercontent.com/45570407/89449034-c9259a00-d758-11ea-9c6d-bd54826b66f6.png)

Now if I try to run sass commands I get another error:
![image](https://user-images.githubusercontent.com/45570407/89449159-fc682900-d758-11ea-9079-30954e7f5daa.png)

Here's the English translation of the message:
```
Commands sequence:
C:\User\airda\AppData\Roaming\npm\node_modules\sass\sass.js
Line: 1
Character: 1
Error: No valid character
Code: 800A03F6
Origin: Complation error of Microsoft JScript.

```
I've tried to run `where sass` and got this:
![image](https://user-images.githubusercontent.com/45570407/89449508-78fb0780-d759-11ea-9bf1-1623a74cf16c.png)

What should I do?

**Comment by jathak** [comment]
It looks like your path is now correctly pointing to the NPM package, but there's some sort of Node error. What version of Node are you using? Do other Node-based command-line tools work?

**Comment by airda2895** [comment]
I only have Angular CLI as a node-based command and yes, its command `ng` seems to work:
![image](https://user-images.githubusercontent.com/45570407/89450074-4271bc80-d75a-11ea-9c22-bbffd832683d.png)

I'm using Node v12.18.3:
![image](https://user-images.githubusercontent.com/45570407/89450145-5e755e00-d75a-11ea-8ac1-d5ba1c8deac2.png)

**Comment by jathak** [comment]
Hmm. This looks like some issue with our JS release on Windows then. I'll look into it

**Comment by airda2895** [comment]
Ok, thank you. Let me know :)

**Comment by jathak** [comment]
I'm not able to replicate this on my own Windows machine, but it looks like the error is coming from trying to run `sass.js` directly with Microsoft's JS interpreter, rather than through Node. What does `sass.cmd` look like on your machine? I assume you're using the latest version of Windows?

**Comment by airda2895** [comment]
I get this when running `sass.cmd`
![image](https://user-images.githubusercontent.com/45570407/89452590-34be3600-d75e-11ea-949a-437bb68058bf.png)

However, running just `sass` still shows up the same error message.

Yes, I'm using Windows 10 x64 version 18362.959.

**Comment by jathak** [comment]
Okay. I think the issue is with your PATH variable, not with our scripts then. [Follow these instructions](https://katiek2.github.io/path-doc/) to edit your PATH variable and remove `C:\Users\airda\AppData\Roaming\npm\node_modules\sass\` from your PATH (since that's picking up `sass.js` directly before `sass.cmd`)

**Comment by airda2895** [comment]
Ok. That fixed the issue. I can run sass with no problems now. Thanks for all your help!! :)
