### ISSUE TITLE
Add Flatpak support

### ISSUE THREAD

**Issue by Atlas48** [sass/dart-sass#1057]
I'd like to propose this project supports flatpak, as a form of an all-in-one linux package that saves having to configure multiple different distro-specific package managers.

Currently, the process for installing this software is to download a precompiled version and point to it on `$PATH`. I feel there are too many disadvantages to this strategy to justify long-term support of it.

- Has to be redownloaded for every version available.
- People have to *remember* to download each version, which might not always happen.
- People can be careless with modification of `$PATH`, and lead to being unable to access their regular system applications, or induce security holes.

**Comment by Awjin** [comment]
Sass can be installed on Linux via Homebrew, which has the added benefit of being shared infrastructure with MacOS. I've updated the (documentation)[https://github.com/sass/sass-site/pull/467] to reflect that.

**Comment by Atlas48** [comment]
I would prefer not to install an entirely new package manager just for a single package.

**Comment by nex3** [comment]
We use the [`cli-pkg`](https://github.com/google/dart_cli_pkg) for our releases. If you'd like to contribute flatpak support, that would be the place to do it.
