### ISSUE TITLE
How to use import alias

### ISSUE THREAD

**Issue by oknoorap** [sass/dart-sass#1058]
I want to import file in root directory, since my structures are nested, it's looks ugly when I import relative path or absulute path with "../../..", how to define import alias in `package.json`? is there any documentation to it.

note: I'm using CLI version

**Comment by jathak** [comment]
You can use a [load path](https://sass-lang.com/documentation/cli/dart-sass#load-path) for this. When calling Sass from the command line, you can add this with the `--load-path` flag (or `-I` shorthand). When calling Sass via the JS API, you can use the [`includePaths`](https://github.com/sass/node-sass#includepaths) option.
