### ISSUE TITLE
source-map can't be closed

### ISSUE THREAD

**Issue by Lin-study** [sass/dart-sass#1067]
source-map defaults is on
![image](https://user-images.githubusercontent.com/30727128/91827324-40275300-ec71-11ea-8238-abe74a4cab3a.png)

add source-map is error

**Comment by jathak** [comment]
(moved this to the dart-sass repo, since it's specific to this implementation)

`--source-map` is a flag, not an option, so you can disable it with `--no-source-map` instead of `--source-map=none`.
