### ISSUE TITLE
webpack builds using sass-loader are failing on updating to sass@1.26.12

### ISSUE THREAD

**Issue by royson-ct** [sass/dart-sass#1104]
The fix committed in #1096 is causing the webpack builds using sass-loader to fail with the following error:
```
ERROR in ./web/src/shared/themes/bootstrap/bootstrap.scss (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/sass-loader/dist/cjs.js??ref--11-2!./web/src/shared/themes/bootstrap/bootstrap.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: Instance of 'SassColor0': type 'SassColor0' is not a subtype of type 'SassString0'
 @ ./web/src/shared/themes/bootstrap/bootstrap.scss 4:14-168
```

The bootstrap.scss has the following code:
```scss
@import '~bootstrap-vue/dist/bootstrap-vue';
@import '~bootstrap/dist/css/bootstrap';
@import '../../css/bootstrap-overrides';
@import "../globals/globals";
```

On reverting to sass@1.26.11 the webpack build is working fine.

Any insights on what could be the issue here would be of great help. Thanks :)

**Comment by nex3** [comment]
This is unlikely to be caused by #1096, since that doesn't touch anything related to SassScript values. More likely it's caused by a change in the JS output between Dart 2.9 and 2.10.

It's difficult to tell what's triggering this without a simpler reproduction. Can you provide me an example repository that fails and *doesn't* depend on Bootstrap? Even better would be one that doesn't depend on Webpack either.

**Comment by XhmikosR** [comment]
Note that we test Sass upstream on CI and there's no error https://github.com/twbs/bootstrap/runs/1214705073. We also plan to switch to Sass for v5 https://github.com/twbs/bootstrap/pull/31728

**Comment by royson-ct** [comment]
@nex3 Here is the simple reproduction repository of the issue: https://github.com/royson-ct/scss-playground

The above error occurs when I use `bootstrap/dist/css/bootstrap`. Replacing this import with `bootstrap/scss/bootstrap` works fine.

Also I tried building dart-sass master with Dart version 2.9.3 and still face the above issue.

Here is the error output on running `npm run sass`:
```
> scss-playground@1.0.0 sass /Users/royson/github/scss-playground
> sass --no-source-map --load-path=node_modules index.scss index.css

Unexpected exception:
TypeError: Instance of 'SassColor': type 'SassColor' is not a subtype of type 'SassString'


node_modules/sass/sass.dart.js 1194:17   Object.wrapException
node_modules/sass/sass.dart.js 2495:15   Object._failedAsCheck
node_modules/sass/sass.dart.js 2492:9    Rti._generalNullableAsCheckImplementation
node_modules/sass/sass.dart.js 2446:22   Rti._installSpecializedAsCheck
node_modules/sass/sass.dart.js 58043:41  _SerializeVisitor0._writeReindentedValue$1
node_modules/sass/sass.dart.js 58788:12  _SerializeVisitor_visitCssDeclaration_closure.call$0
node_modules/sass/sass.dart.js 46463:23  NoSourceMapBuffer0.forSpan$1$2
node_modules/sass/sass.dart.js 46466:19  NoSourceMapBuffer0.forSpan$2
node_modules/sass/sass.dart.js 58003:12  _SerializeVisitor0.visitCssDeclaration$1
node_modules/sass/sass.dart.js 32279:22  ModifiableCssDeclaration.accept$1$1
```

FYI, @XhmikosR

**Comment by nex3** [comment]
You're right, it looks like this was caused by #1096 after all...

**Comment by Awjin** [comment]
Here is a good minimal repro: https://github.com/sass/dart-sass/issues/1107
