### ISSUE TITLE
1.26.12: Compiling  a css file to minified css file runs into errors when using sass vars in css custom properties

### ISSUE THREAD

**Issue by mirelvt** [sass/dart-sass#1107]
Example:
`$accent-color: #fbbc04;`
`$grid: 40px;`

`:root {`
`    --accent-color-right: #{$accent-color};`
`    --grid: #{$grid};`
`}`

`body { color: var(--accent-color-right);  }`
`section { width: var(--grid); }`

- Compiling base.scss > base.css (uncompressed): no issues
- Compiling base.scss > base.min.css (compressed): no issues
- Compiling base.css > base.min.css: sass errors

In case of $grid variable you get the TypeError:
`TypeError: Instance of 'SassNumber': type 'SassNumber' is not a subtype of type 'SassString'`

In case of the $accent-color you get the TypeError:
`TypeError: Instance of 'SassColor': type 'SassColor' is not a subtype of type 'SassString'`

The interesting part is that if you set e.g. $accent-color: blue, this variable will be compilated correctly.

Dart-sass 1.26.11 has no issues.

**Comment by Awjin** [comment]
Thanks for reporting this, this is actively being investigated here: https://github.com/sass/dart-sass/issues/1104.
