### ISSUE TITLE
Any recommendations for troubleshooting poor performance

### ISSUE THREAD

**Issue by ronnyek** [sass/dart-sass#1109]
Ok, so I know the `sass` npm package is the dart2js version of dart-sass, but rather than continuing to complain about performance there, I was curious if there were ways to set super details verbosity or anything so I can identify whether I'm running into other issues.

I believe when sass-loader switched to defaulting to dart-sass, the sass compile step went from like 1-2 seconds to 2+ minutes. Rather than assume all of that is because of dart runtime etc... I want to see if there are problems with my scss files.

I was initially concerned that I had circular references or something, but dont get any warnings. I believe there is a verbosity flag, but for me that just gave me more information when a file include failed.

I am really open to any other ideas. I tried to run some older node apps that attempt to detect scss "graphs", but they seem to be older and somewhat unsupported, and don't complete against my scss files. That being said, these scss files do ultimately end up compiling and rendering exactly as I expect.

**Comment by nex3** [comment]
That's a *much larger* compilation time increase than expected. In [our benchmarks](https://github.com/sass/dart-sass/blob/master/perf.md) the JS version ranges from 2x-5x slower than LibSass and the Dart VM, not 60x. If you want to dig into this yourself, the best way is either to use a [Node profiler](https://nodejs.org/en/docs/guides/simple-profiling/) to figure out where time is being spent or to bisect your Sass stylesheets to try to figure out what's triggering such a dramatic performance hit.

If you're able to share your stylesheets, I could also take a look and try to figure out what's going wrong.

**Comment by steveetm** [comment]
I've even worse experience. I am trying to upgrade our whole dev env including webpack, loaders, everything. Also want to try to adopt yarn pnp and moved to dart-sass for this very reason.
With node@10 I see oom issues after 10 minutes of compile time with node@14 the longest I left it run was 45 minutes.
Thats only the css, in the past with webpack@3 and sass-loader our _whole_ project compiled in 2 minutes worst case, scss was around 10 seconds.

Profile of 5 minutes of runtime attached, memory around 700 megs, increase is 2MB/s but that speed is decreasing.
I am pretty sure we have some braindead legacy extends lurking somewhere in the code, but this is just not normal.
I can't compile that scss directly with dart-sass as there is a lot of ~imports in it, but I highly doubt it is a sass-loader or webpack issue.

![Képernyőfotó 2020-10-15 - 21 20 46](https://user-images.githubusercontent.com/11589541/96176302-74f31f00-0f2c-11eb-8581-92c08f429154.png)

**Comment by nex3** [comment]
It's good to know that your issues are coming from `@extend` code, but it'll be hard to fix without knowing exactly which extends are taking so long. Again, if you're able to share your stylesheets, that's the best way to get this figured out.

**Comment by steveetm** [comment]
Yea, struggled to narrow down the issue since last night, but now figured out what is happening, here is a bare minimal repro which kills dart-sass:
```
.root {
  a {
    .child1{
      color: red;
    }
  }

  a.type1,a.type2 {
    @extend a, .child1;
  }
  a.type3,a.type4 {
    @extend a, .child1;
  }
  a.type5,a.type6 {
    @extend a, .child1;
  }
}
```

It slows down exponentially as you add more and more extends, it is fine you have one of this,  even the generated css matches with the output of node-sass.
But if you add the second one(`a.type3, a.type4`), something breaks:
```
.root a .child1, .root a a.type3, .root a a.type4, .root a.type3 .child1, .root a.type3 a.type3, .root a.type3 a.type4, .root a.type4 .child1, .root a.type4 a.type3, .root a.type4 a.type4, .root a.type1.type3 .child1, .root a.type1.type3 a.type3, .root a.type1.type3 a.type4, .root a.type1.type4 .child1, .root a.type1.type4 a.type3, .root a.type1.type4 a.type4, .root a.type2.type3 .child1, .root a.type2.type3 a.type3, .root a.type2.type3 a.type4, .root a.type2.type4 .child1, .root a.type2.type4 a.type3, .root a.type2.type4 a.type4, .root a.type3.type4 .child1, .root a.type3.type4 a.type3, .root a.type3.type4 a.type4, .root a.type4.type3 .child1, .root a.type4.type3 a.type3, .root a.type4.type3 a.type4, .root a a.type1, .root a.type3 a.type1, .root a.type4 a.type1, .root a.type1.type3 a.type1, .root a.type1.type4 a.type1, .root a.type2.type3 a.type1, .root a.type2.type4 a.type1, .root a.type3.type4 a.type1, .root a.type4.type3 a.type1, .root a a.type1.type3, .root a.type3 a.type1.type3, .root a.type4 a.type1.type3, .root a.type1.type3 a.type1.type3, .root a.type1.type4 a.type1.type3, .root a.type2.type3 a.type1.type3, .root a.type2.type4 a.type1.type3, .root a.type3.type4 a.type1.type3, .root a.type4.type3 a.type1.type3, .root a a.type1.type4, .root a.type3 a.type1.type4, .root a.type4 a.type1.type4, .root a.type1.type3 a.type1.type4, .root a.type1.type4 a.type1.type4, .root a.type2.type3 a.type1.type4, .root a.type2.type4 a.type1.type4, .root a.type3.type4 a.type1.type4, .root a.type4.type3 a.type1.type4, .root a a.type1.type3, .root a.type3 a.type1.type3, .root a.type4 a.type1.type3, .root a.type1.type3 a.type1.type3, .root a.type1.type4 a.type1.type3, .root a.type2.type3 a.type1.type3, .root a.type2.type4 a.type1.type3, .root a.type3.type4 a.type1.type3, .root a.type4.type3 a.type1.type3, .root a a.type1.type4, .root a.type3 a.type1.type4, .root a.type4 a.type1.type4, .root a.type1.type3 a.type1.type4, .root a.type1.type4 a.type1.type4, .root a.type2.type3 a.type1.type4, .root a.type2.type4 a.type1.type4, .root a.type3.type4 a.type1.type4, .root a.type4.type3 a.type1.type4, .root a a.type1.type2.type3, .root a.type3 a.type1.type2.type3, .root a.type4 a.type1.type2.type3, .root a.type1.type3 a.type1.type2.type3, .root a.type1.type4 a.type1.type2.type3, .root a.type2.type3 a.type1.type2.type3, .root a.type2.type4 a.type1.type2.type3, .root a.type3.type4 a.type1.type2.type3, .root a.type4.type3 a.type1.type2.type3, .root a a.type1.type2.type4, .root a.type3 a.type1.type2.type4, .root a.type4 a.type1.type2.type4, .root a.type1.type3 a.type1.type2.type4, .root a.type1.type4 a.type1.type2.type4, .root a.type2.type3 a.type1.type2.type4, .root a.type2.type4 a.type1.type2.type4, .root a.type3.type4 a.type1.type2.type4, .root a.type4.type3 a.type1.type2.type4, .root a a.type1.type3.type4, .root a.type3 a.type1.type3.type4, .root a.type4 a.type1.type3.type4, .root a.type1.type3 a.type1.type3.type4, .root a.type1.type4 a.type1.type3.type4, .root a.type2.type3 a.type1.type3.type4, .root a.type2.type4 a.type1.type3.type4, .root a.type3.type4 a.type1.type3.type4, .root a.type4.type3 a.type1.type3.type4, .root a a.type1.type4.type3, .root a.type3 a.type1.type4.type3, .root a.type4 a.type1.type4.type3, .root a.type1.type3 a.type1.type4.type3, .root a.type1.type4 a.type1.type4.type3, .root a.type2.type3 a.type1.type4.type3, .root a.type2.type4 a.type1.type4.type3, .root a.type3.type4 a.type1.type4.type3, .root a.type4.type3 a.type1.type4.type3, .root a a.type2, .root a.type3 a.type2, .root a.type4 a.type2, .root a.type1.type3 a.type2, .root a.type1.type4 a.type2, .root a.type2.type3 a.type2, .root a.type2.type4 a.type2, .root a.type3.type4 a.type2, .root a.type4.type3 a.type2, .root a a.type2.type3, .root a.type3 a.type2.type3, .root a.type4 a.type2.type3, .root a.type1.type3 a.type2.type3, .root a.type1.type4 a.type2.type3, .root a.type2.type3 a.type2.type3, .root a.type2.type4 a.type2.type3, .root a.type3.type4 a.type2.type3, .root a.type4.type3 a.type2.type3, .root a a.type2.type4, .root a.type3 a.type2.type4, .root a.type4 a.type2.type4, .root a.type1.type3 a.type2.type4, .root a.type1.type4 a.type2.type4, .root a.type2.type3 a.type2.type4, .root a.type2.type4 a.type2.type4, .root a.type3.type4 a.type2.type4, .root a.type4.type3 a.type2.type4, .root a a.type2.type1.type3, .root a.type3 a.type2.type1.type3, .root a.type4 a.type2.type1.type3, .root a.type1.type3 a.type2.type1.type3, .root a.type1.type4 a.type2.type1.type3, .root a.type2.type3 a.type2.type1.type3, .root a.type2.type4 a.type2.type1.type3, .root a.type3.type4 a.type2.type1.type3, .root a.type4.type3 a.type2.type1.type3, .root a a.type2.type1.type4, .root a.type3 a.type2.type1.type4, .root a.type4 a.type2.type1.type4, .root a.type1.type3 a.type2.type1.type4, .root a.type1.type4 a.type2.type1.type4, .root a.type2.type3 a.type2.type1.type4, .root a.type2.type4 a.type2.type1.type4, .root a.type3.type4 a.type2.type1.type4, .root a.type4.type3 a.type2.type1.type4, .root a a.type2.type3, .root a.type3 a.type2.type3, .root a.type4 a.type2.type3, .root a.type1.type3 a.type2.type3, .root a.type1.type4 a.type2.type3, .root a.type2.type3 a.type2.type3, .root a.type2.type4 a.type2.type3, .root a.type3.type4 a.type2.type3, .root a.type4.type3 a.type2.type3, .root a a.type2.type4, .root a.type3 a.type2.type4, .root a.type4 a.type2.type4, .root a.type1.type3 a.type2.type4, .root a.type1.type4 a.type2.type4, .root a.type2.type3 a.type2.type4, .root a.type2.type4 a.type2.type4, .root a.type3.type4 a.type2.type4, .root a.type4.type3 a.type2.type4, .root a a.type2.type3.type4, .root a.type3 a.type2.type3.type4, .root a.type4 a.type2.type3.type4, .root a.type1.type3 a.type2.type3.type4, .root a.type1.type4 a.type2.type3.type4, .root a.type2.type3 a.type2.type3.type4, .root a.type2.type4 a.type2.type3.type4, .root a.type3.type4 a.type2.type3.type4, .root a.type4.type3 a.type2.type3.type4, .root a a.type2.type4.type3, .root a.type3 a.type2.type4.type3, .root a.type4 a.type2.type4.type3, .root a.type1.type3 a.type2.type4.type3, .root a.type1.type4 a.type2.type4.type3, .root a.type2.type3 a.type2.type4.type3, .root a.type2.type4 a.type2.type4.type3, .root a.type3.type4 a.type2.type4.type3, .root a.type4.type3 a.type2.type4.type3 {
  color: red;
}
```
vs node-sass
```
.root a .child1, .root a a.type1, .root a a.type2, .root a a.type3, .root a a.type4 {
  color: red; }
```

`
node_modules/sass/sass.js  --version
1.27.0 compiled with dart2js 2.10.1
`

**Comment by ronnyek** [comment]
I just realized I have a hand full of places we're doing @extend as well, and its really quite simple stuff, not extending styles that were extended from anything else or anything.

I'm going to try removing these @extends, or exclude those styles from the build all together and see if it helps improve speed at all.

**Comment by nex3** [comment]
@steveetm That's *definitely* a bug. I'll look into fixing it today. It looks like this is about as small of a reproduction as possible:

```scss
a .child1 {
  color: red;
}

a.type1, a.type2 {
  @extend a, .child1;
}
a.type3, a.type4 {
  @extend a, .child1;
}
```

It's definitely something about Dart Sass's "as-needed" `@extend` resolution, because it doesn't reproduce with either

```scss
a .child1 {
  color: red;
}

a.type1, a.type2, a.type3, a.type4 {
  @extend a, .child1;
}
```

or

```scss
a.type1, a.type2 {
  @extend a, .child1;
}
a.type3, a.type4 {
  @extend a, .child1;
}

a .child1 {
  color: red;
}
```

even though they should be semantically identical.

---

@ronnyek If you can figure out whether `@extend`s are causing problems, and if so which ones (like @ronnyek did), that would be very helpful.

**Comment by nex3** [comment]
@steveetm It's worth noting that you're pushing Sass pretty hard here. You're asking it to consider all possible combinations of `.type1` through `.type6` on both the parent selector and the child selector—that's an inherently exponential operation, and if you push it far enough you're going to see performance creater at some point in any implementation (for example, in LibSass it starts taking multiple seconds once you get to `.type11, .type12`; adding `.type13, .type14` makes it take long enough that I gave up after five minutes). We can probably tweak some parameters so that Dart Sass doesn't exhibit as bad of exponential behavior as early as it is here, but the underlying issue is that the structure of `@extend`s you're demonstrating is difficult to process in general.

**Comment by steveetm** [comment]
@nex3 Don't get me wrong, I know this kind of ruleset is pia, I don't even want the compiler to be super fast even in this case. I am even sure it was only a mistake from us to use rules in this way, but the compiler should tell me that I am doing something really nasty, e.g. in some pre-parse phase limit selector complexity and issue a warning, pointing out the potentially problematic rules( and I know compilers are a different kind of animal, easier to say this than do it)

This one almost forced us to stay on libsass, as the legacy scss code base is not so simple, it was a nightmare to figure out the actual rule:/

Anyway, thanks for fixing this:)

**Comment by nex3** [comment]
I think this is about as good as we're going to get for now.
