### ISSUE TITLE
Find a representative suite of stylesheets

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#111]
Right now, we do our benchmarking and application snapshot training on artificial files full of many repeated style rules that are individually very simple. These are useful for measuring a few aspects of performance, but they aren't representative of the performance characteristics of real-world Sass. We need to find a collection of stylesheets, ideally those pulled from real apps, that we can use instead or in addition.

**Comment by xzyfer** [comment]
Bootstrap and foundation are a good starting point

**Comment by nex3** [comment]
Bootstrap is very quick to compile even on Ruby Sass, so I don't know if it's going to provide a useful benchmark. Is Foundation substantially larger?

**Comment by xzyfer** [comment]
Not substantially. I test bootstrap, foundation, sassdash, and eyeglass with LibSass however I'm specifically looking for regressions.

I don't think extends heavy benchmarks are representative of most (recent) production code given the anti-extends sentiment in recent years. 

Judging by blog post in recent years, and my personal experiences, something with a lots of map lookups for config and mixins is probably representative of modern Sass. This is also pattern foundation follows.

**Comment by nex3** [comment]
[This test file](https://github.com/alex-page/sass-a11ycolor/blob/5c719eb75e7c2462e40c90a0e9b3cd9b6518761d/test/test1.scss) uses a real-world library takes close to a second when running Dart Sass from an app snapshot, and around 10s on JavaScript. It would be good to use for benchmarking.

**Comment by nex3** [comment]
I've added Bootstrap, Susy, and a11ycolor to the benchmark suite so I think we can close this out. More real-world benchmarks would always be welcome, of course!
