### ISSUE TITLE
@charset not lifted to the top of file

### ISSUE THREAD

**Issue by SLKnutson** [sass/dart-sass#1119]
Hi,
I'm using dart-sass via angular 10 cli. We have a few instances of things like `content: '\f00c'`, which are automatically converted to the actual unicode character and `@charset` is added within the css file. We also have a couple `@import url(...`s within our code. For some reason, those imports are being placed above the `@charset`, causing the charset to not work (it has to be the first thing in the file). The top of our file ends up looking something like:
```
@import url(https://fonts.googleapis.com/css?family=Raleway:400,500,600,700);
@import url(https://fonts.googleapis.com/css?family=Material+Icons);

@charset "UTF-8";

...rest of the css
```
Thanks!

**Comment by Awjin** [comment]
For which version of `dart-sass` are you experiencing this error? I'm unable to replicate with `1.26.11`.

**Comment by SLKnutson** [comment]
I'm using 1.26.10.

**Comment by Awjin** [comment]
Thanks for checking. It looks like this is not a language bug (I'm unable to reproduce on `1.26.10`). My hunch is that Angular is treating your url imports separately from the rest of the css, placing them above the `charset` declaration. I would recommend filing a bug with [Angular](https://github.com/angular/angular-cli).

**Comment by SLKnutson** [comment]
@Awjin Thanks! I did a little debugging, and the css looks good coming out of dart-sass. For perpetuity, here is the link to the angular ticket: https://github.com/angular/angular-cli/issues/19246
