### ISSUE TITLE
Switching from node-sass caused something to break with jest

### ISSUE THREAD

**Issue by yarhamjohn** [sass/dart-sass#1131]
I upgraded from `node-sass: 4.14.1` to `sass: 1.28.0` via my `package.json` file as per the guidance here: https://sass-lang.com/blog/libsass-is-deprecated, and found that while my app appeared to still work, my test suite which uses `jest: 26.6.2` broke with the following error:

![image](https://user-images.githubusercontent.com/7828988/97966808-3a0a3b80-1db4-11eb-81fa-54671adfb2ee.png)

I changed nothing other than the dep reference in my `package.json` file - I can't find anything to suggest that jest doesn't work with dart-sass but maybe I missed something else I need to upgrade?

**Comment by stof** [comment]
Looking at the error, it seems like `request-promise-native` tries to use the `request` package and this package is not installed.
`node-sass` depends on `request` through its usage of `node-gyp` while `sass` does not have such dependency.

To me, this indicate that a package unrelated to sass has broken metadata about its dependencies, and that your project worked by luck thanks to the way npm hoists packages (and so allows packages to use dependencies of other packages in most cases)

**Comment by stof** [comment]
Looking at its readme, `request-promise-native` defines `request` as a peer dependency. running `npm install` or `yarn` was probably showing a warning about an unmet peer dependency.

**Comment by yarhamjohn** [comment]
> Looking at its readme, `request-promise-native` defines `request` as a peer dependency. running `npm install` or `yarn` was probably showing a warning about an unmet peer dependency.

You are entirely correct - thank you its working now :)
