### ISSUE TITLE
Improper handling of Node.js importers that use custom URL schemes

### ISSUE THREAD

**Issue by sebakerckhof** [sass/dart-sass#1138]
In https://github.com/sass/dart-sass/issues/1100 it was suggested that our custom importer uses URL's like:
```
@import 'meteor:somepackage/somefile'
```

This works to some extend (at least since sass `1.26.0` and higher), but only if we can successfully resolve and return the contents.
However, in the case where either an error is thrown, or the contents does not exist (and thus we return null), then dart-sass expects the url to have a file scheme. And dart-sass would throw something like:

```
Invalid argument(s): Uri meteor:somepackage/somefile must have scheme 'file:'
```

**Comment by jathak** [comment]
I'm a bit confused by what you're asking for here.

What would you expect Sass to do in this situation? It doesn't have any concept of `meteor:` URLs; it's the custom importer's job to handle those, so if it doesn't, Sass can't find the file in question, so it throws an error. Is it just about what the error message should say?

**Comment by sebakerckhof** [comment]
Ok, I see how I could have worded this better.

Of course, I don't expect sass to know how to handle `meteor:` urls.
However, if I read the documentation here: https://sass-lang.com/documentation/js-api#importer , it only mentions another importer is going to be tried when an importer returns null (meaning import not found)

So in the case when an importer throws an error, I would expect to see that error message appear. And this works sometimes, like here:
https://gist.github.com/sebakerckhof/4f42ff22554439934f631a2b3a4f3d12

But if an error is thrown deeper down the tree, it gives me the error about the file scheme, e.g.:
https://gist.github.com/sebakerckhof/05bc122d4c97e2da9571e605ad54cbb1

And the behavior when I return null is similar. E.g. here I would get a file not found error:
https://gist.github.com/sebakerckhof/1d295b78301534a1ed96b39d32faf1c9
But here I would get a file scheme error:
https://gist.github.com/sebakerckhof/2cd3644668b5802f8cedffcd7ad48701

**Comment by jathak** [comment]
Okay, I see. This is definitely a bug then. We'll take a look.

**Comment by nex3** [comment]
To be clear: are you using the Node.js importer API, or the Dart importer API?

**Comment by jathak** [comment]
I checked and confirmed that this only occurs with the Node API (updated the title to match)

**Comment by nex3** [comment]
Sorry to take so long to circle back to this! I'm working on it now.

**Comment by hosseinghs** [comment]
How can I fix this problem?
