### ISSUE TITLE
Add information on how to use the new package in a dart project

### ISSUE THREAD

**Issue by enyo** [sass/dart-sass#114]
I understand that this is still in alpha, so this might be a bit premature, but since there is no transformer anymore, I wonder how this is supposed to be used within a dart project. Is this already assuming that Bazel will be used in the future to build projects? Or is it planned that the transformer would be able to use the dart sass package?

**Comment by zoechi** [comment]
https://github.com/sass/dart-sass/pull/53 was missing (just landed). I guess Luis will provide a transformer soon. 
Angular doesn't work with Bazel yet, therefore a transformer is currently the only way.

**Comment by enyo** [comment]
Great news! This will speed up our continuous integration since we don't need to install ruby and sass separately anymore.

**Comment by zoechi** [comment]
And no `--packages-dir`

**Comment by nex3** [comment]
Transformers and Bazel are outside the scope of this package. The primary goal of Dart Sass is to provide a Sass implementation for the world at large; Dart-specific concerns would be great for the community to address.
