### ISSUE TITLE
Create a -w shorthand for --watch

### ISSUE THREAD

**Issue by vinliao** [sass/dart-sass#1145]
Hi people.

Having a `-w` flag to watch seems like a minor nice-to-have thing in this package.

What do you think?

**Comment by zaydek** [comment]
I saw somewhere previously that this wasn’t planned to be added. I could be wrong. In any matter I do this and it works well enough for me:

```
yarn add --dev watch
yarn watch --interval 0.1 'yarn sass ...' src
```

So when there’s a change inside of `src`, `watch` fires the stringified command.

**Comment by jathak** [comment]
@zaydek: Dart Sass already supports a `--watch` flag. This issue is just for adding a `-w` flag as a shorthand for the existing one.

**Comment by zaydek** [comment]
Oh my bad! I must have misunderstood. Thanks @jathak for clarifying. ☺️

**Comment by stof** [comment]
@nex3 this issue should be closed as it has been implemented in https://github.com/sass/dart-sass/pull/1276

**Comment by nex3** [comment]
Thanks!
