### ISSUE TITLE
[Question] JavaScript API using Dart

### ISSUE THREAD

**Issue by romulof** [sass/dart-sass#1151]
I'm researching a replacement of `node-sass` for a huge project, where build performance matters.

Is there a way to use the native Dart version with JavaScript bindings?

**Comment by Awjin** [comment]
Good question—this is one of our priorities right now. The [Embedded Host ](https://github.com/sass/embedded-host-node) will provide Node bindings to native Dart Sass. You can track the progress here: https://github.com/sass/embedded-host-node/issues/13. The current plan is to release a minimal `render` function as an alpha, then iterate to full functionality.

If you could share information about your use case and how you currently use `node-sass`, I might be able to offer guidance on using the Embedded Host when it's available.

**Comment by zaaack** [comment]
@Awjin Thanks for your work! We hit same problem,too. Currently we have a big project using node-sass with sass-loader in webpack,  it would be really help to support sass-loader.

**Comment by nex3** [comment]
The embedded host [has now launched](https://sass-lang.com/blog/embedded-sass-is-live)!
