### ISSUE TITLE
Request: set default of Node API `includePaths` option to `require.resolve.paths(``)`

### ISSUE THREAD

**Issue by lunelson** [sass/dart-sass#1156]
I don't know how to write this in Dart, but I recently found out that you can retrieve the entire hierarchy of `node_modules` search paths from any given directory, with the expression `require.resolve.paths('')`. I believe this should be the default for this option in the Node API, since resolving a node module is almost always what is desired with this option.

Example just now, from my home directory:

```sh
node

Welcome to Node.js v12.16.1.
Type ".help" for more information.

> require.resolve.paths('')

[
  '/Users/lunelson/repl/node_modules',
  '/Users/lunelson/node_modules',
  '/Users/node_modules',
  '/node_modules',
  '/Users/lunelson/.node_modules',
  '/Users/lunelson/.node_libraries',
  '/Users/lunelson/.nvm/versions/node/v12.16.1/lib/node',
  '/Users/lunelson/.node_modules',
  '/Users/lunelson/.node_libraries',
  '/Users/lunelson/.nvm/versions/node/v12.16.1/lib/node'
]
```

Dart line is here AFAICT:
https://github.com/sass/dart-sass/blob/e51ec0455a3df5e074f31026eb4523a6f0279820/lib/src/node.dart#L253

**Comment by nex3** [comment]
Would https://github.com/sass/sass/issues/2739 work for this?

**Comment by lunelson** [comment]
Oh nice. Yeah I think the `@import "pkg:..."` syntax makes a lot of sense in the current general Sass 4 syntax, but it sounds like the implication of that change would be the elimination of the `includePaths` option ultimately, in favour of an implicit behaviour...which will probably take some time until various other tools update their own wrappers I guess?

So maybe my suggestion here is rather an interim one. It just seemed to me that in the many different node tooling contexts that I've used sass in the last few years, whether `node-sass` or `dart-sass` this option was always one that required some case-specific hard-coded values until I discovered a way to make node spit out the list of `node_module` search paths, which was finally a general solution

**Comment by nex3** [comment]
We don't have plans to remove `includePaths`, even with package imports.

I'd like avoid interim solutions here, because they impose a cost to users to migrate onto them *and* away from them. I'm hoping to have time to spec out package imports in the first half of next year.
