### ISSUE TITLE
TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by GunterJameda** [sass/dart-sass#1157]
Hi!

I'm trying to use this module to compile some scss in my React project with Typescript. I installed the module, imported it and got the error in the title. What could it be? Some type of imports I tried:

```
import { renderSync } from 'sass';
import sass from 'sass';
const sass = require('sass');
```

Everything throws that error.

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
