### ISSUE TITLE
Interpolation not compiling correctly

### ISSUE THREAD

**Issue by kaleidografik** [sass/dart-sass#1159]
Using Dart to compile and process SCSS, as recently it was recommended to upgrade from Liblass to Dart, for future proofing.

This seems to be an easy switchover, however I do have one snippet of code that is throwing an error during compilation. I wonder if anyone might be able to assist with? The error is: Dart Sass failed with this error: Error: expected "$".

The code in question is intended to iterate over a number of nth-child() elements and incrementally apply a transition-delay to them, increasing by 150ms per item.

```
@for $i from 1 to 50 {
  &:nth-child($i) { transition-delay: calc($i * 150ms); }
}
```

It seems this is an issue with interpolation, however the following does not compile correctly, although it will process without errors:

```
@for $i from 1 to 50 {
  &:nth-child(#{$i}) { transition-delay: calc($i * 150ms); }
}
```

This outputs as:

`:nth-child(#{1})` rather than `:nth-child(1)`

Thank you.

**Comment by Awjin** [comment]
Interpolating is the correct way to achieve this. Could you share a bit of the surrounding code? (What is the `&` in ` &:nth-child(#{$i})` selecting?)

**Comment by zaydek** [comment]
This works for me on Sassmeister:

```sass
@for $i from 1 to 50 {
    #{&}:nth-child(#{$i}) {
        transition-delay: $i * 150ms;
    }
}
```

```
:nth-child(1) {
  transition-delay: 150ms;
}

:nth-child(2) {
  transition-delay: 300ms;
}

:nth-child(3) {
  transition-delay: 450ms;
}

...
```

Also, Sass is smart enough to understand milliseconds — so you can let Sass multiply `ms` for you so you don’t need to use `calc` during runtime.

@Awjin I assume — concerning what is the ampersand selecting — the OP was copying their snippet from their code base.

@kaleidografik Does the above work for you?

**Comment by kaleidografik** [comment]
Hi @zaydek @Awjin - thanks for following up on this.

@zaydek - I have the same results on Sassmeister, so I think unfortunately the issue is elsewhere in my build process perhaps. Also, yes, nothing to worry about with the `&:`

The following SASS:

```
@for $i from 1 to 50 {
    &:nth-child(#{$i}) {
      transition-delay: $i * 150ms;
		}
	}
```

Outputs as:

```
:nth-child(#{4}) {
    transition-delay: 4 * 150ms;
  }
```

My postcss.config.js file is as follows:

```
module.exports = {
  parser: 'postcss-scss',
	plugins: [
		require('postcss-import'),
		require('postcss-for'),// Must come before tailwindcss
		require('tailwindcss'),
                 require('postcss-nested'), // Must come after tailwindcss
  ]
}
```

Any suggestions of what to explore next?

**Comment by zaydek** [comment]
Oh. I may see the problem. So you’re trying to use PostCSS which in theory _implements_ Sass / Dart Sass APIs with some edge-case differences. I think you want to either stick strictly to Dart Sass or PostCSS logic and not try to mix-and-match them because I suspect they don’t implement identical APIs.

**Comment by kaleidografik** [comment]
Thanks @zaydek - will have to revert to previous setup using Libsass for now I think, not sure what the next best steps would be on this one.

**Comment by zaydek** [comment]
> Thanks @zaydek - will have to revert to previous setup using Libsass for now I think, not sure what the next best steps would be on this one.

I would actually use Dart Sass if it doesn’t annoy you too much — unless you’re using PostCSS specific features. Dart Sass is actively being invested in by Google and company.

Best of luck!

**Comment by zaydek** [comment]
@Awjin I recommend this issue be closed. 😀
