### ISSUE TITLE
CI is not working anymore

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1163]
According to https://travis-ci.com/github/sass/dart-sass/requests, the sass organization does not have Travis credits anymore (and they seem to have suspended the granting of free open-source credits according to https://twitter.com/ArnaudLigny/status/1336077586888318977).

**Comment by nex3** [comment]
Thanks for the heads-up. We do have a paid account so I was not expecting this to be a problem, and the Travis team isn't answering my emails. We may need to move to a different CI solution in a hurry.

**Comment by stof** [comment]
would it make sense to migrate to github actions ?

**Comment by nex3** [comment]
We're considering that and CircleCI, but there are real costs associated with migrating a bunch of repos.

**Comment by stof** [comment]
@nex3 any decision on which CI system to use ?

**Comment by nex3** [comment]
I think we're going to go with GitHub Actions, because there's a pretty robust Dart action ecosystem available. We'll try to budget some time to migrate this quarter.
