### ISSUE TITLE
Support keyword arguments with arbitrary arguments in mixins and functions

### ISSUE THREAD

**Issue by McCarthyCode** [sass/dart-sass#1171]
# Overview

One limitation of the Sass/SCSS language is that keyword arguments can apparently not be used effectively in mixins or functions that use arbitrary arguments as well. Take, for example, the following Sass code. Here, we define a mixin that takes optional keyword arguments `$duration` and `$behavior` along with arbitrary argument `$properties...` to build a list of values for the `transition` property.

```sass
@mixin transition($duration: .15s, $behavior: ease-in-out, $properties...)
  $value: ""
  @each $property in $properties
    $value: "#{$value}, #{$property} #{$duration} #{$behavior}"
  transition: unquote(str-slice($value, 3, -1))
```

# Example Usage

## Overriding Defaults

This mixin works fine when overwriting the defaults for `$duration` and `$behavior`.

### Include

```sass
@include transition(.3s, linear, background-color)
```

### Resulting CSS

```css
transition: background-color .3s linear;
```

However, how do we make use of the default values? Here are some examples of includes that I have tried using, but result in an error.

### Include

```sass
@include transition($duration: .3s, background-color)
```

### Desired CSS

```css
transition: background-color .3s ease-in-out;
```

###  Actual Result

```css
Error: Positional arguments must come before keyword arguments.
    ╷
192 │                 @include transition($duration: .3s, background-color)
    │                                                     ^^^^^^^^^^^^^^^^
    ╵
```

### Analysis

Sass does not recognize `background-color` as an arbitrary argument. Instead, it is treated as a positional argument, as a value for `$behavior`. This is possible if Sass respects the order positional, keyword, arbitrary and treats positional and arbitrary arguments as separate (albeit very similar) entities.

### Include

```sass
@include transition(background-color, $duration: .3s)
```

### Desired CSS

```css
transition: background-color .3s ease-in-out;
```

###  Actual Result

```css
Error: Argument $duration was passed both by position and by name.
    ╷
192 │                 @include transition(background-color, $duration: .3s)
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```

### Analysis

By reversing the order of arguments in the last example, we haven't achieved the goal of placing positional arguments before keyword arguments (as per the error message) because the keyword argument `$duration` is being used in the second position, where `$behavior` is defined. So as far as the compiler is concerned, the include is giving two values to the same argument: `background-color` by position and `.3s` by name.

### Include

```sass
@include transition(color, background-color, border-color)
```

### Desired CSS

```css
transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out;
```

### Actual Result

```css
transition: border-color color background-color;
```

### Analysis

Here, the first two arbitrary arguments are treated as keyword arguments; again, there is no clear separation between positional, keyword, and arbitrary arguments.

# Summary

I'm not sure if the results from these examples are the intended behavior, but it's certainly not what I expected. Surely there is a way to implement this without completely breaking how arguments are defined, right? As mentioned before, there should be a clear separation between types of arguments, although I'm sure there's a great deal of edge and corner cases to cover, considering how the same argument (or list of arguments) can be used in different ways.

**Comment by Awjin** [comment]
Since SassScript doesn't have an `undefined` value, there's no good way to achieve this with arbitrary arguments.

Instead, you could pass in `$properties` as a List:

```sass
@mixin transition($properties, $duration: .15s, $behavior: ease-in-out)
  $value: ""
  @each $property in $properties
    $value: "#{$value}, #{$property} #{$duration} #{$behavior}"
  transition: unquote(str-slice($value, 3, -1))
  
a
  @include transition(background-color opacity, .3s, linear)

b
  @include transition(background-color)
```

which outputs

```css
a {
  transition: background-color 0.3s linear, opacity 0.3s linear;
}

b {
  transition: background-color 0.15s ease-in-out;
}
```

**Comment by nex3** [comment]
You can also access arbitrary keyword arguments passed to a function that takes a variable number of arguments using the [`meta.keywords()` function](https://sass-lang.com/documentation/modules/meta#keywords). For example:

```sass
@use "sass:map"
@use "sass:meta"

@mixin transition($properties...)
  $keywords: meta.keywords($properties)
  $duration: map.get($keywords, "duration") or .15s
  $behavior: map.get($keywords, "behavior") or ease-in-out

  $value: ""
  @each $property in $properties
    $value: "#{$value}, #{$property} #{$duration} #{$behavior}"
  transition: unquote(str-slice($value, 3, -1))
```
