### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by TheJaredWilcurt** [sass/dart-sass#1176]
Hey, I've been basically the only person answering questions in the `node-sass` Gitter for the last 4 years:

* https://gitter.im/sass/node-sass

But, y'all are gonna kill node-sass off soon, and people wanna ask dart-sass questions, so probably should make a place for that.

👍 🐙 🦞 📜 🦅 🥗 🌺 🏨 💵 🧯 🪀 🦙 👍 🤔 💭 👍 ❓ 👍 

❔ 👍 ☂️ 

![agree yes agreeable](https://user-images.githubusercontent.com/4629794/103360502-f156c200-4a86-11eb-9784-dbf924978ed9.gif)

**Comment by nex3** [comment]
I've created https://gitter.im/sass/sass. I can't promise anyone from the Sass team will be super active in there, but if you're willing to keep answering questions we'd be happy to have you!
