### ISSUE TITLE
[Bug] `This module was already loaded` false positive

### ISSUE THREAD

**Issue by zaydek** [sass/dart-sass#1180]
Hi Sass team, I’ve noticed a bug that has confused me many times. It may be something I’m doing, but I managed to reproduce it in a minimum viable repo for demonstration purposes.

This repo demonstrates my experience: https://github.com/zaydek/sass-with-bug. That being said, the repo is small enough I can just put the files here (do see the repo if you want to reproduce the bugs locally).

```scss
// consumer.scss

@use "lib" as * with (
	$this-is-a-bogus-variable: "hello",
);
```

```scss
// lib/_index.scss

@forward "b";
@forward "a";
```

```scss
// lib/a.scss

// This is an empty file. It must exist or this error will be thrown:
// Error: Can't find stylesheet to import.
```

```scss
// lib/b.scss

@use "a";
```

The bug is basically this: When I compile Sass (1.32), I run `yarn sass consumer.scss`. What I see is this:

```
Error: This module was already loaded, so it can't be configured using "with".
  ┌──> lib/_index.scss
2 │   @forward "a";
  │   ^^^^^^^^^^^^ new load
  ╵
  ┌──> lib/b.scss
1 │   @use "a";
  │   ━━━━━━━━ original load
  ╵
  ┌──> consumer.scss
1 │ ┌ @use "lib" as * with (
2 │ │     $this-is-a-bogus-variable: "hello",
3 │ │ );
  │ └─^ configuration
  ╵
  lib/_index.scss 2:1  @use
  consumer.scss 1:1    root stylesheet
```

**The problem is that I accidentally left `$this-is-a-bogus-variable: "hello"` at the `with` import statement, but the Sass error I get doesn’t correlate with my mistake.**

The reason this is confusing is because:

1. `$this-is-a-bogus-variable` this variable is never actually defined anywhere, I simply forgot to remove it from my source.
2. By simply removing this variable from my input file, Sass builds as expected.

I’m working on a rather large Sass project and false positives like this are really scary for me. Yes — I shouldn’t forget variables like this — but I did — and what ensued was me chasing down what I believe to be a false positive from the compiler. The expected behavior would be Sass letting me know that I’m using a variable that doesn’t actually exist. In my own project, when I remove my extraneous variable at the `with` import statement, everything seems to be OK.

Curiously, if I edit `lib/_index.scss` to from this:

```scss
@forward "b";
@forward "a";
```

```scss
@forward "a"; // This is now first, not last
@forward "b";
```

I get the expected behavior:

```
Error: This variable was not declared with !default in the @used module.
  ╷
2 │     $this-is-a-bogus-variable: "hello",
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  consumer.scss 2:2  root stylesheet
```

Is this a problem with how I’ve been writing Sass or is the compiler misfiring?

**Comment by Awjin** [comment]
It looks like there are two errors in the Sass code:
1. `a` was already loaded by `b`, so *any* downstream configuration of `a` will throw an error. This means that as soon as the compiler sees `use "lib" as * with (`, it throws an error.
1. There is no such variable `$this-is-a-bogus-variable`.

Since the first error throws before the compiler even tries to look for `$this-is-a-bogus-variable`, that is the error message you are seeing.

**Comment by zaydek** [comment]
Thanks for responding @Awjin. This is a pattern I’m currently using in my code base which _is_ working but yeah, it has definitely confused me.

I’ll think about what restructuring my source code would look like so I don’t trip over myself like this again. It sounds like I need to hoist all of my configured modules before importing them.

If you know any recommended documentation / examples on this I’d be grateful to take a closer look. Coming from JS-land I have to unlearn some common idioms.

**Comment by Awjin** [comment]
This is a good resource: https://sass-lang.com/documentation/at-rules/use#with-mixins. The key takeaway is that while configuring modules using `@use... with ...` is convenient, it's mostly suited for simpler use cases. The general pattern/recommendation in Sass is to write your libraries using mixins, which allows more flexibility in downstream configuration and consumption of those libraries.

**Comment by zaydek** [comment]
Thank you!

**Comment by jaami** [comment]
Hi, 
I got into same problem while i was following  Material UI setup for sveltekit. link i followed is this https://sveltematerialui.com/SVELTEKIT.md/
The technical information you guys talk about is too heavy on my head. Please tell me what steps to follow to get rid of the problem.  I attached files that were asked to modify through above link. Please take a look and kick the bug out for me.
[githubError.posting.txt](https://github.com/sass/dart-sass/files/7734988/githubError.posting.txt)

**Comment by nex3** [comment]
@jaami This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by arikorn** [comment]
Hi Natalie, (@nex3), this really is a bug in error reporting. Perhaps it's worth reopening the issue. The problem occurs when including a module using the `with` argument, but the module doesn't define one of the configurations variables. (or more precisely, as below?) I have encountered it when trying to use an external module and, unlike the OP, changing `@forward` line order did not help.  At the very least, the documentation could be modified to make it clear that including a variable that does not have !default defined in the submodule is an error.

Thank you!

**Comment by nex3** [comment]
@arikorn Please feel free to open a new issue with a standalone reproduction if you have a case where Sass is producing the wrong error message.
