### ISSUE TITLE
return relative paths in result.map.sources - not absolute file:// URL

### ISSUE THREAD

**Issue by milahu** [sass/dart-sass#1185]
dart-sass always returns absolute file URLs like `file:///absolute/path/to/src/input.css`
in the `sources` array of `result.map`
also when i enter relative filepaths like `src/input.css`

is there a way to get relative file paths in `result.map.sources`?

im looking for the equivalent of `options.source_map_file_urls` in libsass

```cpp
// libsass/src/source_map.cpp

if (ctx.c_options.source_map_file_urls) {
  source = File::rel2abs(source);
  // check for windows abs path
  if (source[0] == '/') {
    // ends up with three slashes
    source = "file://" + source;
  } else {
    // needs an additional slash
    source = "file:///" + source;
  }
}
```

but i had no luck grepping through dart-sass sources

related to https://github.com/sass/node-sass/pull/3057

**Comment by Awjin** [comment]
This is a limitation inherent to the way that the JS API currently handles file paths. We're actively redesigning the API to allow for the use case that you describe here.
