### ISSUE TITLE
[FEATURE] Find unused sass variables while compiling

### ISSUE THREAD

**Issue by danny007in** [sass/dart-sass#1206]

**Comment by jathak** [comment]
This isn't really something that's feasible in any case where code depends on third-party libraries, as the compiler (or a standalone static analysis tool) can't really distinguish between variables that are meant to be referenced within the current project and variables that are just part of an API exposed by a library.

It would be possible to detect unused [private members](https://sass-lang.com/documentation/at-rules/use#private-members) (whose names start with an underscore), but support for that would be better handled by a separate static analysis tool like stylelint.
