### ISSUE TITLE
Preserve escaped content

### ISSUE THREAD

**Issue by IgnacioHR** [sass/dart-sass#1209]
Hello,

If I've the input file input.scss
```
.test::before {
	content: "\ea01";
}
```
and I run `sass input.scss` the output obtained is:
```
.test::before {
  content: ;
}
```

I want it to be exactly the same escaped string without converting the escaped character into the utf-8 character as this is generating undesired side effects as you can see in the attached image capture

![Papirix___iXBRL_data_tagging](https://user-images.githubusercontent.com/16385090/104812290-8a186c00-5801-11eb-831a-83a5b36a6a6a.jpg)

I can't find a proper way to handle this situation via options or anything.

Any help or bug fix will be appreciated
Best

**Comment by jathak** [comment]
Duplicate of #568.
