### ISSUE TITLE
Question - use an existing variable in @use configuration

### ISSUE THREAD

**Issue by jwhitmarsh** [sass/dart-sass#1214]
I've checked the docs, but can't find the answer. Is it possible to do something like:

```scss
@use '~bootstrap/scss/bootstrap' with (
  $headings-color: $primary // <-- primary is an existing bootstrap variable
)
```

This currently isn't working for me, and I tried using `bootstrap.$primary` too.

**Comment by Awjin** [comment]
Bootstrap needs to explicitly enable configuration of their variables. One of the ways they could do this is by defining the variables with a `!default` flag (see: https://sass-lang.com/documentation/at-rules/use#configuration). Another common pattern is to allow configuration through mixins.

In general, Sass doesn't allow downstream users to arbitrarily configure upstream dependencies. This protects library authors from breaking their downstream users if they make a change to the implementation without changing the public API. If you want to configure Bootstrap in this way, I'd recommend filing an issue asking them to support, whether it be through a mixin or `!default`.
