### ISSUE TITLE
@debug displayed twice

### ISSUE THREAD

**Issue by borisdamevin** [sass/dart-sass#1228]
Hi,

I don't know if someone have already seen this issue, but, when do a `@debug ...`, is always displayed twice for each line.

Anyone have this problem?

**Comment by Awjin** [comment]
Could you provide the code that is causing the issue and the exact output? Which version of Sass are you using?

**Comment by borisdamevin** [comment]
Provide the code wolud be complicated. I try to find a way to make a plublic example.

Version of Sass: `1.32.6`
