### ISSUE TITLE
calculation does not resolve variables

### ISSUE THREAD

**Issue by Tealk** [sass/dart-sass#1230]
Hello

I wanted to use a calculation with a variable, but it is not resolved

Code:
```
$userbar_iconbox: 40px
...
left: calc(-100vw - $userbar_iconbox)
width: calc(100vw - $userbar_iconbox)
```

Result:
```
left: calc(-100vw - $userbar_iconbox);
width: calc(100vw - $userbar_iconbox);
```

Desired result
```
left: calc(-100vw - 40px);
width: calc(100vw - 40px);
```

sass-loader@^11.0.0
sass@^1.32.6

**Comment by Awjin** [comment]
Sass is leaving the calc expression untouched, because a calc that involves `vw` must be resolved in the browser. If you want the variable to be resolved to `40px` first, you should interpolate it:

```scss
left: calc(-100vw - #{$userbar_iconbox});
width: calc(100vw - #{$userbar_iconbox});
```
