### ISSUE TITLE
How to parse/get variables from scss/sass ? 

### ISSUE THREAD

**Issue by fasvald** [sass/dart-sass#1231]
Have a question. Maybe you can help me.
Is it possible to get a variables info from rendering the `scss` file via `dart-sass`.

For example, I have a style.scss:

```
$md: 768px;

.class {
  min-height: 0;
}
```

And running this script:

```
const path = require('path')
const sass = require('sass')

const res = sass.renderSync({file: path.join(__dirname, 'style.scss')})

console.log(res.css.toString())
```

I've got the result: `.class { min-height: 0; }`. I've checked the documentation and didn't find anything related to the render process and ger the scss file content rather than css file content as a string.

Thanks a lot. Have a nice day.

**Comment by stof** [comment]
what do you mean about the scss file content ?

If it is about getting a string containing the content of the scss file, you don't need sass for that. Use the `fs` module to read the file.

**Comment by fasvald** [comment]
@stof so if I want to parse variables from scss file I should use fs module? Is it correct?

**Comment by stof** [comment]
what do you mean by parsing variables from scss file ? What are you trying to do ?

**Comment by fasvald** [comment]
@stof sorry for confusing. I want to write a script to extract all variables from scss files to json file, so I can use it in js code.

**Comment by stof** [comment]
there's no API for that in Sass (and it would be quite tricky to implement while respecting the scoping rules of variables IMO)

**Comment by jathak** [comment]
@stof is right. Dart Sass itself is for compiling Sass source files into CSS.

If you want to extract variable declarations, you should read the file's contents itself and then parse them yourself. You may want to consider using [postcss-scss](https://github.com/postcss/postcss-scss) to get an AST (its parsing behavior doesn't match Dart Sass's exactly, but it's probably close enough for your use case).

**Comment by fasvald** [comment]
@stof @jathak Thanks a lot. You helped me a lot. Have a nice day.

**Comment by markhalliwell** [comment]
https://github.com/niksy/get-sass-vars

**Comment by bsully75** [comment]
> _I found this while looking for an answer for another solution and decided to post this answer for people who are still looking for a solution to this issue as I understand it based off of the first post and comments: "Extracting Sass variables for use with JavaScript"._

You might be better off using CSS custom properties. Below is an easy setup for converting your Sass variables to CSS custom properties if you're using Dart Sass and it's modules. You can also just use CSS custom properties in your Sass, instead of Sass variables if you don't want to go to these lengths.

// _variables.scss
```
$my-var: 768px;
```
// style.scss (_Use a mixin for the the CSS custom property creation, this is inline to keep the example simple-ish)_

```
@use "sass:meta";
@use "path_to_variables_partial/variables";

:root {
  @each $key, $value in meta.module-variables("variables") {
    --#{$key}: #{meta.inspect($value)};
  }
}

.myClass {
  width: var(--my-var);
}
```
// style.css _(after being compiled)_
```
:root {
  --my-var: 768px;
}

.myClass {
  width: var(--my-var);
}
```
And then in your JavaScript you can interact with the CSS custom properties
```
// get element
const element = document.querySelector(".myClass");

// get variable from inline style
element.style.getPropertyValue("--my-var");

// get variable from wherever
getComputedStyle(element).getPropertyValue("--my-var");

// set variable on inline style
element.style.setProperty("--my-var", jsVar + 4);
```
See https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#values_in_javascript
