### ISSUE TITLE
--compressed removes space after plain css @import

### ISSUE THREAD

**Issue by dpouliot** [sass/dart-sass#1232]
I'm using: `"sass": "^1.32.7"`

Running
`sass --style=compressed ./src:./dist/`

against:
`@import “url(http:…)”` compiles out to" `@import“http…”` <-- no space

It removed `url()` too, which is contrary to the web site's documentation.

Curiously, when I use webpack and `sass-loader`, it compiles correctly.

**Comment by jathak** [comment]
This is working as intended. `@import "url(http://...)"` and `@import"http://..."` are equivalent, so compressed mode emits the shorter version.

**Comment by dpouliot** [comment]
The missing white space after `@import` is not a problem?

**Comment by jathak** [comment]
It shouldn't be a problem. Since the URL is quoted, it's clearly separated from the `@import` even without whitespace. It's less readable for humans, but `--style=compressed` is optimizing for output size, not readability.

Does this break in some browser?

**Comment by dpouliot** [comment]
@jathak I was an intermediary on this issue. I haven't been able to reproduce it, so I'll go with your answer. Thank you.
