### ISSUE TITLE
[Bug] 0.5px is translated to 0.13rem where should be 0.013rem

### ISSUE THREAD

**Issue by suxuelengyin** [sass/dart-sass#1240]
ENV：
      "devDependencies": {
          "@babel/plugin-proposal-do-expressions": "^7.12.13",
          "@babel/plugin-proposal-function-bind": "^7.12.13",
          "@babel/plugin-proposal-pipeline-operator": "^7.12.13",
          "@typescript-eslint/eslint-plugin": "^2.18.0",
          "@typescript-eslint/parser": "^2.18.0",
          "@vue/cli-plugin-babel": "~4.2.2",
          "@vue/cli-plugin-eslint": "~4.2.2",
          "@vue/cli-plugin-typescript": "^4.2.3",
          "@vue/cli-service": "~4.2.2",
          "@vue/eslint-config-typescript": "^5.0.1",
          "args": "^5.0.1",
          "babel-eslint": "^10.0.3",
          "babel-plugin-import": "^1.13.0",
          "copy-webpack-plugin": "^5.0.5",
          "css-loader": "^3.2.0",
          "eslint": "^6.7.2",
          "eslint-plugin-prettier": "^3.1.3",
          "eslint-plugin-vue": "^6.1.2",
          "fs-extra": "^8.1.0",
          "inquirer": "^7.0.0",
          "postcss-px2rem": "^0.3.0",
          "pug": "^3.0.0",
          "pug-plain-loader": "^1.1.0",
          "runjs": "^4.4.2",
          "sass": "^1.32.8",
          "sass-loader": "^8.0.0",
          "ssh2": "^0.8.7",
          "style-loader": "^1.0.0",
          "tim-js-sdk": "^2.8.5",
          "typescript": "~3.7.5",
          "uglifyjs-webpack-plugin": "^2.2.0",
          "vue-template-compiler": "^2.6.10",
          "webpack-bundle-analyzer": "^3.6.0",
          "webpack-cli": "^3.3.10",
          "webpack-merge": "^4.2.2"
        },
postcss-px2rem config:
      const postcss = px2rem({
            remUnit: 37.5 
       })

ERROE RESULT:
    from:  border: 0.5px solid #fed8d5;
    =>
    to:  border: 0.1333rem solid #fed8d5;
Expectation:
    style:  border: 0.01333rem solid #fed8d5;

**Comment by Onesimu** [comment]
the node-sass version will have correct value of 
`border: .013333rem solid #fed8d5;`

**Comment by stof** [comment]
why are you reporting that to dart-sass ? sass is not responsible for translating px to rem at all.

**Comment by Awjin** [comment]
@stof is correct. Looking at your code, this looks like a `postcss-px2rem` bug:

```
postcss-px2rem config:
const postcss = px2rem({
remUnit: 37.5
})
```

**Comment by Awjin** [comment]
@stof is correct. Looking at your code, this looks like a `postcss-px2rem` bug:

```
postcss-px2rem config:
const postcss = px2rem({
remUnit: 37.5
})
```

**Comment by tangxiangmin** [comment]
dart-sass will converts 0.5px to.5px, which causes px2rem parsing errors

**Comment by stof** [comment]
`.5px` is perfectly valid CSS. If `px2rem` cannot parse it, it is a bug on their side, not on dart-sass side.

**Comment by tangxiangmin** [comment]
Thanks! Is there any configuration item that can cancel "omit 0 before decimal less than 1" in dart-sass?

**Comment by stof** [comment]
@tangxiangmin use the expanded output instead of the compressed one (the compressed one uses the shorter notation), and then maybe run your own CSS compression *after* using `px2rem` (so that it runs on the uncompressed output, as CSS minifiers I know of are also doing this transformation for `0.x` numbers).

However, the right fix would be the fix the bug in `px2rem` (however, given that the last release was 6 years ago, I'm not sure that package is maintained, in which case it might be better to stop using it). A PR trying to fix it even exist already: https://github.com/songsiqi/px2rem/pull/43

**Comment by tangxiangmin** [comment]
Thank you very much !! Expanded mode temporarily solved this problem

in px2rem, var pxRegExp = /\b(\d(\.d +)?) Px \b/ will handle the.5px case incorrectly. I will try to communicate with the author of px2rem.

Thanks again!
