### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by ludwiktrammer** [sass/dart-sass#1248]
Are there plans to make the package compatible with null safety ([here is the migration guide](https://dart.dev/null-safety/migration-guide))?

**Comment by jathak** [comment]
Yes. We're actively working on it, but we still have dependencies that haven't migrated yet (which we're also working on migrating).

**Comment by ludwiktrammer** [comment]
Great, thank you for the update!

**Comment by matehat** [comment]
Hello! Any updates on this?

**Comment by matehat** [comment]
Nvm! pub.dev indicates null safety is functional. Maybe this issue should be closed?
