### ISSUE TITLE
Security vulnerability being brought in through package glob-parent

### ISSUE THREAD

**Issue by emma3333** [sass/dart-sass#1252]
A security vulnerability -  Regular Expression Denial of Service (ReDoS) - is being brought in through the package glob-parent.

A fix for this is included in glob-parent versions 5.1.2 or higher.

Sass is currently using glob-parent version 5.1.1.

More details on the issue can be viewed here: https://app.snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905

**Comment by stof** [comment]
sass does not use `glob-parent` at all. chokidar does. But the version range used in `chokidar` allows using patched versions of `glob-parent` already.

**Comment by jathak** [comment]
Closing this since the vulnerability is not in a direct dependency, so there's not anything to update on our end.
