### ISSUE TITLE
Pass-through comment/annotation to PostCSS?

### ISSUE THREAD

**Issue by strarsis** [sass/dart-sass#1259]
For toggling a specific PostCSS plugin feature, I have to add annotations/special comments to e.g. a line or before a CSS function in a declaration value. Those comments however are stripped and not passed to PostCSS by SASS, hence they can't be used.
It is understandable that SASS strips non-protected comments in the end - but is there a way to add annotations like these? Those would also be stripped by the PostCSS plugin using it or by another PostCSS plugin specifically for cleaning up these comments in the final build.

**Comment by Awjin** [comment]
Sass is agnostic to downstream build tools (annotations that make sense for PostCSS could be confusing in other contexts). Is there a way to configure PostCSS by using loud Sass comments?

**Comment by strarsis** [comment]
@Awjin: Yes, that would be my question: How can a PostCSS plugin be configured using SASS comments - without special configuration tweaking?

**Comment by Awjin** [comment]
That should be done at the PostCSS plugin level. It would need to support being configured by loud Sass comments (`/*! of this form */`), since those are always included in the emitted CSS.

**Comment by strarsis** [comment]
@Awjin: In order to prevent the output of these loud comments, the PostCSS plugin has to clean it up by itself.
