### ISSUE TITLE
Migration plan to remove the package_resolver dependency

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1263]
The `package_resolver` dependency is an archived unmaintained package. It is incompatible with the null-safe 2.0 release of `package_config`.
This dependency is forbidding to update other dependencies to their latest version, which includes updating `test` to a version which works fine for JS on dart 2.12+ (i.e. to 1.16.7+ of `test`)

#1253 worked on replacing it with `package_config` directly, but this PR was closed.
As the work on null safety is not completed yet, waiting for some dependencies (node_interop and cli_pkg at least, plus `grinder` which only has a pre-release), it might make sense to work on this removal separately first

**Comment by stof** [comment]
for reference, here is the output I got after forcing `test ^1.16.7` in pubspec.yaml and bumping the max version of lots of other dependencies (including https://github.com/google/dart_cli_pkg/pull/77 for the cli_pkg dependencies)

```
Because test >=1.16.6 depends on package_config ^2.0.0 and package_resolver >=1.0.4 depends on package_config >=0.1.0 <2.0.0, test >=1.16.6 is incompatible with package_resolver >=1.0.4.
And because package_resolver <1.0.4 requires SDK version >=1.14.0 <2.0.0 or >=2.0.0-dev.17.0 <2.0.0, test >=1.16.6 is incompatible with package_resolver.
So, because sass depends on both package_resolver ^1.0.0 and test ^1.16.7, version solving failed.
```

**Comment by Awjin** [comment]
@nex3 is actively migrating Dart Sass to nnbd (continuing the work done in #1253). We're trying to complete this asap to minimize the divergence between the migration and master. All of these related problems (`test`, `package_resolver`) should go away once the migration is completed.
