### ISSUE TITLE
Feature request: handling irregular whitespace

### ISSUE THREAD

**Issue by jchiem** [sass/dart-sass#1265]
### Background

I've noticed that I sometimes end up typing a bit too fast when adding white spaces in my code when I've recently used `alt` or `option` key + space in Mac in VS Code (for example when adding a $ for a variable), this results in non-breaking spaces (`&nbsp`) being added to the code which look identical to regular white spaces, but when parsed through sass this causes issues since the output CSS still ends up getting a non-breaking whitespace and also an additional white space added from the parsing.

**Input:** 
```scss
$var: 1rem;

.my-class { padding: 0 $var 0 0; }
```

**Output:**
```
.my-class { padding: 0  1rem 0 0; }
```

The output having an additional non-breaking whitespace character which in browsers will be considered an invalid CSS rule and the styles will not be applied.

It seems to be a not too uncommon occurrence, since I did a quick search on `option + space` in my VS Code workspace and found over 8000 occurrences of non-breaking whitespace characters in external node_modules.

### Feature request
Would it be possible to ensure excluding nonbreaking whitespace characters from the final output when running `sass` ?

Potentially `content: ` will need to be excluded/exempted from the exclusion of these irregular whitespace characters.

**Comment by Awjin** [comment]
Unfortunately non-breaking spaces are a component of valid CSS; for example, a CSS selector can contain an nbsp.

This would be better handled by a linter to detect the nbsps, or by changing your keyboard/IDE configuration to disable typing nbsps accidentally.
