### ISSUE TITLE
global-variable-exists returning false for varialbes imported via @use

### ISSUE THREAD

**Issue by pete-hotchkiss** [sass/dart-sass#1266]
This may well be intended behavior - but I'm puzzled as to why a variable imported into a wild card name space returns false for `global-variable-exists` checks

_a.scss_
```scss
$foo: 24px;
```

```scss
@use "a" as *;
@debug meta.global-variable-exists("foo"); // false
```

should it not return true ?

If I switch out the `@use` for the legacy `@import` it returns true.

Am I implementing this incorrectly perhaps ?

**Comment by Awjin** [comment]
`global-variable-exists` does return true for `@use`ed vars. It's hard to say why this is returning false without more context.

**Comment by stof** [comment]
@pete-hotchkiss when I try your code snippet (adding the missing `@use 'sass:meta';` to make it working), the `@debug` shows `true`, not `false`.
which version of dart-sass are you using, and are you indeed reproducing the issue with the code snippet you shared ?
