### ISSUE TITLE
Unable to resolve files inside mocha webpack and jsdom

### ISSUE THREAD

**Issue by emerikool** [sass/dart-sass#1270]
Similar to #710, scss import are not correctly resolved due to environment detection.
We also use jsdom so it's not detected as Node environment as it should be and imports are not resolved:

Due to jsdom window object is emulated, from the lib 
`var dartNodeIsActuallyNode = !dartNodePreambleSelf.window`

I did not find src code related to this so perhaps it's coming from a dependency.

**Comment by paztis** [comment]
in fact, even if window is present, it didn't means we're not in a webpack process.
I encounter the same problem with mocha + webpack + jsdom
As jsdom is instanciated inside mocha beofre the webpack compilation, the window variable is already injected inside the global variable
This makes all the internal scss import resolving fail.

**Comment by jathak** [comment]
This seems like it's due to an underlying issue in node_preamble. You should [file an issue](https://github.com/mbullington/node_preamble.dart/issues/new) there and, once it's fixed, we should pick it up in our next release automatically.
