### ISSUE TITLE
decimal precision of 10 leads to issues with firefox

### ISSUE THREAD

**Issue by Hirbod** [sass/dart-sass#1271]
Hi,

I've spent couple of hours to bugfix an issue with firefox yesterday. The main reason is not CSS itself, but when you try to calculate with those values in JS (Firefox only).

I had a masonry grid, which was working perfectly fine before I've ported from browserify to webpack. (node-sass)

Before, my elements had a width of `33.33333%`. So my grid had 3 elements in a row. Was working in every major browser.
After my port to webpack, the output transpiled by dart-sass outputted `33.3333333333%`. No issues on Chrome, Safari and Edge, but Firefox. Only 2 elements per row.

Searching all the web and debugging via devtools, I tried to change the `precision` to 5 until I realized this setting is not available with dart-sass.

While I understand that the high percision is a good thing for `line-height` issues and other scenarios, it does lead to issues if you calculate with high precision values via JS in Firefox.

I've ended up adding some some ugly `margin-right: -0.001px` to my elements in order to fix this.
Since I had 0 issues with a precision of 5, I would kindly ask you guys to introduce a `precision` setting. I don't have any issues with a default value of 10, but you should still give the developer the power to change this value.

**Comment by hendotcat** [comment]
This is a really fascinating problem and I'm so glad you shared the details here. I'm weirdly excited to try and spin up a demo of this behaviour in Firefox at some point to see it with my own eyes!

Do you reckon you might be able to use something like https://gist.github.com/terkel/4373420 to adjust the precision of those numbers yourself directly? Might be your quickest way to get rid of those margin hacks!

**Comment by nex3** [comment]
Although generally speaking we do try to accommodate all the browser issues we can in Sass, in this case you're describing something that's clearly a bug in Firefox—there's no world in which `33.3333333333% * 3 > 100%`. Even in floating-point arithmetic (which can get pretty messy), the result is `99.99999999989998%`. And given that lower precisions *also* cause bugs in practice, and configurable precisions have performance and complexity problems, we're not very keen on making the default lower than 10.

**Comment by Hirbod** [comment]
The issue I had was caused by this package: https://github.com/metafizzy/isotope (which does break in Firefox with this high precision values)

Using this values directly via CSS didn't cause any issues, but since the JS does do some math with those values, it got messed up. This might be an implementation issue with the masonry algorithm used by isotope or a JS math bug by Firefox, I am fine with your decision.
