### ISSUE TITLE
--load-path not working for partials

### ISSUE THREAD

**Issue by danny007in** [sass/dart-sass#1272]
using `@use`
in bootstrap based theme making

**Comment by danny007in** [comment]
file name adminlte.scss
```scss
// Bootstrap
// ---------------------------------------------------
@use "bootstrap/scss/functions" as *;
@use "variables" as *;
@use "bootstrap/scss/bootstrap" as *;

// Variables and Mixins
// ---------------------------------------------------
@use "static-variables" as *;
```scss
// Variables and Mixins
// ---------------------------------------------------
@use "variables" as *;
@use "bootstrap/variables" as *;
```

**Comment by jathak** [comment]
It looks like your URL is incorrect. There's no file at the URL `bootstrap/variables` (at least when I install that module on my machine). You might be looking for `bootstrap/scss/variables` instead.

**Comment by danny007in** [comment]
thanks, it worked.
but anyhow we can not properly implement `@use` and `@forward` in bootsratp

**Comment by jathak** [comment]
Yes, we generally recommend waiting until your dependencies migrate to the module system before migrating yourself.

It's possible to migrate out of order, but unmigrated upstream libraries that depend on a shared global scope will pretty much always cause issues.
