### ISSUE TITLE
@use loading a module multiple times conflicts to configuration

### ISSUE THREAD

**Issue by duduluu** [sass/dart-sass#1273]
I get a error when i load the same module multiple time in different namespaces with configuration.

Code
```scss
@use '../../src/cep' as cepCustomPrefix with ($prefix: 'b', $componentName: 'foo');
@use '../../src/cep' as cepDefaultPrefix with ($componentName: 'bar');
@use '../../src/cep' as cepNoPrefix with ($prefix: null, $componentName: 'foobar');
```

Error:
```
Error: This module was already loaded, so it can't be configured using "with".
  ╷
1 │ @use '../../src/cep' as cepCustomPrefix with ($prefix: 'b', $componentName: 'foo');
  │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original load
2 │ @use '../../src/cep' as cepDefaultPrefix with ($componentName: 'bar');
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new load
  ╵
  test/configs/prefix.scss 2:1  root stylesheet
```

But if i remove the configs of the second and third namespace, they cannot get those configs from the first namespace.

**Comment by jathak** [comment]
This is working as intended. In the module system, each module is only ever loaded once per compilation, so attempting to `@use` a module with two different configurations is not possible.

If you're only loading this module for their CSS output, you can instead use the [`meta.load-css` mixin](https://sass-lang.com/documentation/modules/meta#load-css), which doesn't have the import-once constraint, so you can call it multiple times for the same stylesheet with different configurations.

**Comment by duduluu** [comment]
regret, what i expect is a closure-like behavior via loading same module with different configs.
thx!
