### ISSUE TITLE
--watch starting with 1.32.0 no longer watches @import partials

### ISSUE THREAD

**Issue by cwalker-reveille** [sass/dart-sass#1274]
using npm sass  1.30.0:

```
sass --load-path=node_modules  --watch sass/admin.scss:css/build/administration/administration.css
```

This will watch the admin.scss file and all of its `@import` partials which are located in several different folders.  For example in admin.scss, I have 
`@import "administration/_collectors.scss`. Any change to this partial will be recognized by the watcher and recompile  administration.css.

starting with npm sass 1.32.0,  (and the current 1.32.8),  the partials, when changed, are not triggering a recompile. However when changing the admin.scss file, the watcher will trigger a recompile.

**Comment by nex3** [comment]
What version of Node are you using? What's the contents of your `package-lock.json`?

**Comment by cwalker-reveille** [comment]
Node- 14.15.3
I assume for the lock you are looking for the sass entry:
```
  "sass": {
      "version": "1.32.8",
      "resolved": "https://registry.npmjs.org/sass/-/sass-1.32.8.tgz",
      "integrity": "sha512-Sl6mIeGpzjIUZqvKnKETfMf0iDAswD9TNlv13A7aAF3XZlRPMq4VvJWBC2N2DXbp94MQVdNSFG6LfF/iOXrPHQ==",
      "dev": true,
      "requires": {
        "chokidar": ">=2.0.0 <4.0.0"
      }
    },
```

**Comment by nex3** [comment]
No, I'm looking for your entire lockfile.

**Comment by cwalker-reveille** [comment]
[package-lock.zip](https://github.com/sass/dart-sass/files/6267617/package-lock.zip)

**Comment by nex3** [comment]
I can't see anything in there that would be causing a problem. Can you provide a minimal github repo that reproduces the issue?

**Comment by cwalker-reveille** [comment]
@nex3 Natalie, I will create the repo for you in the next few days. However I experimented around with this scss and think I see a pattern. 

Here is the contents of the admin.scss in question:

`@import "_variables.scss";
@import "administration/_variables.scss";

@import "_mixins.scss";
@import "includes/_fonts.scss"; //this is Themify Icons import
@import "includes/_defaultfont.scss";

@import "../node_modules/bootstrap/scss/_functions.scss";
@import "../node_modules/bootstrap/scss/_variables.scss";
@import "../node_modules/bootstrap/scss/_mixins.scss"; 
@import "includes/_preloader.scss";
@import "administration/_home.scss";
@import "administration/_groups.scss";
@import "administration/_monitors.scss";
@import "administration/_dashboards.scss";
@import "administration/_scorecard.scss";
@import "administration/_security.scss";
@import "administration/_notifications.scss";
@import "administration/_schedules.scss";
@import "administration/_supportgroups.scss";
@import "administration/_downloads.scss";
@import "administration/_remote.scss";
@import "administration/_oauth.scss";
@import "administration/_collectors.scss";
`
Like I said earlier if I change something in 'administration/_collectors.scss' while in watch, it does not recompile. However if I move the _collectors.scss to be in the same folder as admin.scss and change the import to be 
`@import "_collectors.scss";`

Then changes to _collectors.scss will fire a recompile.

**Comment by cwalker-reveille** [comment]
@Nex3: I have been able to reproduce this issue using this repository:  https://github.com/cwalker-reveille/sasstest
Let me know if you need any more info. Thanks

**Comment by Awjin** [comment]
The folder you are importing from is capitalized. To fix this, either rename `Administration/` to `administration/`, or change the import from `@import administration/_collectors.scss` to `@import Administration/_collectors.scss`.
