### ISSUE TITLE
Test for unicode range of length 6 followed by question mark

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1280]
I've stumbled upon what is (as far as I can tell) surprising behavior of `dart-sass`.

For the input
```scss
a {
  color: U+123456?;
}
```
`dart-sass` will not throw an error. [It seems `dart-sass` does not check the length of a unicode range before scanning a question mark](https://github.com/sass/dart-sass/blob/master/lib/src/parse/stylesheet.dart#L2447).

`libsass` *does* raise an error on this input. 

For the sake of complete parity, it would be nice to add a test for this case, as it is not immediately obvious that `dart-sass` would allow this.

**Comment by stof** [comment]
Quoting the CSS spec:

> Consume as many hex digits from text as possible. then consume as many U+003F QUESTION MARK (?) code points as possible. If zero code points were consumed, or more than six code points were consumed, this is an invalid <urange>, and this algorithm must exit.

dart-sass does not implement the `consume as many as possible` part then checking the consumed length
