### ISSUE TITLE
Ouput warning to CLI when sass variables are not defined

### ISSUE THREAD

**Issue by left23** [sass/dart-sass#1285]
Hello,

I'm in the midst of changing from gulp and `node-sass` to using the CLI and `dart-sass`.
In the past, I would get an error output to the console when a sass variable was not defined.
```
.pipe(sass({outputStyle: 'expanded'}).on('error', sass.logError))
```
I can't find any information about how I do that with dart-sass CLI. Could someone point me in the right direction?

**Comment by Awjin** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
