### ISSUE TITLE
>= 1.32.9 version breaks vuetify

### ISSUE THREAD

**Issue by loopingz** [sass/dart-sass#1287]
```
 ERROR  Failed to compile with 3 errors                                                                                                                                10:36:20 AM

 error  in ./node_modules/vuetify/src/components/VSelect/VSelect.sass

SassError: Expected identifier.
   ╷
68 │       position: relative
   │                         ^
   ╵
  node_modules/vuetify/src/components/VSelect/VSelect.sass 68:25  root stylesheet


 @ ./node_modules/vuetify/lib/components/VSelect/VSelect.js 3:0-54
 @ ./node_modules/vuetify/lib/components/VSelect/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/vuetify/src/components/VWindow/VWindow.sass

SassError: Expected identifier.
  ╷
4 │   overflow: hidden
  │                   ^
  ╵
  node_modules/vuetify/src/components/VWindow/VWindow.sass 4:19  root stylesheet


 @ ./node_modules/vuetify/lib/components/VWindow/VWindow.js 2:0-54
 @ ./node_modules/vuetify/lib/components/VWindow/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./node_modules/vuetify/src/components/VCalendar/VCalendarCategory.sass

SassError: expected ":".
   ╷
13 │   .v-calendar-daily__day-container
   │                                   ^
   ╵
  node_modules/vuetify/src/components/VCalendar/VCalendarCategory.sass 13:35  root stylesheet


 @ ./node_modules/vuetify/lib/components/VCalendar/VCalendarCategory.js 2:0-66
 @ ./node_modules/vuetify/lib/components/VCalendar/VCalendar.js
 @ ./node_modules/vuetify/lib/components/VCalendar/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
```

It works well with `1.32.8`, this might be intended but I would expect patch version to not have breaking changes

**Comment by ivysrono** [comment]
Delete all and reinstall 1.32.8, breaks again.

**Comment by wagich** [comment]
@ivysrono: Did you by chance specify the version as `^1.32.8`? 
This happened to me, yarn then naturally bumped me to the newest patch version. When I locked the version (version number only, without prefix) it installed 1.32.8 and worked. You can verify the installed version by checking the file `node_modules/sass/package.json`.

**Comment by tmcdos** [comment]
I confirm that version `1.32.8` works just fine with Vuetify but versions `1.32.9` and `1.32.10` break. I do not understand what is wrong - the SASS file(s) seem totally valid when inspected visually.
The stacktrace is
```
Z:\3>npm start

> vuetify@0.1.0 start Z:\3
> sass node_modules/vuetify/src/components/VWindow/VWindow.sass --trace

Error: Expected identifier.
  ?
4 │   overflow: hidden
  │                   ^
  ?
  node_modules\vuetify\src\components\VWindow\VWindow.sass 4:19  root stylesheet


node_modules\sass\sass.dart.js 1235:17   Object.wrapException
node_modules\sass\sass.dart.js 42945:19  SassParser.wrapSpanFormatException$1$1
node_modules\sass\sass.dart.js 42951:19  SassParser.wrapSpanFormatException$1
node_modules\sass\sass.dart.js 43938:19  SassParser.parse$0
node_modules\sass\sass.dart.js 8210:122  Object.Stylesheet_Stylesheet$parse
node_modules\sass\sass.dart.js 41273:16  ImportCache_importCanonical_closure.cal
l$0
node_modules\sass\sass.dart.js 24888:24  JsLinkedHashMap.putIfAbsent$2
node_modules\sass\sass.dart.js 41224:32  ImportCache.importCanonical$3
node_modules\sass\sass.dart.js 15499:34  <fn>
node_modules\sass\sass.dart.js 4360:15   _wrapJsFunctionForAsync_closure.$protec
ted
```

**Comment by wagich** [comment]
I did some tests, and it seems that an empty, but indented line in SASS mode is handled incorrectly.
Just including a comment gets it working again.

#### Test case
```sass
.v-window
  overflow: hidden
// if this line is empty and has no indent, it works. Indented to same level as previous line but otherwise empty, it doesn't
  &__container
    position: relative
```

**Comment by hawkeye64** [comment]
Getting this as well:

```
Error: Nothing may be indented beneath a @import rule.
  ╷
3 │ .q-calendar-day
  │ ^
  ╵
```

On this sass:
```css
@import './q-calendar.sass'
  
.q-calendar-day
  display: flex
  flex: 1
  flex-direction: column
```
Pinning to v1.32.8 works

**Comment by ivysrono** [comment]
> 
> 
> @ivysrono: Did you by chance specify the version as `^1.32.8`?
> This happened to me, yarn then naturally bumped me to the newest patch version. When I locked the version (version number only, without prefix) it installed 1.32.8 and worked. You can verify the installed version by checking the file `node_modules/sass/package.json`.

You are right, thanks.

**Comment by Tofandel** [comment]
I can confirm, those last 2 release shouldn't have passed tests, they should be unpublished

**Comment by jacekkarczmarczyk** [comment]
should be resolved in vuetify in https://github.com/vuetifyjs/vuetify/pull/13439

**Comment by Tofandel** [comment]
Yes but that shouldn't have been vuetify's to fix in the first place
https://github.com/sass/dart-sass/blame/master/lib/src/parse/sass.dart#L387 I think this is the culprit, previously the currentIndentation was not modified in this function
@nex3 Please have a look, thanks

**Comment by daaanstraight** [comment]
I can confirm the solution at this link: https://stackoverflow.com/a/67148859 worked for me.

**Comment by datnguyen987** [comment]
I remove and install sass version 1.32.8 but this not worked for me

**Comment by hawkeye64** [comment]
@datnguyen987 When downgrading you must remove node_modules and yarn.lock/package-lock.json and then only re-install

**Comment by idanchenko** [comment]
Also Vuetify released a hotfix 2.4.10 that works around this issue in sass 1.32.9 and 1.32.10.

**Comment by Tofandel** [comment]
You don't need to remove anything, just run `npm install sass@1.32.8 --save-dev`

**Comment by nex3** [comment]
Sorry for the breakage, folks. Version 1.32.9 is outside the unpublish window at this point, but I'm working on a fix now and should have it launched within a few hours.

**Comment by loopingz** [comment]
> Sorry for the breakage, folks. Version 1.32.9 is outside the unpublish window at this point, but I'm working on a fix now and should have it launched within a few hours.

No worries it happens, thanks for the fix

**Comment by datnguyen987** [comment]
i fixed with upgrade vuetify last version and  sass version 1.32.8, tks so much
