### ISSUE TITLE
--load-path flag not working in Lerna monorepo

### ISSUE THREAD

**Issue by adriennemcd** [sass/dart-sass#1292]
hi all, 
I'm having trouble getting the new dart sass --load-path flag to work for packages in a monorepo which uses Lerna and Yarn workspaces. I'm working on my company's design system. We have one package (Core) that provides base styles, variables, and mixins that are all `@forward`ed to component CSS packages as well as consuming applications. The CSS component packages `@use` a partial from core called `_tools.scss` to get access to variables. 

When compiling sass files in another React web app, I've successfully gotten the load path flag to work:
in `package.json`, the script to compile sass is:
```"build-sass": "sass --style=compressed --load-path=./node_modules ./src/styles/main.scss ./dist/css/main.css"```

then in `_dependencies.scss` I can bring in dependency sass files like:
```
@forward "@namespace/namespace-styleguide-core/scss/core"; // contains all variables and mixins for use in consuming app
@use "@namespace/namespace-styleguide-button/scss/_component.button"; // button specific styles
```

However, this doesn't seem to work in a monorepo set up. The monorepo directory set up is like this (simplified):
```
|__ node_modules
|   |__ @namespace
|       |__ namespace-styleguide-core
|           |__ scss
|               |__ _tools.scss // contains all variables and mixins for use in components
|       |__ namespace-styleguide-button
|           |__scss
|               |__ _component.button.scss
|__ package.json
|__ packages
|   |__ css
|      |__ namespace-styleguide-core
|      |__ namespace-styleguide-button
|         |__scss
|            |__ _component.button.scss
```

The core and button packages have their own package.json, node_modules directory etc, since they are their own self contained packages. However, because of how yarn workspaces and lerna work, all dependencies are actually in the root node_modules, and the node_modules in each individual package relies on symlinks. 

In `namespace-styleguide-button`, `_component.button.scss` has the button specific styles. In order to utilize variables from core, it does `@use "@namespace/namespace-styleguide-core/scss/tools.scss"` at the top. Except - this doesn't work! If I try to compile this, I get an unknown file error. 

It _does_ work if I do `@use "../../../../node_modules/@namespace/namespace-styleguide-core/scss/tools.scss"`, which gets me to the root `node_modules` folder. When a consuming app brings in `_component.button.scss` as a dependency, this relative path just happens to work...I think because of the directory structure of the `namespace-styleguide-button` package in `node_modules`...? But that seems like a very brittle solution.

I'm having a lot of trouble finding examples of how to use the new dart sass modular set up in a monorepo structure. So I know this might not be a dart sass specific bug...but I'm hoping for some guidance if anyone else has solved this.

**Comment by jathak** [comment]
This seems like an issue with Lerna, not with Sass. One thing to try would be to pass an absolute path to `--load-path` just to make sure that `./node_modules` is being resolved from the correct directory.

**Comment by adriennemcd** [comment]
well...this seemed to just be a terrible case of trying to learn a new thing in a complex environment, and confusing myself 😂 
Using `--load-path=../../../node_modules` works
