### ISSUE TITLE
Provide a JavaScript API configuration for setting the actual URL in the sourceMappingURL located in the .css file.

### ISSUE THREAD

**Issue by jeffschwartz** [sass/dart-sass#1293]
The options the JavaScript API provide for manipulating the sourceMappingURL that is generated in the css file are inadequate for some use cases, such as for some cache busting tools. For instance, assuming the following web site project  folder structure:

> project
>> source
>>> css
>>>> main.css

the site's build process would run the Dart JavasScript API and generate the following within the project's release folder:

> project
>> release
>>> css
>>>> main.css
>>>> main.css.map

and the sourceMappingURL generated in project/release/css/main.css is currently:

`/*# sourceMappingURL=main.css.map */`

But some cache busting tools require site relative URLs and paths in order to be able to identify file content to update to match hashed file names, which would include the map file. Therefore, the site relative sourceMappingURL that the cache busting software expects is:

`/*# sourceMappingURL=/css/main.css.map */`

The cache busting tool when run would target the `project/release` folder. When cache busting the folder's content, the css map file's name would be modified to `main.unique-hash.css.map` and the cache busting software would then search the content of the the release folder's other files, including `main.css`, for references to `/css/main.css.map`, the original map file's site relative path, and when found would update those to include the unique hash, such as:

`/*# sourceMappingURL=/css/main.unique-hash.css.map */`
 
Is this currently possible using the JavaScript API and if not can it be added to the JavaScript API as a config option (i.e. __sourceMappingURL: "/css/main.css.map__")? The benefit here is that Dart Sass wouldn't have to try to include every use case imaginable that might be needed for generating the sourceMappingURL and could just accept the value provided by the developer and use that making it very adaptable and open to all use cases. 

I'd also like to mention that JavaScript bundlers have already seen the seen to provide this feature. For example, Parcel (i.e. https://parceljs.org/) does for both its CLI (i.e. `--publice-url`) and for its JavaScript API  (i.e. `publicUrl: `).

**Comment by Awjin** [comment]
This seems like the responsibility of a bundler, and is probably out-of-scope for the Sass compiler. Is there a reason why this can't be done in post-processing?

**Comment by jeffschwartz** [comment]
Yes, @Awjin, you are correct on both accounts. It should be provided as an option by _postcss_ but it can also be done manually as I have been doing it:
```javascript
postcssResult.css.replace(`/*# sourceMappingURL=${parse(mainSassFile).name}.css.map */`,
    `/*# sourceMappingURL=/css/${parse(mainSassFile).name}.css.map */`);
```
I am closing out this ticket and will generate a similar one for the postcss project.

Thank you for your reply.
