### ISSUE TITLE
npm sass.renderSync({ file: 'relative/path/to/file' }) called within a react test has http://localhost context prepended to file path causing load to fail

### ISSUE THREAD

**Issue by t2mercer** [sass/dart-sass#1294]
This is an issue with the _renderSync method in the npm sass version 1.32.11 in file sass.dart.js
How to reproduce on Linux:

```
npx create-react-app sass-dart-error
cd sass-dart-error
code .
open a terminal in VS Code
npm install sass --save-dev
```

this is minimal package.json (note the extra script line to run sass to compile the scss (though this is not required for this bug just to prove that sass does compile scss to css)
  
```
  {
    "name": "sass-dart-error",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
      "@testing-library/jest-dom": "^5.12.0",
      "@testing-library/react": "^11.2.6",
      "@testing-library/user-event": "^12.8.3",
      "react": "^17.0.2",
      "react-dom": "^17.0.2",
      "react-scripts": "4.0.3",
      "web-vitals": "^1.1.1"
    },
    "scripts": {
      "start": "react-scripts start",
      "build": "react-scripts build",
      "test": "react-scripts test",
      "eject": "react-scripts eject",
      "sass": "sass src/scss:src/css -w"
    },
    "eslintConfig": {
      "extends": [
        "react-app",
        "react-app/jest"
      ]
    },
    "browserslist": {
      "production": [
        ">0.2%",
        "not dead",
        "not op_mini all"
      ],
      "development": [
        "last 1 chrome version",
        "last 1 firefox version",
        "last 1 safari version"
      ]
    },
    "devDependencies": {
      "sass": "^1.32.11"
    }
  }
```

```
mkdir scss
mkdir css
cd scss
touch bbb.module.scss
open bbb.module.scss in VS Code
```

add the following to the file and save:

```
.fw_9 {
  font-weight: 900;
}
```

replace the default content of App.js wit the following:
All that is added is the import of the scss and the reference in the code element

```
import logo from "./logo.svg";
import "./App.css";
import bbbStyle from "./scss/bbb.module.scss";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code className={`${bbbStyle.fw_9}`}>src/App.js</code> and
          save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

replace the content of the default App.test.js file with the following:

Note this issue is independent of whether the sass.renderSync call is directly done in the test or done in the setup of the test.
The issue is independent of whether includePaths option is used or not (the includePaths is totally ignored)

```
import React from "react";
import { render, screen } from "@testing-library/react";
import App from "./App";
import sass from "sass";
import { unmountComponentAtNode } from "react-dom";

let container = null;
beforeEach(() => {
  const bbb = sass.renderSync({ file: "src/scss/bbb.module.scss" });
  container = document.createElement("style");
  container.innerHTML = bbb.css.toString();
  document.body.appendChild(container);
});

afterEach(() => {
  // cleanup on exiting
  unmountComponentAtNode(container);
  container.remove();
  container = null;
});

test("renders learn react link", () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});

test("code had font-weight of 900", () => {
  render(<App />);
  const code = screen.getByText(/src\/App.js/i);
  expect(getComputedStyle(code).getPropertyValue("font-weight")).toBe("900");
});
```

in the terminal run:

```
npm run test
```

The result will be:

```
src/scss/bbb.module.scss: no such file or directory

       7 | let container = null;
       8 | beforeEach(() => {
    >  9 |   const bbb = sass.renderSync({ file: "src/scss/bbb.module.scss" });
         |                    ^
      10 |   container = document.createElement("style");
      11 |   container.innerHTML = bbb.css.toString();
      12 |   document.body.appendChild(container);

      at Object._newRenderError (node_modules/sass/sass.dart.js:13170:19)
      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:12978:18)
      at Object.Primitives_applyFunction (node_modules/sass/sass.dart.js:1131:30)
      at Object.Function_apply (node_modules/sass/sass.dart.js:5886:16)
      at _callDartFunctionFast (node_modules/sass/sass.dart.js:7552:16)
      at Object.renderSync (node_modules/sass/sass.dart.js:7530:18)
      at Object.<anonymous> (src/App.test.js:9:20)
```

If you open node_modules/sass/sass.dart.js and go to line 12946 which is inside the _renderSync method and you put the following - the console.log(t2) is the new line:

```
} else if (file != null) {
          t2 = file;
          console.log(t2);
          t3 = B._parseImporter(options, start);
          t4 = B._parseFunctions(options, start, false);
          t5 = t1.get$indentedSyntax(options);
```

the output is now:

```
   console.log
    http://localhost/src/scss/bbb.module.scss

      at StaticClosure._renderSync (node_modules/sass/sass.dart.js:12946:19)
```

Something in the line 

```
file = X.NullableExtension_andThen0(t1.get$file(options), D.path__absolute$closure());
```

which is at line 12927 adds the http://localhost/

Pulled this project, installed Dart, compiled the code using 

```
dart run grinder before-test
```
The version of the sass.dart.js file created has a new implementation of _renderSync but it still has the same issue.

I am not skilled enough at Dart to work through what might be the underlying issue but it starts in the 
RenderResult _renderSync(RenderOptions options) method in the node.dart file.

The hack that works is to add the following line in the sass.dart.js file - note the line after the console.log.  This sets it back to the relative path set by the filename passed into the renderSync method from within the test code.

```
  } else if (file != null) {
          t2 = file;
          console.log(t2);
          t2 = t1.get$file(options);
          t3 = B._parseImporter(options, start);
          t4 = B._parseFunctions(options, start, false);
```

Reseting t2 (which is passed to t10 = B.readFile0(t2); later in the code) all works as expected and the style is loaded and applied to the element and the test can see the applied style that came from a class built in an scss file.

If I use node-sass instead of sass, this is not an issue but as node-sass is deprecated I am hoping to use sass.  

Thank you for looking at this.  Please let me know if I have missed something that I should have added to the package.json file or another config that would resolve this.  

### Update 1:

I started looking at the dart code:

In lib/src/node.dart, the last line goes off and deals with nulls nicely and the calls p.absolute which is a call to path.dart code (Dart language code)

```
RenderResult _renderSync(RenderOptions options) {
  try {
    var start = DateTime.now();
    CompileResult result;

    var data = options.data;
    var file = options.file.andThen(p.absolute);
```
In the ~/.pub-cache/hosted/pub.dartlang.org/path-1.8.0/lib/path.dart file the absolute method proxies for the absolute method on the context ~/.pub-cache/hosted/pub.dartlang.org/path-1.8.0/lib/src/context.dart we have this code

```
// If there's a single absolute path, just return it. This is a lot faster
    // for the common case of `p.absolute(path)`.
    if (part2 == null && isAbsolute(part1) && !isRootRelative(part1)) {
      return part1;
    }

    return join(current, part1, part2, part3, part4, part5, part6, part7);
```
the part1 value being passed is src/scss/bbb.module.scss which is NOT an absolute path so the join method is called and current (which must be http://localhost/ for some reason) is then bound to the part1 value which is the relative file path.

Might you know how "current" is set ... I am running in react testing library test framework which likely is what is setting the context to an http://localhost/ context.

What is more odd is that if I pass in the absolute (Linux) path to the renderSync method it is still treated as not absolute.

I cannot see the implementations of isAbsolute and isRootRelative as they seem to call ~/.pub-cache/hosted/pub.dartlang.org/path-1.8.0/lib/src/internal_style.dart which seems to wrap compiled code.

### Update 2: - Suggested Fix

In lib/src/node.dart:

```
/// [render]: https://github.com/sass/node-sass#options
RenderResult _renderSync(RenderOptions options) {
  try {
    var start = DateTime.now();
    CompileResult result;

    var data = options.data;
    //var file = options.file.andThen(p.absolute);
    var file = options.file;
    if (data != null) {
```

Remove the need to force an absolute path as the rest of the code works without issue when passed a relative path that is relative to the project root (same level as node_modules)

So 

``` 
var file = options.file.andThen(p.absolute);
```

becomes

```
var file = options.file;
```

### Update 3: - Not fully fixed with the above Suggested Fix

The above fix works when re-compiling the code to the javascript npm module (`dart run grinder before-test`) and copying the sass.dart.js over the node_modules/sass/sass.dart.js file in the project allows the scss file to load and be parsed but fails if the loaded scss file has a `@use` statement in it.

After more walking around the sass.dart.js code and trying to pluck away at the dart code, the Suggested Fix would also need to make a change to the lib/src/importer/node/implementation.dart code.

```
/// Tries to load a stylesheet at the given [path] relative to [previous].
  ///
  /// Returns the stylesheet at that path and the URL used to load it, or `null`
  /// if loading failed.
  Tuple2<String, String>? _resolveRelativePath(
      String path, Uri? previous, bool forImport) {
    if (p.isAbsolute(path)) return _tryPath(path, forImport);
    // if (previous?.scheme != 'file') return null;

    // 1: Filesystem imports relative to the base file.
    return _tryPath(p.join(p.dirname(p.fromUri(previous)), path), forImport);
  }
```

removing the ` if (previous?.scheme != 'file') return null; ` line of code from this method allows the `@use` file referenced to be loaded and processed correctly.

(It should be noted that previous object has an empty scheme even though it should be file - not sure why)

**Comment by fangbinwei** [comment]
I guess it's the same problem as https://github.com/sass/dart-sass/issues/710

**Comment by t2mercer** [comment]
Agreed.  Thank you @fangbinwei.
