### ISSUE TITLE
My nested imports (via meta.load-css) broken since Sass 1.32.9

### ISSUE THREAD

**Issue by philwareham** [sass/dart-sass#1299]
I'm using a collection of nested CSS imports (previously via `@import` but recently via `meta.load-css`)...

``` sass
@if not setup.$modules-user-defined {
    /* ==========================================================================
       Styling and layout for screen media (mobile first)
       ========================================================================== */

    @media screen {
        @include meta.load-css("modules/fonts");
        @include meta.load-css("modules/layout");
        @include meta.load-css("modules/layout-helpers");
        @include meta.load-css("modules/navigation");
        ...
```

All was working well up to Sass 1.32.8 but now I keep getting the following types off message:

```
Fatal error: Error: Declarations may only be used within style rules.
   ╷
35 │         padding: 0;
   │         ^^^^^^^^^^
   ╵
  src/assets/sass/modules/_navigation.scss 35:9  load-css()
  src/assets/sass/style.scss 61:9                root stylesheet
```

For reference, the line in my `_navigation.scss` file that throws the error (although plenty of other lines would also cause this issue - it's just the first one it picks up):

``` sass
#site-navigation {
    margin: 0 auto;

    ul {
        margin: 0 0 0.75em;
        padding: 0; /* THIS LINE SEEMS TO CAUSE THE ERROR */
        list-style: none;
        font-family: var(--font-serif);
        font-size: 1.125rem; // 18px / 16px
        font-variation-settings: "wght" 500; // older browsers will just ignore this
        font-weight: 400;
        line-height: 1.4444444; // 26px / 18px
    }
```

Not sure if this is something I've set up wrong, or a bug since v1.32.9? As I say it, worked fine previous to that version.

**Comment by Awjin** [comment]
This is most likely a syntax error somewhere in the code. I'm unable to repro with Dart Sass 1.32.12, using the following code:

```
<===> _lib1.scss
$a: false;

<===>
================================================================================
<===> _lib2.scss
#a {
  b: c;

  d {
    margin: 0;
    padding: 0;
    list-style: none;
  }
}

<===>
================================================================================
<===> input.scss
@use "sass:meta";
@use "src/lib1";

@if not lib1.$a {
  @media screen {
    @include meta.load-css("src/lib2");
  }
}
```

**Comment by philwareham** [comment]
OK, thanks for investigating. Still unsure why my Sass complies absolutely fine using Dart Sass 1.32.8 yet not with 1.32.9 onwards though, without any real CLI messaging as to what the error is either. Stylelint and Sass-lint both not picking up any obviously syntax errors either. I will go over my stylesheets with a fine toothcomb and see if I can spot any mistakes.

**Comment by webholics** [comment]
Did you find anything? Because we have the same issue with this update in our codebase, too.

**Comment by philwareham** [comment]
@webholics no I didn't find any issues with my code. I'm staying on Sass 1.32.8 for now, which works fine.

**Comment by webholics** [comment]
Same.

We are using a mixin where it breaks:

```
&--mobileBlock {
      @include libs.media(mobile-only) {
        width: 100%;
      }
}
```

The mixin of course is using a media query + `@content`. It seems this is not supported as expected anymore.

**Comment by nex3** [comment]
@webholics or @philwareham can either of you provide a stand-alone reproduction of this issue?

**Comment by philwareham** [comment]
I've gone back to using `@import` for now to bring in my modules instead of `@include meta.load-css`, which fixes the issue short-term. I know `@import` is deprecated but I can't see any other reason why the compile breaks.
