### ISSUE TITLE
Provide evidence for claim on README.md file

### ISSUE THREAD

**Issue by preetpalS** [sass/dart-sass#131]
The README.md (on lines 129 - 130) file states that "Dart is substantially easier to learn than Ruby" as of [commit ddefa9f](https://github.com/sass/dart-sass/commit/ddefa9f95527fafd7748d6394018570f0922a89d). IMHO, this is more of an opinion than a fact. I feel that the statement should be removed as it might be viewed negatively by Ruby programmers (potential contributors) unless the statement could be validated with at least some evidence.

**Comment by nex3** [comment]
I think it's pretty self-explanatory. Dart is similar to widely-used langauges like C#, Java, and JavaScript to a degree that Ruby is not. I don't see a strong need to elaborate on this in the README.

**Comment by preetpalS** [comment]
That argument is reasonable but in my experience I've never heard of Ruby being described as a difficult language to learn (I've honestly only heard of positive experiences from those I know who have learnt it).

**Comment by nex3** [comment]
We experienced very limited contributions to Ruby Sass, in large part because its user base (largely JS devs) didn't know Ruby and weren't interested in learning. The fact that Dart is closer to JS was part of our reasoning in choosing it as a new language, which is why it's in the README.

**Comment by preetpalS** [comment]
First of all I want to state that I like Sass and that I that I actually use it in all of my web projects, so I appreciate your work on the Sass compiler (and I in the past used your Emacs package [perpectives.el](https://github.com/nex3/perspective-el)).

I am not sure how you are able to determine the size of the JS developer user base of Sass (that I am curious to know) but I suspect that there are a lot of Ruby developers who use Sass as there are over 92.925 million downloads of the [sass gem](https://rubygems.org/gems/sass/versions/3.4.22).

Besides the fact that Sass was implemented in Ruby and the implications that has on the proportion of the Sass user base size which is able to contribute, I suspect there are other relevant issues (these are my just my perceptions/suspicions) that may account for the fact that you experienced very limited contributions to Ruby Sass including:

1. Sass is really well written and many users may have never encountered issues while using it (I have never encountered any issues) and didn't find a personal need to contribute.
2. Sass is widely used and that makes it more intimidating of a project to contribute to in general.
3. Sass is essentially a programming language implementation which raises the bar in terms of the knowledge needed to make meaningful contributions since many developers do not have experience or knowledge in the design and implementation of programming languages (which is a specialized domain that many may perceive (and perhaps rightly so) as requiring a mathematics/computer-science background).
4. Since Sass is a superset of CSS, contributing to Sass requires extensive knowledge and experience using CSS.
5. Sass's code base is not small and therefore requires a larger investment in time to get acquainted with in order to become able to understand and modify in a meaningful manner.

Again I use Sass, and hope you are able to get more contributors to the project by switching to Dart (although I suspect the path of least resistance (in terms of attracting contributors) may have been to choose JavaScript as the implementation language). I also apologize if this comment is perceived as being rude (which is 100% not my intent) but I felt that it might be useful (maybe just as a different perspective).
