### ISSUE TITLE
Internal server error: NoSuchMethodError: method not found: 'apply$2' on null

### ISSUE THREAD

**Issue by JacBian** [sass/dart-sass#1310]
![image](https://user-images.githubusercontent.com/8401855/118450275-99afaf00-b726-11eb-82c7-e650cf88d6e6.png)

**Comment by JacBian** [comment]
Today , update npm  devDependencies, appear the error

**Comment by JacBian** [comment]
![image](https://user-images.githubusercontent.com/8401855/118451608-04adb580-b728-11eb-8e3c-5e560a2cc86a.png)


receiver is undedined.  
![image](https://user-images.githubusercontent.com/8401855/118451684-17c08580-b728-11eb-9388-2c0f3e1e1369.png) 
i can't find solution 。。
help

**Comment by jathak** [comment]
It looks like this error is coming from an importer. Are you passing any [custom importers](https://github.com/sass/node-sass#importer--v200---experimental) into Sass?

To debug this beyond that, we'd need a more minimal reproduction of the issue.
