### ISSUE TITLE
Returning error with `@@` interpolation

### ISSUE THREAD

**Issue by dziul** [sass/dart-sass#1314]
have a project related to chrome extension: [Html inserter for your email](https://chrome.google.com/webstore/detail/inserir-html-na-mensagem/omojcahabhafmagldeheegggbakefhlh?hl=en). For now I am redoing its structure, to take advantage of the power of the webpack much more.

The chrome extesion, has a standard to implement internationalization (i18n) in which you can use variables to get the messages, example: `__MSG_appName__` or` chrome.i18n.getMessage('appName') `

But there are some [special variables](https://developer.chrome.com/docs/extensions/reference/i18n/#overview-predefined) that start with _@@_, for example `@@extension_id`.

These variables I can use directly in: css, js, html. Which are converted at the time of its execution in Chrome.

But now I'm using sass, typescript, html.

The problem I'm taking in the  _\*.scss_ file, I need to use the variable `__MSG_@@ extesion_id__` as a selector, example:

```scss
.__ MSG_@@extesion_id__ {
    display: block;
}
```

that way I get the error `SassError: expected selector.`. 

![image](https://user-images.githubusercontent.com/19353873/118885822-99eaae80-b8ce-11eb-9c45-b784e8228d0a.png)

I understand that the `@` is reserved for sass. Okay. With that I tested it on an [online converter](https://jsonformatter.org/sass-to-css), and it gave the same error.

As an alternative, I appealed to the interpolation, example:

```scss
.__ MSG_#{"@@"}extesion_id__ {
    display: block;
}
```

I received the same error - `SassError: expected selector.`

But in the [online converter](https://jsonformatter.org/sass-to-css), it worked as expected

![image](https://user-images.githubusercontent.com/19353873/118886252-154c6000-b8cf-11eb-9a79-17fa3dd3c501.png)

the rules in the webpack, is the basic one:

```js
{
  test: /\.scss$/,
  use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
}
```

is there any solution for this case?

> _sorry, i am not fluent in english, so i used google translator_

**Comment by stof** [comment]
well, the issue is that `.__MSG_@@ extension_id__` is indeed an invalid CSS selector.

The truth is that your CSS file using `__MSG_@@ extension_id__` is not actually a CSS file anymore: it is a template file for the templating syntax of the chrome extension builder. the CSS is the *output* of rendering the template, not the input (and so the input is free to use any syntax that is invalid CSS).

But when trying to use sass, you are now trying to make the output of Sass be that template. that's not supported. The output of a Sass compilation is CSS.

**Comment by dziul** [comment]
@stof , 

Exactly, it is an invalid _CSS_ selector, but it would be great to have an option to ignore this selector validation in this case. Just like the online tool I mentioned: https://jsonformatter.org/sass-to-css; When using interpolation, example: `.__MSG_#{"@@"}extension_id__` there is no error.

an option could be something like: `strictMode: false`.


But okay, I will make a plugin to meet what I need. Thank you very much 😉

**Comment by stof** [comment]
@dziul this online converter does not document anywhere which tool it uses to compile the Sass source you give it. But it is clearly not the official compiler. So what it compiles does not seem to be Sass, but their own Sass-like syntax.

> since when using `__MSG_\@\@extension_id__` does not trigger an error and works as expected.

`__MSG_\@\@extension_id__` is a valid CSS selector, as the `@` is escaped.

**Comment by dziul** [comment]
@stof , 

Sorry, I think the translators are not translating as expected, 

What I mentioned about using escaped, was referring to _dart-sass_ and not the online converter.

Using it this way does not trigger the error:

```scss
.__MSG_\@\@extension_id__{
  .example{
    display:block;
}
}
```
the output is `.__MSG_\@\@extension_id__ .example{ display:block; }`.



I will close this edition. Thank you for answering me.
