### ISSUE TITLE
Using the math:div function throws an expected newline error

### ISSUE THREAD

**Issue by tcitworld** [sass/dart-sass#1320]
## Environment
Node: v14.15.4
Dart-Sass: 1.33.0

## Reproduction code
```sass
@use "sass:math"

@debug math:div(12px, 4px)

```
`sass myfile.sass` outputs the following:
```
Error: expected newline.
  ╷
3 │ @debug math:div(12px, 4px)
  │            ^
  ╵
  test.sass 3:12  root stylesheet
```

Same when assigning to a variable, etc.

Am I missing something here? The issue is in Dart-Sass 1.32.12 as well.

**Comment by EtienneBruines** [comment]
I couldn't help but notice: why are you using a colon instead of dot?

```
math.div(1 / 2)
```

**Comment by tcitworld** [comment]
Nice catch, I failed a search & replace !
