### ISSUE TITLE
Handling multiline strings in grid-template-area

### ISSUE THREAD

**Issue by stevenle** [sass/dart-sass#1321]
What's the best way to handle multiline strings when using [grid-template-area](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas)?

Here's an example:

```
.foo
  grid-template-areas: "icon title"
                       "icon subtitle"
                       "body body"
```

This generates this error:

```
Error: Expected identifier.
   ╷
48 │     grid-template-areas: "icon title"
   │                                      ^
   ╵
```

Changing to a single line works (e.g. `grid-template-areas: "icon title" "icon subtitle" "body body"`), but it hurts readability.

**Comment by Awjin** [comment]
This is currently only supported in the SCSS syntax. For the indented syntax, see the tracking issue https://github.com/sass/sass/issues/216.
