### ISSUE TITLE
Limit the amount of printed warnings/errors

### ISSUE THREAD

**Issue by Awjin** [sass/dart-sass#1323]
In https://github.com/sass/dart-sass/issues/1319, an overwhelming number of deprecation warnings were printed to the terminal, forcing the user to end the process.

We should add a ceiling to the number of warnings that get printed to the terminal—100?—that, when surpassed, just prints the remaining count. Something along the lines of:

```bash
Warning: This is warning #1.

Warning: This is warning #2.

...

Warning: This is warning #${ceiling}.

${remaining count} more warnings.
```

**Comment by stof** [comment]
Rendering the remaining count will be tricky: warnings are rendered during the compilation, not at the end.

For errors, it is impossible to have multiple ones: reaching an error means the end of the compilation.

**Comment by Awjin** [comment]
We will also need a way to explicitly enable printing all warnings (e.g. with a `--verbose` flag).

**Comment by tobiasweibel** [comment]
Is there an option to hide all the deprecation warnings for version 1.*? In one of my projects we do have a dependency to [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L369) which probably won't get fixed.
