### ISSUE TITLE
20,000 lines of deprecation warnings - any way to disable these?

### ISSUE THREAD

**Issue by ffxsam** [sass/dart-sass#1324]
Since updating `sass` in my Vue project, I now have 20,000 lines of deprecation warnings from Vuetify, a third-party library that I have no control over. Is there some way to silence deprecation warnings completely?

**Comment by Awjin** [comment]
Duplicate of https://github.com/sass/dart-sass/issues/1319. We're actively working on a fix. Currently you can work around this by passing the `--quiet` flag to silence warnings.
