### ISSUE TITLE
after update latest version does errors 

### ISSUE THREAD

**Issue by YallaDealz** [sass/dart-sass#1325]
after update latest version does errors 

Recommendation: math.div($m, $grid-columns)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
94 │           margin-right: $m / $grid-columns * 100%
   │                         ^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VGrid/_grid.sass 94:25  @content
    node_modules/vuetify/src/styles/tools/_rtl.sass 3:5         rtl()
    node_modules/vuetify/src/components/VGrid/_grid.sass 93:9   root stylesheet

: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

so I tried to revert to the previous version but not able to do that 

I use nuxtjs latest version

**Comment by stof** [comment]
this is a warning, not an error (btw, you are missing the first line in the output, that mentions that it is a deprecation warning).

**Comment by YallaDealz** [comment]
but render noott completed to run nuxtapp 

ok i put full message

**Comment by stof** [comment]
> but render noott completed to run nuxtapp

I don't understand what you mean

**Comment by YallaDealz** [comment]
thank you, it's solved today after the latest update release for sass 1.35

**Comment by kelvshi** [comment]
> thank you, it's solved today after the latest update release for sass 1.35

where is the 1.35?

**Comment by Awjin** [comment]
I believe they meant version 1.34.0, which reduces the number of duplicate warnings.
