### ISSUE TITLE
whose bright idea was it to deprecate / for division?

### ISSUE THREAD

**Issue by bastinald** [sass/dart-sass#1328]

**Comment by nex3** [comment]
This is not an appropriate place or way to debate language decisions. We solicited comments for this change [two years ago](https://sass-lang.com/blog/request-for-commentsforward-slash-as-separator), and the change was duly reviewed and approved.

**Comment by bastinald** [comment]
> This is not an appropriate place or way to debate language decisions. We solicited comments for this change [two years ago](https://sass-lang.com/blog/request-for-commentsforward-slash-as-separator), and the change was duly reviewed and approved.

This is literally called "issues" and I'm raising an enormous issue that will require thousands of libraries to update their code once this becomes a breaking change. My main question was really more along the lines of why this change was necessary at all.

In the only discussion I found about this, [you were given a very specific reason](https://github.com/sass/sass/issues/2565#issuecomment-469911466) as to why this might be a bad idea. And abrasiveness aside, they are kind of right, no?

Even in CSS itself, we already have access to the `calc` function, which makes everything you're doing here a waste of your time that can be better spent petting kittens, going for walks on the beach, and listening to T-Pain.

Have a nice day :)

**Comment by moleCuleFFF** [comment]
You can close and try to shut down ordinary developers views all you like but plenty of devs will be very unhappy about this.

**Comment by bastinald** [comment]
This whole debacle gave me the final push I needed to embrace tailwind. 

Goodbye and thanks for all the shoes.
