### ISSUE TITLE
Clarification about the supported statements inside a for loop in a at-rule

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1337]
I'm currently rewriting the parser of scssphp from scratch, by porting the dart-sass one (this will solve lots of issues we have with cases where our existing parser is not compliant). While doing so, I found a weird thing in the dart-sass parser, which I think might be a bug rather than an intended feature.

When parsing at rules inside property declarations, the dart-sass stylesheet parser uses a different `child` callback for `@for` than for other at rules (`@each`, `@if` and `@while`). It will only allow other at rules as child instead of also allowing property or variable declarations. Is it actually intended or should it use  `_declarationChild` like the others ?

https://github.com/sass/dart-sass/blob/b098adb289cee3a16ac265e6cc69e1afcef10802/lib/src/parse/stylesheet.dart#L677-L685

**Comment by nex3** [comment]
You're right, this is a bug. Are you willing to send out a pull request for it?

**Comment by stof** [comment]
sure
