### ISSUE TITLE
Custom importers result is ignored

### ISSUE THREAD

**Issue by marvinhagemeister** [sass/dart-sass#1341]
## Steps to reproduce

1. Clone repo https://github.com/marvinhagemeister/sass-importer-bug
2. install packages via `npm install`
3. run `npm test`

## Expected outcome

Running `npm test` prints `SUCCESS`.

## Actual outcome

Sass calls the custom importer but seems to ignore the result. It then errors because it cannot find the `$color` variable, which is only present in the file that was resolved in the custom importer.

```bash
Error: Undefined variable.
  ╷
4 │   background: $color;
  │               ^^^^^^
  ╵
```

**Comment by semoal** [comment]
Hello Marvin! 

Actually I saw that modifying a bit your code in the importer, I got it working:

### renderSync

> Here you can't use done() callback, you should use just the return. This is not documented, just try/error..

```js
function run() {
  const css = sass.renderSync({
    file: path.join(__dirname, "src", "index.scss"),
    importer: (url, prev) => {
      if (/my-aliased/.test(url)) {
        const resolved = path.join(__dirname, "src", "foo.scss");
        console.log("--> rewriting", url, "to", resolved, "\n");
        return { file: resolved }
      }
    },
  });

  console.log(css.css.toString())
}
```

### render

> Here you must use the callback

```js
function run() {
  sass.render({
    file: path.join(__dirname, "src", "index.scss"),
    importer: (url, prev, done) => {
      if (/my-aliased/.test(url)) {
        const resolved = path.join(__dirname, "src", "foo.scss");
        console.log("--> rewriting", url, "to", resolved, "\n");
        done({ file: resolved });
      }
    },
  }, (exc, result) => {
    if (exc) {
      console.error(exc)
    }
    console.log("SUCCESS", result.css.toString());
  });
}
```

I think the main problem was the promisify part which is not working properly. Hope this helps you. I found this iterating over my issue (https://github.com/sass/dart-sass/issues/1342)

**Comment by jathak** [comment]
Yes, it looks like this is due to mixing Promises and callbacks, not anything to do with Sass itself. Performance is generally better with `renderSync` anyway, so since your importer is synchronous, it makes more sense to use that instead of promisifying `render`.

**Comment by marvinhagemeister** [comment]
@semoal Ohh that makes a lot of sense! I totally missed that, thanks for clearing it up 👍
