### ISSUE TITLE
`~/path`, becomes in `Can't find stylesheet to import`

### ISSUE THREAD

**Issue by semoal** [sass/dart-sass#1342]
Hi Sass folks 👋,

Actually I'm migrating an internal project which used node-sass under the hood to this new implementation of sass, and everything worked fine but imports with `~monorepo-symlinks` paths didn't work.

The package it's linked with `yarn workspaces` in the node_modules, and accessing through vscode works fine, also worked fine in node-sass.

### Actual workaround:
The actual workaround is to remove the `~`, and correctly points to the node_modules root including it to the includePaths property.

But I'm worried because a lot of clients inject his scss with our tool, and they probably point some references with ~

### Possible solution

Indicate to sass to follow symlinks?

### Reproduction repo: 
https://github.com/semoal/sass-importer-bug

**Comment by semoal** [comment]
Found a proper solution for this, is this a correct approach?

```js
    importer: (url, prev, done) => {
      if (url.startsWith("~")) {
        const resolved = require.resolve(url.replace("~", ""));
        done({ file: resolved });
      }
    }
```

**Comment by semoal** [comment]
I saw that sometimes it fails:

```sh
(node:7888) UnhandledPromiseRejectionWarning: Error: Error: done is not a function
  ╷
1 │ @import "~@project/css/index.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/index.scss 1:9  root stylesheet
    at Object._newRenderError (/Users/sergio.moreno/OSS/sass-importer-bug/node_modules/sass/sass.dart.js:13190:19)
```

**Comment by jathak** [comment]
The `~` syntax isn't something that Sass supports directly. It's a feature of Webpack's Sass loader. If you're not using Webpack (or some other custom importer that supports it), Sass handles it like any other file URL.
