### ISSUE TITLE
calling dart-sass from C

### ISSUE THREAD

**Issue by aep** [sass/dart-sass#1354]
since libsass is now deprecated, it's unclear how to compile sass from something not javascript.

dart2native appears to only compile to an executable, which makes sense if it requires a VM.

Is this simply no longer an option and sass can no longer be used on platforms not supported by nodejs?

**Comment by jathak** [comment]
There isn't a direct API, but you can use [the Embedded Sass protocol](https://github.com/sass/embedded-protocol) to call out to an [embedded version of Dart Sass](https://github.com/sass/dart-sass-embedded).
