### ISSUE TITLE
Async importer fails if it returns a `Promise`

### ISSUE THREAD

**Issue by marvinhagemeister** [sass/dart-sass#1357]
There seems to be a missing check when it comes to the return value. When function starts with an `async` keyword it will return a `Promise` object, regardless of whether the `return` keyword is present in the function body or not.

When `dart-sass` encounters that the value passed into `done` seems to be ignored. Returning the value doesn't work either.

```js
// Works
(url, prev, done) => {
  done({ file: url, contents: "main {color: blue}" });
}

// Works
(url, prev) => {
  return { file: url, contents: "main {color: blue}" };
}

// Doesn't work
async (url, prev) => {
  return { file: url, contents: "main {color: blue}" };
}

// Doesn't work
async (url, prev, done) => {
  done({ file: url, contents: "main {color: blue}" });
}

// Doesn't work
(url, prev, done) => {
  return Promise.resolve({ file: url, contents: "main {color: blue}" });
}
```

Full reproduction case:

```js
const sass = require("sass");

sass.render(
  {
    data: `@import 'foo.scss';`,
    importer: [
	  // Works without the async keyword, but not with it
      async (url, prev, done) => {
        done({ file: url, contents: "main {color: blue}" });
      },
    ],
  },
  (err, result) => {
    console.log(result.css.toString());
  }
);
```

**Comment by nex3** [comment]
This is consistent with the behavior of Node Sass. *Any* object that's returned from an importer callback will cause it to be treated as synchronous, even if that object doesn't have `file` or `data` fields. You must return `undefined` to tell Sass to wait for `done()`. If you want to use `await`, you can write it in an IIFE:

```js
sass.render({
  importer: [
    (url, prev, done) => {
      (async () => {
        // ...
        done(/* ... */)
      })();
    ]
});
```

**Comment by marvinhagemeister** [comment]
> Note that the new importer API (sass/sass#2509) will be entirely promise-based and won't have this problem.

Awesome, really excited for this API 👍
