### ISSUE TITLE
quiet-deps isn't quieting dependencies

### ISSUE THREAD

**Issue by jdelStrother** [sass/dart-sass#1360]
In [this sample project](https://github.com/jdelStrother/sass-quiet-deps), if I run `yarn sass --load-path=./node_modules --quiet-deps ./style.scss`, I get deprecation warnings from Bootstrap - eg:

```

$ yarn sass --load-path=./node_modules --quiet-deps ./style.scss

Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    bootstrap/scss/_variables.scss 302:31  @import
    style.scss 2:9                         root stylesheet
```

From a debugger I can see that in here - 

```js
    _warn$3$deprecation: function(message, span, deprecation) {
      var _this = this;
      if (_this._quietDeps && _this._inDependency)
        return;
      if (!_this._warningsEmitted.add$1(0, new S.Tuple2(message, span, type$.Tuple2_String_SourceSpan)))
        return;
      _this._evaluate$_logger.warn$4$deprecation$span$trace(0, message, deprecation, span, _this._evaluate$_stackTrace$1(span));
    },
```

_this._quietDeps is true and _this._inDependency is false, but I'm struggling to figure out why `bootstrap/scss/_variables.scss` might not be considered a dependency.

**Comment by cedx** [comment]
Same issue here: the `--quiet-deps` flag worked as expected with Sass v1.34.1, but after upgrading to v1.35.0 it doesn't work anymore.

**Comment by strarsis** [comment]
+1, just noticed the same thing after updating `sass` to `1.35.0`.
The `quietDeps` option is passed - but apparently `sass` is unable to correctly determine what files are `deps` to be skipped.

**Comment by jdelStrother** [comment]
Thanks @nex3 !

**Comment by xavierfoucrier** [comment]
Hello @nex3,

What about files that I `@use` and that contain `@forward` of an external dependency?
Should the `quietDeps` flag work in this case?

Thanks!

**Comment by alexbuznik-stark** [comment]
Happening to me on 1.80.3

**Comment by nex3** [comment]
> Happening to me on 1.80.3

Can you file a separate issue with a reproduction?

**Comment by Aetherinox** [comment]
also getting it on `1.83.0`

```yml
      loader: 'sass-loader',
      options: {
          sassOptions: {
              outputStyle: 'expanded',
              quietDeps: true
          },
          sourceMap: !devMode
      }
```

**Comment by nex3** [comment]
@Aetherinox Same request as before, please file a separate issue with a reproduction.

**Comment by raph5** [comment]
Got the same issue in 1.80.0 and later versions with `darken` and `transparentize`

```
Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use color.adjust instead.

More info and automated migrator: https://sass-lang.com/d/import

    ╷
111 │     background-color: transparentize(darken($primary, 60), 0.5);
    │                                      ^^^^^^^^^^^^^^^^^^^^
    ╵
    file:///home/raph/code/eve-market-browser/apps/website/scss/ui.scss 111:38  root stylesheet
```

It think this exemple will reproduce the issue
```scss
body {
  background-color: darken(white, 0);
}
```

I downgraded to sass 1.79.6 as a workaround and don't have the warnings anymore

**Comment by nex3** [comment]
@raph5 In order to understand why `--quiet-deps` isn't working how you expect, we need more than just a code snippet. `--quiet-deps` affects depenencies loaded *through importers*, so we'd need to know how you're loading the dependency you expect to be silenced.

**Comment by raph5** [comment]
Im using @ import. But actually I think this not related to the `--quiet-deps` flag the deprecation warning still appears without importing anything:

```
~ echo "p { color: darken(white, 0) }" | sass --stdin --silence-deprecation import,color-functions --quiet-deps

Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use color.adjust instead.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ p { color: darken(white, 0) }
  │            ^^^^^^^^^^^^^^^^
  ╵
    - 1:12  root stylesheet

p {
  color: white;
}
```

This may be related to #2418

**Comment by jdelStrother** [comment]
@raph5 Try this:

```shellsession
$ echo "p { color: darken(white, 0) }" | sass  --stdin --silence-deprecation color-functions,global-builtin
p {
  color: white;
}
```

(It would help if sass made it clearer exactly which deprecation it was warning about - it does say `Global built-in functions are deprecated`, but it's sometimes not obvious how to get from that to the exact deprecation-label you want to silence)

**Comment by nex3** [comment]
@jdelStrother That's a good point, I've put out https://github.com/sass/dart-sass/pull/2475 to fix that.

**Comment by jdelStrother** [comment]
Nice, thank you!
