### ISSUE TITLE
CLI switch for dry run (noemit)

### ISSUE THREAD

**Issue by IlBaffo** [sass/dart-sass#1361]
Hi,
I've read the docs for the command line interface but I couldn't find a way to prevent files from be outputted to disk like, for example, typescript does with [-noEmit ](https://www.typescriptlang.org/tsconfig#noEmit).

I ask this because I'm setting up a CI build for gated checkin (to prevent the commit of syntactically wrong files) and with libsass I used to do this with the js api interface.
Now since I'm on windows and I'm using the compiled exe file (because the js implementation much slower in my case) I can't use /dev/null or similar tricks.

If this is out of scope for the project I understand it but I'd like to find at least a workaround.

Thanks in advance.

**Comment by jathak** [comment]
Apparently `command > NUL` should work for Windows if you're looking for a workaround

**Comment by IlBaffo** [comment]
Kind of, in Powershell there is $null because NUL throws error.

```
PS D:\Temp\dart\dart-sass-1.35.1-windows-x64\dart-sass\src> .\dart.exe sass.snapshot style.scss 1> NUL
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:', call CreateFile, then use the FileStream constructors that take an OS handle as an IntPtr.
```

A combination of `1> $null` and ` $LASTEXITCODE` can be used to evaluate the result like this:

```
PS D:\Temp\dart\dart-sass-1.35.1-windows-x64\dart-sass\src> .\dart.exe sass.snapshot style.scss 1> $null
Error: Undefined variable.
  ╷
4 │     height: $err;
  │             ^^^^
  ╵
  style.scss 4:10  root stylesheet
PS D:\Temp\dart\dart-sass-1.35.1-windows-x64\dart-sass\src> $?
False
PS D:\Temp\dart\dart-sass-1.35.1-windows-x64\dart-sass\src> $LASTEXITCODE
65
```

I think I will use this for CI but the `noEmit` does more than that, it can be used to test-run the syntax of complex command lines, without writing to disk, and be a little more confident that removing only the flag should work.

I'm closing this since that would be probably a more complex feature request.

Thanks.
