### ISSUE TITLE
Permission error when invoking dart-sass in a Makefile

### ISSUE THREAD

**Issue by torenware** [sass/dart-sass#1365]
I'm working on golang based project, and drive my builds through a makefile.  I've just added sass to the stack, and am getting permission related error only when sass runs via make.

The Makefile looks like this:

```Makefile
# Inspire by -> https://medium.com/@olebedev/live-code-reloading-for-golang-web-projects-in-19-lines-8b2e8777b1ea

PID      = /tmp/nodemon-golang-project.pid
TMPL_FILES = $(shell find . -type f -name '*.tmpl') 
GO_FILES =  $(shell find . -type f -name '*.go')
CMD_FILES = $(shell find ./cmd -type f -name '*.go')
SASS_FILES = $(shell find ./scss -type f -name '*.scss')
APP      = ./app
CSS      = ./static/css/style.css

serve: restart
	@fswatch -o . | xargs -n1 -I{}  make restart || make kill

kill:
	@kill `cat $(PID)` || true

before:
	@echo "\nRESTARTED ..."

$(APP): $(GO_FILES) $(TMPL_FILES)
	echo $(GO_FILES)
	@go build -o $@ $(CMD_FILES)

$(CSS): $(SASS_FILES)
	@echo Generated CSS
	@sass scss/styles.scss static/css/style.css

restart: kill before $(APP) $(CSS)
	@$(APP) & echo $$! > $(PID)
	@$(CSS)

.PHONY: serve restart kill before scss
```

And the error I'm getting is

```bash
$ make serve

RESTARTED ...
Generated CSS
make: ./static/css/style.css: Permission denied
make: *** [restart] Error 1
```

Any idea why `sass` would annoy make in this manner?  It's killing make, as you can see, but does not seem to prevent make from recreating the `/static/css/style.css` file.

The sass binary is on MacOS Mojave installed via homebrew, version 1.35.1

**Comment by jathak** [comment]
We'd need more information to help debug this. There's a good chance the issue is something to do with make and its interactions with macOS, but it could also be a bug in the Dart SDK.

What permissions specifically does `static/css/style.css` have? How do those permissions change if you run Sass directly from the command line?

**Comment by torenware** [comment]
Turned out the missing "permission" was "execute" on the last line for $(CSS), which is not an executable :-)  Lack of understanding of Makefile syntax on my part.
