### ISSUE TITLE
Raise error on invalid output from importer function

### ISSUE THREAD

**Issue by mvolfik** [sass/dart-sass#1367]
I'm trying to use a [custom `importer`](https://sass-lang.com/documentation/js-api#importer) in my project and I was running into a weird "_Undefined variable_" error. I was debugging this for over two hours, and I just realized that I was returning `{content: "..."}` instead of content**s**. Please raise an error when importer returns seemingly nothing. `{contents: ""}` should be indeed ok, but returning `{ foobar: "a{color: red};"}` shouldn't make the import successful, but silently import nothing.

**Comment by jathak** [comment]
This is unfortunately something we're locked into with the current API, but the good news is that we're working on a [new JS API for importers](https://github.com/sass/sass/issues/2509), and it will be much more explicit about the required return values.
