### ISSUE TITLE
Importer never called when `file` option is used

### ISSUE THREAD

**Issue by marvinhagemeister** [sass/dart-sass#1370]
Just noticed that importer functions are only called when the `data` option is set. When only `file` is present they are never called.

Given a project with three files:

```scss
// foo.scss
$color: red;
```

```scss
// index.scss
@import "foo.scss";
body { background: $color }
```

```js
// index.js
const sass = require("sass");
const path = require("path");

let called = false;
sass.renderSync({
  file: path.join(__dirname, "index.scss"),
  importer: () => {
    called = true; // The importer is never called
    return { contents: "$color: blue;" };
  },
});

console.log("called importer:", called);
// logs: false
```

**Expected result:**

That the importer function would be called when encountering the `@import "foo.scss"` import.

**Actual result:**

The importer function is never called.

**Comment by marvinhagemeister** [comment]
FYI: This issue is not present in `node-sass`. There the importer function is called as expected.

**Comment by duzun** [comment]
I can confirm this is an issue.
I also try:

```scss
@import "foo.css";
@import url("foo.css");
```

Neither `importer`, nor my custom `url` function is invoke in this case.

I've created another custom function called `resolve`, and the only way it works is:


```scss
@import url(resolve("foo.css"));
```

Which results in a `@import url(...);` statement in CSS,
but I would like to do the actual import:

```scss
@import resolve("foo.css");
```

This does not work :(

**Comment by duzun** [comment]
BTW, a workaround is to remove the file extension, thus forcing it to invoke the importer:

```scss
@import "foo";
```
