### ISSUE TITLE
Cannot exported SCSS map/list variables for use in JavaScript

### ISSUE THREAD

**Issue by D-Pow** [sass/dart-sass#1381]
# Issue

`node-sass` allowed us to export all types of variables from SCSS files when using Interoperable CSS (ICSS). For example, I could write

```scss
// MyStyles.scss
$my-var: 500px;
$colors: (
    "light": #fff,
    "dark": #000
);

:export {
    myVar: $my-var;
    colors: #{$colors};
}
```

and then import it via

```javascript
import MyStyles from 'MyStyles.scss';

console.log(MyStyles.myVar);
// output: "500px"
console.log(MyStyles.colors);
// output: "(light: #fff, dark: #000)"
```

But apparently, `dart-sass` doesn't support this. Instead, it throws a compilation error:

```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: (light: #fff, dark: #000) isn't a valid CSS value.
   |
10 |   colors: #{$colors};
   |             ^^^^^^^
```

This happens regardless of if the `:export` is any of the following:

1. `colors: $colors;`
2. `colors: #{$colors};`
3. `colors: "#{$colors}";`

As the "new and improved" `node-sass`, it seems like something as basic as this should be supported. It is clearly an important feature based on [how](https://www.npmjs.com/package/sass-export) [many](https://www.npmjs.com/package/Sass-JSON) [different](https://www.npmjs.com/package/sassyjson) [packages](https://www.npmjs.com/package/sass-vars-to-json) [have](https://www.npmjs.com/package/sass-json-export) [been](https://www.npmjs.com/package/get-sass-vars) [made](https://github.com/nahody/postcss-export-vars) to solve this issue. (Granted, the ones I linked are for converting to JSON, but even if only the SCSS string representation for maps/lists were exported, the user could at least parse it themselves.)

EDIT:

I discovered that if I rewrite my export like below, the string is exported as expected, however, I still believe it should be a built-in feature rather than being offloaded onto the user to debug (it took me hours to figure out).

```scss
:export {
    colors: inspect($colors);
}
```

# Proposed solution

Any of the following would be acceptable solutions to this issue (listed in order of increasing efficacy):

1. Add a compiler option to export maps/lists using their string representations.
2. Do (1) automatically without requiring an option.
3. Add a compiler option to export maps/lists using their JSON string representations.
4. Add a new function in the built-in `sass:meta` module to convert variables to JSON strings (e.g. `meta.to-json()`).
5. Do (1) and (3)/(4) automatically so that `:export { myMap: $myMap }` is converted to `myMap` and `myMapJson`, allowing users to pick which one they want, e.g.

    ```javascript
    import { myMap, myMapJson } from './styles.scss';
    console.log(myMap);
    // output: '(light: #fff, dark: #000)'
    console.log(myMapJson);
    // output: '{"light": "#fff", "dark": "#000"}'

    // or alternatively

    import { myMap } from './styles.scss';
    console.log(myMap.scss);
    // output: '(light: #fff, dark: #000)'
    console.log(myMap.json);
    // output: '{"light": "#fff", "dark": "#000"}'
    ```

6. Do (5) except automatically run `JSON.parse(myMapJson)` on the JSON string so users don't have to do it themselves.

**Comment by jathak** [comment]
Sass map syntax is not valid CSS syntax, so Sass will not support assigning a map to a property.

`:export` isn't a feature of Sass or standard CSS, so it's not something we support, as allowing this non-standard behavior could cause Sass to emit invalid CSS for users who don't use this feature. Node Sass's behavior here is incorrect.

**Comment by casp4** [comment]
I've got the same issue. What is the syntax we should replace it with then?  From ` colors: #{$colors};` to what?

**Comment by D-Pow** [comment]
For anyone returning to this later, the solution I found was to use the [ICSS module type in `css-loader`](https://github.com/webpack-contrib/css-loader#modules) since it [supports `:export` blocks](https://github.com/css-modules/icss#export). The syntax of the newest version of the loader might differ from what I have, but my [current config](https://github.com/D-Pow/react-app-boilerplate/blob/515c84306ba8370523f6c068635b54425f98ea19/config/webpack.config.mjs#L156-L159) uses:

```javascript
{
    loader: 'css-loader',
    options: {
        modules: {
            // Don't default to CSS-Modules; parse as normal CSS
            compileType: 'icss',
        },
    },
},

// allows
:export {
    myVar: $my-var;
}
```

However, it gets more complicated for maps. You have to either convert them to strings from [within the SCSS files themselves](https://github.com/D-Pow/react-app-boilerplate/blob/515c84306ba8370523f6c068635b54425f98ea19/src/styles/Common.scss#L246) (likely more robust since it converts by type instead of by characters), or do the [string conversion in JS](https://github.com/D-Pow/react-app-boilerplate/blob/515c84306ba8370523f6c068635b54425f98ea19/src/utils/Scss.js#L37-L52) (still worked for me, but I haven't tested all edge cases).

e.g.

```javascript
/* File.scss
:export {
    myVar: $my-var;
    colors: #{$colors};
    colorsJson: json.json-stringify($colors);
}
*/

import Styles from 'File.scss';

const colorsParsedInScss = JSON.parse(Styles.colorsJson);
const colorsParsedInJs = JSON.parse(Styles.colors.replace('see regex in link above', '...'));
```

Note: Regardless of how you export the variables from SCSS, you can only use default imports in JS (see [this commit](https://github.com/D-Pow/react-app-boilerplate/commit/994c330303581ddc5b0547e89c4ce0a5e125cefe) for more details).

**Comment by farooqkz** [comment]
I'm facing a similar issue: A UI library I use, used `:export` and `node-sass` and now after switching to Dart SASS, I'm having problems. What is the standard way in Dart SASS to use import variables into Javascript?

**Comment by wojtekxtx** [comment]
> What is the standard way in Dart SASS to import variables into Javascript?

@farooqkz you may try `@import` directive. Classic JS-style import may also work.

**Comment by farooqkz** [comment]
> 

I have done so:

https://github.com/farooqkz/chooj/blob/parcel/src/ui/Header.js#L2

but the element is still unstyled.

The colors.scss file:

https://github.com/farooqkz/KaiUIv2/blob/master/src/theme/colors.scss
