### ISSUE TITLE
CSS charset is omitted in compressed output mode.

### ISSUE THREAD

**Issue by scream87** [sass/dart-sass#1387]
### Description

When `.scss` file holds some non-ASCII character, then sass is adding `@charset "UTF-8";` row to the begining of output. It works fine with `expanded` output mode, but does not work with `compressed` output mode.

### System parameters

- Operating System: Windows 10
- Node Version: 14.17.0
- NPM Version: 6.14.13
- sass: ^1.35.1

### How Do We Reproduce?

Follow instructions in this repo - https://github.com/scream87/sass-css-charset-bug

### Expected Behavior

Both output modes (`expanded` and `compressed`) will include `@charset "UTF-8";`

### Actual Behavior

Only in `expanded` output mode charset is included, in `compressed` it is omitted.

**Note:** Also discussed here https://github.com/webpack-contrib/sass-loader/issues/973#issuecomment-871402666

**Comment by stof** [comment]
In compressed mode, dart-sass outputs a BOM instead, which has the same effect for CSS parsers and is shorter

**Comment by nilesh-godhani** [comment]
> In compressed mode, dart-sass outputs a BOM instead, which has the same effect for CSS parsers and is shorter

Is there any provision to retain `@charset "UTF-8";` instead BOM in compressed CSS output? When we concatenate CSS with other CSS files, BOM character in between creates issue (it alters first selector in file after BOM, for Ex. .xyz{} to \uffef.xyz{}).

**Comment by nex3** [comment]
Naively concatenating CSS files is never safe. A `@charset` is _also_ not valid anywhere other than the beginning of a file. You should use a CSS-aware tool to combine CSS instead.
