### ISSUE TITLE
Improvement for message if a class uses @extends accidentally a second time

### ISSUE THREAD

**Issue by Jugibur** [sass/dart-sass#1393]
Hi,
I'm in the process of changing a third-party WordPress theme that still uses "@import" to "@use".
Thereby a class was extended via @extend a second time in two different files.
Following a simplified example:

File "import-for-extend.scss":
`
%to-extend {
  outline: 1px solid red;
}
.class1 {
  @extend %to-extend;
}
`
File "test.scss":
`
@use "import-for-extend" as *;
.class1 {
  @extend %to-extend;
}
`
With this constellation the following error message appears:
> Error: The target selector was not found.
> Use "@extend %to-extend !optional" to avoid this error.

Of course extending something a second time makes no sense but it took a while in this large Sass project to find out the reason. I think the Sass message should be informing about this equal extendings not that the selector was not found.

**Comment by Awjin** [comment]
Sorry for the late reply here. This looks like an actual bug caused by `@use`'s interaction with `@extend`.
