### ISSUE TITLE
Dead code in `url(...)` parsing 

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1399]
There exists dead code inside the parsing for  `url(...)`

https://github.com/sass/dart-sass/blob/main/lib/src/parse/stylesheet.dart#L2924-L2931

```dart
      } else if (next == $exclamation ||
          next == $percent ||
          next == $ampersand ||
          (next >= $asterisk && next <= $tilde) ||
          next >= 0x0080) {
        buffer.writeCharCode(scanner.readChar());
      } else if (next == $backslash) {
        buffer.write(escape());
```

The issue lies in `(next >= $asterisk && next <= $tilde)` -- `$backslash` lives within this range, and so the condition immediately following is never hit.

Normally I'd send a PR to remove this, but I wanted to clarify the behavior here w.r.t. the parsing of escape sequences inside `url(...)`

**Comment by connorskees** [comment]
This has implications in the resolution of escape sequences inside `@url`. 

The input
```css
a {
  color: url(\61x);
}
```
will generate
```css
a {
  color: url(\61x);
}
```

**Comment by nex3** [comment]
Yes, this is a bug. It's more dire than just the example you posted: `url(\))` is valid CSS but will be rejected by Sass.
