### ISSUE TITLE
Feature Request: Autoprefixing in compiled output

### ISSUE THREAD

**Issue by dELUSION-MS** [sass/dart-sass#1400]
First of all I love Sass, and I use Dart Sass to much. 
Every time I use dart-sass to compile scss I have to **_again compile the output file for adding Browser prefixes_**.
So if dart-sass provide an option to enable **autoprefixer** then it would be a huge time and work saver.

**Comment by Awjin** [comment]
Auto-prefixing CSS is outside of the scope of the Sass compiler, so it wouldn't make much sense to couple the postcss transformation to the compilation.
