### ISSUE TITLE
Unquoted if string fails to parse

### ISSUE THREAD

**Issue by connorskees** [sass/dart-sass#1405]
Given the following input,
```scss
@#{if} true {}
```
`dart-sass` will give the following error,
```scss
Error: expected "(".
  ╷
1 │ @#{if} true {}
  │      ^
  ╵
```

Other @-rules do not exhibit this behavior, and instead appear to be recognized as unknown @-rules. For the following input
```scss
@#{while} true {}
@u#{s}e "sass:color";
@#{for} $i from 0 through 5 {}
@#{import} "foo.scss";
```

`dart-sass` will emit

```css
@while true {}
@use "sass:color";
@for $i from 0 through 5 {}
@import "foo.scss";
```

**Comment by jathak** [comment]
It looks like this applies to any interpolation of `#{if}`, and likely has something to do with the top-level `if` function.

**Comment by jathak** [comment]
Actually, it's even more than this. It looks like any attempt to parse `if` as an unquoted string causes this error (e.g. `a { b: if }`)

**Comment by connorskees** [comment]
Ran into this in another context, same issue occurs with
```scss
a {
  color: \69 \66;
}
```
Not sure how `dart-sass` handles escape sequences, apologies if this is redundant.
