### ISSUE TITLE
JS Api for Quiet

### ISSUE THREAD

**Issue by Brian-Bartels** [sass/dart-sass#1408]
We can pass quietDeps but if we are running the tool through grunt or other automation we can't run regular quiet

**Comment by jathak** [comment]
FYI: The new Logger API we're working on will support this.

**Comment by Brian-Bartels** [comment]
That's awesome thanks. In the mean time I rewrote process.stderr to be a no-op just for sass (it's a bit messy oops). One other observation is that the warnings seem to be written to stderr, whereas actual errors are written to stdout. Is this just a side effect of dart?

**Comment by stof** [comment]
@nex3 @jathak this should be closed now that the new JS API is released
