### ISSUE TITLE
Case-sensitive @use statements

### ISSUE THREAD

**Issue by arogers-enthink** [sass/dart-sass#1415]
### Issue
I have recently had some difficulties debugging why some CSS was being duplicated after compilation, and it turned out to be one @use statement with different case/capitalization on the filename.

Simple replication example using Bootstrap:
- `vendor\bootstrap.scss` file on file system with numerous `@import` calls to chosen core features of bootstrap, (in other words, something that will output some CSS):
```
// ...
@import "node_modules/bootstrap/scss/variables";
// ...
@import "node_modules/bootstrap/scss/grid";
// ...
```
- `main.scss` file:
```
@use 'abstracts/mixins';
@use 'Vendor\Bootstrap;
```
- `mixins.scss` file:
```
@use 'vendor/bootstrap';
// ... some code that might use a variable or such from Bootstrap 
```

Notice the different first-letter capitalization on the @use statement, this resulted in double the bootstrap CSS!

### Desired solution

I do not presume to label this a bug as I do not know if there are reasons to allow this, in other languages for example? For now I would simply ask if you would consider adding a second "Heads Up!" box at the top of the [@Use at-rule documentation page](https://sass-lang.com/documentation/at-rules/use) warning people about case-sensitivity.

### Additional context

This was extremely difficult to identify in a project with a lot of moving parts. I had recently done some package updates to dart-sass etc., and it took a long time to work out if it was them while referencing the changelog. I have complex Gulp tasks that are responsible for compiling the Sass, along with other steps, which created a long list of things to try for debugging (sass-glob, sourcemaps, etc.). I have other tools installed in Visual Studio /  .NET Core that could have been impacting compilation. I know this sounds like a personal problem, but this is the kind of thing that could make someone cry/drink/whatever! Hopefully you can come up with something to help the next poor soul. 

Thanks for your time.

**Comment by arogers-enthink** [comment]
Shower thought: perhaps even a warning during compilation that there are two namespaces that are the same just different case.

**Comment by jathak** [comment]
`@use` and other rules use URLs to refer to dependencies, not filepaths. URLs are always treated as case-sensitive, so this behavior is intended.

We can't add a warning about URLs that differ only in case because we can't reliably and efficiently determine whether those two URLs actually refer to the same file or not.

You're right that this should be clearer in the documentation, so I've filed sass/sass-site#566 to add a clarification about this to the documentation.

**Comment by nex3** [comment]
See also https://github.com/nodejs/node/issues/24942 and https://github.com/dart-lang/sdk/issues/35370, where I requested APIs that would make it possible to efficiently determine the real case of a file on disk.
