### ISSUE TITLE
Releases loop?

### ISSUE THREAD

**Issue by rijkvanzanten** [sass/dart-sass#1422]
Hi there!

Just noticed that there were a lot of patch releases in rapid succession seemingly without any changes. Just wanted to check in if that's expected or if a CI/CD process went for a loop 🔁 

Cheers, and thanks for all the amazing work!

**Comment by jathak** [comment]
It's expected. There's no actual changes, but each release was manually initiated as we were debugging some issues with releasing the [`sass_api` package](https://pub.dev/packages/sass_api).
