### ISSUE TITLE
sass generate empty file in watch mode

### ISSUE THREAD

**Issue by javadbat** [sass/dart-sass#1424]
I use this library to compile my ".scss" file and it work really good without any problem but in watch mode after some file save it start to produce empty file. I restart app and it compile successfully again.
my watch file is in this link:
[sass builder file](https://github.com/javadbat/hybrid-boilerplate/blob/facc838593f931b9483cb8bd3d1cbf35d7866541/Command/Build/SassBuilder.js)
I don't know is this is my watcher problem or sass  problem or even windows file system

**Comment by jathak** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
