### ISSUE TITLE
sourceMapEmbed and sourceMapContents doesn't work as expected while compiling to string 

### ISSUE THREAD

**Issue by JohnyCilohokla** [sass/dart-sass#1425]
I'm using the library to compile the scss during runtime by using renderSync and modifying the require function to inject the compiled scss into the dom, I want to embed the sourceMap and the source to css output.

The following will not work:
```
let rendered = sass.renderSync({
	file: "./source/test.scss",
	sourceMapContents: true,
	sourceMapEmbed: true
});
let style = rendered.css.toString();
```

This code will also not work:
```
let rendered = sass.renderSync({
	file: "./source/test.scss",
	sourceMap: true,
	sourceMapContents: true,
	sourceMapEmbed: true
});
let style = rendered.css.toString();
```

I could only get it to work by specifying the sourceMap parameter as a string, but I would expect that to produce a file for the sourceMap, like so:
```
let rendered = sass.renderSync({
	file: "./source/test.scss",
	sourceMap: "",
	sourceMapContents: true,
	sourceMapEmbed: true
});
let style = rendered.css.toString();
```

Expected behavior: sourceMapEmbed and sourceMapContents should still work while compiling to string, either by having the sourceMap set to true or not requiring sourceMap to be set at all.

**Comment by jathak** [comment]
It's unintuitive, but the [JS API docs](https://github.com/sass/node-sass#sourcemap) do specify that `sourceMap: true` will be ignored if `outFile` is not set. Passing a string when you want an embedded source map is indeed what you should do here.

We do have a proposal out for a new JS API (that's not yet available, but will be in the future) if you have any comments on it: https://github.com/sass/sass/issues/3056
