### ISSUE TITLE
Error if filename starts with number

### ISSUE THREAD

**Issue by claudia-romano** [sass/dart-sass#1436]
Hi there, is it possible to use a number as the first character of a file name? I get the 'Invalid Sass identifier' error if the filename starts with a number:
```
Error: Invalid Sass identifier "3d-cards"
   ╷
14 │ @use "components/_3d-cards.scss";
```

Thanks!

**Comment by stof** [comment]
you need to alias it as to a valid identifier instead of relying on the auto-generated one that takes the file name (as the file name does not produce a valid identifier):

```scss
@use "components/_3d-cards.scss" as cards;
```

**Comment by claudia-romano** [comment]
Thank you!
