### ISSUE TITLE
[Question] Does render/Sync() support option for source maps URL as 'relative'?

### ISSUE THREAD

**Issue by jordwms** [sass/dart-sass#1437]
I am troubleshooting a runtime issue with absolute paths in the compiled source map. When running from the CLI, dart-sass compiles source maps with relative paths, as expected. However, when running in JS using `sass.render()` or `sass.renderSync()` the source maps are generated with absolute paths. This is problematic as the generated source maps' URLs point to where they are found on my local storage rather than where a user can access them from relative web directory.

I have been unable to determine any options I can pass to these functions to generate relative source map URLs. Is there something I am missing?

**Comment by jathak** [comment]
Unfortunately, this isn't supported. You can `JSON.parse(result.map)` and modify its URL if you need it to be portable.
