### ISSUE TITLE
[Question] Is there any possibility to import JSON into SCSS?

### ISSUE THREAD

**Issue by krutoo** [sass/dart-sass#1439]
Hi. In my project i use `sass` npm package trough webpack and sass-loader, and i want to import json inot my scss file.

I found this solutions:
- https://www.npmjs.com/package/node-sass-json-importer
- https://github.com/vigetlabs/sass-json-vars

but I do not know if it is possible to use them together with dart-sass.

How can i configure dart-sass trough sass npm pacakge for using json imports?

**Comment by stof** [comment]
node-sass-json-importer *should* work, as the JS API exposed by dart-sass is the same than the node-sass one, and so supports passing custom importers. But I haven't tried it.
sass-json-vars won't work, as it is a ruby gem extending the dead ruby-sass implementation.

**Comment by jathak** [comment]
Closing, as `node-sass-json-importer` should work, and if not, a bug should be filed against it instead of here.
