### ISSUE TITLE
Start Sass watch and only compile assets if required

### ISSUE THREAD

**Issue by mangelozzi** [sass/dart-sass#1442]
Is it even possible, if yes what is the combination of command line flags to get SASS to start start monitoring for changes, and comile only if a changes occurs.

To me something like `--watch --update`. What is the difference between watch with the update option, and without, it seems to behave the same.

I think the default behaviour is good and applicable most of the time, just would be advantageous to be able to control whether to compile at start up or not with watch.

**Comment by jathak** [comment]
I'm a little confused as to what you're asking for. `--watch` should already work like `--update`, in that it won't recompile files that are already up-to-date.
