### ISSUE TITLE
Tabs in Sass files still don't work

### ISSUE THREAD

**Issue by wortwart** [sass/dart-sass#1461]
I'm opening a new ticket as the old one was closed but the problem still exists:

https://github.com/sass/dart-sass/issues/87

I switched to dart-sass today and can't compile my project anymore because I'm using tabs in my project. The code is in Sass-syntax. I'm amazed that such an error remains in the product for 4 years.

**Comment by stof** [comment]
Can you please provide a reproducer ? #87 has been fixed in dart-sass years ago.

**Comment by wortwart** [comment]
I found out what went wrong. I used a 3rd party stylesheet (based on https://github.com/dangvanthanh/carousel.sass/blob/master/carousel.sass) and converted it to tab indentation which I use throughout the project. The file has a JSDOC style header, so several lines at the top are indented with a single space, like that:

`/**
 * some metadata ...
 */
`

Every line indented with tabs now results in an error. As this was unfortunately the first file in the buildchain I didn't realize this is an edge case. In node-sass there never was a problem, though.

[test.sass.txt](https://github.com/sass/dart-sass/files/7110561/test.sass.txt)

**Comment by Awjin** [comment]
In the indented syntax, Sass also expects comments to have correct indentation. In this case, you need to convert your JSDoc-style comment to a Sass-style comment. See the [Sass comment documentation](https://sass-lang.com/documentation/syntax/comments#in-sass).

**Comment by wortwart** [comment]
For anyone who has this problem:
- JSDoc with tab indentation is highly unusual but seems to work
- Automatic conversion from spaces to tabs might miss JSDoc indentation because it's only a single space
- I still think dart-sass should ignore JSDoc as obviously node-sass did
