### ISSUE TITLE
Capturing warnings

### ISSUE THREAD

**Issue by unilynx** [sass/dart-sass#1474]
As far as I can see, there's no real way to capture the warnings generated by dart-sass (it looks like I might be able to monkeypatch the function dart sends its output to). It would be nice to be able to capture the warnings, ideally as an array of filename,linenumber,warning

**Comment by stof** [comment]
When using the Dart API, you can get them thanks to the Logger API.
When using the legacy JS API inherited from node-sass, there is indeed no way to configure the logger. This will change with the new JS API that is being worked on. See https://sass-lang.com/blog/request-for-comments-new-js-api

**Comment by jathak** [comment]
@stof's response here is correct. For Dart, use the existing Logger API. The equivalent in the new JS API is tracked here: https://github.com/sass/sass/issues/2979
