### ISSUE TITLE
Thanks for the gift ;-)

### ISSUE THREAD

**Issue by julmot** [sass/dart-sass#1490]
Release [v1.40.0](https://github.com/sass/dart-sass/releases/tag/1.40.0) introduced a breaking change...:

> calc() expressions will be parsed more thoroughly, and errors will be highlighted where they weren't before. **This may break your stylesheets**, but only if they were already producing broken CSS.

...but it was shipped with a patch level version. This caused effort on my end to debug and get poorly developed CSS files of plyr up and running ([reference](https://github.com/sampotts/plyr/issues/2323)).

I totally agree that the issue here isn't dart sass, rather CSS files that contain unsupported statements. However, introducing this should have been done with a major version. I'd really appreciate following [semver](https://semver.org/) here.

Thanks!

**Comment by nex3** [comment]
We don't consider changes that only cause errors for CSS that was already invalid to be "breaking". If you're writing invalid CSS, you're effectively outside of the officially-supported API surface of the Sass language. I understand that this can cause some pain when updating for users who don't run validity checks, but the alternative is *constantly* bumping the major version which has many downsides: it forces a lot of churn on downstream users, it encourages users to get stuck on outdated versions, and it makes it much harder to tell when changes are coming that will *actually* break valid code.
