### ISSUE TITLE
Unknown property: 'content-visibility'

### ISSUE THREAD

**Issue by 6643** [sass/dart-sass#1491]

**Comment by stof** [comment]
where are you getting this message ? dart-sass does not enforce using known properties.

**Comment by 6643** [comment]
svelte style scss

**Comment by stof** [comment]
Please describe how to reproduce the issue, otherwise there is no way to help you (especially given that I don't use svelte and I have no interest learning it just to try guessing how to reproduce your issue).

**Comment by 6643** [comment]
![Screenshot from 2021-09-19 21-28-53](https://user-images.githubusercontent.com/3087856/133929380-09bfcc7b-db00-473f-914e-15974cefe620.png)

**Comment by stof** [comment]
I'm almost sure that this error does not come from the Sass compiler.

**Comment by 6643** [comment]
OK
thanks
