### ISSUE TITLE
The list of pseudo-selectors using the An+B micro syntax is incomplete

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1495]
The SelectorParser has a special handling of CSS pseudo-selectors using the An+B micro-syntax: https://github.com/sass/dart-sass/blob/52ef3c6ef17aec7cc1f9602671de666d35d0b0b3/lib/src/parse/selector.dart#L320-L330

However, this logic only handles `nth-child` and `nth-last-child`. this misses support from other pseudo-classes from CSS Selectors level 3 (which is a W3C recommendation):

- [`nth-of-type`](https://www.w3.org/TR/selectors-3/#nth-of-type-pseudo)
- [`nth-last-of-type`](https://www.w3.org/TR/selectors-3/#nth-last-of-type-pseudo)

Note that those 2 pseudo-classes don't use the `of <selector>` syntax that is supported by `nth-child` and `nth-last-child`.

**Comment by stof** [comment]
As this is about parsing CSS selectors rather than about a Sass feature, does it need to define a spec in https://github.com/sass/sass first ? Currently, there is nothing about parsing selectors in there, so I assume the CSS spec is normative in that regard.

**Comment by nex3** [comment]
Since `:nth-of-type()` and `:nth-last-of-type()` don't contain selectors, we don't need to do any special parsing for them. The default `InterpolatedDeclarationValue` that's used for the contents of unknown pseudo-selectors consumes (a superset of) the an+b syntax.

**Comment by stof** [comment]
OK, closing that then. I missed the fact that `declarationValue` is actually a superset of `aNPlusB`
