### ISSUE TITLE
Migrating from @import to @use when needing multiple instances 

### ISSUE THREAD

**Issue by mmestas** [sass/dart-sass#1505]
If I try using @use for my variables file, instead of @import, this only allows me to import the file ONCE, otherwise, I get a compilation error saying that module has already been imported.  If I only import it into one file at the top level, all the other files that need the global variables give the compile error that those variables are undefined.  

All examples I have found in your docs only show instances for ONE import of a file.  How do you handle the cases where the variables/mixins/functions need to be accessed across multiple files without using @import -( since you are deprecating this) and with the added complication that the file/module can only be loaded once - but not accessed everywhere?

**Comment by mmestas** [comment]
found an answer here: https://github.com/sass/dart-sass/issues/1084 but it's not allowing me to delete this issue

**Comment by stof** [comment]
@mmestas organizing related variables and functions in modules, instead of organizing them by type (which removes circular references, which are causing a chicken-and-egg problem with `@import` too anyway)
