### ISSUE TITLE
Versions v1.42.x broken (and maybe other previous ones...) 

### ISSUE THREAD

**Issue by jeanlescure** [sass/dart-sass#1512]
Our team had to downgrade back to `1.38.2` because latest versions are reporting errors that were not errors before:

![2021-09-25_19-47](https://user-images.githubusercontent.com/3330339/134790582-a7f33e5b-660e-4dfd-b104-f88bc063b37d.png)

The previous error happenes both with `v1.42.1` and `1.42.0`. Since this was affecting a time-sensitive deployment I simply switched `^1.38.2` to `1.38.2` on our `package.json` to revert to the last known stable version (to our knowledge).

NOTE: I think semantic-ui is using the syntax `--0.05rem - 1.2em` because what they mean is `-(-0.05rem - 1.2em)`, as in flipping the negative to positive or viceversa. Either way this detail is mostly irrelevant to the issue. The real issue is that something that used to work is now broken, and downgrading to a previous version fixes the problem.

**Comment by stof** [comment]
`calc(--0.05rem - 1.2em)` is invalid CSS. It is **not** the same than `-(-0.05rem - 1.2em)`

**Comment by jeanlescure** [comment]
Hi @stof , thanks for the prompt reply. I did state that it was a supposition on my end, and more importantly, irrelevant:

> Either way this detail is mostly irrelevant to the issue. The real issue is that something that used to work is now broken, and downgrading to a previous version fixes the problem.

I can see now that I should not have mentioned it.

Apologies.

**Comment by jeanlescure** [comment]
Now in hopes to get the conversation back on track.

This issue seems to be related to:

https://github.com/sass/dart-sass/issues/1496

There, it is reported Bootstrap 5 cannot be transpiled with dart-sass since v1.40.0

Here, I'm reporting that since v1.40.0, Semantic-UI cannot be transpiled.

So it seems to be less about valid vs invalid css and more about dart-sass being currently broken, given that it is unable to compile large-scale production-ready libraries that it had been able to compile without an problem in the past.

**Comment by stof** [comment]
@jeanlescure the case of semantic-ui is precisely broken since 1.40.0 **because** they were producing broken CSS, that is now caught by the dart-sass compiler. See the release notes: https://github.com/sass/dart-sass/releases/tag/1.40.0

> `calc()` expressions will be parsed more thoroughly, and errors will be highlighted where they weren't before. **This may break your stylesheets,** but only if they were already producing broken CSS.

**Comment by stof** [comment]
> This issue seems to be related to:
> 
> #1496
> 
> There, it is reported Bootstrap 5 cannot be transpiled with dart-sass since v1.40.0

This is not what is actually reported there. The failure only occurs in `create-react-app|, that does not run only the Sass compiler. Compiler Bootstrap directly works fine (and the dart-sass CI does it before each release).

**Comment by jeanlescure** [comment]
> @jeanlescure the case of semantic-ui is precisely broken since 1.40.0 **because** they were producing broken CSS, that is now caught by the dart-sass compiler. ...

Thanks @stof , truly, for corroborating that what I am reporting is true and correct 👍🏼 

Our project is a large-scale product with over 30 million weekly visits/interactions and over 2k dependencies maintained with blood, sweat, and tears, by a team of 10 developers, so you can imagine it is virtually impossible for us to keep track of the release notes for each of those 2k+ dependencies.

We trust that projects such as Sass will adhere to proper standards and in this instance it was not the case, since (as you so kindly helped to point-out @stof ) a breaking change was released with a minor version bump:

> ...See the release notes: https://github.com/sass/dart-sass/releases/tag/1.40.0
> 
> > `calc()` expressions will be parsed more thoroughly, and errors will be highlighted where they weren't before. **This may break your stylesheets,** but only if they were already producing broken CSS.

Breaking changes **should only be introduced as part of major version changes**, precisely to ensure that tools like npm/yarn/pnpm can install minor and patch versions when using the carat symbol `^` when determining a dependency version on the `package.json` (i.e. `^1.38.2` should be able to install `v1.42.1` [without introducing BREAKING CHANGES](https://www.conventionalcommits.org/en/v1.0.0/#how-does-this-relate-to-semver)).

> fix type commits should be translated to PATCH releases. feat type commits should be translated to MINOR releases. Commits with BREAKING CHANGE in the commits, regardless of type, should be translated to MAJOR releases.

_(source: https://www.conventionalcommits.org/en/v1.0.0/#how-does-this-relate-to-semver)_

And I think we can also agree on the fact that both the open source community and businesses should expect adherence to these standards by projects with the scope and scale such as that of Sass.

We are all in this together, we already learned that [11 lines of code are perfectly capable of breaking the internet](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/), and as such we should be more conscientious with our Open Source contributions.

**Comment by nex3** [comment]
Almost any behavioral change can in principle break existing downstream projects that are behaving badly. A bug fix can break a package that's somehow relying on that bug, a new method can break a package that's subclassing and adding a method with the same name, a more accurate type declaration can break users who were relying on implicit `any` conversion. In none of those cases do packages typically increment their major version numbers. Even semver ultimately comes down to human judgment calls.

This is the same sort of thing: invalid plain CSS is never valid input to the Sass compiler, but there are some cases where we historically haven't checked for it. When we add those checks in later, we'll inevitably cause build errors in some stylesheets that were previously only causing errors in the browser. We don't consider this a breaking change. From a more pragmatic perspective, if we *did* consider this a breaking change we'd need to increment the major version constantly which is much worse for the vast majority of users who have valid CSS and only minimally better for the few who already have invalid CSS.
