### ISSUE TITLE
Sass returns "Error: ("primary": #0075dd !important, ...) isn't a valid CSS value. When converting colors from Hex with !important to RGB

### ISSUE THREAD

**Issue by aLexiusxx** [sass/dart-sass#1517]
Whenever you try to convert a hexadecimal color into rgb with `!important` property, sass returns an error instead. For example:

```
@use "sass:color"

$color: "#ffbbcc"
$important-color: "#ffbbcc" !important;

// Sample function
@function toRGB($value) {
  @return color.red($value), color.green($value), color.blue($value)
}

// $color is passed to "toRGB" as "#ffbbcc" without the quotes
// and no problem.
$color-in-rgb: toRGB($color); 

// but $important-color is passed as "#ffbbcc !important" without
// the quotes and throws an error because while #ffbbcc is a valid
// CSS color in hexadecimal, !important is not!
$important-color-in-rgb: toRGB($important-color);
```

The same error also shows up when importing partials using "@use" but works fine with "@import"!

**Comment by jathak** [comment]
The `$color` variable you declare here is not a color value, but a string. Remove the quotes surrounding `#ffbbcc` to make it evaluate as a color that can be manipulated by the built-in color functions.

`!important` should only be used for CSS property declarations, not Sass variables. `$important-color` in your code is actually a list where the first item is the quoted string `"#ffbbcc"` and the second item is the unquoted string `!important`.
