### ISSUE TITLE
@extend compound

### ISSUE THREAD

**Issue by robocoder** [sass/dart-sass#1529]
I'm trying to migrate some old .scss (uses Bootstrap 2.2.1) to compile under dart-sass, and I ran into this breaking change:
* https://sass-lang.com/documentation/breaking-changes/extend-compound

The simplified original:
```
@import 'bootstrap';

button {
    i:before {
        @extend [class*=" icon-"]:before;
    }
}

a[role=button] {
    i:before {
        @extend [class*=" icon-"]:before;
    }
}

.button-reject {
    i:before {
        @extend .icon-trash:before;
    }
}

.button-edit {
    i:before {
        @extend .icon-edit:before;
    }
}

.button-new {
    i:before {
        @extend .icon-plus-sign:before;
    }
}

.button-new[role=button] {
    i:before {
        @extend .icon-plus-sign:before;
    }
}
```

Extending each simple selector:
```
@import 'bootstrap';

button {
    i:before {
        @extend [class*=" icon-"], :before;
    }
}

a[role=button] {
    i:before {
        @extend [class*=" icon-"], :before;
    }
}

.button-reject {
    i:before {
        @extend .icon-trash, :before;
    }
}

.button-edit {
    i:before {
        @extend .icon-edit, :before;
    }
}

.button-new {
    i:before {
        @extend .icon-plus-sign, :before;
    }
}

.button-new[role=button] {
    i:before {
        @extend .icon-plus-sign, :before;
    }
}
```

* With ruby sass 3.4.21, it compiles under a second (in a VM).
* With dart-sass 1.43.1, compiling the above appears to be stuck in a loop (consuming 100% CPU and over 1GB of memory before I killed the process).
* Remove any of the `@extend` lines to allow dart-sass 1.43.1 to compile the remaining file in under 2 seconds.

Is this the same as #1109?

**Comment by nex3** [comment]
A couple things to note here:

* As @stof points out, the suggestion of how to update compound extends doesn't produce the *exact same behavior*, it just produces the best approximation. The behavior in Ruby Sass was contrary to the stated semantics of the `@extend` rule and as such is considered undesirable.

* This difference in behavior is likely behind the slowdown. The `@extend` algorithm is exponential in the worst case, and your CSS is probably tickling that worst case by having many nested selectors extending many of the same base selectors.

When figuring out how to get `@extend` to do what you want, it's usually a good idea to think about it in terms of which elements should be styled like which other elements. In this case, it looks like you want `i` tags in buttons to be styled like icons. The fact that the `.icon-*` style rules use the `:before` pseudo-element as part of their styles is essentially an implementation detail; what you care about is that *`.icon-trash` shows a trash icon*. That suggests that you should have your `i` tags directly extend the `.icon-*` selectors:

```scss
@import 'bootstrap';

button i {
  @extend [class*=" icon-"];
}

a[role=button] i {
  @extend [class*=" icon-"];
}

.button-reject i {
  @extend .icon-trash;
}

.button-edit i {
  @extend .icon-edit;
}

.button-new i {
  @extend .icon-plus-sign;
}

.button-new[role=button] i {
  @extend .icon-plus-sign;
}
```

This way, `@extend` will *automatically* apply the `:before` styles to `i:before` for all of these classes, but it'll also include any non-`:before` styles that are necessary to set it up properly.
