### ISSUE TITLE
sass <input folder>:<output folder> copies over CSS files not compiled from SCSS

### ISSUE THREAD

**Issue by ChristianMay21** [sass/dart-sass#1543]
Hi. I'm using the `sass` npm library. Imagine I have a directory like this:

```
root
  ├ src
   | ├ header.scss
   | └ nav.css
  └ dist
```
  
 And then I run `sass src:dist`:
```
 root
 ├ src
  | ├ header.scss
  | └ nav.css
  └ dist
    ├ header.css
    └ nav.css  
```
For some reason, I get `nav.css` copied over to the `dist` folder as well as `header.css`. I want to move css compiled from scss - I do not want to be moving my css files that aren't built from scss. Is there a way to prevent this without having to manually compile each individual file?

**Comment by jathak** [comment]
This is working as indented, as `.css` files are valid input to the Sass compiler (just without any Sass-specific features). If you need more complex logic for deciding which files to compile, you could implement it using the API for a shell script yourself.
