### ISSUE TITLE
calc(0 - 32px) is valid css but errors out in dart-sass

### ISSUE THREAD

**Issue by elirov** [sass/dart-sass#1544]
calc() requires same units, so calc(1 - 32px) should error out with: Value Error : max-width The types are incompatible 32px)

HOWEVER, 0 is treated as a special case and validates just fine with other units:
(as tested under https://jigsaw.w3.org/css-validator/validator)

this used to work under 1.39.2 but broke as of 1.40.0

in addition, svelte-material-ui/bare.css uses this pattern all over the place, and dart-sass simply hangs when trying to import their bare.css file.

When fixing their bare.css file by replacing all calc(0 ... with calc(0<UNIT> ..., then dart-sass completes happily.

**Comment by Awjin** [comment]
According to the spec, unitless 0 is not supported in `calc()`: https://www.w3.org/TR/css-values-3/#calc-type-checking. In this case Sass is providing the correct output. I would encourage you to file an issue with svelte-material-ui
