### ISSUE TITLE
Can't use CSS custom properties in SASS modules (sass:color)

### ISSUE THREAD

**Issue by Karmalakas** [sass/dart-sass#1546]
Having this issue with custom props

```css
  --color: 123,214,123;

  //color: scale-color(rgb(var(--color)), $lightness: -30%); // <-- Error: $color: rgb(var(--color)) is not a color.
  color: scale-color(rgb(123,214,123), $lightness: -30%); // <-- Works just fine
```

Found same [issue on node-sass repo](https://github.com/sass/node-sass/issues/2251), but neither uppercase nor sass variable solutions helped, Tried a lot of different approaches (including assigning to variables different parts)
Currently solved with mapping as suggested on [this SO post](https://stackoverflow.com/a/31008539/632687)

BTW:
```
sass --version
1.43.4 compiled with dart2js 2.14.4
```

**Comment by jathak** [comment]
This is expected. CSS custom properties are resolved at render time in browser, not compile time by Sass, so Sass doesn't know what the value of `var(--color)` is. Use Sass variables if you need to know their value at compile time.

**Comment by Karmalakas** [comment]
Makes sense. Thank you
