### ISSUE TITLE
`calc()` with different operators wrongly considered equal

### ISSUE THREAD

**Issue by oscarmarcelo** [sass/dart-sass#1548]
The following example:

```sass
@debug calc(40px + 2rem) == calc(40px - 2rem)
```

returns `true` when should return `false`, since there are different operators (`+` and `-`), which in CSS will produce different results.

However, the following does return `false`:

```sass
@use "sass:meta"

@debug meta.calc-args(calc(40px + 2rem)) == meta.calc-args(calc(40px - 2rem))
```

But I believe we shouldn't have to rely on `meta.calc-args()` to do this check otherwise we would have to always be checking for type `calculation`.

---

Using Dart Sass 1.43.4

**Comment by stof** [comment]
this is indeed a bug. I opened a PR with a fix
