### ISSUE TITLE
Unable to compile the sass files packaged inside a jar file in CLI

### ISSUE THREAD

**Issue by satmish** [sass/dart-sass#1549]
Hi,

I am using the dart-sass version: 1.43.4

I tried various ways to compile the sass files packaged inside a jar file in CLI. But the CLI tool is unable to read the file.
I tried several URL types to read the sass files packaged inside a JAR file, but I am unable to read the scss files.

As an example:
I have a scss "my-sass.scss" file inside sass-bundle.jar at /sass/theme path inside the jar.

I tried the following way to compile the sass file through CLI.
sass **file:/C:/jar-file/sass-bundle.jar!/sass/theme/my-sass.scss** temp1.css

But it's not getting compiled. I think sass CLI tool is not loading the scss file from the JAR file. Also I tried differrent combinations for JAR URL. But none worked.

If I can get some help for "how to compile the sass files present inside a JAR file", that will be really great. Also if this is an issue at present, can this issue be fixed?

Also, I am unable to load the path using load-path CLI option from a JAR file, where the SCSS files are packaged.

I tried the following CLI command to load the path from JAR file:
**sass --load-path=file:/C:/jar-file/sass-bundle.jar!/sass/theme my-sass2.scss temp1.css**

where all the sass import paths are present at /sass/theme PATH inside the JAR file.

Also I tried several different URL to load path from a JAR file, but none worked.

If I can get some help for "how to load the import paths present inside a JAR file", that will be really great. Also if this is an issue at present, can this issue be fixed?

**Comment by jathak** [comment]
Sass loads files from the filesystem. If you want to load them from elsewhere, you need to make sure they're actually accessible there. I believe `.jar` files are just `.zip` files under the hood, so you should be able to extract the JAR and then pass the extracted files to Sass.
