### ISSUE TITLE
Sass-loader can't parse unicode-range value

### ISSUE THREAD

**Issue by nenravitsa** [sass/dart-sass#1551]
### Bug report

![image](https://user-images.githubusercontent.com/10672224/140926430-77da5ed8-cad3-45c5-85ec-50502842b74e.png)

### Expected Behavior

Range values should be preserved after compile.

### How Do We Reproduce?

```
{
          test: /\.scss$/,
          exclude: /\.module\.scss$/,
          use: [
            { loader: IS_DEV ? "style-loader" : MiniCssExtractPlugin.loader },
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                modules: {
                  mode: "icss",
                },
              },
            },
            {
              loader: "sass-loader",
              options: {
                implementation: require("sass"),
                sourceMap: IS_DEV,
              },
            },
          ],
        },
```

Adding @charset "utf-8"; to the top of the file didn't help

Webpack: 5.62.1
Sass-loader: 12.3.0
Sass: 1.43.4
Node: 14.17.6

**Comment by jathak** [comment]
Can you provide a minimal reproduction of the Sass code that causes this error?

**Comment by jathak** [comment]
Looking at this closer, I think your issue is that your unicode range syntax is wrong. You want `U+05B9-05F4` and `U+FB1D-FB4F`.
