### ISSUE TITLE
Importing only abstracts from a file

### ISSUE THREAD

**Issue by Mushr0000m** [sass/dart-sass#1553]
Hi,

I'm migrating to `@use` instead of `@import` and was thinking about my file structure. I often have mixins and variables for some components like `button` and sometime I need to use mixins from this component in an other component. I like the use of `@use`  because it make it clear that one component uses things from an other one, but with `@use` or `@import` it will give me access to those mixins and variable but also paste de css rules. So until now I have create separated folders for the actual components css rules and their abstracts, somehting like : 

```
abstracts/
--button
--input
components/
--button
--input
```

My question is, would it be possible in the future, to add the ability to import a file with `@use` and take only its non private mixins/variables/functions/placeholders, just so it does't write any css rules... It would help keep things in one place and not having to split the css rules from the abstracts for every of my components. something like : 

```
@use-abstracts "components/button";
// Or
@abstracts "components/button";
// Or
@use "components/button" without-css;
// Or
…
```
If I'm not the only one finding this usefull.

**Comment by Awjin** [comment]
I'm not sure I completely understand your use case. Would using [private module members](https://sass-lang.com/documentation/at-rules/use#private-members) solve this for you?

**Comment by Mushr0000m** [comment]
Sorry if I was not clear enough. I use private module members but it's not the things I'm talking about here. I'll try to explain a use case, imagine you have a file containing styles and mixins for a `.button` :
```
// components/button.scss
@mixin base() {
    // Some css rules
}
@mixin white() {
    background-color: white;
    // Some css rules
}
@mixin green() {
    background-color: green;
    // Some css rules
}
.button {
    // Some css rules
    @include base();
    
    &.is-green {
        @include green();
    }
    &.is-white {
        @include white();
    }
}
```
now I need to style other things with these mixins from `button` : 
```
// components/foo.scss
@use "components/button"
.foo {
    @include button.base();
    @include button.green();
}
// components/bar.scss
@use "components/button"
.bar {
    @include button.base();
    @include button.white();
}
```
By doing this the `.foo` and `.bar` classes will contain the right styles BUT it will also duplicate the whole style of `.button`. And I just want to import/use the mixins/functions/variables from the `button.scss` file not its actual style to be paste again.

From the [doc](https://sass-lang.com/documentation/at-rules/use) the definition of `@use` is  :
**"The @use rule loads mixins, functions, and variables from other Sass stylesheets, and combines CSS from multiple stylesheets together"**
My need would be to have : 
**"The @use rule loads mixins, functions, and variables from other Sass stylesheets, ~~and combines CSS from multiple stylesheets together~~"**

So right now I extract all these abstracts (mixins/functions/variables) in an other file in an other folder `abstracts/button` for my example. It's working but it makes it more difficult to reuse peaces of code or components in other project and it would make sense IMHO to have everything in a single and being able to only import these abstracts anywhere else without pasting the style. I hope there is already a way that I don't know about 🤷🏻‍♂️ but it looks more like a new feature...

**Comment by Awjin** [comment]
Usually, it's recommended to not write style rules in a shared module. Instead, you could split `components/button.scss` into two files:

`components/button/utils.scss`:
```scss
@mixin base() {
    // Some css rules
}
@mixin white() {
    background-color: white;
    // Some css rules
}
@mixin green() {
    background-color: green;
    // Some css rules
}
```

`components/button/index.scss`:
```scss
@use './utils';

.button {
    // Some css rules
    @include base();
    
    &.is-green {
        @include green();
    }
    &.is-white {
        @include white();
    }
}
```

This way, other components like `foo` and `bar` can `@use 'components/button/utils.scss'` without pulling in the button-specific style rules.

**Comment by Mushr0000m** [comment]
Ok so the way I'm doing it right now. I was hoping to have a more centralized way but I'll continue this way 😉. Thanks
