### ISSUE TITLE
Provide clarification within deprecation warnings regarding support for `/` as division operator within `calc()` functions

### ISSUE THREAD

**Issue by cccharle** [sass/dart-sass#1559]
The deprecation warning regarding support for `/` as a division operator indicates that users should switch to using `math.div()` instead of `/`. 

 ```

Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

```

However, as I only recently learned, **the deprecation of `/` as a division operator does not affect its use within `calc()` functions**. 

As the move away from `/` toward the arguably more cumbersome `math.div()` could be perceived as a deterrent for some — as it nearly was for me — it may be worth mentioning the continued support within `calc()` as part of the `/` deprecation warning.

**Comment by stof** [comment]
I suggest changing the recommendation from `math.div(1, 4)` to `math.div(1, 4) or calc(1 / 4)` instead, as first-class calc is now supported. What do you think @nex3 ?

**Comment by stof** [comment]
And https://sass-lang.com/documentation/breaking-changes/slash-div should probably be updated too to mention it

**Comment by nex3** [comment]
Yeah, I think that's reasonable. We can also say "is deprecated **outside of calc**".

**Comment by stof** [comment]
I opened PRs to change that

**Comment by arnonrdp** [comment]
The warning keeps appearing in building:
```console
DEPRECATION WARNING:
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
```

**Comment by Awjin** [comment]
@arnonrdp To clarify, do you see this warning when the only use of `/` is inside of a `calc()`?

Any uses of `/` outside of `calc()` will trigger this warning.

**Comment by arnonrdp** [comment]
I got it @Awjin. The point is that I am not using any `/` in my code.

The division outside `calc()` occurs inside `node_modules` folder.

**Comment by stof** [comment]
@arnonrdp use the `quietDeps` option to silence warnings coming from files loaded from dependencies (assuming you use a load path or a custom importer to load files from `node_modules`, and not a relative path to that location)

**Comment by arnonrdp** [comment]
Thank you very much @stof. Worked perfectly!
For those of you who are Vue users and coming here in the future, just add this to the `vue.config.js` file:
```json
module.exports = {
  …
  css: {
    loaderOptions: {
      sass: {
        sassOptions: {
          quietDeps: true,
        },
      },
    },
  },
};

```
