### ISSUE TITLE
I got an issues "Error: NoSuchMethodError: method not found: 'isTTY' on null"

### ISSUE THREAD

**Issue by hothvictor** [sass/dart-sass#1564]
When I trying to render scss on a react application, I got an error  **"Error: NoSuchMethodError: method not found: 'isTTY' on null**"

Code:
`sass.render({ data: ".my-css {}" }, function (err, result) {
    console.log(err, result);
  });`

**Comment by DangerousDetlef** [comment]
Same here.

**Comment by jathak** [comment]
This looks like you're trying to run Sass from within a browser, which is not currently supported (see #25). If that's not the case, let us know how you are running Sass and we'll reopen this.

**Comment by hothvictor** [comment]
@jathak Yes, I'm using it in my reactJS project. I read the #25, may I ask how to use a service worker to run sass on the browser?

**Comment by jathak** [comment]
Since #25 is not done yet, running in a browser is not currently possible, service worker or not.
