### ISSUE TITLE
Dart-Sass 1.44, Apache-NetBeans 12.5, MacOS Monterey - does not recognise @use or @forward

### ISSUE THREAD

**Issue by cliff-in-auld-reekie** [sass/dart-sass#1566]
This issue is doing my head in.  I had NetBeans working fine and compiling on save with Dart-Sass.
I was using @include's.  I'm now striving to move to @use and @forward.

Dart-Sass was installed by (per Dart site) simply loading it down and adding to my MacOS Path then "**which sass**" to get that path:     **/Applications/dart-sass/sass**
      and add it to NetBeans css preprocessor.
I get this issue every time I try @use.
So, I removed NetBeans to start over, and re-installed it (no difference)
To demonstrate the issue, I created the very simple project shown in the image.
Inside the _fonts.scss is the simplest definition ...

$font-size: 1.25rem;

So, even at this simplest of levels, NetBeans doesn't seem to like @use (or @forward for that matter).

Has anyone seen this issue and able to offer a suggested way forward?  I haven't found any other issues describing this.

![image](https://user-images.githubusercontent.com/50075955/144512285-c2d760fd-5b01-4ca5-b812-75d2d96cf2dc.png)

Thanks

**Comment by nex3** [comment]
I don't know anything about NetBeans, but it seems like the problem is there. The error message "Unexpected token SEMI found" is definitely not from Dart Sass, so I'm guessing that NetBeans either bundles its own version of Sass or has a separate Sass syntax highlighter that hasn't been updated to the new syntax. I recommend reaching out to though NetBeans' support system for help.

**Comment by cliff-in-auld-reekie** [comment]
Thanks for that
I've been leaning that way with this issue hence why I de-installed and re-installed NetBeans.
My next step was to run test compiles from the command line to check SASS was working fine.

Guessing I won't be too revealing....
Great to be able to narrow the issue down so much appreciated.  Will chase the NetBeans channel.

**Comment by cliff-in-auld-reekie** [comment]
I have raised an incident at NB.  After a bit of faff, I have SASS @use and @forward working with VSCode so, though there are things I like about NB, I need to be current.  Dart did not work for me in VSCode with a simple save down and modify the PATH as it did in NB (albeit not supporting the new features).  It needed an npm -g install.  But that did not fix NB.

Anywho, I'm moving to VSCode and therefore am done with this NetBeans thread.  Thanks Natalie for the assist.
