### ISSUE TITLE
@use with absolute paths to node_modules

### ISSUE THREAD

**Issue by MatteuSan** [sass/dart-sass#1567]
Lately I've been having this problem
```shell
Message:
    src\scaffold\theme\_index.scss
Error: Can't find stylesheet to import.
   ╷
23 │ @use '~@matteusan/sentro' with ($prefix: 'gs', $context: 'theme');
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\scaffold\theme\_index.scss 23:1  @use
  src\scaffold\color\_apply.scss 23:1  @forward
  src\scaffold\color\_index.scss 23:1  @forward
  src\scaffold\_index.scss 25:1        @use
  test\styles\main.scss 23:1           root stylesheet
```
I can't seem to use absolute paths to node_modules in sass?
Explanations and solutions for this problem is greatly appreciated :>

**Comment by stof** [comment]
`~@matteusan/sentro` is **not** an absolute path to node_modules

This is the webpack's sass-loader convention for resolving to the node_modules path through a custom importer.

**Comment by jathak** [comment]
@stof is correct. If Webpack is not resolving URLs as you expect, that should be brought up there.
