### ISSUE TITLE
Is there a way to turn quiet-deps on at specific import?

### ISSUE THREAD

**Issue by fifzteen** [sass/dart-sass#1575]
Hi!
I want to check deperecation warnings about only styles wrote myself, but ignore third-party styles.
Can I hide deprecation warnings on specific `@import, @use, @forward` line? 
(like `eslint-disable-next-line`)

ef. `sass-quiet-deps-next-line` is ignore only importing bootstrap.scss

```
// sass-quiet-deps-next-line
@import "~bootstrap/scss/bootstrap.scss"; // hide deprecation warnings
@import "partial"; // show deperecation warnings
```

**Comment by nex3** [comment]
No, there isn't. The `--quiet-deps` option is intrinsically heuristic, which means that there's always going to be some limits on how perfect its logic can be. If you want more customized logic, we recommend implementing a [custom logger](https://sass-lang.com/documentation/js-api/interfaces/Logger) that can have arbitrarily complex logic about which files should and should not log deprecation warnings.
