### ISSUE TITLE
can't find stylesheet to import "~@angular/material/theming";

### ISSUE THREAD

**Issue by Karan653** [sass/dart-sass#1578]
We have migrated our angular version from 11 to 12 and removed 'node-sass' in the favour of sass package , we have a shared library used across multiple mircro applications. While building library we are getting following isssue

can't find stylesheet to import "~@angular/material/theming";

we have tried different alternatives with and without tilday (~) and adding node_modules In the path. Please suggest if this is
bug or we have any resolution for that.

Apologies if it's a duplicate issue. Please advice.

**Comment by nex3** [comment]
How is your Sass compilation set up? What importers and load paths are you passing in?

These `~`-style imports aren't supported natively by Sass, they come from the `sass-loader` package's custom importer. If they're not working, chances are that package is configured incorrectly somehow. Similarly, Sass doesn't intrinsically know where `node_modules` is; you need to pass any directories you want Sass to use to look for files to the [`includePaths`](https://sass-lang.com/documentation/js-api/interfaces/LegacySharedOptions#includePaths) option.

**Comment by Karan653** [comment]
includePath fixed my problem. Thanks.
