### ISSUE TITLE
JS API: Missing options in new `compile` method

### ISSUE THREAD

**Issue by glenn2223** [sass/dart-sass#1585]
Finally got round to implementing the new `compile` method instead of the deprecated `renderSync`. However, I noticed there were a few missing options that I hadn't picked up on before.

Can the `linefeed`, `indentType`, `indentWidth` be added as options on the new methods? I went over the issues/discussions and couldn't see any reference as to why they might have been left out (sorry if there was and I missed it).

**Comment by nex3** [comment]
There are no plans to add these options. They were only supported in the old API for compatibility with Node Sass, and they generally go against Sass's philosophy of not providing deep output customization. If you really want specific formatting for your CSS, I recommend writing a custom PostCSS plugin to do so after the Sass is compiled.
