### ISSUE TITLE
Duplicate rules with multiple execution of mixin and placeholder selector

### ISSUE THREAD

**Issue by amzac-rait** [sass/dart-sass#1590]
Hi,

I am not sure if this is considered as a bug or if we are misunderstanding the specification, but this was quite an unexpected behaviour for my team :

Minimal use case : 

```
@mixin mymixin($somecolor){
    %btn{
        color: red;
        background: $somecolor;
    }
}

@include mymixin(blue);
@include mymixin(black);
//@include mymixin(white);


.tata{
    @extend %btn;
}
```

Results : 

```
.tata {
  color: red;
  background: blue;
}

.tata {
  color: red;
  background: black;
}
```

Expected : 
```
.tata {
  color: red;
  background: black;
}
```

We expected the %btn would be overriden by the new mixin execution, but it actually add a "new one" in the context. Which kind of strangely duplicate the CSS rule. 
If you uncomment the third execution, it will print a third CSS rule.

Have a good day,

**Comment by Awjin** [comment]
This is working as intended—Sass does not deduplicate style rules.
