### ISSUE TITLE
Can't import files with custom extension

### ISSUE THREAD

**Issue by stulnikov-roud** [sass/dart-sass#1595]
I'm using custom extension `.pcss` for style files.
After migration from node-sass to sass I'm getting `Can't find stylesheet to import.` message.
In documentation I can't find anything about using custom file extensions.

**Comment by jathak** [comment]
While you could accomplish this with a custom importer, we advise against it, as Sass uses file extensions to detect syntax (`.scss` for the SCSS syntax, `.sass` for the indented syntax, and `.css` for plain CSS).

If you'd like to use a custom file extension, we'd recommend something of the format `filename.custom.scss`.

**Comment by stulnikov-roud** [comment]
@jathak thank you for your answer.
I was trying to use custom importer, but it didn't work. 
Unfortunately the only option for me was to drop sass and to use postcss plugins, what I would rather not do if I had a possibility to configure it in the compiler.
Please consider this feature in future or add some more examples in the docs for custom importer.
Thank you!

**Comment by nex3** [comment]
Can you provide an example of the custom importer that wasn't working?
