### ISSUE TITLE
FileImporter as importer in StringOptionsWithImporter would not be invoked if URL is provided

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#1599]
In `Interface StringOptionsWithImporter<sync>`, we have url and importer options. The doc says:

> A relative load's URL is first resolved relative to url, then passed to importer. If the importer doesn't recognize it, it's then passed to importers and loadPaths.

``` js
sass.compileString('@import "test.scss";', { importer: { findFileUrl: function() { console.log('invoked') } } })
// "invoked" is printed

sass.compileString('@import "test.scss";', { url: 'file:///main.scss',
                                             importer: { findFileUrl: function() { console.log('invoked') } } })
// "invoked" is not printed
```

Here is what I found:
| | With `url` | Without `url` |
| - | - | - |
| `Importer` as `importer` | Works | Works |
| `FileImporter` as `importer` | **Never got invoked** | Works |

In summary, when passing a `url` and a `FileImporter` as `importer` to `compileString`, if a certain import is not resolvable against `url`, `sass` would throw an error right away instead of attempting to invoke `FileImporter`.

**Comment by ntkme** [comment]
@nex3 I'm not following what you're saying. In my understanding:

1. The reason we have a dedicated `importer` option in addition to `importers` is: this `importer` is only used for resolving imports defined in the input (the root) scss, unlikely the `importers` are global to all nested imported files. If it is otherwise, maybe I'm not  understanding the purpose of `importer` correctly.
2. A relative load's URL is first resolved relative to url, then passed to importer.
3. One use case of `FileImporter` as [documented](https://sass-lang.com/documentation/js-api/interfaces/FileImporter) is to redirect how files are resolved. E.g. redirecting `~/a/test.scss` to `node_modules/a/test.scss`.

Given all of above, I don't see why a user supplied FileImporter as `importer` should be ignored. For example:

```
sass.compileString('@import "~/test/style.scss"', {
  url: 'file:///build/root.scss',
  importers: [{
    findFileUrl(url) { // This works as expected.
      if (!url.startsWith('~')) return null;
      return new URL(url.substring(1), pathToFileURL('node_modules'));
    }
  }]
});

sass.compileString('@import "~/test/style.scss"', {
  url: 'file:///build/root.scss',
  importer: {  // This FileImporter just get ignored and never get invoked.
    findFileUrl(url) {
      if (!url.startsWith('~')) return null;
      return new URL(url.substring(1), pathToFileURL('node_modules'));
    }
  }
});
```

**Comment by nex3** [comment]
> 1. The reason we have a dedicated `importer` option in addition to `importers` is: this `importer` is only used for resolving imports defined in the input (the root) scss, unlikely the `importers` are global to all nested imported files. If it is otherwise, maybe I'm not  understanding the purpose of `importer` correctly.
> 2. A relative load's URL is first resolved relative to url, then passed to `importer`. The doc says `importer` can be `Importer` or `FileImporter` just like `importers`.
> 3. One use case of `FileImporter` as [documented](https://sass-lang.com/documentation/js-api/interfaces/FileImporter) is to redirect how files are resolved. E.g. redirecting `~/a/test.scss` to `node_modules/a/test.scss`.

Step 2 here is the key. A relative load is resolved relative to the containing file's *canonical URL*. In this case, the canonical URL is `file:///build/root.scss`, so resolving `~/test/style.scss` gives us `file:///build/~/test/style.scss`. This is a valid `file:` URL, so the `FileImporter` handles it itself rather than passing it on to `findFileUrl()`.

You can think of a file importer's implicit canonicalize method as essentially equivalent to:

```js
canonicalize(url) {
  if (url.protocol !== 'file') {
    url = this.findFileUrl(url);
    if (!url) return null;
  }

  // Additional logic to resolve partials, index files, and file extensions
  return url;
}
```

**Comment by ntkme** [comment]
Since one use case of `FileImporter` is redirection, maybe `findFileUrl` should still be invoked if the file at url does not exist like below?

``` js
canonicalize(url) {
  if (url.protocol !== 'file' || !fileExistsAtURL(url)) {
    url = this.findFileUrl(url);
    if (!url) return null;
  }

  // Additional logic to resolve partials, index files, and file extensions
  return url;
}
```

**Comment by nex3** [comment]
That violates the purpose of canonical URLs. It also doesn't satisfy any unaddressed use case—you can always do what you want by passing the importer to both `importer` and `importers`.

**Comment by ntkme** [comment]
Okay. That makes sense.

Can we print a warning if `url` is passed to `compile_string` and `importer` is a `FileImporter`? This issue was pretty confusing just reading the documentation literally.

**Comment by nex3** [comment]
I think there's actually a valid use-case for passing a `FileImporter` as an `importer` to `compileString`: if you want to supply the entrypoint as a string but you want any of its relative loads to come from the filesystem, a `FileImporter` is the best way to make that happen, even though the `findFileUrl()` function will never actually be called.

**Comment by ntkme** [comment]
That seems to be true, but part of it is from the non-intuitive API design:

> If the StringOptionsWithImporter.importer field isn't passed, the entrypoint file can't load files relative to itself and the url field is optional.
> If the StringOptionsWithImporter.importer field is passed, the entrypoint file uses it to load files relative to itself and the url field is mandatory.
> A relative load's URL is first resolved relative to url, then passed to importer. If the importer doesn't recognize it, it's then passed to importers and loadPaths.

In the first case, what's the purpose for passing an optional url other than for error reporting?

In my opinion, it would be more intuitive to always resolve relative to url first as long as url is passed.

A more user-friendly API in my opinion can be:

1. Only url is passed: relative import in source string resolved against.
2. Only importer is passed: relative import in source string is canonicalized by importer and then load by importer.
3. Both url and importer are passed: relative import in source string is resolved against url, if not exists then resolved by importer.

Apparently the current design works very differently than what I imagine, it would be great if you can provide more information on the motivation and reason behind the current design.

**Comment by nex3** [comment]
> In the first case, what's the purpose for passing an optional url other than for error reporting?

That's the only purpose. If you don't pass any importers or load paths, there's no way to resolve `@import`s at all, so there's nothing else we can do with a URL.

> A more user-friendly API in my opinion can be:
> 
> 1. Only url is passed: relative import in source string resolved against.
> 2. Only importer is passed: relative import in source string is canonicalized by importer and then load by importer.
> 3. Both url and importer are passed: relative import in source string is resolved against url, if not exists then resolved by importer.

There are a few issues with this API:

* In situation (1), it assumes that the string file should be resolved against the local filesystem despite the user not requesting that in any way. The filesystem is just one source among many that an importer may use to find stylesheets; it's only special in that we provide a few shorthands for creating importers that refer to it (`loadPaths` and `FilesystemImporter`). If you don't use one of those to explicitly tell Sass "look for these files on the filesystem", it won't ever touch the filesystem. This ensures that users who want to load stylesheets exclusively from some other location or from a virtual filesystem can't accidentally load files from the physical filesystem instead.

* Situation (2) is what happens if you pass an importer to the `importers` option. It doesn't make sense to do the same thing for the `importer` option, because that's specifically only for handling loads relative to the entrypoint's canonical URL and that URL doesn't exist in this scenario.
