### ISSUE TITLE
Does it support ES6?

### ISSUE THREAD

**Issue by elgs** [sass/dart-sass#1603]
I wonder if I can do something like this without Webpack?
```html
<script type="module">
  import { sass } from 'path/to/sass.js';
</script>
```

**Comment by jathak** [comment]
This doesn't have anything to do with ES6 imports. Sass does not support running in a browser. See #25.

**Comment by elgs** [comment]
Thanks for confirming it. I got this https://github.com/medialize/sass.js/ to work, not sure how compatible it is, but better than nothing.
