### ISSUE TITLE
JS API custom functions have no context options?

### ISSUE THREAD

**Issue by dasiux** [sass/dart-sass#1611]
When using the custom fuctions: https://sass-lang.com/documentation/js-api/interfaces/Options#functions
I was looking for context information, like path of the file where the function is being executed to be able to resolve relative paths for example.

I have not used the custom functions for the _node-sass_ or the _dart-sass legacy api_, but according to this as i understand it: https://github.com/sass/dart-sass/issues/1233 there should be a context object that should hold that information even when using the _new dart-sass JS API_.

I don't seem to be able to retrieve that information using **sass@^1.49.0**, either because its not there or I'm too stupid to find it,
you can find a repository with a reproducable setup here:
https://github.com/dasiux/sass-functions-context-test

I've run it with **osx@11.5.2** on **node@^v10.x.x** but i assume the node version is not the problem, also sync or async does not and should not make a difference.

Would be great to find a solution for this, thanks for any help in advance.

**Comment by Awjin** [comment]
This is working as intended—the new JS API does not modify the `this` context, in order to prevent unexpected behavior.

**Comment by dasiux** [comment]
So there is no way to aquire the context information in the current state? not even the file path where the function was called?

**Comment by dasiux** [comment]
> This is working as intended—the new JS API does not modify the `this` context, in order to prevent unexpected behavior.

So there is no way to aquire the context information in the current state? not even the file path where the function was called?
