### ISSUE TITLE
How to prevent the usage of inset (and other non-compatible CSS properties)?

### ISSUE THREAD

**Issue by MelvilQ** [sass/dart-sass#1613]
We recently migrated our Angular project from node-sass to dart-sass and now are facing a browser compatibility issue. 

The following SCSS:

```
position: fixed;
top: 0;
bottom: 0;
left: 0;
right: 0;
```

is compiled to this CSS:

```
position: fixed;
inset: 0;
```

This is a problem, because iOS Safari < 14.5 does not support the property `inset`. See https://caniuse.com/mdn-css_properties_inset. The incompatibility affects 2.58% global usage (which is higher than 2%). We did not find a way to configure the compilation to obey to our browserslist. If we can't prevent dart-sass from generating incompatible CSS, we have to go back to node-sass.

**Comment by Awjin** [comment]
The Sass compiler does not perform transformations like this. It's likely happening elsewhere in your build pipeline.

**Comment by flolovebit** [comment]
my workaround:
.class{
    right: 0!important;
    bottom: 0;
    top: 0;
    left: 0;
}

**Comment by nbrookie** [comment]
Fwiw, the root cause ended up being a bug in chrome: https://stackoverflow.com/questions/65899348/prevent-chrome-browser-from-converting-position-property-to-inset
