### ISSUE TITLE
Projects using dart unable to run "npm install" with node version less than 12.0.0

### ISSUE THREAD

**Issue by bryceosterhaus** [sass/dart-sass#1621]
With the release of [1.49.1](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1491), projects that depended on `sass` at either `^1.x.x` or `~1.x.x` no longer can install with node versions less than 12.

I understand that your policy that says you can break support if necessary for non-LTS versions, however this is pretty harsh since it breaks `npm install` and not just a sass feature.

---

For context, my project is a tool that allows developers to compile and build a theme for the Liferay platform. We are constrained to node 10.x for older versions of our platform and provide dart sass as an opt-in feature over node-sass. With this change to the `engines` field in 1.49.1, we can no longer run `npm install` because our dependency on sass is `^1.3.0`.

My recommendation would be to keep your current guidelines of only functionally supporting latest node LTS, but I think you should only update the `engines` field at major version intervals. This would prevent legacy projects from breaking on install.

Also, I know I am able to work around this issue by using [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) or by locking my sass dependency at 1.40.0. Simply wanted to open this issue to raise concern for anyone else who may run into this.

**Comment by Awjin** [comment]
@bryceosterhaus Thank you for raising the concern. Sass tries to be as backwards compatible as possible, which is part of the reason why we are very intentional about publishing major versions. Dropping support for legacy versions of Node does not meet the criteria for a major version update. In this case, since you have a reasonable workaround by pinning Sass, I'll close this issue out.

**Comment by bryceosterhaus** [comment]
Thanks for the feedback @Awjin!

Just adding some discoveries I had while investigating this for anyone reading this in the future.

Per [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines), `engines` mismatch should only log a warning unless `engine-strict` is specified. However, if you are using `yarn` instead of `npm` it will produce an error on install. In `yarn`, strict seems to be the default. The work around for this in yarn is to use the `--ignore-engines` flag.
