### ISSUE TITLE
Dart APIs to provide a custom `ImportCache`?

### ISSUE THREAD

**Issue by simolus3** [sass/dart-sass#1626]
The `sass_api` package exports the `(Async)ImportCache` class, which is helpful to avoid duplicate parsing costs when compiling multiple entrypoints. However, it looks like the only way to actually use a fixed import cache is to use the compile functions in `package:sass/src/(async_)compile.dart`, the public functions don't accept an import cache as an argument.

Would it be possible to export the internal compile functions from the `sass_api` package? I'm happy to contribute this change, I just wanted to ask if there's an intentional reason for this or if I'm overlooking something. At the moment I'm using implementation imports which obviously isn't great.

**Comment by nex3** [comment]
Rather than exposing more internals than we need to, I'd prefer to expose a higher-level API that expresses the *intent* of what's happening here. We've talked over what this might look like for JS in https://github.com/sass/sass/issues/2745, and the principle would be the same for Dart.
