### ISSUE TITLE
meta.load-css resolves url relative to the url of initial sass file being compiled

### ISSUE THREAD

**Issue by climam** [sass/dart-sass#1627]
It seems that meta.load-css resolves url relative to the url of initial sass file being compiled. I am unsure if this is a desired behavior but it makes difficult to build a sass library that is using meta.load-css.

Reproduction scenario:
- a/styles.scss
`@use "../b/lib`
- b/_lib.scss
`@use "sass:meta"`
`@include meta.load-css("core")`
- b/_core.scss

Compile a/styles.scss

Error: Can't find stylesheet to import

When I do change the url passed to meta.load-css to "../b/core" it does work.

I feel the issue comes from this place:

https://github.com/sass/dart-sass/blob/e3bf3eb3a3a8708877a86a08c7e3bee92160ac1f/lib/src/visitor/evaluate.dart#L484

Why do we initialize baseUrl with callableNode.span.sourceUrl instead of _stylesheet.span.sourceUrl ?

**Comment by jathak** [comment]
I'm not able to replicate this issue on the latest version of Dart Sass (both the native Dart version or the NPM version).

How are you compiling your Sass code?

**Comment by climam** [comment]
Hi, the issue occurs when using the legacy API. Here is js code that you can use to reproduce the issue:

```
const sass = require("sass");
sass.renderSync({file:"a/styles.scss"});
```

**Comment by climam** [comment]
@jathak, were you able to reproduce with those new details?

**Comment by jathak** [comment]
The code you've provided on its own should work. We'd need to a full repo reproduction to actually debug it.

**Comment by climam** [comment]
Here is a repo to reproduce the issue: https://github.com/climam/dart-sass-issue-1627

**Comment by nex3** [comment]
Worth noting that this only reproduces with the legacy JavaScript API. If it's possible, I recommend upgrading to the new JS API to avoid issues like this as well as get improved performance.

**Comment by nex3** [comment]
It also doesn't reproduce with `sass-embedded` even with the legacy API.
