### ISSUE TITLE
 Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by Alihumza121** [sass/dart-sass#1639]
$base: 16 !default;

@function scut-strip-unit ($num) {
  @return $num / ($num * 0 + 1);
}

@function rem ($pixels) {
  @return scut-strip-unit($pixels) / $base * 1rem;
}
@function em ($pixels, $context: $base) {
    @return #{$pixels/$context}em;
  }

after complie it throws an warning . my sass is properly complied in css folder , only thing is that are these warning . how can i get rid of this

**Comment by jathak** [comment]
@stof is correct. As mentioned in the breaking change page, we have a [migrator](https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration) to automatically convert your code to use `math.div`.
