### ISSUE TITLE
Feat: empty css body should be omitted

### ISSUE THREAD

**Issue by imcuttle** [sass/dart-sass#1644]
In my screen, I use [`typescript-plugin-css-modules`](https://www.npmjs.com/package/typescript-plugin-css-modules), but It's not works in `empty css body`. I found the question's point is the css which is compiled by sass

### Input
- Sass
```
.main {
}
```

### Output
- Css Expected
```
.main {
}
```

- Css Actual
```

```

**Comment by jathak** [comment]
Empty CSS rules have no effect, so Sass omitting them is valid by the CSS spec. An empty CSS file is still a valid one (it just does nothing), so if `typescript-plugin-css-modules` doesn't support empty files, you should file a bug with it.
