### ISSUE TITLE
hsl() with calc() error!

### ISSUE THREAD

**Issue by ve3** [sass/dart-sass#1647]
I have mixin where `$colorValue` is CSS 3 variable.

```
@mixin link-actions-color($colorValue) {
    &:active {
        @if (type-of($colorValue) == 'string' and str-index($colorValue, '--')) {
            color: hsl(from var(#{$colorValue}) calc(h + 180deg) s l);
        } @else {
            color: darken($colorValue, 15);
        }
    }
}

@each $colorName, $colorValue in ("danger", $danger-color), 
                        ("disabled", --text-disabled-color) {
    .text-color-#{$colorName} {
        color: $colorValue;
    }
    a.text-color-#{$colorName} {
        color: $colorValue;
        @include link-actions-color($colorValue);
    }
}
```

When I run build, I got this error.

> Error in plugin "sass"
> Message:
>     assets\scss\rdta\global-common\_common-mixins.scss
> Error: Expected "(" or ".".
>    ╷
> 38 │             color: hsl(from var(#{$colorValue}) calc(h + 180deg) s l);
>    │                                                       ^
>    ╵

If I remove `calc()` part, everything works fine.
```
color: hsl(from var(#{$colorValue}));
```

Reference:
1. https://stackoverflow.com/a/55330103/128761
2. https://www.w3.org/TR/css-color-5/#relative-HSL
3. https://www.w3.org/TR/css-color-5/#relative-colors

**Comment by voltaek** [comment]
Looking at your example, I would think Sass would have to explicitly add support for using `calc()` on components of a color (in this case 'h' AKA hue).

Browsers don't yet support relative colors (Safari TP doesn't qualify) nor the rest of CSS Color 5 (which is still a working draft). Sass doesn't add support for features that aren't supported by browsers yet. CanIUse [hasn't even added it](https://github.com/Fyrd/caniuse/issues/5405) to their tracked feature list yet.

**Comment by ve3** [comment]
Thank you.
