### ISSUE TITLE
[Question] Multiple load paths in CLI

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [sass/dart-sass#1655]
Hello, I am trying to update my rails application to use dart sass, but i cant make the build process work with multiples load_paths (https://sass-lang.com/documentation/cli/dart-sass#load-path).
```bash
project
├──app
│   ├── assets
│   │   ├── stylesheets
│   │   │   ├── themes
│   │   │   │     ├── theme1.sass.scss
│   │   │   │     └── theme2.sass.scss
│   │   │   ├── utils
│   │   │   │     ├── _size.scss
├── node_modules
├── package.json
```

```scss
// theme1.sass.scss
@import "utils/size";

// Colors
$primary-color: rgb(64, 0, 119);
$primary-color-dark: rgb(2, 0, 60);

$secondary-color: #2e3131;
$secondary-color-dark: #0c100f;

$warning-color: #ffc107;

// Theme Colors
$theme-colors: (
  'primary': $primary-color,
  'secondary': $secondary-color,
  'success': $primary-color-dark
);


@import "bootstrap";
```

```json
// package.json
{
  "name": "my-project",
  "private": true,
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "bootstrap": "^5.1.3",
    "esbuild": "^0.14.26",
    "sass": "^1.49.9",
    "sortablejs": "^1.13.0"
  },
  "devDependencies": {},
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass -I node_modules ./app/assets/stylesheets --no-source-map ./app/assets/stylesheets/themes:./app/assets/builds/themes"
  }
}

```

When i run `sass -I node_modules ./app/assets/stylesheets --no-source-map ./app/assets/stylesheets/themes:./app/assets/builds/themes`, raises this erro:
```
Error: Can't find stylesheet to import.
  ╷
4 │ @import "utils/size";
```

When i run `sass -I ./app/assets/stylesheets node_modules  --no-source-map ./app/assets/stylesheets/themes:./app/assets/builds/themes`

```
Error: Can't find stylesheet to import.
   ╷
20 │ @import "bootstrap";
   │         ^^^^^^^^^^^
   ╵
```
I guess is loading only one load path at once, thanks for the help!!

**Comment by jathak** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large. To get a helpful answer from StackOverflow, I'd encourage you to add more details to your question, like what problem you are trying to solve, and which sections of your Sass code are actively breaking.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @jathak ok, no problem!! I post because maybe is a bug, i can make this work using this follow command:
```bash
sass --load-path node_modules -I ./app/assets/stylesheets ./app/assets/stylesheets/themes:./app/assets/builds/themes
```
