### ISSUE TITLE
`url` documentation does not match js-api-spec

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#1657]
https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithoutImporter#url

> The canonical URL of the entrypoint stylesheet. If this isn't passed along with `StringOptionsWithoutImporter.importer`, it's optional and **only used for error reporting**.

The problem is that the wording `only used for error reporting` is inaccurate as specifying `url` would allow imports to be resolved relative to to this `url`. In some cases setting `url` is not desirable, e.g. in an asset pipeline where files need to be preprocessed before imported by sass. It looks like the only way to prevent sass to resolve imports relative to the `url` (provided for error reporting only) is to not specify `url` at all or specifying a non-file url that sass cannot resolve.

``` js
const sass = require('sass')
const fs = require('fs')
const path = require('path')
const url = require('url')

fs.writeFileSync('child.scss', 'a{b:c}');

console.log(
  sass.compileString('@import "child.scss";', {
    // without url option, the import fails
    // with url option, the import works
    url: url.pathToFileURL(path.join(process.cwd(), 'main.scss'))
  }).css
)
```

**Comment by nex3** [comment]
This looks like a bug. A `compileString()` invocation shouldn't ever load anything from the filesystem unless it's passed *some* sort of filesystem importer.

**Comment by ntkme** [comment]
The problem comes from:

https://github.com/sass/dart-sass/blob/33f18c4b54b7dfe5b5c7a9e41de392fba8f4ba15/lib/src/node/compile.dart#L77-L78

If `url` is set and `importer` is unset, `null` will be passed.

https://github.com/sass/dart-sass/blob/ba38c09c6869c1c7da19f05298a270da29d93e73/lib/src/async_compile.dart#L111

Then, `null` becomes `FilesystemImporter('.')`.

**Comment by ntkme** [comment]
Found that we have a JS API spec that is different than what the document says:

> The canonical URL of the entrypoint stylesheet. If this isn't passed along with StringOptionsWithoutImporter.importer, it's optional and only used for error reporting.

https://github.com/sass/sass-spec/blob/126d17ff9f77372b6f68cb0d43dd357165519c93/js-api-spec/compile.test.ts#L124-L133

``` js
    it('url is used to resolve relative loads', () =>
      sandbox(dir => {
        dir.write({'foo/bar/_other.scss': 'a {b: c}'});

        expect(
          compileString('@use "other";', {
            url: dir.url('foo/bar/style.scss'),
          }).css
        ).toBe('a {\n  b: c;\n}');
      }));
```

**Comment by ntkme** [comment]
> This looks like a bug. A `compileString()` invocation shouldn't ever load anything from the filesystem unless it's passed _some_ sort of filesystem importer.

This statement is true for the Dart API, but for the JS API. A `null` importer in JS API would become `FilesystemImporter('.')` when it get to the Dart API.

Assuming the JS API Spec quoted above is correct, this is a documentation issue.
