### ISSUE TITLE
pubspec.yaml pins cli_pkg to a non-existent version

### ISSUE THREAD

**Issue by grawlinson** [sass/dart-sass#1660]
Package maintainer for Arch Linux here, the latest release of dart-sass (1.49.10) fails to build from source.

```sh
pub get
Because sass depends on cli_pkg ^2.1.0 which doesn't match any versions, version solving failed.
```
As far as I can tell, the commit that broke this stems from PR #1643.

Namely, the change of `cli_pkg` to `^2.0.0` to `^2.1.0`, when the latest [version](https://pub.dev/packages/cli_pkg/versions) of `cli_pkg` is 2.0.3.

The issue has been fixed [downstream](https://github.com/archlinux/svntogit-community/blob/774b6f314791a07a66ae35568dad4e16c3a3e9b4/dart-sass/trunk/PKGBUILD).

**Comment by ntkme** [comment]
2.1.0 is retracted and replaced by 2.1.1.

**Comment by grawlinson** [comment]
Thanks! I'll close this issue. :)
