### ISSUE TITLE
What does watch do and won't do

### ISSUE THREAD

**Issue by Luuk1983** [sass/dart-sass#1666]
I've been playing around with the watch and it's really hard to understand what it will and won't do when it comes to partial sass-files. I could use some clarification because it's driving me crazy :)

Let's consider this script:
sass --watch build/sass:wwwroot/public/css

From my understanding, this will watch the build/sass folder and when any non-partial scss file is changed, it will perform a compilation of those files.
Question 1: Will it only watch the given folder, or all descendant folders? Based on the documentation and online comments, I think it watches all descendant folders as well?

Question 2: I know that sass won't dynamically watch all related partial sass files by following the @imports, @use etc. But is it possible to recompile the non-partial sass files when any partial sass-file in the watched folders is updated? In my experiments, it's really easy to watch and get non-partial sass-files to compile. However, in reality, I'm mostly working in partial sass files and if the watch is unable to update the non-partial sass files, the watch functionality is practically unusable and I'd have to resort to other watch methodes or plugins. It would be a real shame though, because I wanted to eliminate as many plugins as possible ;)

Consider it a feature request if there is no way to watch partial files.

Thanks in advance!

**Comment by nex3** [comment]
> Question 1: Will it only watch the given folder, or all descendant folders? Based on the documentation and online comments, I think it watches all descendant folders as well?

It will watch the entire directory tree recursively.

> Question 2: I know that sass won't dynamically watch all related partial sass files by following the @imports, @use etc. But is it possible to recompile the non-partial sass files when any partial sass-file in the watched folders is updated? In my experiments, it's really easy to watch and get non-partial sass-files to compile. However, in reality, I'm mostly working in partial sass files and if the watch is unable to update the non-partial sass files, the watch functionality is practically unusable and I'd have to resort to other watch methodes or plugins. It would be a real shame though, because I wanted to eliminate as many plugins as possible ;)

When any partial file within the watched directories (or within a load path passed to `--load-path`) changes, Sass will recompile every concrete file that transitively `@import`s or `@use`s that partial file.

**Comment by Luuk1983** [comment]
Thanks Natalie for your response! What you describe is awesome and exactly what I would want. However, I can't get it to work as described for many days now. Maybe I'm missing something, or maybe where is a bug somewhere so I thought I'd explain my example.

I'm running Sass 1.49.9.

My file structure is:
build
--- sass
------Test
--------- _partial.scss
------example.scss

_partial.scss contains:
`$example-color:green;

input {
    background-color:orange;
    font-size:1.5rem;
}`

example.scss contains:
`@use "test/partial" as p;

body {
  background-color: red;
  color: p.$example-color; 
}`

I created an NPM script to start the watch:
"watch": "sass --watch build/sass:wwwroot/public/css"

Now when I run the script, the watch starts without problems and when I change something in the example.scss file, it will recompile. However, when I make changes to _partial.scss, it will not pick up on the changes and not recompile.

Even worse, when I change something in _partial.scss it will not compile, when I then change something in example.scss, it will compile example.scss, but the changes done to _partial.scss that were done before are not reflected in the recompiles example.scss.

So I'm puzzled thy this is not working because it's such a simple example and you're posts suggests this should work. Thank you for your reply in advance once again.
