### ISSUE TITLE
Compiled error if the name of library has `.css` suffix 

### ISSUE THREAD

**Issue by nzbin** [sass/dart-sass#1670]
I'm not sure if this is a bug. Sass will compiled error if the name of library has `.css` suffix.

For example:

1. npm package [snack.css](https://www.npmjs.com/package/snack.css) with `.css` suffix

```sass
@use 'snack.css' ; // ❌
@use 'snack.css/index' ; // ✔️
```

2. npm package [snack-helper](https://www.npmjs.com/package/snack-helper) without `.css` suffix

```sass
@use 'snack-helper' ; // ✔️
@use 'snack-helper/index' ; // ✔️
```

**Comment by stof** [comment]
When an imported URL ends with a `.css`, `.sass` or `.scss` extension, Sass does not treat it as maybe being a folder name (note that when using `@import` it does not even treat it as a Sass import but as a CSS import if the extension is `.css`)
