### ISSUE TITLE
How to install `dart-sass` in WSL2?

### ISSUE THREAD

**Issue by KunalTanwar** [sass/dart-sass#1679]
I have searched on Google as well as YouTube but didn't find any article or video covering **"How to install sass in Windows Subsystem for Linux (WSL2)?"**. Also the `sass` website have installation example for Windows, Mac and Linux (using brew) but its just I don't want to use `brew`. So is there any way around?

**Comment by stof** [comment]
there is not yet a package for Debian-based Linux distributions. This is tracked at https://github.com/sass/dart-sass/issues/1164 (the work has started on it in the tooling used to produce the releases).

For now, you either need to use brew or to download it manually from the GitHub releases.

**Comment by KunalTanwar** [comment]
Thanks for letting me know!! I am closing this issue now.
