### ISSUE TITLE
Show all importers when an import fails

### ISSUE THREAD

**Issue by zoechi** [sass/dart-sass#168]
https://github.com/sass/dart-sass/blob/master/lib/src/visitor/evaluate.dart#L643
only prints the import source line, but it doesn't show what resolved path(s) were tried to read.
This makes it cumbersome to debug.

I tried to make dart imports (`@import 'package:my_package/my_style';`) but it only tells me

```
Can't find file to import.
@import 'package:my_package/my_style';
```

which doesn't help because `my_style.scss` exists there.

**Comment by nex3** [comment]
In this case, I'm not sure what more information we could provide that would help. We currently don't support `package:` imports from the command line (see #128), so from Sass's perspective this is just an arbitrary URL that we have no idea what to do with.

In general, it's probably a good idea to list all known importers when we have an import error, so I'll keep this open targeting that. But in this case, you probably have *no* importers, which makes that not very useful for you.

**Comment by zoechi** [comment]
I tracked it down. It's a bug in package path resolution when `.packages` contains a relative path (to a path dependency) which is currently resolved relative to the sass file containing the import instead relative to the `.packages` file.
During debugging I saw there wasn't even a specific path to try (or print), but instead it returned just `null` because it bailed out early from further path resolution.
I'll see if I can make a PR.

**Comment by zoechi** [comment]
Actually I think relative paths in `.packages` are a bug.

**Comment by zoechi** [comment]
I'm not sure anymore about relative paths. It might be an issue in package_resolver
See also - dart-lang/pub#1681
(or I'm just missing something)

**Comment by zoechi** [comment]
It's working fine when `await SyncPackageResolver.loadConfig(...)` is used.
I'll create a PR with a test that uses it this way.
Seems the transform_sass package copied it from the `dart_script_test.dart` but that doesn't work with relative paths.

**Comment by zoechi** [comment]
#169 is the PR with the added test
