### ISSUE TITLE
[feature-request]: Respect package.json exports

### ISSUE THREAD

**Issue by calebdwilliams** [sass/dart-sass#1683]
In version 12, Node added support for [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) which allows package authors to define package entry points that may not necessarily correspond to the directory structure of the published package.

I would like to propose that Sass be given the ability to respect a package's exports. This would allow developers to publish several partials locally to break up logic or behavior while also controlling which files can be directly accessed by consumers. It would also allow package authors to provide clean entry points to their Sass files even if some circumstance necessitates the directory structure be more complex.

Obviously I realize that this could be seen as a breaking change, so would be happy to have this fall under a flag (either permanently or temporarily) such as `--module-resolution=node` or something else.

**Comment by michaelfaith** [comment]
@jathak which version was this complete in?  I'm having issues

```bash
Error: Can't find stylesheet to import.
  ╷
7 │ @use '@angular/material';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

**Comment by jathak** [comment]
This was closed as a duplicate of https://github.com/sass/sass/issues/2739 before GitHub distinguished between different types of closures (it seems odd that they'd treat all of those old closures that way, but ¯\_(ツ)_/¯)
