### ISSUE TITLE
Compound selector deprecation - suggested fix kinda breaks 

### ISSUE THREAD

**Issue by jurchiks** [sass/dart-sass#1689]
I recently spent a lot of time upgrading node dependencies in a work project, and ran into a weird issue with `gulp-iconfont-css`, described here: https://github.com/sass/sass/issues/3309 (wrong repo, I know, hence why I'm making an issue here now).
Before, my project was using `gulp-sass` v4, but after upgrading to v5, it required `dart-sass`, after installing which I received some build errors about compound selectors not being supported anymore:
https://sass-lang.com/documentation/breaking-changes/extend-compound
Code before: 
```scss
.my-element:before {
    @extend .icon:before;
    @extend .icon-arrow-down:before;
}
```
Code after:
```scss
.my-element:before {
    @extend .icon, :before;
    @extend .icon-arrow-down, :before;
}
```
This fixed the build error, but resulted in broken page styles, which I didn't notice at the time because I was busy fixing all the other build stuff.

Here's a gist of what `dart-sass` does, IMO, wrong: https://gist.github.com/jurchiks/ed72c379532b07be1d9897c909d33199
As you can see in the output, `.some-other-element` is added to ALL `.icon*` classes, not just the ones that should apply based on my code.
If I add `:before` to `.some-other-element` then the output is as expected, but it seems weird that it doesn't have the same output without that. Why would it add `.some-other-element` to all other classes? It makes no sense.

Here's a version of the gist with all variants (without pseudo-selector, with :before, with :after) - https://gist.github.com/jurchiks/2c741027d4bc0979b662a48583a50536
And it really looks like it's not quite making sense of what to do, and borks everything - it adds `.foo` and `.qux` to all specific icon classes even though they should not apply.

**Comment by jathak** [comment]
This is working as intended. As mentioned in the breaking change page, LibSass's behavior when extending compound selectors is incorrect. `@extend .icon, :before` within `.some-other-element` means that any rules with a selector matching `.icon` or `:before` now also apply to `.some-other-element`.

If you need more control over what properties you want to apply to `.some-other-element`, you should extend a placeholder selector or just use a mixin.
