### ISSUE TITLE
Unable to @import absolute paths on windows

### ISSUE THREAD

**Issue by DavidSouther** [sass/dart-sass#1690]
In an automated build system, my tool generates an absolute path to the root stylesheet to render. On mac/linux, sass loads the entry point from the correct location, but it fails in windows with 

```
'Can't find stylesheet to import.
  ╷
3 │ @import "C:\Users\david\Documents\GitHub\computron5k\node_modules\@davidsouther\jiffies\src\pico\pico.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 3:9  root stylesheet'
 ```

Windows 10 Home
Node v16.14.0
sass 1.49.9

**Comment by DavidSouther** [comment]
This is probably a duplicate of https://github.com/sass/dart-sass/issues/1258, and I expect the answer is "@import uses urls, not paths". Still, I couldn't find this discussed, so I wanted to get it captured for Google to index.

**Comment by nex3** [comment]
You've answered your own question :smile:. Sass loads do indeed use URLs and not paths, so if you write this as a `file:` URL instead it will work.
