### ISSUE TITLE
'Sass Watch' doesn't work  in Linux Background

### ISSUE THREAD

**Issue by JesusHerreraUS** [sass/dart-sass#1691]
Hello,
I'm trying to execute sass in a very simple script in Debian 10. The script is as the follow:

**#! /bin/sh -e
sass --watch $scssPath:$cssPath > ./sass_watch2.log 2>&1 &**

$scssPath and $cssPath are the paths of the files sccs and css. I save stdin and stderr in a file (ass_watch2.log).

This script executes sass in background but with this way it stops working (the process dies
).

However, if I execute it in foreground (without the last &), it works correctly.

I'm using version 1.50.0. When I used  version 1.39.1, it works good.

Any idea?

Thanks.

**Comment by nex3** [comment]
https://github.com/sass/dart-sass/pull/1665 should fix this.
