### ISSUE TITLE
Map isn't valid CSS value

### ISSUE THREAD

**Issue by roydukkey** [sass/dart-sass#1693]
The following does not produce a return and indicates `Exception: (key: "value") isn't a valid CSS value.`

```js
const sass = require('sass');
const { OrderedMap } = require('immutable');

const result = sass.compileString(`
body {
	result: '#{test-map()}';
}`, {
	functions: {
		'test-map()': function () {
			const key = new sass.SassString('key', { quotes: false });
			const value = new sass.SassString('value', { quotes: true });

			return new sass.SassMap(OrderedMap([[key, value]]));
		}
	}
});
```

https://runkit.com/roydukkey/62812b44fae7900008195a44

**Comment by nex3** [comment]
The custom function's working fine; you'd get the same result if you just directly wrote

```scss
body {
  result: '#{(key: "value")}';
}
```

As the error message says, a Sass map isn't a valid CSS value. If you want to inspect the output anyway, use the `meta.inspect()` function.
