### ISSUE TITLE
Tilde '~' can't be replaced with importer

### ISSUE THREAD

**Issue by feng-xiao** [sass/dart-sass#1715]
Setting importer still doesn't replace tilde '~'. I have to use @mr-hope/gulp-sass to make it work

**Comment by nex3** [comment]
I'm not sure what you mean by this. Can you provide a working, stand-alone example of a Sass importer, what you expect it to do, and what it actually does?

**Comment by tadejkan** [comment]
I'm not sure what OP meant, but I myself have issues with libraries using ~ (tilde) for importing from node_modules.
Specifically, my issue is with Blueprint (see file https://github.com/palantir/blueprint/blob/develop/packages/datetime/src/_datepicker.scss).
One way to solve this, would be to provide an option to strip away (i.e. delete) tildes from import statements, and combine it with existing --load-path option.

**Comment by nex3** [comment]
I believe those imports are specifically intended to be used with Webpack's custom importer. I don't think it's a good idea to enshrine it in the official Sass implementation, even just by adding an option to strip it off.
