### ISSUE TITLE
features request 

### ISSUE THREAD

**Issue by spicestudio** [sass/dart-sass#1720]
Hi i want some new features like documentation (you can use docusarus)
new features like conditional import, autoprefixer , JIT complier , official Vscode extensions with full intellisense
and a variable will called compress takes a Boolean and at compile every class has the same property take it like extend at rule it's very useful for components
@apply directive like in tailwind

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/3331

Please don't open the same issue in multiple repositories.
