### ISSUE TITLE
How to convert HSL to HEX?

### ISSUE THREAD

**Issue by SamuelMiller** [sass/dart-sass#1743]
The now deprecated node-sass automatically converted HSL to Hex in css. Now, that I switched to the newer dart-sass in my gulpfile.js, it no longer converts--the result is still hsl. Is there a way, I can enable the conversion?

```
const sass = require('gulp-sass')(require('sass'));
function buildCss() {
    return src('src/assets/scss/bootstrap.scss')
        .pipe(sass.sync().on('error', sass.logError))
        .pipe(dest('src/assets/css/'));
}
```

**Comment by jathak** [comment]
While in this case, compiling in compressed mode should use hex colors, in general, you should avoid depending on Sass producing a specific output format and instead update your tooling to consume any valid CSS colors.
