### ISSUE TITLE
[QUESTION] - Question as to why SassList's contents are undefined even though there should be a value.

### ISSUE THREAD

**Issue by classicmike** [sass/dart-sass#1760]
**SASS version:** 1.52.3

### Description of problem
Hi,

Wasn't so sure if I should put it as an issue here as I might need some pointers from the original contributers but here goes...

I'm trying to write a script to be able to extract some Sass variables from a sass file to which I can then eventually put in a JSON file using the Dart SASS compiler (Very similar to https://www.npmjs.com/package/sass-extract).  You could say I'm trying to minic as much of the behaviour of Sass extract as much as possible for dart-sass.

During the extraction phase, I have to parse the sass variables and convert in to formats that would be readable in javascript (using the Dart SASS Javascript API) after starting to run a ```compileAsync```. Now, the entry point where I would do the parsing would be through the ```functions``` passed into the ```functions``` option when compiling.

All is good far in that I can process other sass types such as ```SassString```, ```SassNumber``` etc. Except, that when I want to process 'SassList' data. Here is an example of a value from a variable I want to process:
``` 
$font-family: TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif;
```
When attempting to determine if the value passed through is an instance of ```SassList``` like so:
```
sassValue instance of SassList
```
it returns ```true``` and when trying to determine the constructor's name, i.e: ```sassValue.constructor.name```, it tells me it is ```SassList0```.

If memory serves me correct, since this ```sassValue``` is of the ```SassList``` type and thus I should be able to access the attributes and methods inside of https://sass-lang.com/documentation/js-api/classes/SassList. 

However when I attempt to run ```sassValue.contents```, it returns ```undefined```, which doesn't sound right. Could there have been a mistake in the way how I understand how the SassList works? or is there possibly an issue in which the SassList might not be constructed correctly with the contents that should be there?

Again I'm not so sure where to look at and I'm hoping I could get some pointers from the original contributors.

Apologies if I can't give you an minimal example but here is a fragment from a piece the piece code that I am encountering the issue:

```
const NO_TYPE = 'no-type';

const AVAILABLE_TYPES = [
  SassString,
  SassBoolean,
  SassColor,
  SassMap,
  SassList,
  SassNumber,
];
....
const getSassType = (sassValue) => {

  let type = NO_TYPE;

  for(let i = 0; i < AVAILABLE_TYPES.length; i++) {
    const availableType = AVAILABLE_TYPES[i];

    if(availableType !== sassNull && sassValue instanceof availableType) {
      type = availableType;
      break;
    } else if(sassValue === sassNull){
      type = sassNull;
      break;
    }
  }

  if(type !== NO_TYPE){
    return type;
  }

  throw new Error(`getSassType(): Unsupported sass variable type '${sassValue.constructor.name}'`);
}

const makeValue = (sassValue) => {

  const sassType = getSassType(sassValue);

  switch(sassType) {
     ....
     case SassList:
        console.info('This is a SassList');
        console.info('Output the Sass value', sassValue);
        console.info('What are the keys of the Object?', Object.keys(sassValue));
        console.info('What is the constructor name?', sassValue.constructor.name);
        console.info('Is Sass list an instance of SassList?', sassValue instanceof SassList);
        console.info('Sass value contents through sassValue.contents', sassValue.contents);
    .......
  }
  ......
}
....
```
Part of the output for running the above script/s. Remember in the SCSS file I would've passed in ```$font-family: TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif;```
```
This is a SassList
Output the Sass value TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif
What are the keys of the Object? [ '_list1$_contents', '_list1$_separator', '_list1$_hasBrackets' ]
What is the constructor name? SassList0
Is Sass list an instance of SassList? true
Sass value contents through sassValue.contents undefined
```

Thanks very much in advance for the assistance.

**Comment by stof** [comment]
In the doc you linked, the accessor is named `asList`, not `contents`

**Comment by classicmike** [comment]
@stof - Ah cool, must've misunderstood. Thanks very much for the help.
