### ISSUE TITLE
Some colors are converted into huge format even with compression

### ISSUE THREAD

**Issue by mkahvi** [sass/dart-sass#1761]
For example:
```css
background-color: #ffa50029;
```
becomes
```css
background-color: rgba(255, 165, 0, 0.1607843137);
```
even with `-s compressed` defined.

Specific use is sass 1.54.0 as acquired via npm.

**Comment by svivian** [comment]
I have the same issue. Just did some digging and the bug was introduced in version **1.49.10**. Below that I get hex codes/named colours, from 1.49.10 up I get `hsl()` definitions which are much longer.

Weirdly it's not all colours, for example this:

    background-image: linear-gradient(#f0f0f0, #dbdbdb);

becomes this:

    background-image: linear-gradient(#f0f0f0, hsl(0deg, 0%, 86%));

**Comment by nex3** [comment]
The eight-digit hex format is not yet widely-supported enough for Sass to emit it as an output format. According to the [browser support policy](https://github.com/sass/dart-sass#browser-compatibility), we can't release a change that would break more than 2% of browsers without a major version, including emitting non-opaque colors as eight-digit hex.

If you want compression that targets a narrower range of browsers, I recommend finding a PostCSS plugin to run on the CSS generated by Sass.

**Comment by mkahvi** [comment]
Supported by all browsers in this list that are still being maintained at least: <https://caniuse.com/css-rrggbbaa>  
But okay, I guess?

**Comment by nex3** [comment]
Our policy doesn't have to do with which browsers are being maintained, it has to do with percentage of market share.
