### ISSUE TITLE
Color calculation error

### ISSUE THREAD

**Issue by wyhPro** [sass/dart-sass#1763]
background-color: (map-get($map, 'bg-color') - #222);     
Undefined operation "#2d3436 - #222".

**Comment by wyhPro** [comment]
version: sass 1.50.1

**Comment by nex3** [comment]
Sass hasn't supported color arithmetic in years, because it doesn't correspond very well to a human understanding of what colors look like. I suggest using `color.adjust(..., $lightness: -13.3%)`.
