### ISSUE TITLE
Deep object-to-map conversion in objectToMap()

### ISSUE THREAD

**Issue by borutjures** [sass/dart-sass#1766]
_I used dart-sass to learn and implement a Dart library used in Node.js. Thanks Dart Sass team!_

I used `objectToMap()` (`lib/src/node/utils.dart`) to convert JavaScript JSON objects but it only converts the first level.
My JSON data uses more than one level of `Map<String, dynamic>`.
(_I use standard Dart `fromJson()` which expects the entire object to be converted into a map on every level_)

I changed the following line in `objectToMap()` to make a deep conversion to Map:

```
Map<String, Object?> objectToMap(Object object) {
  var map = <String, Object?>{};
---  jsForEach(object, (key, value) => map[key] = value);
+++  jsForEach(object, (key, value) => map[key] = value == null || value is String || value is num || value is bool ? value : objectToMap(value));
  return map;
}
```

Your implementation obviously works for how you use it. I just thought it might be useful to support any JSON.

_Thank you for the best example for JavaScript code to call Dart code!
(I'm still struggling with how to [call Dart static methods from JavaScript](https://stackoverflow.com/questions/73176388/how-to-call-a-dart-static-method-from-javascript))_

**Comment by nex3** [comment]
Thanks for the thought, but we can already do what you're suggesting with [`jsutil.jsify()`](https://api.dart.dev/stable/2.17.5/dart-js_util/jsify.html). `objectToMap()` exists explicitly to do this _only_ at the top level.

**Comment by borutjures** [comment]
Thank you for the clarification about the intent of objectToMap(). However it cannot be replaced with jsify - see table below. I’ll remove the change and create a dartify().

jsify: Dart => JS
dartify: JS => Dart
objectToMap: JS => Dart
