### ISSUE TITLE
SassError: NoSuchMethodError

### ISSUE THREAD

**Issue by ssinghal571** [sass/dart-sass#1768]
I am getting the following error while using sass-loader:

**Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: NoSuchMethodError: method not found: 'line' on null**

WebpackConfigue: 

module: {
rules: {
[ test: /\.scss$/, exclude:/node_module/, use: ['style-loader', 'css-loader', 'sass-loader']
}
}

**Comment by nex3** [comment]
Please file this issue against the webpack loader, or provide a reproduction that only uses the Dart Sass API.

**Comment by loilo** [comment]
For future visitors encountering this error: The reason for this problem is `sass-loader` trying to access [`SourceSpan`](https://sass-lang.com/documentation/js-api/interfaces/SourceSpan) properties that are absent in some situations, as described in #1790.
