### ISSUE TITLE
Have a JS/TS API to have the same behavior as the command line

### ISSUE THREAD

**Issue by Gnuk** [sass/dart-sass#1773]
With the the command line, it's possible to use `sass path/to/source:path/to/destination -s compressed --source-map --embed-sources` (or with other options like watch for example).

Is it possible to have this in JS/TS API with the same behavior?

An example with types on what I imagine:

```typescript

type Style = 'compressed' | 'expanded';

interface Options {
  sourceMap: boolean;
  style: Style;
  embedSources: boolean;
  watch: boolean;
 // …
}

type RenderDirectory = (from: string, to: string, options: Partial<Options> = {}) => void;
type RenderDirectoryAsync = (from: string, to: string, options: Partial<Options> = {}) => Promise<void>;

interface Sass: { // Here is the augmentation of Sass
  renderDirectory: RenderDirectory;
  renderDirectoryAsync: RenderDirectoryAsync;
}
```

Example of usage:

```typescript
sass.renderDirectory('path/to/source', 'path/to/destination', {
  style: 'compressed',
  sourceMap: true,
  embedSources: true,
});
```

Motivations on why I need this: Because I use the directory rendering (currently available only with the command line) inside a program and I should use child_process to launch `npx` to start the `sass` execution and for a lot of reason there is some cases where `npx` isn't recognized.

**Comment by Goodwine** [comment]
As you pointed out, the JS/TS API does not support the feature of compiling an entire directory.

For the sourceMap feature:
> [Options.sourceMap](https://sass-lang.com/documentation/js-api/interfaces/Options#sourceMap)
> Whether or not Sass should generate a source map. If it does, the source map will be available as [CompileResult.sourceMap](https://sass-lang.com/documentation/js-api/interfaces/CompileResult#sourceMap).
> ⚠️ **Heads up!**
> Sass doesn't automatically add a sourceMappingURL comment to the generated CSS. It's up to callers to do that, since callers have full knowledge of where the CSS and the source map will exist in relation to one another and how they'll be served to the browser.

You'd need to implement the directory-compiling and sourcemap-attaching features in your own code, we have no plans of implementing said feature.
