### ISSUE TITLE
TypeError: t1.call$1 is not a function

### ISSUE THREAD

**Issue by MahmudulHassan5809** [sass/dart-sass#1774]
i am facing this problem . 
![image](https://user-images.githubusercontent.com/35035594/183836578-c4301536-5af1-45d3-bbdb-cc1e9b778cfe.png)
Any help . Thanks

**Comment by nex3** [comment]
This definitely looks like a bug, but there's no way for us to help without more information. What version of Sass are you using? What's the smallest stylesheet that still produces this error message?

**Comment by njalcock** [comment]
I was facing this problem on Ubuntu 22.04. It seems to be caused in large projects hitting an upper limit of file watchers. To fix, I did the following:

```bash
$ echo fs.inotify.max_user_watches=393210 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by njalcock** [comment]
I'm not sure how. I can say that in our case we are running v1.50.1.

**Comment by nex3** [comment]
This looks like it's _probably_ an issue with the `chokidar` library that we use for filesystem watching on Node, but without a consistent repro it's hard to say for sure.

**Comment by LionyxML** [comment]
> ```shell
> $ echo fs.inotify.max_user_watches=393210 \
> | sudo tee -a /etc/sysctl.conf \
> && sudo sysctl -p
> ```

Aug 2023. This just saved me on Debian 12.

**Comment by TheProdigyLeague** [comment]
Greetings,
I see this issue is still opened...any closure? I thought I would just offer my assistance. Hope this helps. #2045 
```typescript
srcURL="https://github.com/amyipdev"

sass ~ $ scss/custom.scss:assets/css/custom_bootstrap.css 

TypeError: String can not be coerced into Integer
  Use --trace for backtrace.
$ --trace 
/usr/share/gems/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in '-': nil can not be coerced into Integer (TypeError)

      (num1 - num2).abs < epsilon
              ^^^^
```

**Comment by nex3** [comment]
> I see this issue is still opened...any closure?

As I said in all of my comments above, we cannot do anything here until we have a consistent reproduction.
