### ISSUE TITLE
[Question] How to compile all sass/scss files in folder?

### ISSUE THREAD

**Issue by aldanchenko** [sass/dart-sass#1775]
Hello 👋,

I'm trying to use dart-sass in my nodejs application. Right now I can compile one file using 

`const result = sass.compile("file_path");`

But I need to compile all sass/scss files in specified folder. Could you advice how to do this better? Or I need to call `sass.compile()` for each file in folder?

Thank you for help!

Best regards,
Alex

**Comment by Goodwine** [comment]
The NPM package is designed to give customizability to sass compilation and it doesn't come with a mode to compile all Sass files in a directory, it has to be one by one.

But FYI the dart-sass CLI does have the feature for compiling an entire directory
See: https://sass-lang.com/documentation/cli/dart-sass#many-to-many-mode

If this is not sufficient for your use-case you'll have to implement the logic in your own code, we currently have no plans of implementing this feature in the npm library

**Comment by aldanchenko** [comment]
Thank you for response @Goodwine!

I see. I'm working on VS Code extension which needs to work with scss, so trying to avoid additional dependencies.

One additional question: if scss file contains reference to another scss file will npm package handle it? For example, if I have main.scss and it contains next code

`@import "../../_variables";`

will it handle it?

Thank you for help!

**Comment by Goodwine** [comment]
Yup, it works just fine for both the CLI and the npm package. If you use `compileString` you'd need to add [`{url: ...}`](https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithoutImporter#url) to the options parameter if you have relative imports, and you may need to define [`loadPaths`](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) just [like in the CLI](https://sass-lang.com/documentation/cli/dart-sass#load-path)

To learn more about the JS API visit https://sass-lang.com/documentation/js-api/

And for community support you can also visit StackOverflow
https://stackoverflow.com/questions/tagged/sass

**Comment by aldanchenko** [comment]
Great! Thank you @Goodwine! 👍

**Comment by dan-goyette** [comment]
> The NPM package is designed to give customizability to sass compilation and it doesn't come with a mode to compile all Sass files in a directory, it has to be one by one.
> 
> But FYI the dart-sass CLI does have the feature for compiling an entire directory See: https://sass-lang.com/documentation/cli/dart-sass#many-to-many-mode
> 
> If this is not sufficient for your use-case you'll have to implement the logic in your own code, we currently have no plans of implementing this feature in the npm library

I'm not sure if I'm misreading this, or if I'm doing something wrong, but it does seem that dart-sass will recursively compile all sass in a directory.

My build script is simply `sass src:src`. This doesn't merely compile the scss files in 'src'. It recurses and compiles scss in all child directories as well. (I was happy to discover that, btw, given that I was previously using `node-sass -r` in the same way.)
