### ISSUE TITLE
rgba mistakenly converted to hex

### ISSUE THREAD

**Issue by Jarzka** [sass/dart-sass#1786]
I have the following SASS code in a SASS file which is imported to my Vue component in Nuxt 3:

```sass
.page {
  background-color: rgba(0, 0, 0, 0.87);
}
```

I convert this to CSS using `nuxt generate` (with nuxt 3.0.0-rc.8 & dart-sass 1.54.4), I get the following output:

```
.page {
  background-color: #000000de;
}
```

This is wrong, because there is no opacity anymore. The output should be:

```
.page {
  background-color: rgba(0, 0, 0, 0.87);
}
```

What causes this problem?

Side note: I could use opacity property instead of rgba, but it cannot always replace rgba, for example if I have something like `box-shadow: 0 -0.1rem 0.4rem rgba(0, 0, 0, 0.5) inset;`

**Comment by stof** [comment]
`#000000de` has the alpha channel value, as it is an 8-char hex value, not a 6-char one.

**Comment by Jarzka** [comment]
Interesting, I did not know that hex codes can contain alpha channel. Anyway, the output looks a bit different between `#000000de` and `rgba(0, 0, 0, 0.87)`, I guess the problem is somewhere else rather than in actual SASS->CSS generation.

**Comment by jathak** [comment]
Sass doesn't output RGBA hexadecimal notation, since it's not yet widely supported enough in browsers, so this is likely coming from some other tool in your build process.
