### ISSUE TITLE
"importer" function is not called for dependencies of dependencies

### ISSUE THREAD

**Issue by afshinm** [sass/dart-sass#1788]
I'm using the [`importer` option](https://sass-lang.com/documentation/js-api/interfaces/LegacyStringOptions#importer) to define a custom importer function, but it seems like this function is not called for dependencies of dependencies. 

For example:

> main.scss
```
@import "second.scss";
...
```

> second.scss
```
@import "fonts.scss";
@import "normalize.scss";
...
```

In this example, the `importer` function is called _once_ for the `second.scss` import, and not `fonts.scss` and `normalize.scss` imports.

**Comment by loilo** [comment]
It would be helpful to see how you apply the importer (i.e. your according JavaScript code). :)

**Comment by stof** [comment]
could it be that those `fonts.scss` and `normalize.scss` imports are resolved as relative imports ?

**Comment by nex3** [comment]
This is expected. As @stof suggests, if your importer points Sass to the filesystem it will always resolve relative loads *directly* from the filesystem if possible. This is an important usability consideration: it means that users will always be able to be confident that a relative import behaves how they expect, even if they have other importers in play.

**Comment by afshinm** [comment]
Yep, the reason the importer function doesn't get invoked is because those files actually exists on the disk and therefore, the custom importer function is not called.

I think it's useful to have this option to change the ordering of importers and let users handle the imports themselves, if they need to. In our case, we definitely need this feature. I'm happy to work on a PR. What do you think @nex3 @stof?

**Comment by stof** [comment]
@afshinm making relative imports win over importers is an explicit design choice of Sass, to avoid that adding a new importer suddently override relative imports somewhere in your Sass files (which would make it impossible to reliably write a library split between multiple files as you could not trust your relative imports). So to me, there is no chance that such BC break will be accepted.

**Comment by afshinm** [comment]
Understood, thanks @stof

**Comment by vvsamin** [comment]
@afshinm Did you somehow solve this problem?
Due to this behavior of the compiler, I still have to use node-sass, where the "importer" is applied to every "@import" declaration, even in nested dependencies.

**Comment by afshinm** [comment]
@vvsamin we ended up writing a custom imports processor to deduplicate the imports. You can pass in a function delegate to the DartSass import process and use a hashmap/set to deduplicate the imports in your codebase.

**Comment by nex3** [comment]
Yes, if you want full control over even relative imports, you need to write a full [`Importer`](https://sass-lang.com/documentation/js-api/interfaces/importer/) that handles _all_ filesystem loads itself rather than a [`FileImporter`](https://sass-lang.com/documentation/js-api/interfaces/fileimporter/) that delegates them back to the compiler. The [`Importer.canonicalize()`](https://sass-lang.com/documentation/js-api/interfaces/fileimporter/) documentation describes the algorithm for resolving a Sass file in the same way as the filesystem importer.
