### ISSUE TITLE
windows binary in winget.

### ISSUE THREAD

**Issue by fluentmoheshwar** [sass/dart-sass#1807]
It would be awesome if I can install sass via `winget install sass`

**Comment by nex3** [comment]
I looked into this a little bit, and it seems like the winget package repository is entirely pull-based: it compares hashes of release versions and automatically creates a PR to update a package each time the upstream version changes. As such, there's not really any change we need or (or can) make in this repo to publish there. You could just send a PR to winget to add the package there yourself.
