### ISSUE TITLE
Sass watcher doesn't re-compile on changes to meta.load-css() loaded modules?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/dart-sass#1808]
(I'm using v1.55.0)

In order to use CSS `@layer` efficiently on an existing code-base, I switched from e.g.:

```scss
/* screen.scss */
@use 'default';
@use 'layout';
@use 'theme';
```

to:

```scss
/* screen.scss */
@use 'sass:meta';

@layer default { @include meta.load-css('default'); }
@layer layout { @include meta.load-css('layout'); }
@layer theme { @include meta.load-css('theme'); }
```

That's by far the simplest upgrade path, rather than wrapping each module individually with a layer or mixin. 

But since making that change, the watcher no longer compiles any changes to modules _other than `screen.scss` itself_. Changes to any of the loaded modules are ignored by the watcher. I don't see anything about that in the docs, or the specs, or any other issues mentioning it - but I was able to reproduce the problem consistently.

Is that the expected behavior? Are others able to reproduce this?

**Comment by mirisuzanne** [comment]
As CSS is adding more of these architectural tools (layers, scope, etc) - these issues are becoming more and more important. As we're designing these features at the CSSWG, the main question we always get is 'how can I load stylesheets _into_ one of these structures'. In every case we end up adding additional `@import`/`<link>` tooling to make that possible. If Sass makes all those use cases _more difficult_, we become a major barrier to adoption.

I don't think that's a low priority to address _somehow_. It may be that we want to address it in some other way - but 'nested imports' are becoming more and more central to basic CSS functionality. We need to give that some attention.

**Comment by mirisuzanne** [comment]
(sorry, I meant to open this in the sass repo - not sure why I ended up in dart-sass)

**Comment by nex3** [comment]
Miriam and I talked about this, and we're going to handle it by special-casing `@include meta.load-css()` with a literal string argument as something the watcher can recognize.
