### ISSUE TITLE
sass outputs empty css file

### ISSUE THREAD

**Issue by data-handler** [sass/dart-sass#1809]
I am following the Material Design Color theming example,[here](https://material.io/develop/web/theming/color), but running sass generates an empty css file, with no errors reported.

Input file:
```
@use "@material/theme" with (
  $primary: #BB86FC,
  $secondary: #03DAC6,
  $background: #121212
);
```
Command line:
sass --load-path=node_modules --no-source-map scss:css

**Comment by nex3** [comment]
This is probably because the `@material/theme` library only defines variables and mixins, and doesn't contain any concrete CSS styles. Note that the example you link also contains `@use "@material/button/mdc-button";`.
