### ISSUE TITLE
list.join() changes a map to a list

### ISSUE THREAD

**Issue by starkis** [sass/dart-sass#1810]
In the following example, `list.join()` is used to join a value of type 'map' with a list containing two strings:

`@debug list.join( ("key": "value"), ("item1", "item2") );`

The expected result is a list containing three values, the map and two strings:
`("key": "value"), "item1", "item2"`

What actually happens is the map gets changed to a list with a space separator:
`"key" "value", "item1", "item2"`

I'm aware that the docs equate these two types:
"Every map counts as a list that contains a two-element list for each key/value pair. For example, (1: 2, 3: 4) counts as (1 2, 3 4)."

However, the change of type still causes unexpected issues.

**Comment by starkis** [comment]
I wonder if this is related to the way `@each` works on a map. Of course, you would normally give the `@each` rule _two_ variables (representing each key/value pair) when iterating over a map, but if you give it only _one_, it returns each key/value pair as a _list_ with space separator:

```
@each $item in ("key1": "value1", "key2": "value2") {
	@debug $item;
}
// DEBUG: "key1" "value1"
```

This happens, even if the map has only one pair:

```
@each $item in ("key1": "value1") {
	@debug $item;
}
// DEBUG: "key1" "value1"
```

I don't know—perhaps this is the expected behaviour? It all feels quite odd though.

**Comment by starkis** [comment]
> For maps, it is a comma-separated list containing space-separated lists for each key-value pair.

Thanks @stof, that certainly does seem to explain the behaviour in both cases.

Coming from other programming languages where an array is an array and a hash is a hash, it's certainly unsettling to see types changing like that though—remembering that Sass has a `meta.type-of()` function which _does_ distinguish between a list and a map. In my case, I'm writing a `product($lists...)` function (roughly equivalent to Ruby's `product()` array method). It's a recursive function which uses both `@each` and `list.join` and if the list happens to contain single key/value maps, it all starts to go pear-shaped.

The workaround that I came up with is this (the extra comma does the magic):

`@if list.length($list) == 1 { $list: $list,; }`

**Comment by stof** [comment]
@starkis a list and a map are different types in Sass. But **all** Sass types are castable to lists. And `list.join` works only for lists, so it casts other types if provided as argument.

**Comment by starkis** [comment]
Yes, and that mostly works as expected since, as you said before, 'for most values, this is a single-element list containing that value'. So most values will simply grow a set of brackets as needed and come through `list.join` unscathed. But it falls apart when working with a single-item list that contain a _map_, because Sass takes the liberty of unwrapping the list and reinterpreting the value itself (the map) as the list. The only way I know of telling Sass to keep the protective outer list intact, thereby preserving the map, is to tack that extra comma at the end. It gets the job done, but it does feel like a hack.

**Comment by stof** [comment]
checking `list.length($list) == 1` looks like the wrong check to me: an actual list might have a length of 1 (and your code will wrap it too) and a map can have a length higher than 1 (when it contains multiple keys).

Also note that `("key": "value")` is *not* a single-item list containing a map. It is a map.

**Comment by starkis** [comment]
> checking `list.length($list) == 1` looks like the wrong check to me: an actual list might have a length of 1 (and your code will wrap it too) and a map can have a length higher than 1 (when it contains multiple keys).

My function expects to work with lists. It doesn't care what type of object is in those lists, just that those types are preserved. You're right of course, `list.length($list) == 1` isn't specifically looking for a map, but that's the case where the comma really matters. I suppose I could change that line to:

`@if meta.type-of($list) == map { $list: $list,; }`

The intent is clearer perhaps, but now our code reflects Sass's own confusion over whether we're dealing with a list or a map! ;-)

> Also note that `("key": "value")` is _not_ a single-item list containing a map. It is a map.

Sure, but the same could be said for `(("key": "value"))`, or indeed `((("key": "value")))`—it doesn't matter how many brackets you add, Sass digs in and finds a map. As I said, the only way around this seems to be to add that comma:

```
@debug meta.type-of( (("key": "value"),) );
// DEBUG: list
```

**Comment by nex3** [comment]
> Sure, but the same could be said for `(("key": "value"))`, or indeed `((("key": "value")))`—it doesn't matter how many brackets you add, Sass digs in and finds a map. As I said, the only way around this seems to be to add that comma:
> 
> ```
> @debug meta.type-of( (("key": "value"),) );
> // DEBUG: list
> ```

Parentheses don't define a list in Sass. Parentheses are *only* for controlling precedence, like you do in math. A list is defined by the presence of *separators* (like spaces or commas) or *brackets*. So if you want a single-element list, you must either add a comma to the end as you discovered, or use brackets as in `[("key": "value")]`. We recommend the bracketed syntax any time you're dealing with lists that aren't intended to be emitted directly to CSS.

See https://sass-lang.com/documentation/values/lists for a full explanation of how lists work in Sass and what syntax they support.

**Comment by starkis** [comment]
> > it doesn't matter how many brackets you add, Sass digs in and finds a map
> 
> that's not true. list casting does not perform _deep_ list casting. So unless your own function is doing recursion (which I cannot know as you haven't shared it), I don't understand your issue.

@stof: Regardless of what it's actually doing under the hood ([explained by Natalie](https://github.com/sass/dart-sass/issues/1810#issuecomment-1275254472)), the fact remains: `meta.type-of( (("key": "value")) ) == map`.

I did mention that my function was recursive, but it isn't digging into nested lists. It's iterating over the top-level list items and branching to create every combination of those items. If it hits a list item that contains a single pair map, the outer list is forgotten and the map gets treated as the list. That's my issue.


> Parentheses don't define a list in Sass. Parentheses are _only_ for controlling precedence, like you do in math. A list is defined by the presence of _separators_ (like spaces or commas) or _brackets_. So if you want a single-element list, you must either add a comma to the end as you discovered, or use brackets as in `[("key": "value")]`. We recommend the bracketed syntax any time you're dealing with lists that aren't intended to be emitted directly to CSS.

@nex3: Thanks Natalie. Gosh, I've read (or perhaps skimmed) that document so many times, but never (at least not recently) stopped and noticed the key point:

> A single-element list can be written either `(<expression>,)` or `[<expression>]` …

So there it is. The square bracket syntax kinda feels less hacky to me, so I'll go with that. Taking on both of your comments, I'll go with this:

`@if meta.type-of($list) == map { $list: [$list]; }`

Thank you both. 😊
