### ISSUE TITLE
Issue grunt-sass error

### ISSUE THREAD

**Issue by vanthan303** [sass/dart-sass#1811]
Setup Grunt-Sass have been error, help me!!!
![Screenshot_76](https://user-images.githubusercontent.com/10190623/195109597-4cec9aa7-e02f-4963-9aaa-4ce62ea7ef5e.png)
![Screenshot_77](https://user-images.githubusercontent.com/10190623/195109606-9c4df139-339a-4106-975a-dd0e9d3dae48.png)

**Comment by nex3** [comment]
This is not an error that is raised by Dart Sass. You may be using the deprecated Node Sass implementation, but Dart Sass doesn't require any compilation on the user's end.
