### ISSUE TITLE
running sass in bun env

### ISSUE THREAD

**Issue by maor-benami** [sass/dart-sass#1815]
https://github.com/sass/dart-sass/blob/d17f70fd520bed3936e95968be1b6d30513efe1f/lib/src/io/node.dart#L195

bun version 0.2.1
running sass in `bun` env throws this error:
```
TypeError: undefined is not an object (evaluating 'self.process.stdout.isTTY')
      at /Users/user/node_modules/sass/sass.dart.js:17465:10
```

i made a quick fix on my machine in `sass.dart.js` (added the question mark mefore `isTTY`):
```
color = color0 == null ? J.$eq$(self.process.stdout?.isTTY, true) : color0,
```

**Comment by nex3** [comment]
Dart Sass is written for Node.js. If bun doesn't support Node.js's `process.stdout` API, I think that's a bug in bun, not in Sass.

That said, if this is indeed the only incompatibility, I'm open to a PR working around it and adding support for bun that way—as long as it comes with a link to a tracking issue in bun so we know when we can remove the workaround.

**Comment by dhbaird** [comment]
Priorities seem upside down here: Doing an isTTY check to pretty print colors on a console does not seem like a truly essential/core feature of a SASS compiler, and from other issues it's very apparent that the isTTY check is preventing use cases that people really want/need (https://github.com/sass/dart-sass/issues/25).

What would be wrong with accepting @maor-benami (question mark before `isTTY`) as to get these use cases working, rather than insisting all runtime environments must be node?

**Comment by nex3** [comment]
I'm not insisting that everyone use Node—both this issue and #25 remain open, and I explicitly said that I'd accept a patch for this. But Bun specifically says that it's "designed as a drop-in replacement for your current JavaScript & TypeScript apps or scripts" and that it "natively implements hundreds of Node.js and Web APIs, including ~90% of Node-API functions", so it's not unreasonable to expect that `process.stdout` will be implemented eventually and link a tracking issue for it.

**Comment by Jarred-Sumner** [comment]
Please don't take any action to fix this issue on Dart's end.

This issue is on Bun to resolve. We will have a fix before the end of next week

**Comment by dhbaird** [comment]
Just want to say a quick thanks to everyone for your hard and appreciated work on both of these projects, and please don't mind the presumptuousness of my previous comment (no offense intended). Have been successfully using the workaround suggested by @Jarred-Sumner's. Again, many thanks.

**Comment by nex3** [comment]
Closing at @Jarred-Sumner's request.
