### ISSUE TITLE
Self-hosted runner for macos-arm64 release is stuck

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#1826]
https://github.com/sass/dart-sass/actions/runs/3390247020/jobs/5634239987

**Comment by ntkme** [comment]
Looks like this is still an issue.

**Comment by nex3** [comment]
Yep, looks like. I'm having trouble accessing the Mac Stadium bot at the moment, so this is blocked on me hearing back from support on their end.

**Comment by nex3** [comment]
Okay, I believe this is fixed now. For future reference, I just reinstalled the runner on MacStadium and re-added it to the Sass org and it picked up the pending tasks automatically.
