### ISSUE TITLE
How to lint/check set of sass files without compile it?

### ISSUE THREAD

**Issue by krutoo** [sass/dart-sass#1830]
Hi, in my projects i use Sass with SCSS syntax.

I want to use something like `tsc --noEmit` which is essentially a TypeScript file validity check and it returns a code other than 0 if there are static analysis errors.

Is there any way to use Sass CLI in a similar way for static analysis?

Tools like stylelint don't quite fit, as they are more for checking the code style.

**Comment by nex3** [comment]
Your two options here are either using stylelint or running a full Sass compilation and discarding the result. Because Sass isn't statically typed, it doesn't really have any logic for doing static checks separately from a full compilation because so much of its logic only makes sense with a full compilation context available.

**Comment by krutoo** [comment]
@nex3 Thank you

Are there any plans to introduce static analysis? Now it is quite inconvenient not to receive any information about the validity of the code before the launch, even with stylelint

Sass has a certain logic that I would like to learn at the stage of static analysis. For example, the use of `@use` should be at the very beginning before `@import` (if i remember the compilation error correctly)

Also, stylelint does not say whether this or that mixin is imported correctly (by `@use` or `@import`) and whether such a mixin exists in principle

**Comment by nex3** [comment]
We aren't likely to have bandwidth to support this any time soon.

**Comment by krutoo** [comment]
> We aren't likely to have bandwidth to support this any time soon.

@nex3 This would be very useful in the future. Is there any way to make a proposal or support existing developments?

**Comment by nex3** [comment]
We're always happy to work with people on patches or additional tooling.

**Comment by Grawl** [comment]
I finished with following Node script:

```js
const { glob } = require('glob');
const { execSync } = require('node:child_process');

glob('src/**/*.scss').then((files) =>
    files.forEach((file) => {
        try {
            execSync(`./node_modules/.bin/sass --load-path=. ${file}`);
        } catch (e) {
            throw void 0;
        }
    }),
);
```

Why not `sass src/**/*.scss`? Dart Sass CLI cannot glob.

Why not `glob "./src/**/*.scss" --cmd="sass"`? Dart Sass CLI can process only one file as input, but `glob` sends a list of files.

`try/catch` and `throw void 0` is to ignore extra output including stack trace and buffers.

**Comment by nex3** [comment]
> Dart Sass CLI can process only one file as input

This isn't accurate, you can use [many-to-many mode](https://sass-lang.com/documentation/cli/dart-sass/#many-to-many-mode) to compile multiple files at once. You can also run `sass src` to compile all Sass files in the `src` directory.
