### ISSUE TITLE
NPM package support for Deno

### ISSUE THREAD

**Issue by oscarotero** [sass/dart-sass#1834]
Deno has implemented support for NPM packages but it's incorrectly detected by the SASS npm build.

I noted the following code in the JavaScript to detect if SASS is executed in the browser or in Node:

```js
// if we're running in a browser, Dart supports most of this out of box
// make sure we only run these in Node.js environment

var dartNodeIsActuallyNode = !dartNodePreambleSelf.window
```

The `window` object exists in Deno, so SASS incorrectly assume that the code is executed in a browser and fails on resolve `@import`.

I propose to change the code to the following:

```js
// if we're running in a browser, Dart supports most of this out of box
// make sure we only run these in Node.js or Deno environment

var dartNodeIsActuallyNode = !dartNodePreambleSelf.window || dartNodePreambleSelf.window.Deno;
```

With this change, SASS will work perfectly fine in Deno. I didn't found where this code is generated so couldn't make a pull request.

**Comment by jathak** [comment]
This code is coming from the [`node_preamble` package](https://github.com/mbullington/node_preamble.dart), so this issue should be filed there:

**Comment by oscarotero** [comment]
Okay, thanks!
