### ISSUE TITLE
Compile without folder path ?

### ISSUE THREAD

**Issue by bckthomas** [sass/dart-sass#1836]
Hi
My scss folder looks like this :
```
src/
    layout/layout.scss
    components/
        accordion/accordion.scss
        blockquote/blockquote.scss
```

When I compile files with sass src:dist/css, I get
```
dist/css/
    layout/layout.css
    components/
        accordion/accordion.css
        blockquote/blockquote.css
```

It is possible to compile files without folder path to have something like this ? I can't find an option about this
```
dist/css/
    accordion.css
    blockquote.css
    layout.css
```
Thanks !

**Comment by Goodwine** [comment]
It is not possible to do so from the CLI tool, if you want to customize the compilation of your Sass files you can use the JS API and store the files on your desired location - https://sass-lang.com/documentation/js-api/
