### ISSUE TITLE
Why were old release binaries just updated?

### ISSUE THREAD

**Issue by tylerprete** [sass/dart-sass#1844]
We rely on release 1.24.0 in our builds, and we use the SHA to verify integrity. 2 hours ago, it appears the binaries were updated (https://github.com/sass/dart-sass/releases/tag/1.24.0) and the sha is now different. From what I can tell, basically all release binaries were updated.

I'm reluctant to update our SHA until I know this was intentional and safe. Was this done for a reason?

**Comment by binoche9** [comment]
Looks like this happened for all releases

**Comment by jathak** [comment]
This was due to a security issue. See [the blog post](https://sass-lang.com/blog/security-alert-tar-permissions).
