### ISSUE TITLE
Cannot find module 'sass'

### ISSUE THREAD

**Issue by Belmiro-webdeveloper** [sass/dart-sass#1863]
I always encounter this error, when trying to use SASS with react and is very difficult for me to resolve it, sometimes I solved it instantly sometimes I take days to solve it, can someone please help me how can I resolve this issue . 
I used `npm install sass` to install the module, when I check under `node_modules` Sass is install but Compile fails due to missing of sass module. This confuses me a lot
![image](https://user-images.githubusercontent.com/71973458/210233356-b7a4a9b1-a572-4e67-b714-be25158cffbf.png)
![image](https://user-images.githubusercontent.com/71973458/210233398-fa7e79a8-115a-43dc-86a1-e0f472b0d02b.png)

**Comment by Goodwine** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
