### ISSUE TITLE
Add timestamp to printed compile statement

### ISSUE THREAD

**Issue by dannypernik** [sass/dart-sass#1869]
Since I often switch between projects, I am frequently unsure whether my `sass --watch` is watching the correct folder, even when I look at the Terminal pane. I imagine the screenshot below looks familiar. I would love to have a timestamp at the beginning or end of the print statement whenever sass compiles so that I can immediately see whether I have things set up correctly.

![image](https://user-images.githubusercontent.com/3347095/212449388-682b4699-1189-4a1e-a0ee-0f41a64067f7.png)

**Comment by wojtekxtx** [comment]
@nex3 what do you need help exactly with?

**Comment by dannypernik** [comment]
@wojtekxtx guessing @nex3 has higher priorities and would like someone to knock this one out. If I had any experience with Dart, I would do it.

**Comment by wojtekxtx** [comment]
@dannypernik Guessing you are correct

**Comment by dannypernik** [comment]
@wojtekxtx would you be willing to do it? I promise to be grateful every time I look at my timestamped sass message.

**Comment by connorskees** [comment]
You probably just need to update [this print](https://github.com/sass/dart-sass/blob/main/lib/src/executable/compile_stylesheet.dart#L135) to include the current datetime, which you can find in dart using `DateTime.now()`.

https://github.com/sass/dart-sass/blob/b98fa4fbd1b8a9a807441c418fea3fc931eed903/lib/src/executable/compile_stylesheet.dart#L135

**Comment by dannypernik** [comment]
Thanks @connorskees - I saw similar statements such as `expect(sass.stdout, emits('Compiled test.scss to out.css.'));` in other places and wasn't sure whether a change to the print statement would break something.

**Comment by connorskees** [comment]
You may have to update the newly failing tests, but changing that print statement shouldn't be a breaking semver change for the `dart-sass` executable.

**Comment by dannypernik** [comment]
@connorskees I have something close to what I want with:
```
var dateTime = DateTime.now();
var formattedDateTime = dateTime.subtract(Duration(milliseconds: dateTime.millisecond, 
    microseconds: dateTime.microsecond));
buffer.write('$formattedDateTime - Compiled $sourceName to $destinationName.');
```
My goal with formattedDateTime is to get rid of fractional seconds, which just seem excessive. Microseconds do not print if equal to 0, but milliseconds do. So the above gives me timestamps like `2023-01-28 22:11:12.000`. Is there an easier way to print a timestamp in `yyyy-mm-dd hh:mm:ss` format?

**Comment by wojtekxtx** [comment]
> would you be willing to do it?

@dannypernik why not?

**Comment by connorskees** [comment]
@dannypernik Without bringing in 3rd party libraries, you could do something like this:

```dart
DateTime now = new DateTime.now();
String date = "${now.year.toString()}-${now.month.toString().padLeft(2,'0')}-${now.day.toString().padLeft(2,'0')}";
String time = "${now.hour.toString().padLeft(2,'0')}:${now.minute.toString().padLeft(2,'0')}:${now.second.toString().padLeft(2,'0')}";
String formatted = "$date $time";
print(formatted);
```

Though I'm not super familiar with the dart stdlib either, so something better may be suggested during code review.

**Comment by connorskees** [comment]
Oh, I suppose you could use string slicing to remove the trailing decimal. A simple example:

```dart
var dateTime = DateTime.now();
var formattedDateTime = dateTime.subtract(Duration(milliseconds: dateTime.millisecond, 
    microseconds: dateTime.microsecond));

var formatted = formattedDateTime.toString();
print(formatted.substring(0, formatted.length - 4));
```

**Comment by wojtekxtx** [comment]
@connorskees first code is overcomplicated IMO. Second one is way better.

**Comment by connorskees** [comment]
The formatting is intentional to show the newly added lines.

**Comment by connorskees** [comment]
https://github.com/mozilla/experimenter/issues/7585#issuecomment-1241019726

**Comment by dannypernik** [comment]
@wojtekxtx @connorskees thank you both for your input. I've renamed the variables and simplified a step further:

```
var nowStr = DateTime.now().toString();
var timestamp = nowStr.substring(0, nowStr.length - 7);
buffer.write('$timestamp - Compiled $sourceName to $destinationName.');
```

With regards to why bother removing fractional seconds... sass is about style, right?? 😉  my opinion, while mathematically false, is that all else being equal, less is more. Since there's no functional purpose for fractional seconds in this case, better not to muddy the output with them.

This is actually the first time I'm contributing to a project that isn't my own. Do I need permission to create a branch and PR?

**Comment by connorskees** [comment]
@dannypernik Nope, no additional permissions required. You'll want to first fork the repo on GitHub and then push your commit to that repo.

It might look something like this,

```sh
# create new branch
git checkout -b MY_BRANCH
git commit . -m "MY COMMIT"
# assuming you've already forked the dart-sass repository
git push https://github.com/dannypernik/dart-sass MY_BRANCH
```

Then you can open the pull request using the GitHub UI.

GitHub's official docs have a pretty good explanation of the workflow, with pictures.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by dannypernik** [comment]
Thank you for your explanation, @connorskees - I hadn't forked.

**Comment by wojtekxtx** [comment]
> The formatting is intentional to show the newly added lines

If so, than 👍
