### ISSUE TITLE
Feature Request: Sass without Node 

### ISSUE THREAD

**Issue by gregoirer-mediactive** [sass/dart-sass#1873]
For a project we are trying to compile from a react app. Event if we have done some custom importers sass seems dependant to node (fs...). As javascript is supported It will we great to have a mode without node.

**Comment by wojtekxtx** [comment]
Its required by me also. Node is heavier and heavier with every release.

**Comment by jathak** [comment]
If you're not using Node, what engine are you using to run JavaScript?

If you're trying to run in a browser, that's tracked here: https://github.com/sass/dart-sass/issues/25

If you're trying to run with deno, that's tracked here: https://github.com/sass/dart-sass/issues/1142

If your concern is performance, you can also use the Dart version directly, or the embedded compiler with the Node host.
