### ISSUE TITLE
Are you planning to implement sass-convert?

### ISSUE THREAD

**Issue by ncaq** [sass/dart-sass#188]
I used `sass-convert` which existed in ruby-sass conveniently for code format.
The dart-sass Do you plan to implement this?

**Comment by nex3** [comment]
I'd like to keep that functionality around, but it'll probably be as a separate package that uses the Sass AST, once that's exposed. It's not something I expect to happen until after 1.0.0, though, nor do I expect it to exist in this codebase.

**Comment by ncaq** [comment]
[Prettier](https://prettier.io/) support scss.
sass-convert as a code formatter may have finished its role.
