### ISSUE TITLE
Unexpected token error originating in sass.dart.js

### ISSUE THREAD

**Issue by DanielKorsah** [sass/dart-sass#1886]
Steps to reproduce:

npm install -g sass
make simple test file a.scss
sass a.scss a.css

Expected result: output a.css
Actual result: 
![image](https://user-images.githubusercontent.com/22602906/219216029-9a15c915-7044-4711-bd70-c9c1e4b421ce.png)

**Comment by nex3** [comment]
What version of Node.js are you using?

**Comment by DanielKorsah** [comment]
Wow, I was apparently on 0.12.2 from 2015 and have just been lucky nothing I've needed has had compatibility issues. Seems to work on 18.14.1.
