### ISSUE TITLE
First-class calc and unary operator

### ISSUE THREAD

**Issue by flachware** [sass/dart-sass#1887]
Hi, as slash as division is deprecated by now, I’d like to follow the first-class `calc()` recommendation:
```
Recommendation: math.div(-$var, 2) or calc(-$var / 2)
```
```
$var: 16px;

div {
  margin: calc(-$var / 2);
}
```
```
Error: Expected digit.
  ╷
9 │   margin: calc(-$var / 2);
  │                 ^
  ╵
```
The negation produces an error though – is this expected?
I’m using sass 1.58.1.

**Comment by flachware** [comment]
Thanks for clarifying. May I ask which other arithmetic features are restricted in `calc()`?

**Comment by nex3** [comment]
Sass's calculation support covers all the standard calculation features defined in [Values and Units 3](https://drafts.csswg.org/css-values-3/#calc-notation), as well as the ability to use Sass variables and Sass functions. The only expression-level syntax it doesn't include (that would be meaningful in a calculation context) is unary operations and the `%` operator.

**Comment by flachware** [comment]
All clear, thank you.
