### ISSUE TITLE
Only two positional args may be passed / Positional and ":" arguments may not both be used.

### ISSUE THREAD

**Issue by bureaug** [sass/dart-sass#1894]
After updating to Dart SASS I can't get a hold of the one-liner I was using to watch and compile SASS before the updates.
Here is the old version (with Ruby SASS gem, I believe)
`sass --sourcemap=none --watch ./styles/tu-app.scss:./tu-public/assets/css/app.css --style "compressed"`

Here is the updated version for Dart SASS
`sass ./styles/tu-app.scss:./tu-public/assets/css/app.css --watch -–no-source-map --style compressed`

This particular syntax throws **Positional and ":" arguments may not both be used.**

If I write it like this
`sass ./styles/tu-app.scss ./tu-public/assets/css/app.css --watch -–no-source-map --style compressed`

then I get **Only two positional args may be passed**

What am I missing?

**Comment by nex3** [comment]
The second character in your `-–no-source-map` flag isn't a hyphen—it's actually U+2013 EN DASH. That's causing Sass's argument parser to treat it as a positional argument rather than a flag.

**Comment by bureaug** [comment]
Oh wow, that was unexpected. Thanks Natalie!
