### ISSUE TITLE
Source mappings wrong when using compressed style

### ISSUE THREAD

**Issue by david10sing** [sass/dart-sass#1896]
## Context

I am experiencing an issue when using the JS API, `sourcemap` compile option when used in tandem with `style = compressed`.

The source map is produced and I write it to a file. However, the mappings are broken and in Chrome's devtools, I am seeing styles pointing to the wrong file.

### Wrong
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6714127/221438790-3a26cc25-6b4f-4631-8425-312a8e94796f.png">

### Correct
<img width="713" alt="image" src="https://user-images.githubusercontent.com/6714127/221438694-497d36b3-bd67-44e6-b95f-33f0f47ac12c.png">

## Question
- Is this something that's known or it is not behaving correctly and might be due to the repository's setup and the scss files?

**Comment by nex3** [comment]
Can you provide a minimal repo that reproduces this issue?

**Comment by david10sing** [comment]
Hi @nex3 

Here is a link to a repo

https://github.com/david10sing/minified-sass-breaking-sourcemap

**Comment by nex3** [comment]
That repro looks like it passes the Sass output, including the sourcemap, through PostCSS. Can you reproduce it with Sass alone?

**Comment by david10sing** [comment]
Hi @nex3 

Removed the postcss processing.

As you will see, it has the same issue.

**Comment by nex3** [comment]
I can't reproduce that. Here's what I did:

```shellsession
$ git clone https://github.com/david10sing/minified-sass-breaking-sourcemap
$ cd minified-sass-breaking-sourcemap
$ npm i
$ mkdir dist
$ node sass-compiler.js
```

I then opened https://sokra.github.io/source-map-visualization/ and uploaded the generated `index.css` and `index.css.map` files. The `.index` class is clearly mapped to the correct location in `index.scss`.

**Comment by david10sing** [comment]
@nex3 

It's not in chrome devtools inspector

**Comment by nex3** [comment]
That sounds like abug in the chrome devtools inspector. Have you tried reporting it there?

**Comment by david10sing** [comment]
Thank you @nex3 

Reported ☝️

**Comment by ntkme** [comment]
@david10sing That is not the right place for chrome bugs, please follow instructions on this page: https://www.chromium.org/for-testers/bug-reporting-guidelines/
