### ISSUE TITLE
Update engines value in package.json

### ISSUE THREAD

**Issue by AravinthAro** [sass/dart-sass#1915]
Hi team,
               Build failed when sass upgraded to v1.59.0 in our app that uses Node v12. After debugging for a considerable amount of time, we found that dart-sass uses `??` which is supported in Node >=14.0.0. This could be avoided if `engines` field is properly updated with the NodeJS version that this package supports.

**Comment by jathak** [comment]
We just published 1.59.3, which removes the `??` operators, so it should now support Node 12 again.

We will still drop support for Node 12 soon, since it's end-of-life, but we'll make sure to do it properly. Sorry for the trouble!
