### ISSUE TITLE
Properly drop support for Node 12

### ISSUE THREAD

**Issue by jathak** [sass/dart-sass#1917]
We inadvertently broke Node 12 support in 1.59.0 without declaring that we were doing so in our package.json.

1.59.3 temporarily restored support so that NPM isn't downloading invalid versions for those who are still using Node 12, but we should still drop support properly soon, since it's EOL. We may also want to add a check that we're testing against the minimum Node version we declare support for to prevent similar issues in the future.

**Comment by randombitsUK** [comment]
This also broke support for Node 10 (don't ask) so should definitely have been marked as a major release.

**Comment by stof** [comment]
the supported node version in the `engine` field won't prevent npm from using that version. It will only show a warning. That's why dropping support for node versions is considered a BC break warranting a major version.

**Comment by stof** [comment]
> We may also want to add a check that we're testing against the minimum Node version we declare support for to prevent similar issues in the future.

that's indeed a good idea

**Comment by jathak** [comment]
As stated [here](https://github.com/sass/dart-sass#nodejs-compatibility), we don't consider dropping support for an EOL Node release as a breaking change, as long as we declare this in our package.json (that NPM doesn't use this information for version solving is it's problem, not ours).

Node 10 support was dropped back in 1.49.1 (see #1612). We'll drop Node 12 support in #1911.
