### ISSUE TITLE
Change in SHA of old version 1.35.1-linux-x64

### ISSUE THREAD

**Issue by stefanoborini** [sass/dart-sass#1921]
Hello, 

I am depending on dart-sass 1.35.1-linux-x64, which I downloaded from the assets attached to the release (at https://github.com/sass/dart-sass/releases?page=8 )

To ensure integrity of the package, I computed the SHA and I verify the download. The SHA used to be 3fad2c49e2c5c401cade2ca5ff6c92d7bdacb8bd4a96315ff847b6e887b4d056. It is now 2ac65490970bdbf7ac5da2a4a35f205813cac2b1e315ae3b731dfbe3e06623e3. 

I checked the assets date, and it is marked as Dec 12, 2022, but the 1.35.1 release has been made on Jun 15, 2021. Is it plausible that the specified tar.gz has been rebuilt for some reason, or has the package been compromised?

**Comment by ntkme** [comment]
It has been re-uploaded due to https://sass-lang.com/blog/security-alert-tar-permissions.

**Comment by stefanoborini** [comment]
@ntkme Amazing! thank you so much! Closing.
