### ISSUE TITLE
Can't run dart-sass

### ISSUE THREAD

**Issue by ElnuDev** [sass/dart-sass#1924]
I'm trying to use [dart-sass-embedded](https://github.com/sass/dart-sass-embedded) for Dart Sass support in Hugo, but as I'm having the same issue on dart-sass and its the larger repository, I'm asking here. The README claims that the releases are standalone and ready to run, but this isn't being the case for me.

When I download dart-sass-1.60.0-linux-x64.tar.gz, extract it, and run `./sass` it tells me `./sass: line 20: /home/elnu/Downloads/dart-sass/src/dart: cannot execute: required file not found`, even though this file exists. If I run `./src/dart` it tells me `bash: ./src/dart: cannot execute: required file not found`. What dependencies am I missing?

Thanks in advance!

**Comment by ntkme** [comment]
This error usually means your Linux distribution is not built with glibc. The official dart sdk release only supports glibc as of today. However, building dart sdk with musl (e.g. alpine linux) or bionic (e.g. android ndk/termux) has been possible.

Although it is not official (I’m just a frequent contributor here), I have been providing dart-sass and dart-sass-embedded releases for some non-glibc systems:

- https://github.com/dart-musl/dart-sass/releases
- https://github.com/dart-musl/dart-sass-embedded/releases
- https://github.com/dart-android/dart-sass/releases
- https://github.com/dart-android/dart-sass-embedded/releases

In fact, I contributed alpine/musl support in official dart sdk repository a while ago: https://github.com/dart-lang/sdk/commit/afe921902609e95e5050dad1fe82d2a69bcdcf95

The main challenge to make this official is that the build process for musl isn’t very straightforward that the dart team has not committed to make it part of their official release process, so we have to use my unofficial build of dart sdks:

- https://github.com/dart-musl/dart
- https://github.com/dart-android/dart

There sdk projects are completely automated with GitHub Actions and will keep up with official dart releases as much as possible.

@nex3 I’m happy to continue providing unofficial releases for these systems as it was highly demanded (especially in the Ruby community where alpine was too popular to be ignored). Any thoughts on how can we make it more official?

**Comment by ntkme** [comment]
Another possibility is that if you are using NixOS or some system that glibc is not installed in a standard location. You have to `patchelf` the dart vm binary.

**Comment by ElnuDev** [comment]
Sorry I didn't mention earlier, but yes, I am on NixOS. I'll check out `patchelf`, thanks!

**Comment by nex3** [comment]
@ntkme I'm open to using these custom Dart builds to distribute musl- and Android-compatible binaries. It'll be tricky to integrate with the Node.js embedded host, though, since npm doesn't have a way to select different packages based on which libc is available. We'd probably need to distribute both the musl and the glibc binaries in each Linux package.

Closing this issue out for now since it sounds like the immediate problem has been resolved, and I don't think there's anything we can do in the embedded host to avoid depending on a specific libc path on NixOS.
