### ISSUE TITLE
Windows detect Virus TrojanDownloader:JS/Nemucod.DM

### ISSUE THREAD

**Issue by Audomaro** [sass/dart-sass#1930]
![image](https://user-images.githubusercontent.com/6589247/230653656-5ef6795e-a20b-48d9-98e8-6ebefdd4aa6e.png)

![image](https://user-images.githubusercontent.com/6589247/230653898-f08d58a0-d946-467b-97d2-e15314b14cb0.png)

**Comment by nex3** [comment]
Which version of Sass is supposedly downloading other programs? Do you have any evidence from the JS file itself that it's been corrupted in some way? This looks like a false positive in your virus scan, but out of an abundance of caution I've downloaded the npm release of sass 1.61.0 and verified that sass.dart.js looks the same as the version generated locally for me.

**Comment by zeusec** [comment]
Security researcher here, I just came across this detection yesterday as well. This was a Defender detection at around the same time as the OP. Looks like it's for 1.26.3, in this particular case Defender triggered on 'C:\Users\user\AppData\Local\npm-cache\_cacache\content-v2\sha512\e4\d3\07235f98158c38b0ddf27ca8e92ee57d07997b32a43a165913702e054fea076c14546684a31ebaedfe61349c55c9c98da442d53da2ef47c6f1558cb16ebb'.

Without diving too deep, this is looking like a false positive. Not seeing any other vendor pick this up, and this being an old package there have been no updates since May 2020. Have only seen one case of this detection, doesn't seem widespread.

**Comment by MarkTallentire** [comment]
We're also seeing this on a Azure Pipelines build server using Windows Defender, triggered a ton of alerts in our Security Portal overnight

**Comment by kushneo** [comment]
Same issue in here , any update on this ? Thanks !

**Comment by Audomaro** [comment]
Thank you, everything is fine, the antivirus no longer detects it as malware.

**Comment by siconghe-gep** [comment]
Hi @Audomaro 

how did you get it to work?

we tried to update windows defender and we are still having the same issue.

**Comment by baguettesandbrie** [comment]
Hello, our Defender has just generated an alert for it, detected also as Nemucod

**Comment by siconghe-gep** [comment]
Hi

This seems like a false positive from defender.

This sass.dart.js file has been there for 3 years without any updates.

It's been very stable since then. And according to this ticket https://github.com/sass/dart-sass/issues/1930

The guy who raised the ticket got the issue resolved without any updates to the sass.dart.js file.

Is there anything we can do on our side?

Thanks
Sicong

**Comment by baguettesandbrie** [comment]
Hi and thank you! Yes, I saw that.  However I cannot find a trace of Nemucod within Defenders updates change log matching up with around when the alerts were first reported in this thread; only the original entry from Nov 18th, 2021
What I am trying to obtain is the hash of the original, known-good file.

**Comment by siconghe-gep** [comment]
Is there anything I can help you with?

**Comment by geocine** [comment]
These are the files that is throwing the virus alert on my machine. Just putting here for more details

```
containerfile: C:\Users\geocine\AppData\Local\Yarn\Cache\v6\npm-sass-1.32.6-e3646c8325cd97ff75a8a15226007f3ccd221393-integrity\node_modules\sass\.yarn-tarball.tgz
containerfile: C:\Users\geocine\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\0b\c6\786e3a865a7b186b5d68f21a4a02ea3215d461ad21dc6230abf9701654f48842a0bc9a9d9fe43c787a6d1d2987a13f38395d27a49828ea2671196c896cf4
file: C:\Users\geocine\AppData\Local\Yarn\Cache\v6\npm-sass-1.32.6-e3646c8325cd97ff75a8a15226007f3ccd221393-integrity\node_modules\sass\.yarn-tarball.tgz->(GZip)->package/sass.dart.js
file: C:\Users\geocine\AppData\Local\Yarn\Cache\v6\npm-sass-1.32.6-e3646c8325cd97ff75a8a15226007f3ccd221393-integrity\node_modules\sass\sass.dart.js
file: C:\Users\geocine\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\0b\c6\786e3a865a7b186b5d68f21a4a02ea3215d461ad21dc6230abf9701654f48842a0bc9a9d9fe43c787a6d1d2987a13f38395d27a49828ea2671196c896cf4->(GZip)->package/sass.dart.js
```

This should be a false positive. This has been on my drive since 9/2/2021. Could have been a windows defender definitions update.

**Comment by waitingu2** [comment]
I have an same issue.
![image](https://user-images.githubusercontent.com/5581558/231158454-0cd3df0f-dc76-414d-a63c-89606d13fd46.png)

**Comment by patelsagarr** [comment]
> Is there anything I can help you with?

Can you please help more about this detection? I have posted same in the Chat.


"Can someone please help with this detection, here defender has quarantined all the "saas.dart.js" files from all the systems. some of those files were recently downloaded and some were older than 2 years.
Microsoft hasn't officially published anything about this false detection.
Apart of this channel I haven't find any article about this detection. Has any one have any other article with this information?"

**Comment by jayricx** [comment]
Any update on this? I was alerted by our IT to delete this sass.dart.js file in my device as it was detected as Nemucod Malware.

**Comment by nex3** [comment]
There's nothing we as the Sass team can do about this. It's a false positive and only the people who maintain the databases can fix it.
