### ISSUE TITLE
Importing sass causes unrelated code to overflow stack

### ISSUE THREAD

**Issue by awesometown** [sass/dart-sass#1942]
Our code uses a recursive function (included at the bottom) to flatten a json structure. The expected output of running the script is:

```
{ 'foo.nested': 'whatever', bash: 'baz', func: {} }
```

If I `require("sass");` (1.62.0) anywhere in the same project, calling `flatten` will instead error with:

```
/src/sass/flatten.js:7
    if (Object(cur) !== cur) {
        ^
RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at recurse (/src/sass/flatten.js:7:9)
    at recurse (/src/sass/flatten.js:18:9)
    at recurse (/src/sass/flatten.js:18:9)
    ...
```

The specific issue seems to be that `for (var p in cur)` behaves differently when `sass` is imported. Without it, the loop is never entered. With it, `p` gets a value of `call$0` and we enter the loop and start recursing endlessly. Adding an explicit check for a property being a function fixes the issue.

This is old code and I'm not trying to claim it's a _good_ "flatten" implementation, but it lurked uncomplainingly in the code until we tried to upgrade to `sass`. Quality of our code notwithstanding, I'm mostly just surprised that importing a library like `sass` would have an effect at all on it. I'm relatively new to Javascript as a whole, so even if this isn't ultimately deemed a sass bug, I'm hopeful someone could explain what's going on here?

```
//Uncomment to break things
//const sass = require("sass");

function flatten(data) {
  var result = {};

  function recurse(cur, prop) {
    if (Object(cur) !== cur) {
      result[prop] = cur;
    } else if (Array.isArray(cur)) {
      var curLength = cur.length;
      for (var i = 0, l = curLength; i < l; i++)
        recurse(cur[i], prop + "[" + i + "]");
      if (l == 0) result[prop] = [];
      // Uncomment to fix them again
      // } else if (typeof cur === "function") {
      //   return;
    } else {
      var isEmpty = true;
      for (var p in cur) {
        isEmpty = false;
        recurse(cur[p], prop ? prop + "." + p : p);
      }
      if (isEmpty && prop) result[prop] = {};
    }
  }

  recurse(data, "");
  return result;
}

const data = {
  foo: { nested: "whatever" },
  bash: "baz",
  func: function () {
    console.log("hello world!");
  },
};

console.log(flatten(data));
```

**Comment by nex3** [comment]
You _almost certainly_ don't want to be using `for (var p in cur)` here. That's going to iterate through all properties of `cur`, _including_ anything it inherits from `Object.prototype`. This will break if anyone adds anything to the global prototype chain—arguably doing that is kind of an antipattern, but it's also pretty intrinsic to how Dart's JS compilation works (if you'd like to file an issue about that, the repo is https://github.com/dart-lang/sdk).

Instead, you want to write `for (var [p, value] of Object.entries(cur))`, which will iterate over all `cur`'s _own_ properties, ignoring anything that comes from its inheritance chain.
