### ISSUE TITLE
Flag to set file suffix

### ISSUE THREAD

**Issue by crstauf** [sass/dart-sass#1943]
I have need to change the file extensions of the output CSS files. Having an option to set the file extension for the output files would be excellent.

My specific use-case is that I have need for uncompressed and compressed files (but I suspect there may be other use-cases, like versioning).

Being able to do only two simple

```bash
sass scss:css;
sass scss:css --style=compressed --file-suffix=.min
``` 

rather than list out every file twice 

```bash
sass scss/style.scss:css/style.css;
sass scss/style.scss:css/style.min.css --style=compressed
.
.
.
.
.
.
.
.
.
.
``` 

would be excellent.

**Comment by nex3** [comment]
The Sass CLI aims to provide a core set of widely-useful behavior, not necessarily to meet every use-case. This is the sort of narrow use-case that's better served by writing a wrapper script to rename the generated files after the fact, or using the Sass API to have more fine-grained control over compilation.
