### ISSUE TITLE
scale-color.Error: Only one positional argument is allowed. All other arguments must be passed by name.

### ISSUE THREAD

**Issue by POMXARK** [sass/dart-sass#1947]
```
Message:
    src/assets/scss/settings/_custom-variables.scss
Error: Only one positional argument is allowed. All other arguments must be passed by name.
    ╷
506 │   "primary":    scale-color($primary, $table-bg-level),
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
what does that mean how can i fix this for bootstrap 5.2 preferably without changing the code?

https://github.com/codedthemes/dashboard-kit-free-bootstrap-admin-template

sass@v1.32.13
npm i gulp@v4.0.2
node v16

![image](https://user-images.githubusercontent.com/18720947/235381658-6711afd5-b784-482c-bdff-e7765b40cf73.png)

node v14
with what configuration there are no problems, what does it depend on what has changed during this time where to read?

Figured it out in my case the code was written for **node-sass**

```
npm remove sass
npm i node-sass

#galpfile.js
require('gulp-sass')(require('node-sass'))
```

**Comment by jathak** [comment]
This code is incorrect. Node Sass was not as strict with this, but all parameters passed to `scale-color` other than the first must be named, which Dart Sass enforces. You should update this in the code, or send a PR to the upstream project with this code if you don't own it.

**Comment by POMXARK** [comment]
> This code is incorrect. Node Sass was not as strict with this, but all parameters passed to `scale-color` other than the first must be named, which Dart Sass enforces. You should update this in the code, or send a PR to the upstream project with this code if you don't own it.

I am not a front-end developer and wrote sass back in 2015... when there were no such problems. where can i see examples of valid file?
what should this code look like?

**Comment by jathak** [comment]
You need to say the name of the argument you actually want to scale, e.g.
```scss
scale-color($primary, $red: $table-bg-level)
```

**Comment by POMXARK** [comment]
> You need to say the name of the argument you actually want to scale, e.g.
> 
> ```css-scss
> scale-color($primary, $red: $table-bg-level)
> ```
thanks in my case, I looked at how it is now done in bootstrap and replaced

**node-sass**
```scss
$table-variants: (
  "primary":    scale-color($primary, $table-bg-level),
  "secondary":  scale-color($secondary, $table-bg-level),
  "success":    scale-color($success, $table-bg-level),
  "info":       scale-color($info, $table-bg-level),
  "warning":    scale-color($warning, $table-bg-level),
  "danger":     scale-color($danger, $table-bg-level),
  "light":      $light,
  "dark":       $dark,
) ;
```

**dart-sass**
```scss
$table-variants: (
    "primary":    shift-color($primary, $table-bg-level),
    "secondary":  shift-color($secondary, $table-bg-level),
    "success":    shift-color($success, $table-bg-level),
    "info":       shift-color($info, $table-bg-level),
    "warning":    shift-color($warning, $table-bg-level),
    "danger":     shift-color($danger, $table-bg-level),
    "light":      $light,
    "dark":       $dark,
) ;

```
everything compiled
