### ISSUE TITLE
Dart Sass + Jekyll 4.3.2 + Canonical Vanilla-Framework 3.1.4

### ISSUE THREAD

**Issue by csharpee** [sass/dart-sass#1949]
I tested https://talk.jekyllrb.com/t/making-use-of-vanilla-framework-without-npm-for-jekyll-scss/8213 Ubuntu's vanilla framework 3.1.4 and had all kinds of sassy errors like math.div and interpolation with hsl.

I tested on with the latest jekyll-sass-converter 2.1 with Jekyll 4.2.2 and 4.3.2.

If it helps, I had the following errors with the _latest stable release_ of ubuntu vanilla-framework.

https://github.com/canonical/vanilla-framework/issues/4757

I am unsure what Dart Sass version Jekyll is using, I assume it is 1.6.2.
Related: https://github.com/jekyll/jekyll-sass-converter/issues/152

**Comment by ntkme** [comment]
- jekyll-sass-converter 2.1 runs SassC (libsass).
- jekyll-sass-converter 3.0 runs sass-embedded (Dart Sass)

You were not even using Dart Sass.

**Comment by csharpee** [comment]
Thank you @ntkme

**Comment by ntkme** [comment]
@csharpee Another issue to keep in mind is that the classic github-pages flow is locked to use jekyll-sass-converter 1.5.2 (it ignores your Gemfile/Gemfile.lock). If you want to use github-pages you need to use GitHub Action to build your page.
