### ISSUE TITLE
Running dart sass through dartsass-rails and getting an issue when querying the version

### ISSUE THREAD

**Issue by bdielman** [sass/dart-sass#1950]
When typing `dartsass --version` on the command line I get this output:

```shell
Unexpected exception:
Invalid argument (uri): Value must be a String or a Uri: null
```

I'm running the dev environment on an M2 MBP fwiw.

**Comment by ntkme** [comment]
We don’t manage the distribution of dart-sass for rails, and this cannot be reproduced with standard alone dart-sass. Please open an issue at https://github.com/rails/dartsass-rails

**Comment by bdielman** [comment]
Will do. Thanks!
