### ISSUE TITLE
Include hashes of files in the releases

### ISSUE THREAD

**Issue by cleydyr** [sass/dart-sass#1951]
Hello, team.

I'm the owner of the [dart-sass-maven-plugin](https://github.com/cleydyr/dart-sass-maven-plugin) repo, and I wanted to make my plugin capable of downloading the released files from the [Releases page](https://github.com/sass/dart-sass/releases) and _verifying the integrity_ of the downloaded files. However, currently, GitHub doesn't add hash information automatically in the Release pages. Could you include those hashes in future releases? It would be great if they could be added to previous releases as well.

Thank you for your work!

**Comment by ntkme** [comment]
https://github.com/google/dart_cli_pkg/issues/100

**Comment by cleydyr** [comment]
Hey, @ntkme. Thanks for the hint and the quick response. I searched for "hash" but not for "checksum" in the issues. I'm closing this case now.
