### ISSUE TITLE
hellow? sorry for barging... this is not a issue. i just need a simple guide for scss. plz somebody help me

### ISSUE THREAD

**Issue by nio04** [sass/dart-sass#1953]
**as sass website says,** we should not use "import" anymore but use "use" & "forward". i would love to do it too! but..

i love to folder-ize my structures. like my **all sub pages will go different html folder** & **final css file be generated in different folder**. you get the point.

since i want to use "use" and "forward" in my scss and abandon using "import", how can i achive that same result as before?

another thing to mention, i want all my file `./html/*.html ` (all html files from root directory folder called html) to have access in` sass/page/*.scss` **Can you show me? how to set up package.json so that, it can watch multiple sass files accross from all over my sass folder?**

i have added my site structure  for better understanding. plz help me... i am new at this. but i can see that, scss is very needy for me!  [github link --website structure](https://github.com/nio04/site-structure/tree/main)

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
