### ISSUE TITLE
How to batch compile Sass with relative paths?

### ISSUE THREAD

**Issue by morceaudebois** [sass/dart-sass#1957]
Hi! I have a pretty big project that has lots of subfolders, each of which has an instance of SCSS/CSS files that need compiling. I've been using the sass npm package for a while now and I manually input each file in a large script, like this: 

`sass --watch --no-source-map --style compressed project1/src/scss/project1.scss:project1/src/css/project1.css project2/src/scss/project2.scss:project2/src/css/project2.css ...`

This is obviously very inefficient as there are now at least 50 of those SCSS files in the project. I'm searching for a way to automate it using relative paths. The folder structure is always the same, only the file names change. I tried paths like these: `**/src/scss/*.scss:**/src/css/*.css`  but couldn't find a way to make it work.

I can do it with a VS Code extension as [it supports such filepaths](https://imgur.com/a/jRgH8NM), but I'd rather do it with the npm package. Not sure if this is the right place to ask and I might be missing something, any idea?
Thank you!

**Comment by Goodwine** [comment]
We do not have plans for batch processing or handling glob expansion in the CLI. However you can leverage the use of the [Sass JS API](https://sass-lang.com/documentation/js-api/) and implement this yourself as a node script.
