### ISSUE TITLE
Subsequent import fails in dart-sass-embedded

### ISSUE THREAD

**Issue by Coridyn** [sass/dart-sass#1962]
`sass-embedded` fails to compile with the following setup:

 * using an importer function
 * a file is imported through the importer function twice
 * the next file path passed to the importer function is incorrect and fails to import

The last import path passed to the importer has the wrong format (start with file://) which prevents the importer from being able to resolve the file location.

This compiles correctly with `sass` (`dart-sass`), but fails when compiling with `sass-embedded`.

A minimal repro is available in this repository: https://github.com/Coridyn/sass-embedded-import-error

## Environment

It seems to be OS independent - this fails in Windows 10 and 11 and on Linux (in WSL)

```
sass-embedded 1.62.0
Windows 10 (19045.2913); nodejs v16
WSL running Ubuntu 20.0.4; nodejs v18
```
------------------------------------

## Description of error

When running the [reproduction example](https://github.com/Coridyn/sass-embedded-import-error) the `sass-embedded` build fails with a `Error: Can't find stylesheet to import` error.

For the import statement `@import "foo/_b.scss";`

The import function expects to receive a path like `foo/_b.scss`

But instead it receives a path like `file:///home/coridyn/sass-embedded-import-error/src/foo/_b.scss`, which causes the import to fail.

```
Error: Error: Can't find stylesheet to import.
  ╷
2 │ @import "./foo/_b.scss";
  │         ^^^^^^^^^^^^^^^
```

**Comment by Goodwine** [comment]
OK. I'm able to repro in a new `sass-spec` test. I'll start looking at this

**Comment by Goodwine** [comment]
Investigating here, I realized that _normally_ the compiler requests the host to canonicalize an import like `file://foo/bar.scss` followed immediately by `foo/bar.scss` if the former didn't exist.

In this case, the latter doesn't happen the second time that the import is attempted to be loaded. That's not a problem per se, but the embedded host has a flip-flopping behavior that goes "out of sync" when `foo/bar.scss` is not requested the second time.

So now it's just a matter of determining which side is wrong 😅
