### ISSUE TITLE
Build Error: Unsupported output style "nested”

### ISSUE THREAD

**Issue by Jastin-Infj** [sass/dart-sass#1971]
## Ideal Movement

"nested" works correctly and the css files are stored in the "css" folder dedicated to dist.

Current Status:

"nested" is not called and an error occurs as with "title". See screenshot (1) for details.

Also, "expanded" and "compact" work fine and are stored in the "css" folder dedicated to dist of css files.

## What have done so far.

Referring to other issues

I have installed fiber and sass-loader but they are failing.

Referenced sites

[https://github.com/dcloudio/uni-ui/issues/126](https://github.com/dcloudio/uni-ui/issues/126)

### Development environment

OS: Linux Ubuntu22.04 LTS

**installed packages**

- npm v9.6.7
- node v18.0.0 (Using nodebrew)
- gulp-cli v2.3.0 (local 4.0.2)

**source code:**

**gulpfile.js**

```bash
'use strict'

const gulp = require('gulp');
const sass = require('gulp-sass')(require('sass'));

function buildStyles() {
  return gulp.src('./_src/sass_fld/**/*.scss')
    .pipe(sass({outputStyle: "nested"})).on('error',sass.logError)
    .pipe(gulp.dest('./css'));
};

exports.build = buildStyles;

function watch(){
  gulp.watch('./_src/sass_fld/**/*.scss',buildStyles);
}

exports.watch = watch;

exports.default = gulp.series(buildStyles,watch);
```

**package.json**

```bash
"devDependencies": {
    "@dcloudio/uni-ui": "^1.4.27",
    "fibers": "^5.0.3",
    "gulp": "^4.0.2",
    "gulp-sass": "^5.1.0",
    "sass": "^1.62.1",
    "sass-loader": "^13.2.2"
  }
```

**Screenshots:**

**outputStyle: “nested” or “compact”  1

![Untitled](https://github.com/sass/dart-sass/assets/34806778/7e9328a8-b40e-43c8-9478-3617326121dc)

```bash
tree -L 3 -I node_modules
```

.
├── _src
│   ├── css
│   │   └── style.css
│   └── sass_fld
│       └── style.scss
├── gulpfile.js
├── package-lock.json
└── package.json

**outputStyle: “expanded”: or “compressed” 2

![Untitled (1)](https://github.com/sass/dart-sass/assets/34806778/92476007-95b8-4ff1-aef9-cfa98ccbbeb0)

```bash
tree -L 3 -I node_modules
```

.
├── _src
│   ├── css
│   │   └── style.css
│   └── sass_fld
│       └── style.scss
**├── css
│   └── style.css**
├── gulpfile.js
├── package-lock.json
└── package.json

**Comment by jathak** [comment]
This is working as intended. Past (now deprecated) Sass implementations supported a "nested" output style, but Dart Sass never has, and the [JS API specifically only supports "expanded" and "compressed"](https://sass-lang.com/documentation/js-api/types/OutputStyle)
