### ISSUE TITLE
README is inaccurate about Embedded Dart Sass commands in 1.62.1

### ISSUE THREAD

**Issue by brycewray** [sass/dart-sass#1977]
The README already [describes the ability](https://github.com/sass/dart-sass#embedded-dart-sass) to use the commands `sass --embedded` and `sass --embedded --version`, presumably as a result of the [recently announced](https://sass-lang.com/blog/rfc-embedded-protocol-2) changes regarding Embedded Dart Sass. However, this capability is (obviously) not yet in v.1.62.1, since it was released before those changes.

**Comment by nex3** [comment]
The README always describes the state of the `main` branch of the repository, not necessarily the most recently released package. If you're looking for documentation that tracks the current release, check [the Sass website](https://sass-lang.com/documentation/cli/dart-sass).
