### ISSUE TITLE
latest version of sass introduces breaking change in the minor release

### ISSUE THREAD

**Issue by saket-r** [sass/dart-sass#1984]
The Sass library has introduced, a breaking change in the minor release `1.61.0`
with PR https://github.com/sass/dart-sass/pull/1911/files

Ideally, This should be done in a Major release, Since it's not backward compatible as mentioned in
https://docs.npmjs.com/about-semantic-versioning
![image](https://github.com/sass/dart-sass/assets/17457446/0f65d2b7-36c7-42c6-bd40-80de7a0b3da3)

For instance,

the following `package.json` has `ng-packagr` & the node version is `12.x` due to the constraint by other major libraries.
```
{
  "name": "demo-sass-issue",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "engine":{
   "node": "=12.20.1"
  },
  "devDependencies": {
    "ng-packagr": "^10.1.0"
  }
}
```
which further has a dependency on `sass` v `^1.23.0`
![image](https://github.com/sass/dart-sass/assets/17457446/9c33dd9d-a009-4a80-af44-3a59d3198de2)

> version of node and yarn are v12.20.1 & 1.22.5 respectively

 Running `npm install` / `yarn install` with the above package.json will throw an error 
 > Error sass@1.62.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.20.1"

**Expectation**: The minor release version like `1.61.0` or `1.x.y` should not break backward compatibility / enforce restrictions which could potentially lead to break change. 
Such changes should be done as part of a major release like `2.x.y`.

**Comment by voltaek** [comment]
The reasoning for this change in a minor version is detailed in the README in the [Node.js Compatibility](https://github.com/sass/dart-sass#nodejs-compatibility) section. As `node v12.x` is [over a year past EOL](https://github.com/nodejs/release#end-of-life-releases), this change is following that reasoning.

The Changelog [did note](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1610) this potential breaking change for `v1.61.0`, so this wasn't undocumented (as your post seems to imply?).

**Comment by jathak** [comment]
Yes, [our compatibility policy](https://github.com/sass/dart-sass#compatibility-policy) specifically excludes dropping support for an EOL Node version as a change that requires a major release.
