### ISSUE TITLE
Support source maps

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#2]
We need to support source maps, as close to Ruby Sass and LibSass as possible. Hopefully this shouldn't be too difficult, since we're already tracking source spans everywhere.

- [x] Add support to the Dart API.
- [x] Add support to the JS API.
- [x] Add support to the CLI.
- [ ] Track variable definitions.

**Comment by gabrielmaldi** [comment]
Hey, sorry to bother, but is this on the roadmap anytime soon? It's the only thing preventing us from migrating to the awesome dart-sass 😄 Thanks!

**Comment by nex3** [comment]
This is scheduled for after the 1.0.0 stable release. Our first priority is getting the language implementation compatible, which is largely in place, and getting the JavaScript API node-sass compatible, which is not. Once 1.0.0 is out, though, this will be a high-priority feature.

If you're interested in getting this sooner, contributions would be rad! A lot of the infrastructure is already in place: we store source spans for the full CSS AST, so all you'd need to do is pipe those to the [`source_maps`](https://pub.dartlang.org/packages/source_maps) package.

**Comment by gabrielmaldi** [comment]
Great to see this implemented, thanks!
