### ISSUE TITLE
ReferenceError: _cliPkgExports is not defined

### ISSUE THREAD

**Issue by ve3** [sass/dart-sass#2024]
For anyone who has error **_ReferenceError: _cliPkgExports is not defined_** with sass from npm and JS API.

All you have to do is change from `import sass from 'sass';` to `import * as sass from 'sass';` and everything should now working fine.

I created this issue in case someone who just updated and run via JS API but error occur. Searched but found nothing on Google. The line above is the fix.

From my problems:
Previous known working version: 1.54.9
Updated to 1.63.5 then error occur.
Changed as commented above fixed.

Thank you.

**Comment by nex3** [comment]
1.63.5 _should_ support `import sass from 'sass'` with just a warning, not a crash. I'll investigate.
