### ISSUE TITLE
【🔥】Support generate W3C Native CSS Nest Format

### ISSUE THREAD

**Issue by DaiQiangReal** [sass/dart-sass#2031]
Dart-sass flatten all css selector when compiling css. Can dart-sass compile scss to native nest style format css？  Nest CSS has less size and also easy to analyze for both browser and human. Most modern browser now support nest css.

W3C： https://www.w3.org/TR/css-nesting-1/
Can I Use: https://caniuse.com/?search=CSS%20nest

![image](https://github.com/sass/dart-sass/assets/29626873/15660da1-39d5-43f4-abd7-11af4a6bc38a)

**Comment by nex3** [comment]
Duplicate of https://github.com/sass/sass/issues/3030.
