### ISSUE TITLE
Sudden issue with --watch

### ISSUE THREAD

**Issue by JeffreyHuig** [sass/dart-sass#2037]
Since today, whenever i use command-prompt to execute the --watch command it works for a little while but after one minute it just stops and gives me the following error message:

Unexpected exception:
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\xampp\htdocs\Portfolio_Bijwerking_Kennis\css'

dart:isolate  _RawReceivePortImpl._handleMessage

I am pretty new to working with dart-sass or SCSS in general. Does anyone know a reason why this happens?

**Comment by jathak** [comment]
This looks like an issue coming from the OS. There's only so much we can do here, but you can pass `--poll`, which will be less efficient, but should be more reliable.
