### ISSUE TITLE
SassCalculation.clamp with less than 3 arguments fail the validation

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#2041]
https://sass-lang.com/documentation/js-api/classes/sasscalculation/#clamp

```
clamp(min: CalculationValue, value?: CalculationValue, max?: CalculationValue): SassCalculation
```

In JS API, we can construct `clamp` with only 1 one argument.

In Dart code documentation:

```
  /// This may be passed fewer than three arguments, but only if one of the
  /// arguments is an unquoted `var()` string.
```

Then, this spec seems wrong to throw an error for requiring 3 arguments: https://github.com/sass/sass-spec/blob/e6e6762153c8c6a02d289ab078fb1186c10b91f3/js-api-spec/value/calculation.test.ts#L320-L327

Finally in dart-sass and embedded-host-node, there are extra logic in protofy and deprotofy to enforce 3 arguments:

https://github.com/sass/dart-sass/blob/6c592134fe26ae04be820245a3631f2814f61d42/lib/src/embedded/protofier.dart#L352-L362
https://github.com/sass/embedded-host-node/blob/2b1f4ecaf83a9e949976427f522291f674a04a57/lib/src/protofier.ts#L383-L387

These currently makes it impossible to return a clamp with an unquoted `var()` string in custom functions.

**Comment by nex3** [comment]
The `_verifyLength()` call is correct—that function does include logic to add exceptions for `var()` calls. The verification logic in the protofier and the JS API tests are indeed wrong, though.
