### ISSUE TITLE
Include generated classes in pub.dev releases

### ISSUE THREAD

**Issue by doodlezucc** [sass/dart-sass#2047]
Hi there, I've noticed that it's not possible anymore to compile the latest sass executables via `dart pub global activate sass`. Using sass as a dev dependency in a Dart project yields similar compile/analysis errors. Essentially, the file `embedded_sass.pb.dart` can't be found.

I've tried compiling from source by following your [instructions](https://github.com/sass/dart-sass/tree/1.64.1#from-source), and naturally all analysis errors got resolved after generating the files for the embedded compiler with Buf.

According to the [pub.dev](https://pub.dev/packages/sass/score) page, static analysis has been failing since version [1.63.1](https://pub.dev/packages/sass/versions/1.63.1/score), which introduced the embedded compiler into the repo. I understand that best practice suggests adding generated files to `.gitignore`, but would it be possible to include the `.pg*.dart` files for pub.dev publication?

It's definitely not the standard way to use sass CLI, but as a Dart user myself, it's pretty convenient to simply activate the package from pub. My apologies if this issue has been brought up before, I wasn't able to find anyone mentioning it in this repository.

**Comment by nex3** [comment]
Looks like the definitions are still missing...
