### ISSUE TITLE
compiling css variables with map-get() doesn't resolve the map value

### ISSUE THREAD

**Issue by medarob** [sass/dart-sass#2056]
I have two maps ($colors and $margin) with the following SCSS code:

```
$colors: (
    "schwarzblau90": #314860,
);

$margin: (
    "top": 5px
);

:root {
    --session-sessioninfo-margin: 5px 0;
    --session-sessioninfo-margin: map.get($margin,"top") 0;
    --session-sessioninfo-color: map.get($colors,"schwarzblau90");
    color: map-get($colors,"schwarzblau90");

    --margin-top: map.get($margin,"top");
    margin-top: map.get($margin,"top");
}
```

after compiling I have the following CSS:

```
:root {
  --session-sessioninfo-margin: 5px 0;
  --session-sessioninfo-margin-test: map.get($margin,"top") 0;
  --session-sessioninfo-color: map.get($colors,"schwarzblau90");
  color: #314860;

  --margin-top: map.get($margin,"top");
  margin-top: 5px;
}
```

It seems that the map.get() isn't resolved when used in conjunction with a css variable? However, it works with a CSS property which I included as a reference.
Can anyone reproduce this issue?

Dart SASS 1.63.6

**Comment by ntkme** [comment]
https://sass-lang.com/documentation/breaking-changes/css-vars/

**Comment by pamelalozano16** [comment]
[Custom Properties (or CSS Variables)](https://sass-lang.com/documentation/style-rules/declarations/#custom-properties):
> All tokens, including those that look like SassScript, are passed through to CSS as-is. The only exception is interpolation, which is the only way to inject dynamic values into a custom property.

So instead of
```
--session-sessioninfo-color: map.get($colors,"schwarzblau90");
```
You should write:
```
--session-sessioninfo-color: #{map.get($colors,"schwarzblau90")};
```
