### ISSUE TITLE
1.65.0 and 1.65.1 releases are incomplete due to self-hosted macos-arm64 runner getting stuck again

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass#2058]
The 1.65.0 and 1.65.1 release are incomplete due to macos-arm64 release getting stuck:

- https://github.com/sass/dart-sass/actions/runs/5814287620/job/15763975259
- https://github.com/sass/dart-sass/actions/runs/5814783988/job/15765463125

This has happened a few times in the past and whoever has access to the MacStadium sponsored runner may need to restart it.

@nex3 @pamelalozano16 @Goodwine

**Comment by Goodwine** [comment]
It looks like the job is stuck at "Waiting for a runner to pick up this job...", that said, I don't think neither Pamela nor I have access to the Macstadium setup 🤔 - I'll try rerunning the jobs tomorrow and see if that changes anything

**Comment by larsgrefer** [comment]
In case someone needs them, here are macos-arm64 binaries I built locally:

[dart-sass-1.65.0-macos-arm64.tar.gz](https://github.com/sass/dart-sass/files/12340064/dart-sass-1.65.0-macos-arm64.tar.gz)
[dart-sass-1.65.1-macos-arm64.tar.gz](https://github.com/sass/dart-sass/files/12340065/dart-sass-1.65.1-macos-arm64.tar.gz)

**Comment by nex3** [comment]
I believe I've restarted the runner.

I have no idea why this keeps happening or what to do to handle it in the long term, unfortunately.

**Comment by ntkme** [comment]
@nex3 Just a guess here: Could it be automatic OS upgrade or something else rebooting the machine? Do you have GitHub Action auto-start on OS boot?
