### ISSUE TITLE
"sass": "1.65.1" Error: This variable was not declared with !default in the @used module.

### ISSUE THREAD

**Issue by sysmat** [sass/dart-sass#2063]
- using sass

```scss
@use "./node_modules/@picocss/pico/scss/pico.scss" with ( // overwrite pico
    $primary-500: #E65A00,
    $primary-600: #C54100,
    $primary-700: #A52D00);
```
- **Error**: This variable was not declared with !default in the @used module.
- this working fine with **sass 1.64.2**

**Comment by Goodwine** [comment]
Which pico version? Can you have a minimal repro that doesn't use pico?

**Comment by sysmat** [comment]
"@picocss/pico": "^2.0.0-alpha1",

**Comment by ntkme** [comment]
It appears to be a breaking change between pico 1.x and 2.x, which has nothing to do with sass version.

**Comment by Goodwine** [comment]
As @ntkme mentions, the issue is a breaking change in picocss. I recommend writing a script that can repro the issue and using git-bisect on picocss to identify when the issue started.

https://git-scm.com/docs/git-bisect

**Comment by Yegorich555** [comment]
I have same issue when trying to integrate icomoon fonts - what's wrong on my side ???
![image](https://github.com/user-attachments/assets/4ea46fe8-2173-47a4-a069-6621f8f79135)

**Comment by nex3** [comment]
@Yegorich555 Configuration only works for variables defined in the module you're loading. Your `fonts/icommon/style.scss` loads the `$icommon-font-family` variable, but it doesn't define it itself. You can use [the `@forward` rule](https://sass-lang.com/documentation/at-rules/forward/) as well to make Sass treat `$icommon-font-path` as though it was defined in `fonts/icommon/style.scss`.

(As a side note, when you're using the module system, you don't need to add a manual namespace like `icommon-`. That's what explicit module namespaces are for.)
