### ISSUE TITLE
Inconsistent formatting of degenerate numbers with units

### ISSUE THREAD

**Issue by kaj** [sass/dart-sass#2070]
In `spec/values/numbers/degenerate.hrx` there is tests for degenerate numbers both in css output and in error messages.  The css output formats the numbes like e.g.

```css
a {
  b: calc(-infinity * 1px);
}
```

... while the error messages looks like:

```
Error: calc(-Infinitypx*em) isn't a valid CSS value.
```

Could the expected error messages be updated to have the same formatting as the css output (in this case `calc(-infinity * 1px*em)` with lower-case i and multiplied by one for the unit) ?

It would make other implementations (like rsass) simpler, and my guess is that it should simplify dart sass as well.

**Comment by nex3** [comment]
Other implementations don't have to match the same error output as Dart Sass; since errors are purely cosmetic, you can feel free to have your own formatting as long as you emit errors under the same circumstances.

**Comment by kaj** [comment]
> Other implementations don't have to match the same error output as Dart Sass

That is true, thanks.  But by trying to make the errors exactly the same in rsass as in dart sass, I make it easier for myself to keep track of which things are handled correctly and what remains to be done.

Also, I think avoiding "Infinitypx" and making errors consistent with the css formatting would be an improvement for dart sass as well.  So I agree with @jathak that this is a bug, but only a cosmetic one.
