### ISSUE TITLE
Disable CSS Nesting unfolding

### ISSUE THREAD

**Issue by abcdabcabcabcd00** [sass/dart-sass#2072]
Add an option to disable CSS Nesting unfolding (the part where `body { & > #app { color: red; } }` becomes `body > #app { color: red; }`

https://caniuse.com/css-nesting

**Comment by nex3** [comment]
Our plans for native CSS nesting support are described in [this blog post](https://sass-lang.com/blog/sass-and-native-nesting/).

**Comment by ggedde** [comment]
> 

in the blog post you mentioned it states "We will add support for parsing plain CSS nesting in .css files. This nesting won’t be resolved in any way; Sass will just emit it as-is."
When will this be supported? Or how will it be available?

**Comment by nex3** [comment]
Supporting nesting in plain CSS is tracked in https://github.com/sass/sass/issues/3524.
