### ISSUE TITLE
JS API - Compilation fails with double-slash comments in the given Sass code

### ISSUE THREAD

**Issue by parasshah195** [sass/dart-sass#2099]
My setup is running Sass JS API from the Sass code fetched from Codemirror editor. The project is bundled using Vite, and I'm using the Svelte framework.

I've cleaned up the line breaks, but on sending Sass code with double-slash comments (`//`), it throws an error.

Code sass compilation usage:
```
sass.compileString(sassCode, {
    style: 'compressed',
    quietDeps: true,
    syntax: 'scss',
  });
```
where `sassCode` can be a string literal like:
```
`h1 {
  font-size: 5rem;
  // color: orange;
}`
```

On running it by passing the string after removing line breaks, this is the error I get:
<img width="650" alt="image" src="https://github.com/sass/dart-sass/assets/18551588/b8ec0854-52dc-4426-a320-2eb37991cff5">

On trying to reproduce on different Typescript setups in online code editors (codesandbox, stackblitz, codepen), all of them just straight up fail with altogether another error `Cannot read properties of undefined (reading 'isTTY')`, but that's a different topic. 

Is this error being caused by something in my setup bundling? Or can somebody else reproduce it at their end and is it a bug in the library code?

**Comment by parasshah195** [comment]
Just realized that this error is happening because of removal of line breaks, causing comment to wrap onto the same line and everything else past that being commented (including the closing brace).

In which case, any suggestions/ideas as to how to handle line breaks in Sass string with comments?

**Comment by nex3** [comment]
Sass isn't removing the line breaks here, something else is removing them before Sass ever sees the input.
