### ISSUE TITLE
Failed to release prebuilt binaries for darwin and windows at 1.69.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [sass/dart-sass#2110]
https://github.com/sass/dart-sass/releases/tag/1.69.0

Prebuilt binaries for darwin and windows weren't released.

<img width="466" alt="image" src="https://github.com/sass/dart-sass/assets/13323303/38f3beb7-16b0-4a19-b8d1-2ec2b37b9115">

CI failed.

https://github.com/sass/dart-sass/actions/runs/6425154865/job/17447533839

**Comment by mjesteve** [comment]
Since last night I can't compile my project.
Could you help me? How can I configure my pom-maven to use dart-sass-1.68.0 version?
At the moment:
<plugin>
                <groupId>io.github.cleydyr</groupId>
                <artifactId>dart-sass-maven-plugin</artifactId>
                <version>1.1.0</version>
                
				<executions>
					<execution>
						<id>generate-css-using-sass</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>compile-sass</goal>
						</goals>
					</execution>
				</executions>

                <configuration>
                    
                    <inputFolder>${basedir}/src/main/resources</inputFolder>
                    <outputFolder>${basedir}/src/main/resources</outputFolder>
                    <noSourceMap>true</noSourceMap>
                    
                    <style>EXPANDED</style>

                </configuration>        
            </plugin>

Thx

**Comment by michhey** [comment]
I faced the same problem. As a workaround you can specify the dart compiler version in the configuration section.

```
<configuration>
    <version>1.68.0</version>
    ...
</configuration>
```

**Comment by stof** [comment]
Based on the annotations in https://github.com/sass/dart-sass/actions/runs/6425154865, it looks like a payment failure

**Comment by mjesteve** [comment]
It has worked perfectly. Thanks a lot.

**Comment by BalusC** [comment]
This is blocking project builds. The logic really needs to be changed that there's at least a fallback. E.g. download previous version. If still erroring then fallback further to last successfully used locally cached version.

**Comment by stof** [comment]
@BalusC this is the kind of things you should report to the dart-sass-maven-plugin project, not to dart-sass itself (I don't think this dart-sass-maven-plugin is maintained by the Sass team)

**Comment by nex3** [comment]
Sorry for the trouble; the release process didn't fully complete, and we're working on fixing it.
