### ISSUE TITLE
Node v21 - `navigator` object

### ISSUE THREAD

**Issue by sadiqsalau** [sass/dart-sass#2122]
Can't compile when using Node v21 because of the introduction of navigator object.

**Comment by nex3** [comment]
Can you provide more details? What fails specifically? Why do you think the navigator object is related?

**Comment by bricss** [comment]
Compiler fails with following error: `TypeError: Cannot read properties of undefined (reading 'indexOf')` 💥
Bcos of this code:
```javascript
function(hooks) {
  if (typeof navigator != "object") return hooks;
  var ua = navigator.userAgent;
  if (ua.indexOf("DumpRenderTree") >= 0) return hooks;
  if (ua.indexOf("Chrome") >= 0) {
    function confirm(p) {
      return typeof window == "object" && window[p] && window[p].name == p;
    }
    if (confirm("Window") && confirm("HTMLElement")) return hooks;
  }
  hooks.getTag = getTagFallback;
}
```
Whereas `navigator.userAgent` is _undefined_ 🥴

**Comment by nex3** [comment]
It's astonishing to me that Node.js thought it would be a good idea to add a global `navigator` object, but setting that aside: this is an issue with the standard code generated by dart2js, and should be filed against https://github.com/dart-lang/sdk. There's nothing we can do in Dart Sass to fix this.

Note that Node.js 21 is also not an LTS release, and thus may receive less support than an even-numbered release.
