### ISSUE TITLE
Support server-side absolute sourcemap paths

### ISSUE THREAD

**Issue by jwhitlock** [sass/dart-sass#2132]
When next.js uses dart-sass, the source maps are added as relative paths. This works on the initial page load. However, when next.js changes pages, it injects CSS as inline styles. This leads to a 404, as the sourcemap path is not relative to the page URL (https://github.com/vercel/next.js/issues/27672).

This would work if the source map was an absolute path, as seen by the server. For example, instead of:

```
/*# sourceMappingURL=11bc70d3a586e887.css.map */
```

the path was:

```
/*# sourceMappingURL=/_next/static/css/11bc70d3a586e887.css.map */
```

dart-sass doesn't have this information, so one was to add it would be a new option, like:

```
sass --source-map-urls=relative --source-map-abspath="/_next/static/css/"
```

This way next.js and other tools could tell dart-sass the expected absolute path is to the map file.

**Comment by nex3** [comment]
This is an issue you should file with next.js. Dart Sass's JavaScript API doesn't have any say in how the `sourceMappingURL` comment is added or what URL it uses—it just returns [a source map](https://sass-lang.com/documentation/js-api/interfaces/compileresult/#sourceMap) separately from the CSS output and relies on users to stitch them together however they prefer.

**Comment by jwhitlock** [comment]
I misunderstood the docs, thanks @nex3 for the clarification.
