### ISSUE TITLE
Imports not resolving correctly when in nested path

### ISSUE THREAD

**Issue by zaalbarxx** [sass/dart-sass#2145]
Hi!
Here is some example project in Vite which uses dart-sass under the hood to preprocess SCSS files.
https://stackblitz.com/edit/vue3-vite-starter-wmnist?file=package.json,src%2FApp.vue,src%2Fmain.js,src%2Fapp%2Fstyles%2Fmain.scss

Given this code the processing fails with error saying that it could not file in the path. After some debugger work I've noticed that there seem to be some problem with resolving the imports:
![image](https://github.com/sass/dart-sass/assets/3301242/afb79672-9f41-4787-b173-e710283e392b)

After compilation I get this result:
![image](https://github.com/sass/dart-sass/assets/3301242/f96859b8-a7a1-4468-85c6-f274d6fb165b)
For some reason some of the 3rd party packages (node packages) are correctly not transformed, but some of them will get the `styles` prefix (or whichever folder holds the currently processed SCSS file).  Vite provides "fallback importer" which triggers when SASS is not able to determine the import path, but in that case it looks like it actually thinks it can resolve it on its own and transforms the import path itself.

Any clues with that one ? Should I dig deeper into this one ? :)
Cheers

**Comment by ntkme** [comment]
You should ask this in vite project instead of here because most of these import have to be handled by vite's custom importer. We don't control how that custom importer works.

**Comment by zaalbarxx** [comment]
I did, but actually I think this is some issue with SASS instead of Vite. Like I said when I debugged the code the import which is broken was not handled by custom importer. So my guess is that the Dart itself transformed this path, not Vite.

**Comment by zaalbarxx** [comment]
Ok, I take it back, it is Vite issue. Thanks @ntkme :)
