### ISSUE TITLE
Q&A: How can i fix waring import sass from 'sass'` is deprecated

### ISSUE THREAD

**Issue by yoyo837** [sass/dart-sass#2161]
When I import `sass` with code: `await import('sass')`, it report this:

```
import sass from 'sass'` is deprecated.
Please use `import * as sass from 'sass'` instead.
```

How can i fix this waring?

**Comment by nex3** [comment]
Can you provide a full reproduction of this? I don't see a warning with the following code with Sass 1.70.0:

```js
async function main() {
  const sass = await import('sass');
  console.log(sass.compileString('a {b: c}'));
}

main();
```

**Comment by yoyo837** [comment]
My code looks like this, So is it wrong?

```diff
-- console.log(sass.compileString('a {b: c}'));
++ console.log(sass.default.compileString('a {b: c}'));
```

**Comment by yoyo837** [comment]
It seems I need to treat `sass` and `less` differently.

When I load [less](https://github.com/less/less.js/tree/master/packages/less) using the dynamic `import` method, I need to call the `.default`, but `sass` doesn't. 
Yeah, I'm writing a `postcss` plugin.

**Comment by nex3** [comment]
Yes, you need to avoid using `.default.`.
