### ISSUE TITLE
[feature request] Official Python bindings to replace `libsass-python`

### ISSUE THREAD

**Issue by vadimkantorov** [sass/dart-sass#2166]
I was enjoying a lot embedding some SASS processing (npm-less!) in my basic python SSG code. It would be great if new basic bindings appeared to supercede deprecated libsass and it current bindings libsass-python

There exists these outdated bindings, but it involves calling a subprocess and shipping a lot of binaries which is not very ideal https://pypi.org/project/dart-sass/

Maybe a Python package could embed a Dart VM (as in https://github.com/fuzzybinary/dart_shared_libray) and just call into the existing Dart bitcode

**Comment by vadimkantorov** [comment]
Regarding a shim as in https://pypi.org/project/dart-sass/, it's still useful to have a pip-installable package that could resolve in runtime the correct platform. It might also interesting to have a single binary that does platform dispatch in runtime, akin to https://justine.lol/ape.html

**Comment by nex3** [comment]
It would definitely be useful, but the Sass core team doesn't have the bandwidth to maintain more than one embedded host.
