### ISSUE TITLE
Deprecation message replaces underscores with hyphens

### ISSUE THREAD

**Issue by mikeybinns** [sass/dart-sass#2180]
For some reason, when I see a deprecation message, the recommendation it provides replaces the underscores with hyphens, which then breaks the code. I'm not sure if this happens with the automatic migrator as I'm not using it.

![image](https://github.com/sass/dart-sass/assets/38146638/e3ecd5a2-ce67-4955-a3e8-5bbc9d42f66c)

Steps to recreate:
1. set up a sass file, add 2 variables with underscores in the name
2. divide one variable by another
3. compile the sass to see the message

The projects I've seen this on use Gulp and Gulp Sass, with this package passed into gulp-sass.

**Comment by ntkme** [comment]
Sass identifiers treat hyphens and underscores as identical, and it uses underscores for identifiers internally in its implementation. So, it should not break your code even if you apply it as is.

Technically, we can attempt to use source mapping to get the original input for variable name for recommendation, but it's only cosmetic.
