### ISSUE TITLE
Build Errors with Latest Sass Version in GitHub Actions CI/CD Pipeline

### ISSUE THREAD

**Issue by FareedGuru** [sass/dart-sass#2186]
Hello Sass Team,

I've recently encountered build errors in my GitHub Actions CI/CD pipeline that seem to be related to the latest updates to Sass (as of 2 days ago). These errors were not present before the update. Here's a brief overview of the issues:

"sass": "^1.37.5",
"sass-loader": "8.0.0",

- **Environment:** GitHub Actions using Node.js version 16.x, with `sass` and `sass-loader` configured in my Webpack setup.
- **Symptoms:** The build process fails with multiple errors related to Sass, including critical dependency warnings and module resolution issues. Notably, errors like "Critical dependency: the request of a dependency is an expression" and "Module not found: Error: Can't resolve 'node-sass'" have started appearing.
- **Steps to Reproduce:** The errors occur during the build process initiated by a push to the `dev` branch, triggering the GitHub Actions workflow. The workflow includes steps for setting up Node.js, installing dependencies with Yarn, and executing the build script.

I've verified that these issues are consistent across all runs in the last two days and are not present in my local development environment or in previous builds before the latest Sass update.

Any guidance on resolving these issues or information on recent changes that might affect the build process would be greatly appreciated.

Errors:
1: Module not found: Error: Can't resolve 'node-sass' in '/home/runner/work/ATS-Frontend-V2/ATS-Frontend-V2/node_modules/sass-loader/dist'
 @ ./node_modules/sass-loader/dist/getDefaultSassImplementation.js
 @ ./node_modules/sass-loader/dist/getSassImplementation.js
 @ ./node_modules/sass-loader/dist/index.js
 @ ./node_modules/sass-loader/dist/cjs.js
 @ ./app/components/NewCandidate/index.js
 @ ./app/components/TransferCand/SearchApplicants.js
 @ ./app/components/index.js
 @ ./app/containers/Pages/ShiftCalculation/index.js
 @ ./app/containers/pageListAsync.js
 @ ./app/containers/App/PerDiem/Facility.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js
 
 2: ERROR in ./node_modules/sass/sass.node.js
Module not found: Error: Can't resolve 'module' in '/home/runner/work/ATS-Frontend-V2/ATS-Frontend-V2/node_modules/sass'
 @ ./node_modules/sass/sass.node.js 7:14-31
 @ ./app/components/Common/Modal.js
 @ ./app/containers/Pages/ShiftCancel/index.js
 @ ./app/containers/pageListAsync.js
 @ ./app/containers/App/PerDiem/Facility.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js

Thank you for your support and the great work on Sass!

**Comment by nex3** [comment]
The first error here is related to node-sass, which is a different (deprecated) project.

The second error looks like it's failing to load [the `node:module` module](https://nodejs.org/api/module.html). We did add a load of this module recently for CLI apps, but that module has been present in Node.js since v12 so I don't know why your app is having trouble with it.

What version of Node.js are you using? Do you have a stand-alone reproduction of this error, ideally without `sass-loader`?

**Comment by sbertault** [comment]
I face the same problem on my own computer (node 16.18.1 on Debian Linux) and in the CI (node 16, ubuntu docker image I think). The "module" package is required¹, but not declared in the dependencies section of package.json.
Had to add it manually.

¹ line 7 of sass.node.js : `nodeModule: require("module")`

**Comment by nex3** [comment]
The globally-available [`module` object](https://nodejs.org/api/modules.html#the-module-object) is different from the [`module` module](https://nodejs.org/api/module.html). Although you _can_ use the `node:` prefix to load built-in modules, it's not necessary. I've verified that `console.log(require("module"))` works as expected in Node 16.18.1 on my machine. Can you try running that exact script in the environment where you're seeing failures and report the result?

**Comment by nex3** [comment]
I'd recommend trying to strip out each of those components one by one until you figure out exactly which tool is causing this error, and then filing an issue against that tool.

**Comment by guorun** [comment]
please just check your .vue files. which file use some lines like 

> import * as sass from 'sass' 

or 
`import { types } from 'sass'  `
or any lines want to import sass module
