### ISSUE TITLE
Node Package Importer can't find ESM entry point if args are provided

### ISSUE THREAD

**Issue by jamesnw** [sass/dart-sass#2188]
Currently, [it appears](https://github.com/sass/dart-sass/pull/2181/files#diff-45b33e30ee19fb4177903ae25cb4362536fd34236481da7de55194a445740c73R242) that an entryPoint is only found if `argv` has exactly 2 arguments. 

I'm observing this in a Vite project, with the `css` key in `vite.config.ts` setting up the package importer using the legacy API- 

```
css: {
    preprocessorOptions: {
      scss: {
        includePaths: [path.resolve('./src/sass/')],
        pkgImporter: new NodePackageImporter(),
      },
    },
  },
```

Running `yarn vite` works, but `yarn vite dev` fails with the `The Node package importer cannot determine an entry point because `require.main.filename` is not defined.` error. Stepping through `sass.dart.js` in the debugger, I can see that the value of `process.argv` contains 3 values, and so `if (process.argv case [_, String path])` does not match.

We have worked around this issue by providing `"."` as an entry point to the NodePackageImporter.

**Comment by ntkme** [comment]
I think it's as easy as

```diff
-  } else if (process.argv case [_, String path]) {
+  } else if (process.argv case [_, String path, ...]) {
```
