### ISSUE TITLE
CLI Many-to-Many Mode process .css files

### ISSUE THREAD

**Issue by mwojslaw** [sass/dart-sass#2245]
It seems like when using command `sass input:output` to process directories, not only sass files but also css files are being processed.

**Comment by nex3** [comment]
That's correct and intentional. Sass supports plain CSS files as an input syntax.

**Comment by ntkme** [comment]
If you want to stop process `.css` source files and only use them as dependencies, you can prefix the css filenames with underscore like `_filename.css`. You can still import as `@import "filename";`, but filename begin with underscore will not be processed as an entrypoint.
