### ISSUE TITLE
Converting .sass to .scss?

### ISSUE THREAD

**Issue by hambergerpls** [sass/dart-sass#2249]
Hi, 

I'm trying to convert all my existing .sass file to .scss. I tried to find tools that allow me to do this but all of them that I found are outdated. Is there a way to convert existing .sass indented syntax code to .scss?

When I ran `sass --indented input.sass:output.scss`; where input.sass @use another file,
It generates a compiled .css instead.

I understand that any .css is a valid .scss, but the goal is to just change the indented syntax of sass to non-indented syntax.

**Comment by nex3** [comment]
We don't provide a tool for this. We used to, back in the Ruby Sass days, but it added a large amount of overhead every time we needed to change the AST or add a new language feature. If this would be valuable for you, it would be possible to roll your own using the [`sass_api` package](https://pub.dev/packages/sass_api).

**Comment by KaelWD** [comment]
I needed this too so I made https://github.com/KaelWD/sass-to-scss
