### ISSUE TITLE
dart-sass maven plugin 1.77.4 is not a Win32 valid application

### ISSUE THREAD

**Issue by dani-arm** [sass/dart-sass#2261]
Since May 30, 2024, when compiling with maven plugin 

https://github.com/sass/dart-sass/releases/tag/1.77.4

I receive a Windows error which says: 

"[temp path]...no es una aplicación win32 válida".

I have Win 64 bits, and it seems that the plug-in correctly detects it (as the temp path, where the plugin donwloads sass.exe, contains x64 folder) but when compiling, the error mentioned appears. 

I'm stucked with it. Could you help me to keep on compiling my .sass files please?

Regards.

Dani
![dart-error](https://github.com/sass/dart-sass/assets/172282288/29a0433f-80b8-4147-9a0a-2605e0b3463f)

**Comment by ntkme** [comment]
This is the repository of dart-sass, not the maven plugin. I cannot report this issue standalone with dart-sass.
 
You should report the issue to: https://github.com/cleydyr/dart-sass-maven-plugin

**Comment by ntkme** [comment]
I just realized from your screenshot it appears that you're still using Windows 7?

Dart 3.4 has dropped support for Windows 7 & Windows 8. The minimum supported Windows version is now Windows 10.

**Comment by ntkme** [comment]
https://github.com/dart-lang/sdk/issues/54509
https://github.com/dart-lang/sdk/commit/74baf5e75a754edff091785586214549124c0c18

**Comment by dani-arm** [comment]
Oh! that's the point! I rolled back to dart-sass 1.71.1 and it seems that one uses a lower version of DART, so thank you for your support! Issue solved!
