### ISSUE TITLE
Install defaults to C:/Tools on Windows!!!

### ISSUE THREAD

**Issue by VashJuan** [sass/dart-sass#2269]
PLEASE do NOT clutter my C: drive and change the default install location to something respectful, like ProgramData, Program Files or some other NORMAL path.

Thanks. 

...Now I've got to figure out uninstall and more...

**Comment by jathak** [comment]
When installing with Chocolatey (as seems to be the case here), Sass installs to Chocolatey's directory (which defaults to `C:\ProgramData\chocolatey`, but may be configured elsewhere on your system).

It looks like the dart-sdk Chocolatey package (which we depend on but do not control), instead installs to [`Get-ToolsLocation`](https://github.com/chocolatey/choco-wiki/blob/master/HelpersGetToolsLocation.md), which defaults to `C:\tools`, but can be configured elsewhere with the `ChocolateyToolsLocation` environment variable.

If you have an issue with these defaults, please file an issue against either Chocolatey (the package manager) or Dart (a dependency), as how they work is out of our control.
