### ISSUE TITLE
An option to make nested warning (and similar warnings) fatal

### ISSUE THREAD

**Issue by daniluk4000** [sass/dart-sass#2277]
This will be very different from https://github.com/sass/dart-sass/issues/2276.

I know this will be fatal in Sass v2 (as it seems at least), but as team lead, I want to have an option to draw attention to this warning and make build fail because of it. Of course console spam is insane, but for few issues can be missed sometimes,

**Comment by ajiho** [comment]
I have also encountered this issue. My project, or adminlte, also requires some scss files that rely on bootstrap. If you want to eliminate this warning, I asked if you should release bootstrap 5.3.4 so that we can obtain scss files without warnings?

**Comment by ntkme** [comment]
This already exists today in js-api:
https://sass-lang.com/documentation/js-api/interfaces/options/#fatalDeprecations
https://sass-lang.com/documentation/js-api/interfaces/deprecations/#mixed_decls

Similar option also exists in the command line sass.
