### ISSUE TITLE
Bug: SASS variable not being replaced with actual value for CSS custom property within mixin

### ISSUE THREAD

**Issue by raphaelcohn** [sass/dart-sass#2285]
The following mixing does not replace the variables `$numeric` et al; instead it, outputs to CSS the **_literal variable name_**, `$numeric`

```
@mixin _properties($numeric, $alphabetic-upper, $alphabetic-lower)
{
	@debug $numeric;
	
	--counter-style-numeric: $numeric;
	--counter-style-alphabetic-upper: $alphabetic-upper;
	--counter-style-alphabetic-lower: $alphabetic-lower;
}
```
(debug output is `sass/mixins/language/counter_style.scss:3 Debug: ethiopic-numeric`)

Produces

```
  --counter-style-numeric: $numeric
  --counter-style-alphabetic-upper: $alphabetic-upper;
  --counter-style-alphabetic-lower: $alphabetic-lower;
```

However, the following *does* work:-

@mixin _properties($numeric, $alphabetic-upper, $alphabetic-lower)
{
	@debug $numeric;
	
	counter-style-numeric: $numeric;
}
```

Produces

```
  counter-style-numeric: ethiopic-numeric;
```

**Comment by raphaelcohn** [comment]
Versions: dart-sass 1.77.8; macos; x64

**Comment by raphaelcohn** [comment]
Interesting discovering: Adding an unnecessary string interpolation causes the correct output to then be generated:-

```
@mixin _properties($numeric, $alphabetic-upper, $alphabetic-lower)
{
	--counter-style-numeric: #{$numeric};
}
```

**Comment by ntkme** [comment]
This is expected behavior: https://sass-lang.com/documentation/style-rules/declarations/#custom-properties

**Comment by raphaelcohn** [comment]
@nktme thank you for looking at my report. Certainly didn't find that in the documentation. And I'm not sure the expected behaviour corresponds with expectation, but I susppose without changing SASS' approach to parsing and syntax, there isn;t much of a workaround. That said, it would be nice to have an **opt-in warning** / lint ("use of potential SASS variable as string literal in CSS custom property") or somesuch.

**Comment by nex3** [comment]
:+1: https://github.com/stylelint-scss/stylelint-scss/issues/597 if you'd like such a lint to exist.
