### ISSUE TITLE
Can't access this.options.file in custom functions of sass.compile

### ISSUE THREAD

**Issue by itchyny** [sass/dart-sass#2290]
While `sass.render` allows us to access the compile context with `this.options`. Especially `this.options.file` is useful for modifying the value of `url()` to be relative from the output css file. However, `sass.compile` invokes custom functions with null context, and I cannot tell the context being processed. This prevents me to migrate from the legacy render APIs. Related issue: #1233.

**Comment by nex3** [comment]
This is intentional. If you're looking for URL rewriting, I recommend following along with https://github.com/sass/sass/issues/2535.

**Comment by itchyny** [comment]
Yes, I'm looking for a way to rewrite URL, so I read through https://github.com/sass/sass/issues/2535. The proposal `sass.url.relativeToCss` seems fit to my use case. I'll wait for the feature to be implemented. Thanks.
