### ISSUE TITLE
`unifyCompound` is not commutative when applied to pseudo classes of pseudo elements

### ISSUE THREAD

**Issue by mattrberry** [sass/dart-sass#2335]
The following produces `.y.x::scrollbar:vertical` as expected

```dart
print(unifyCompound(
  CompoundSelector.parse('.x'),
  CompoundSelector.parse('.y::scrollbar:vertical'),
));
```

However, swapping the operands produces `.x.y:vertical::scrollbar`

```dart
print(unifyCompound(
  CompoundSelector.parse('.y::scrollbar:vertical'),
  CompoundSelector.parse('.x'),
));
```

**Comment by Goodwine** [comment]
To clarify, because I was confused, the issue is not that `.x` and `.y` switched places. The issue is that `:vertical` and `::scrollbar` switched places
