### ISSUE TITLE
dart-sass warns when encountering a simple list of selectors in sass file

### ISSUE THREAD

**Issue by AlexanderJohr** [sass/dart-sass#235]
I'm trying to move from node-sass to dart-sass.

dart-sass warns me:

> This selector doesn't have any properties and won't be rendered.
>   logo,
>   ^^^^^

when it encounters this simple list of selectors:

```sass
  logo,
  logo .themeable
    display: block
```

**Comment by nex3** [comment]
I don't see a warning, but I do see it ignoring the selector.

**Comment by AlexanderJohr** [comment]
I created a pull request #237. This fixes the issue but now I get yet another error: 

> Error: Nothing may be indented beneath a @extend rule.
>     width: 130px

But the sass code is fine. The indented line is part of another rule. When I can confirm, this isn't due to my changes, I create another Issue and investigate if I can fix it.

```sass
section
  @extend %settings-panel-container-row

  > span
    width: 130px
```
