### ISSUE TITLE
sourcemap error while using 'modern-compiler'

### ISSUE THREAD

**Issue by joshyu** [sass/dart-sass#2356]
I updated my project to use 'sass-embedded' and 'dart-sass' in my webpack configuration. I found from the documentation that we need to use modern compiler JS API, so my update is as below:

<img width="777" alt="image" src="https://github.com/user-attachments/assets/4a807078-7f9b-4caf-b507-2fbf1c0400ae">

but I incorrectly generate the sourcemap, it can't map to the original SCSS file.
the error message is: **Could not load content for webpack://source-file.scss (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)**

when I switch back to legacy JS API, the source map can map correctly.  

Does anyone know why SASS modern-compiler API will lead to the sourcemap issue? how to fix it?

**Comment by nex3** [comment]
It's up to the code that invokes the compiler—in this case the WebPack plugin—to correctly set up URLs for the source map. I recommend filing an issue against them, unless you can reproduce a case where the Sass API on its own produces incorrect output for the inputs it's given.
