### ISSUE TITLE
Error: EMFILE too many open files with watch flag

### ISSUE THREAD

**Issue by ryanb** [sass/dart-sass#2362]
Since upgrading Sass to v1.79.2, the `sass ... --watch` command crashes after a few minutes with the following error.

```
$ sass --load-path=node_modules --load-path=app/frontend/stylesheets --no-source-map --quiet-deps --update app/frontend/entries/sass/:app/assets/builds/ --watch
Sass is watching for changes. Press Ctrl-C to stop.

Unexpected exception:
Error: EMFILE: too many open files, watch
```

When I run that command and list out which processes are using files with `lsof | awk '{print $1}' | sort | uniq -c | sort -rn` it shows `node` has 39,520 files open.

It may be because I have `--load-path=node_modules`, however this wasn't an issue with sass v1.78.0. When I downgrade back the number of open files for `node` stays around ~160.

It seems Sass v1.79 upgraded chokidar from v3.6 to v4.0 which I assume is causing this issue.

I'm on Mac OS X 14.6.1

**Comment by nex3** [comment]
Please report this issue to Chokidar—we have very limited control over precisely how it works. In the meantime, you can force the dependency back to the 3.x line.

**Comment by ryanb** [comment]
@nex3 sounds like they [won't be able to easily fix it in chokidar](https://github.com/paulmillr/chokidar/issues/1369#issuecomment-2391547036). Is it possible to separate watch path and load paths in sass? I only need `node_modules` in the load path, not watch the entire directory.

**Comment by nex3** [comment]
Generic load paths are too often used for user source code to omit them from watching. I recommend using [`--pkg-importer=node`](https://sass-lang.com/documentation/cli/dart-sass/#pkg-importer-node) to load package dependencies; that won't be covered by the watcher.

**Comment by ryanb** [comment]
Switching to `--pkg-importer=node` worked great. I just needed to prefix all package import paths with `pkg:`. Thanks!
