### ISSUE TITLE
There is no module with the namespace "color" when using sass.compileString.

### ISSUE THREAD

**Issue by GordonCode25** [sass/dart-sass#2364]
Hi all, is this a bug or did I miss something?

I've upgraded to sass@1.79.3 and I keep getting the error There is no module with the namespace "color" when using the function sass.compileString(.... Is there something different I need to do to get this to work with compileString or compileStringAsync?

I was using the lighten and darken function up until today.

```
@use "sass:color";
$color--blue:#00a8cb;
$color--light-blue:color.adjust($color--blue, $lightness:30%);
```

**Comment by GordonCode25** [comment]
Sorry, this should be sass and not dart-sass I think.

**Comment by jathak** [comment]
I'm unable to reproduce this issue. What JS code are you specifically using to run Sass?

**Comment by GordonCode25** [comment]
I've come up with an example that fails in node.js. However it seems to work with adding @use "sass:color". Maybe I'm mistaken. I'll do some more testing.

import sass from 'sass';
try{

		var source="$color--blue:#00a8cb;\r\n$color--light-blue:color.adjust($color--blue, $lightness:30%);a{color:$color--light-blue;}";
		var res = sass.compileString(source, {style: "compressed"});
		console.log("res",res);
		
}catch(err){
  console.error(err);
}

**Comment by nex3** [comment]
You can test this yourself by navigating to https://esm.sh and running the following code in your browser console:

```js
const sass = await import("https://esm.sh/sass@1.79.2");

sass.compileString(`
  @use "sass:color";
  $color--blue:#00a8cb;
  $color--light-blue:color.adjust($color--blue, $lightness:30%);
  @debug $color--light-blue;
`);
```

**Comment by jathak** [comment]
Without `@use "sass:color"`, that code should fail, since the color module hasn't been loaded.

**Comment by GordonCode25** [comment]
Apologies. It seems to work now in testing. Not sure why it failed before. Thanks for getting back to me, I'll close this issue.
