### ISSUE TITLE
Hangs when trying to process BulmaCSS

### ISSUE THREAD

**Issue by SpencerCornish** [sass/dart-sass#238]
_This issue was encountered on version 1.0.0-beta.5.2_

I have been trying to compile the [BulmaCSS](https://github.com/jgthms/bulma) sass files for some time, and essentially nothing happens when I run `dart-sass bulma.sass`. No errors, no output, nothing. I let it run for quite a while, but no luck yet. 
This very well could be something I am doing wrong or misunderstanding, but since when I run `sassc bulma.sass styles.css` I immediately get a CSS output that works fine, I thought I would make an issue.

Below I uploaded a zip file containing the Bulma files I'm trying to compile, and the expected css output from sassc. Thanks!

[sass.zip](https://github.com/sass/dart-sass/files/1726236/sass.zip)

**Comment by nex3** [comment]
It looks like this is caused by us deadlocking on `/*`-style comments in the indented syntax.

Note that once the deadlock is fixed, the code still probably won't work correctly due to #235 (which #237 will eventually fix).

**Comment by SpencerCornish** [comment]
Thanks for investigating! I appreciate the help with getting this up and running.
