### ISSUE TITLE
Deprecation notice for filter: invert(1)

### ISSUE THREAD

**Issue by Epoxide** [sass/dart-sass#2393]
I'm receiving the following deprecation notice using `"sass": "1.80.1"`:

```
Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use color.invert instead.

More info and automated migrator: https://sass-lang.com/d/import

filter: invert(1);
```

It should not be triggered when using invert with CSS.

**Comment by jathak** [comment]
Looks like we incorrectly made that warning a bit too broad. It will be fixed in https://github.com/sass/dart-sass/pull/2394
