### ISSUE TITLE
type 'InterpolatedFunctionExpression' is not a subtype of type 'StringExpression'

### ISSUE THREAD

**Issue by stufro** [sass/dart-sass#2397]
After upgrading from 1.79.4 to 1.79.5, I am getting the following error in my Rails app when running `yarn build:css`:

```
Unexpected exception:
TypeError: Instance of 'InterpolatedFunctionExpression': type 'InterpolatedFunctionExpression' is not a subtype of type 'StringExpression'


node_modules/sass/sass.dart.js 2314:43   Object.wrapException
node_modules/sass/sass.dart.js 3783:15   Object._failedAsCheck
node_modules/sass/sass.dart.js 3772:9    Rti._generalAsCheckImplementation
node_modules/sass/sass.dart.js 57728:39  CssParser._cssImportRule$1
node_modules/sass/sass.dart.js 57697:22  CssParser.atRule$2$root
node_modules/sass/sass.dart.js 59839:22  CssParser._statement$1$root
node_modules/sass/sass.dart.js 63051:17  StylesheetParser_parse__closure.call$0
node_modules/sass/sass.dart.js 59368:30  CssParser.statements$1
node_modules/sass/sass.dart.js 63035:23  StylesheetParser_parse_closure.call$0
node_modules/sass/sass.dart.js 58609:25  CssParser.wrapSpanFormatException$1$1
error Command failed with exit code 255.
```

I have confirmed that I get the same error for any version > 1.79.4.

**Comment by hustcer** [comment]
I came across exactly the same error, Is there any workaround?

**Comment by stuart-frost-b4b** [comment]
I haven't found one yet, I'm now working on trying to identify which CSS rule is causing the issue

**Comment by stufro** [comment]
I haven't found one yet, I'm now working on trying to identify which CSS rule is causing the issue

**Comment by stuart-frost-b4b** [comment]
I managed to fix the issue. It seems to occur when you have a `@import url(...)` line inside a file which is `.css` rather than `.scss`. Renaming all my offending files to have the `.scss` file extension worked for me.

**Comment by stufro** [comment]
I managed to fix the issue. It seems to occur when you have a @import url(...) line inside a file which is .css rather than .scss. Renaming all my offending files to have the .scss file extension worked for me.

**Comment by hustcer** [comment]
@stufro Thanks a lot, I will try it later

**Comment by ntkme** [comment]
After a close examination, there are actually two bugs around `@import` in plain css:

1. `@import url(url-string);` works, but `@import url("quoted-url-string");` results in the crash originally reported, because `dart-sass` does not parse the quoted string correctly as a URL.
2. According to https://www.w3.org/TR/css-cascade-4/#at-import and https://www.w3.org/TR/css-values-4/#url-value, alternative syntax `@import src(url-string);` is not yet supported by sass. The main difference is that `src()` allows plain css variables to be referenced inside, while `url()` does not.

**Comment by ntkme** [comment]
https://github.com/sass/sass/issues/3965
