### ISSUE TITLE
Mixing multiple file variables without `@import`

### ISSUE THREAD

**Issue by Mister-Hope** [sass/dart-sass#2400]
Hi, this is Mister-Hope from VuePress team. I totally understand that `@import` is conflict with standard CSS and it has many issues. But we have some confusion about implementing some achievable features with `@use` and `@forward`.

Our default theme and most of our community theme are using sass, this powerful CSS preprocessor to provide palette system. And to build it, we use variables in Sass.

With `@import` and `!default`, it's pretty easy for us to provide a "palette" file and a "generator" feature, where we have a built-in palette file declaring default colors with `!default`:

```scss
// Example of a palette file
$theme-color: #f00 !default;
$border-color: #efeef4 !default;
```

We also provide a generator which can generate related colors based on palette:

```scss
// Example of a generator file
@use 'sass:color';

$theme-color-soft: color.change($theme-color, $alpha: 0.25) !default;
$border-color-dark: color.scale($border-color, $lightness: -5%) !default;
```

With `@import`, we can add support for customizing:

```scss
@import 'palette';
@import 'user-config';
@import 'generator';
```

Uses can cover the default palette color:

```scss
// Example of a user palette
$theme-color: #ff0; // $theme-color-soft will match the user settings
```

And even override auto-generated colors by generator:

```scss
// Example of a user palette
$theme-color-soft: #c00; // Oops, this is a solid color now!
```

These palette are injected to `:root` as css variables, and can also be an accessible sass module:

```scss
@use '@sass-paleete/example-palette';

@debug example-palette.$theme-color;
@debug example-palette.$theme-color-soft;
// ...
```

So we provide a graceful palette system with sass variables.

However, I do not think we can rewrite this feature with `@use` and `@forward`, because they do not support combine, instead they can only be rewritten/configured with declarations while importing. While in our usage:

- The first and last file is provided by us, while the middle one is from user side, so it seems impossible for us to migrate.
- We want to let users configure easily without adding imports with `@forward/@use <path> with (...)`

Any helps would be appreciated, or could there be any future improvements?

Note: we previously considered merging these variables manually, but a little problem is that `meta.module-variables` does not give any information about whether a variable is announced with `!default`, so we are stucking here.

**Comment by nex3** [comment]
> We want to let users configure easily without adding imports with `@forward/@use <path> with (...)`

Why don't you want users `@use`ing things manually? One of the large-scale goals for the new module system is to be more explicit, and overrides are part of that. I'd recommend having users write something like:

```scss
@use 'vuepress-palette' with (
  $theme-color: #ff0
);
```

Then in your code you can write:

```scss
// _vuepress-palette.scss

// If a users @uses this file, they'll be able to configure variables from
// either of these files.
@forward 'palette';
@forward 'generator';
```

```scss
@use 'user-config';
@use 'vuepress-palette'; // Because modules are only loaded once, this will
                         // still see the configuration from user-config.scss.
```

(Closing this out because there's not core team action to take, but feel free to continue discussion.)
