### ISSUE TITLE
Can't run on arm-musl platform since 1.76.5

### ISSUE THREAD

**Issue by Floppy** [sass/dart-sass#2409]
Context:

* I'm building a Docker container for `arm` (32 bit, not 64), on an Alpine as a base image.
* Alpine uses `musl` instead of `glibc`.
* dart-sass 1.76.5 changed to `@parcel/watcher` for filesystem events.
* `@parcel/watcher` does not currently have a build for the `linux-arm-musl` platform.

Therefore, sass fails on 32 bit arm musl platforms.

> Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-arm-musl. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet.

There are a few possible solutions, I'm not sure which is best:

1. Do nothing. 32-bit is old hat, maybe this is just a "me" problem. 😄 
2. Get `@parcel/watcher` to provide an `arm-musl` build. I've sent them [a PR](https://github.com/parcel-bundler/watcher/pull/192) for that, but it might have problems which is why they've not done it.
3. Allow `sass` to use their cross-platform `watcher-wasm` backend if necessary. I think this will need a code change, it seems to have a different require line.
4. Only throw errors at runtime if watch mode is enabled. In my case, I'm doing a one-off compilation in the Docker build, so there's no need for file watching.

Any thoughts?

**Comment by Floppy** [comment]
ooh, that's by far the easiest solution for my immediate problem! Thank you!

**Comment by nex3** [comment]
I think it would be reasonable to make `@parcel/watcher` an optional dependency.

**Comment by ntkme** [comment]
To be clear, the title of this issue is a bit misleading. The `sass` package itself can be installed, just that when starting up sass command or `require('sass')` API will fail with the error message.

#2414 should be able to fix it.

**Comment by Floppy** [comment]
@ntkme ah sorry, I may have misread the error logs I was looking at, I thought it was an installation failure. I'll update the title!

**Comment by Floppy** [comment]
The `watcher` PR got accepted as well, so that now has (or soon will have) an arm-musl build.
