### ISSUE TITLE
@use and @import statements' problem in nuxt

### ISSUE THREAD

**Issue by ProAndSmiDev** [sass/dart-sass#2411]
Hello everyone, i can't understand where i need to tell about that, but it was a problem with sass 1.80 and more. So my problem is:
i do components in nuxt 3 and i do @import by each component in <style> tag. Ofc, it was working with that:
![изображение](https://github.com/user-attachments/assets/4ed77693-f7cb-45d1-a235-3749bda8b54b)

But since 1.80 what i need to do for work it clearly? I need some help from you cause i read docs about sass i searched all about my problem but i can't understand this and i hope on your help to talking about it

**Comment by ProAndSmiDev** [comment]
![изображение](https://github.com/user-attachments/assets/e2d3ac2d-a78f-4a4c-9cf7-27ff5ad9af5a)

this is the right screenshot. My problem is: i need to use variables and mixins globally, but i can't find a way to do that

**Comment by nex3** [comment]
We don't have any particular expertise in nuxt, so we can't help you with that. I can tell you that `@use` intentionally does not support a global scope, as described [in the documentation](https://sass-lang.com/documentation/at-rules/use/#differences-from-import). You'll need to explicitly `@use` the files that define any variables you use.
