### ISSUE TITLE
Deprecation of mixed declarations seems to be resulting in abusing `&{}` around mixins

### ISSUE THREAD

**Issue by idlist** [sass/dart-sass#2420]
Bumped into this warning by myself and find that this new deprecation is especially hard to cope with when two mixins that both have nested rules are used inside the same class.

[This answer of stackoverflow](https://stackoverflow.com/a/78900347) has indicated a way to work around this limitation, and from my view it seems like the way of solving problem by inserting `&{}` just anywhere a mixin is used...isn't really nice for that:

- it takes at least two indentation;
- so that it makes the code less clean;
- and if not abusing `&{}`, thinking about where to use it and where not to is a burden to the mind.

As a consequence, this deprecation doesn't work well with the design of mixin, and introduces much pain in migration. Large libraries using Sass tend to stop at 1.77.6.

One personal point of view is that as we are abusing `&{}` anyway, could Sass just do this for us when it comes to mixins?

**Comment by nex3** [comment]
Our hands are tied here as to whether or not to make this change. We're obligated to match CSS's behavior as closely as possible for constructs that are syntactically identical. Sass will "do it for you" once the deprecation period is over and we adopt the new CSS behavior entirely, but that period _is_ necessary to ensure that users have a chance to update their CSS in case it caused any incompatibilities.

**Comment by idlist** [comment]
I don't think it answers the things I pointed out: the new behaviors hurts very much on the use cases of mixins, and there seems to be no further action or design change to mixins to "cope with” the new behavior and causes "incompatibilities".

I thought about using `&{}` as clean as possible at the first place, but quickly found that it's not really viable as mainly I cannot presume the calling orders of mixins (and also the "two nested mixin conflictng" problem). Also, I don't think forcing inserting mixin into proper place to cope with `mixed-decl` is a good thing, as it would mix the mixin calling into other style declaration, making the code further unreadable (compared to calling mixin at the first lines of a class). 

There should be two points that Sass can do better at this stage:

1. Help warpping all mixins in `&{}` (which is sematically `nestable`); 
2. Help warpping all plain declarations (those are not nested) below mixins in `&{}` (which is sematically `override`);

For point 1 I'm quite confident that doing this automatically is totally okay. For point 2, I think either having it done automatically or introducing a new at-rule (like `@override`, which could just be an alias to `&{}` but with better semantic meaning) is a good option.

The key point is that mixin should adopt to the new behavior and thus introduce some changes to it, rather than keeping it unchanged and resulting in impaling its functionality and introducing more boilerplate codes.

**Comment by nex3** [comment]
Mixins _will_ automatically start doing the same behavior as they would with `& {}`—that's the upcoming breaking change, as described in detail at https://sass-lang.com/d/mixed-decls. If you're confident that this behavior is fine for your app, you're encouraged to just silence the deprecation warning until we release a Sass version that emits mixed declarations in source order by default.

But we can't just start off by doing that, because it's a potentially breaking change to the way users' Sass is compiled right now. That's why we have deprecation periods. No one is obligated to write `& {}`. It's just a good option if you want to write stylesheets that will work the same way with older versions of Sass and future versions of Sass. If you care about that, you _need_ an explicit way to opt in, and if you don't you can just silence the deprecation and be done with it.

**Comment by idlist** [comment]
So after reading #2401 and sass/sass#3960, I would agree that having an option to opt-in to see how much impact it brings in would be more preferable than generating tons of deprecation warning (which in my opinion shouldn't be "deprecation" but "notification of breaking change", as they are having subtle differences: deprecation usually mean something "should no longer be used", but `mixed-decl` isn't the case). From my own point of view and also the discussion in the original CSS nesting issue, the opt-in is likely to be 99% compatible and only 1% edge cases need to be adjusted (by whether adding `& {}` or adjusting the orders), which would be far better than changing 20~30% codes here and there to make all versions of Sass compiler happy.

This particular case has caused too many confusions, and I would suggest having better tooling support and explanation about common cases (notably `mixin`) in the future would ease the migration curve.

**Comment by alexander-lcp** [comment]
I'm having the same problem. This information would be really handed to be more prominent on the docs

**Comment by nex3** [comment]
Which information specifically would you like to see be more prominent, and where?

**Comment by alexander-lcp** [comment]
It's confusing that this is flagged as a breaking change since (if I understand correctly) even if you have mixed declarations, the compiler will still compile them in the future but will just change the output CSS file. I get that it's better to do it the CSS way so you end up with a smaller CSS file in the end, but for some, that's just not possible. IMO, this information should be added to the breaking change page about mixed declarations so people can make a better decision about whether to implement this or not.

**Comment by nex3** [comment]
> It's confusing that this is flagged as a breaking change since (if I understand correctly) even if you have mixed declarations, the compiler will still compile them in the future but will just change the output CSS file.

The term "breaking change" includes changes where the CSS semantics produced by a given input are different before and after the change. It's about breaking backwards-compatibility, not about throwing errors.

> IMO, this information should be added to the breaking change page about mixed declarations so people can make a better decision about whether to implement this or not.

The breaking change page already has a detailed explanation of how it currently works, how it will work, and the differences between them. What else are you looking for?

**Comment by jmcmahonInfini** [comment]
This is so stupid. 

@mixin ultraWideControl(
    $properties,
    $important: false,
    $start-point: $ultra_wide_break_point,
    $shrink-factor: 1
) {
    @media (min-width: $start-point) {
        @each $property, $value in $properties {
            $vwValue: round((($value * 100vw * $shrink-factor/$start-point) * 100)) * 0.01;

            @if $important {
                #{$property}: $vwValue !important;
            } @else {
                #{$property}: $vwValue;
            }
        }
    }
}


Where's the nested rule here?

No where. Yet I get a warning.

**Comment by jmcmahonInfini** [comment]
Also got a complaint for the first line of this mixin:

@mixin dropShadow($start-size, $color) {
    filter: drop-shadow(0px 0px $start-size $color);

    $super-wide-size: math.div($start-size * 100vw, $super_wide_start);

    @media (min-width: $super_wide_start) {
        filter: drop-shadow(0px 0px $super-wide-size $color);
    }

    $dynamic-size: math.div($start-size * 100vw, $content_dep);

    @media (max-width: $content_dep) {
        filter: drop-shadow(0px 0px $dynamic-size $color);
    }

    $mobile-dynamic-size: math.div($start-size * 100vw, $targetViewWidth * 2);

    @media (max-width: $mobile-breakpoint) {
        filter: drop-shadow(0px 0px $mobile-dynamic-size $color);
    }
}

Not sure how the first line can cause a problem.

**Comment by jmcmahonInfini** [comment]
What can I say except thank you chatgpt for this:


const fs = require('fs-extra');
const path = require('path');
const glob = require('glob');
const postcss = require('postcss');
const postcssScss = require('postcss-scss');

const scssDir = './src'; // Adjust the root directory to your SCSS folder

// Function to reorder properties in a CSS block
const reorderProperties = (css, filePath) => {
    return postcss()
        .process(css, { parser: postcssScss })
        .then((result) => {
            result.root.walkRules((rule) => {
                const regularProps = [];
                const nestedRules = [];
                const mediaQueries = [];
                const comments = [];

                // Separate properties, media queries, nested rules, and comments
                rule.each((node) => {
                    if (node.type === 'decl') {
                        regularProps.push(node);
                    } else if (node.type === 'atrule') {
                        mediaQueries.push(node);
                    } else if (node.type === 'rule') {
                        nestedRules.push(node);
                    } else if (node.type === 'comment') {
                        comments.push(node);
                    }
                });

                // Remove all existing nodes before appending in correct order
                rule.removeAll();
                rule.append([...regularProps, ...comments, ...nestedRules, ...mediaQueries]);
            });

            const updatedCss = result.root.toString(); // Ensure changes are reflected
            return updatedCss;
        });
};

// Function to read and modify SCSS files
const processFiles = () => {
    const scssFiles = glob.sync(path.join(scssDir, '**', '*.scss'));

    scssFiles.forEach((filePath) => {
        fs.readFile(filePath, 'utf8')
            .then((data) => {
                console.log(`Reading file: ${filePath}`);
                reorderProperties(data, filePath)
                    .then((reorderedCss) => {
                        if (data.trim() !== reorderedCss.trim()) {
                            fs.writeFile(filePath, reorderedCss, 'utf8')
                                .then(() => {
                                    console.log(`Successfully processed and updated: ${filePath}`);
                                })
                                .catch((err) => {
                                    console.error(`Error writing file ${filePath}:`, err);
                                });
                        } else {
                            console.log(`No changes detected for: ${filePath}`);
                        }
                    })
                    .catch((err) => {
                        console.error(`Error processing file ${filePath}:`, err);
                    });
            })
            .catch((err) => {
                console.error(`Error reading file ${filePath}:`, err);
            });
    });
};

// Run the script
processFiles();

**Comment by jmcmahonInfini** [comment]
> Our hands are tied here as to whether or not to make this change. We're obligated to match CSS's behavior as closely as possible for constructs that are syntactically identical. Sass will "do it for you" once the deprecation period is over and we adopt the new CSS behavior entirely, but that period _is_ necessary to ensure that users have a chance to update their CSS in case it caused any incompatibilities.

See my comment above. No sweat.

**Comment by nex3** [comment]
Please don't post multiple comments in a row. Edit your previous comment if you have something to add. Also, please post code examples as text using markdown code block syntax rather than images.

> Where's the nested rule here?

`@media (min-width: $start-point)` is the nested rule. This is explicitly highlighted by the deprecation warning:

![Image](https://github.com/user-attachments/assets/73b12642-d847-4957-9f8a-3ef1833d651e)

> Not sure how the first line can cause a problem.

Any property declaration can cause a problem if it comes after a nested rule.
