### ISSUE TITLE
quietDeps not silencing @import warnings

### ISSUE THREAD

**Issue by beshur** [sass/dart-sass#2421]
Hi.

When trying to `@import` external library I'm getting depreciation warning.
I know that, but working with an old codebase does not allow us to switch to `@use` for now.

Adding `quietDeps: true` in next.config does not help.

Workaround is to also explicitly add `silenceDeprecations: ['legacy-js-api']`

Demo: https://github.com/beshur/nextjs-sass-quiet-deps

As per #1360

**Comment by nex3** [comment]
Can you provide a demo that reproduces this _just_ using the Sass API? I don't know how the internals of Next.js are put together, and I want to be sure this is our issue and not theirs.

**Comment by ntkme** [comment]
> Workaround is to also explicitly add silenceDeprecations: ['legacy-js-api']

`legacy-js-api` is not a deprecation from sass dependency, so that cannot be silenced by `quietDeps`. You need to switch to new Sass JS API from legacy JS API. For how to do that in nuxt, you should check nuxt's documentation or ask in nuxt project.

**Comment by nex3** [comment]
Ah, good catch @ntkme.
