### ISSUE TITLE
Problem with sass-embedded when deploying my vite+vue3 website to Cloudflare Pages 

### ISSUE THREAD

**Issue by Dolyn157** [sass/dart-sass#2423]
I imported sass-embedded v1.80.4 into my vite+vue3 static website project, and pushed my project to Github. However, when I tried to deploy it to Cloudflare Pages, it got stuck on 'Building application.' The details are as shown below.
![image](https://github.com/user-attachments/assets/41eb141a-4cf0-4910-9af7-d5d71cf84adc)

After replacing sass-embedded v1.80.4 with sass v1.80.4, my project was successfully deployed. I don't know what caused this bug, that's why I submit this issue here.

**Comment by nex3** [comment]
While this is concerning, it's not really actionable for us... we can't really debug or fix this without a reproduction, and if even _you_ can't reproduce locally there's little help of that. If you'd like to strip this down to the smallest Sass API call that still hangs, we might be able to work with that, but short of that I don't think there's anything we can do.

**Comment by daniandl** [comment]
Finally, I found the cause and ended up here too after going commit by commit until it hangs... this is super annoying :(

**Comment by nex3** [comment]
https://community.cloudflare.com/t/vite-stuck-in-build/696830/18 links to https://developers.cloudflare.com/pages/configuration/build-image/#tools which says CloudFlare only supports Embedded Dart Sass up to 1.62.1. To be clear, **staying on an older version is not something we recommend;** it will gradually become more and more incompatible with the latest releases of various Sass libraries and the latest CSS supported by browsers.

The biggest change in Embedded Dart Sass in 1.63.0 is the introduction of concurrent compilations on multiple threads which provides a substantial performance improvement especially for frameworks like Vite that compile CSS for many smaller components. As far as I can recall, we never received any bug reports from Cloudflare or anyone else that this feature caused deadlocks in any particular computing environment, and without more details and reproducability it'll be hard for us to figure out what's really going on and to fix it.

Given that, my best suggestion for Cloudflare users is to use `sass-embedded` locally where edit/refresh performance is the most relevant, and deploy using `sass` instead. They use the same implementation of the language itself, so as long as the versions match this shouldn't cause any behavior changes.
