### ISSUE TITLE
--quiet-deps is not working with import & command line

### ISSUE THREAD

**Issue by ontiuk** [sass/dart-sass#2429]
Have just gone throught the process of installing sass after a fresh install of node-js & installing sass via npm, so:

node: v22.11.0
npm: 10.9.0
sass: 1.80.6 compiled with dart2js 3.5.4

From windows command line I'm building a stylesheet using a custom Bootstrap 5.3.3 instance.

>sass --quiet-deps --watch ./scss/style.scss:style.css

Getting lots of deprecation errors e.g.
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

   ╷
58 │ @import "bootstrap/bootstrap.scss";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    scss\style.scss 58:9  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 4) or calc($spacer / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
82 │   1: $spacer / 4,
   │      ^^^^^^^^^^^
   ╵
    scss\global\_variables.scss 82:6  @import
    scss\style.scss 53:9              root stylesheet

Am I missing something. A general search shows this has been problematic in the past.

Thanks.

**Comment by ntkme** [comment]
> `@import "bootstrap/bootstrap.scss";`

I can see that you did not set any `--load-path` on command line, so this `@import` appears to be a relative import. Relative imports are not considered as "dependencies".

See: https://sass-lang.com/documentation/cli/dart-sass/#quiet-deps
