### ISSUE TITLE
Silence deprecation warnings

### ISSUE THREAD

**Issue by eldoy** [sass/dart-sass#2445]
All my apps blew up today when upgrading to sass 1.8 with deprecation warnings all over the place. How do I silence them?

Sidenote: There is no way I'm ever going to update all my apps, so I guess this will be the last time I ever use Sass. Whoever's idea it was to break all existing apps, you completely ruined this fine lib.

**Comment by AnonymousArthur** [comment]
read the document bro.
https://sass-lang.com/documentation/breaking-changes/import/

**Comment by nex3** [comment]
Expecting a world with perfect backwards compatibility forever is unrealistic in general, but it's _especially_ unrealistic for a language like Sass that's obligated to support whatever syntax CSS comes up with whether or not it conflicts with existing Sass behavior. We do our best to make them smooth by providing long deprecation periods, automated migration tooling, and powerful options to control when you actually see which deprecations. But there are always going to be situations where breaking changes are necessary.

**Comment by eldoy** [comment]
@nex3 So this was your idea? Imagine how many hours you're wasting for people with this useless change.

**Comment by eballeste** [comment]
i was just hit by these deprecations and trying to migrate some basic starter files even with the provided "migration" tools has been a nightmare, nothing works, you fix some warnings, you start getting errors, you clear the errors, something else produces more warnings, im definitely, for now, chalking this to a personal skill issue and understand the reasoning behind some of these decisions but damn, the difference between how fast i got sass to work with it's legacy implementation vs how i'm supposed to set things up now has been night and day. i still haven't been able to figure things out, putting a pause on this and going to keep things as-is: using @import vs @use/@forward and hiding the deprecations.

**Comment by eldoy** [comment]
@eballeste Just use plain CSS. With postCSS if you want nesting. Much less hassle, and will never expire.

**Comment by eballeste** [comment]
> @eballeste Just use plain CSS. With postCSS if you want nesting. Much less hassle, and will never expire.

i use sass because it allows me to use my own modified version of the BEM naming convention (BE[a] without the M, html attributes) for all of my components. i also use include-media for my media queries. i wouldn't be able to accomplish any of this using vanilla css/postcss even with the nesting.

**Comment by nex3** [comment]
@eballeste If you have specific issues you're running into with the migrator, I encourage you to report them on [the sass/migrator repo](https://github.com/sass/migrator/issues/new). We understand that the module system works differently than `@import` in some pretty substantial ways, and we're always looking to make the migration tooling better.

**Comment by eballeste** [comment]
it was a skill issue, 

this:
```scss
// _entry.scss
@import 'include-media/dist/include-media';

@import './fonts';
@import './variables';
```

became this:
```scss
// _entry.scss
@forward './fonts';
@forward './variables' hide $breakpoints;

@use './variables';
@forward 'include-media/dist/include-media' with (
    $breakpoints: variables.$breakpoints
);
```

**Comment by ashnur** [comment]
Kinda funny that asking "was this your idea" is considered a "personal attack" nowadays.  And then marking completely innocuous comments as "abuse" is just abusing the system and will lessen the ability for the community respond properly to actual abuse.
