### ISSUE TITLE
Support immutable 5.x

### ISSUE THREAD

**Issue by bjornharvold** [sass/dart-sass#2449]
Hi Team Sass,

Thank you for the great work you do 🚀

"immutable" has released v5.x on their library. Is there anything preventing you from bumping the version range for this dependency in your project?

Thx
Bjorn

**Comment by ntkme** [comment]
It’s already there in version >=1.80.7.

**Comment by bjornharvold** [comment]
Cheers - Will inform Angular team to bump their version.
