### ISSUE TITLE
`!default` not compiling in code

### ISSUE THREAD

**Issue by ck-jrd** [sass/dart-sass#2460]
Tested in Prepros with Dart Sass 1.70.0, and on the Sass Playground, on 1.82.0.

Using the `!default` flag in any capacity seems to break the compilation.

```
div {
  color:#00f;
}
.foo {
  color:#f00 !default;
}
```

This code throws an error `expected ";" on line 5`.

Replicatable on the [Sass Playground here](https://sass-lang.com/playground/#eJwzNEzJLFOo5lJQSM7PyS+yUjYwSLPmquXSS8vPRxZOMzBQUExJTUsszSkBygMAtxgQGg==?s=L1C1-L6C2).

Thanks!

**Comment by ntkme** [comment]
`!default` is a syntax only valid when declaring a Sass variable. It’s not a valid syntax as part of a CSS property.

**Comment by ck-jrd** [comment]
@ntkme My mistake! Closing this. Thanks!
