### ISSUE TITLE
JS API - support directories

### ISSUE THREAD

**Issue by helgatheviking** [sass/dart-sass#2461]
I keep getting notifications about the legacy JS API being deprecated, so I am trying to update my grunt tasks. However, it's not clear to me how to upgrade from `node-sass` and support automatically compiling all assets in a particular folder. Here's my `gruntfile.js` currently, but the [documentation](https://github.com/sass/dart-sass?tab=readme-ov-file#from-npm) seems to only support one file at a time? Is that accurate? 

```
module.exports = function(grunt) {

	const sass = require( 'sass' );
	require( 'load-grunt-tasks' )( grunt );

	// Project configuration.
	grunt.initConfig(
		{
			pkg: grunt.file.readJSON( 'package.json' ),

			// Setting folder variables.
			dirs: {
				css: 'assets/css',
				js: 'assets/js',
				scss: 'assets/scss'
			},

			// Compile all .scss files.
			sass: {
				compile: {
					options: {
						implementation: sass
					},
					files: [
					{
						expand: true,
						cwd: '<%= dirs.scss %>/admin/',
						src: ['*.scss'],
						dest: '<%= dirs.css %>/admin/',
						ext: '.css'
					},
					{
						expand: true,
						cwd: '<%= dirs.scss %>/frontend',
						src: ['*.scss'],
						dest: '<%= dirs.css %>/frontend',
						ext: '.css'
					}
					]
				}
			}
		}
	);

**Comment by ntkme** [comment]
In grunt use cases, it’s actually grunt that handles the directory input and then calling sass API to compile files one by one. So there is no need for the sass JS API to support directory.

Google search shows there are two different grunt sass integration libraries, one is grunt-sass and the other is grunt-contrib-sass, where neither supports new JS API. You should file an issue with the integration library you’re using regarding upgrade to new JS API.

**Comment by helgatheviking** [comment]
For anyone else, I have found that [`grunt-node-modern`](https://www.npmjs.com/package/grunt-sass-modern) has fixed this while waiting for `grunt-node` to deploy the fix required.
