### ISSUE TITLE
importer with indentation-based syntax not working correctly

### ISSUE THREAD

**Issue by Conduitry** [sass/dart-sass#247]
(This is on the JavaScript compiled version on npm, if that matters.)

```javascript
sass.renderSync({
	data: '@import file.sass',
	indentedSyntax: true,
	importer: () => ({
		contents: `
span
	color: pink
`,
	}),
})
```

Since I used `indentedSyntax: true` and since the imported file's extension is `.sass`, I would expect this to work, but I'm getting a parse error about expecting a `{`, presumably because the imported file is being parsed as SCSS syntax.

**Comment by nex3** [comment]
This matches Node Sass's behavior. As far as I know, there's no way to import an indented syntax by contents using the Node Sass API, although the @sass/node-sass team might know better.

**Comment by xzyfer** [comment]
This is correct. We have an open tracking issue for this.

**Comment by nex3** [comment]
@xzyfer Can you link to that issue? We should definitely coordinate on revamping the JS importer API in general, since it's now shared between two implementations.

**Comment by xzyfer** [comment]
The issue is https://github.com/sass/node-sass/issues/1192. We need to decide on how to expose sass2scss to the importer.
