### ISSUE TITLE
Trailing !important in custom property value causes error

### ISSUE THREAD

**Issue by xzyfer** [sass/dart-sass#260]
Originally reported in https://github.com/sass/libsass/issues/2590

According to the spec, [this is allowed][1]

>Note: Custom properties can contain a trailing !important, but this is automatically removed from the property’s value by the CSS parser, and makes the custom property "important" in the CSS cascade. In other words, the prohibition on top-level "!" characters does not prevent !important from being used, as the !important is removed before syntax checking happens.

[1]: https://drafts.csswg.org/css-variables/#syntax

**Comment by nex3** [comment]
Yeah, we should allow this.
