### ISSUE TITLE
Misleading site documentation for command line installation

### ISSUE THREAD

**Issue by cdalexndr** [sass/dart-sass#272]
In https://sass-lang.com/install it's stated you can install the command line tool using "npm install -g sass" with a note that this is a pure JavaScript implementation being slower, but with the same interface.
This tool doesn't support the guide from https://sass-lang.com/guide, as it outputs only to console, not to a file:
```
>sass --help
Compile Sass to CSS.

Usage: dart-sass <input>

    --[no-]stdin          Read the stylesheet from stdin.
    --[no-]indented       Use the indented syntax for input from stdin.
-I, --load-path=<PATH>    A path to use when resolving imports.
                          May be passed multiple times.

-s, --style=<NAME>        Output style.
                          [expanded (default), compressed]

-c, --[no-]color          Whether to emit terminal colors.
-q, --[no-]quiet          Don't print warnings.
    --[no-]trace          Print full Dart stack traces for exceptions.
-h, --help                Print this usage information.
    --version             Print the version of Dart Sass.
```

```
>sass --version
1.0.0 compiled with dart2js 2.0.0-dev.36.0
```

The note on "npm install -g sass" should be a warning stating that this is a limited tool.

**Comment by cdalexndr** [comment]
Seems this issue is not related to "npm": https://github.com/sass/dart-sass/issues/274

**Comment by nex3** [comment]
Merging with #274, since this is an issue across all command-line distributions.
