### ISSUE TITLE
Error executing sass script

### ISSUE THREAD

**Issue by TheColucciExperience** [sass/dart-sass#276]
When I execute the sass script inside the "dart-sass" directory it works fine, but when I use it anywhere else I get this error: "21: exec: ./src/dart: not found". I exported the directory (I use linux) path and the "src" directory is indeed inside "dart-sass". Maybe it's a problem relating to absolute paths, but it should be 
changed for ease of use.

**Comment by nex3** [comment]
When you run `sh --version`, what output do you get?

**Comment by TheColucciExperience** [comment]
Hi, when I run `sh --version` I get an error "version is not defined". I used `bash --version` and the output is 4.4.12. I'm currently using ubuntu 17.10. I've already "solved" the issue by replacing the `$path` variable with the actual path to the dart-sass folder in my system (e.g `~Documents/tools/dart-sass/src/dart`, etc.) in the `exec`  line. Pretty sure this is a problem regarding relative paths, as most of the time the script tought the `$path`  variable was relative to the current directory, and tried to find `.src/dart` there. I'm not really into shell script, but I bet it's something simple. Thanks anyway.

**Comment by gabooh** [comment]
Same problem here. Put the sass-dart tarball in /usr/local/bin/dart-sass.
then ln -s dart-sass/sass sass
/usr/local/bin/ is in the $PATH

When launched from PhpStorm (setup in a watcher), using this absolute path "/usr/local/bin/sass" I get this error : 

> /usr/local/bin/sass: 21: exec: dart-sass-1.15.2/src/dart: not found

I guess I will fix it like @TheColucciExperience did, but it's not a nice fix and user experience could be improved here I guess.

**Comment by gabooh** [comment]
In the "sass" executable script, I've changed this :

> path=$(dirname $(realpath -s $0))/`dirname "$(follow_links "$0")"`

**Comment by nex3** [comment]
@gabooh Can you reproduce the error by calling the script directly from the command line?

**Comment by MartinLyne** [comment]
I get the same issue when using the latest on github, extracted to /opt and then `chmod 777`'d

`/opt/dart-sass/sass: 23: exec: /opt/dart-sass/src/dart: not found`

when I `ls -la /opt/dart-sass/src/dart` I get

`-rwxrwxrwx 1 ubuntu ubuntu 19697344 Jan 17 23:39 /opt/dart-sass/src/dart`

The whole folder:

`total 22100
drwxrwxrwx 2 ubuntu ubuntu     4096 Jan 26 17:28 .
drwxrwxrwx 3 ubuntu ubuntu     4096 Jan 27 21:44 ..
-rwxrwxrwx 1 ubuntu ubuntu 19697344 Jan 17 23:39 dart
-rwxrwxrwx 1 ubuntu ubuntu     2500 Jan 17 23:39 DART_LICENSE
-rwxrwxrwx 1 ubuntu ubuntu  2904846 Jan 17 23:39 sass.dart.snapshot
-rwxrwxrwx 1 ubuntu ubuntu     1056 Jan 17 23:39 SASS_LICENSE
`

I tried hardcoding the path in the sass script, but same issue occurs. I tried running as sudo direct from the directory but it gives same issue.

**Comment by nex3** [comment]
@MartinLyne You're at the point where it seems like the OS isn't behaving how it should. This might be a StackOverflow question... you're out of my area of expertise.

**Comment by rtruxal** [comment]
This was my problem:
https://unix.stackexchange.com/questions/13391/getting-not-found-message-when-running-a-32-bit-binary-on-a-64-bit-system

Here's what happened after I extracted and added the package to my `$PATH`:
```sh
$ sass --version
/home/ME/dart-sass/sass: 21: exec: /home/ME/dart-sass/src/dart: not found
```

The only pre-built linux tarball on the download page is 32-bit. If you're on a debian derivative & `uname -a` shows `x86_64` anywhere in the result, you'll likely need to:
- Enable multiarch support & update your `apt` definitions:
`$ sudo dpkg --add-architecture i386 && sudo apt-get update`
- Downloading some required x32 C & C++ libraries:
`$ sudo apt-get install libc6:i386 zlib1g:i386 lib32stdc++6`  
- Try again:
```sh
$ sass --version
1.17.0
```

**Comment by nex3** [comment]
Oh, looks like not all the archives got uploaded in the latest release. Oops! Luckily that's easy to fix. I've uploaded the missing archives, so just download the right one for your OS and you should be good to go.

**Comment by MartinLyne** [comment]
Latest version has fixed it for me, thanks.

**Comment by peterPNG** [comment]
[peterg@AtomicLabs ~]$ sass --version
/opt/dart-sass/sass: line 20: /opt/dart-sass/src/dart: cannot execute binary file: Exec format error
/opt/dart-sass/sass: line 20: /opt/dart-sass/src/dart: Success

I got a similar error after downloading dart-sass from github. I had downloaded sass with ruby with successful but after seeing the error saying it's no longer supported I opted for dart-sass. But now I get the above error which i don't understand.

**Comment by nex3** [comment]
What operating system are you using? What processor architecture? Which file did you download?

**Comment by peterPNG** [comment]
os type

5.15.71-1-MANJARO

this processer architecture

@AtomicLabs ~]$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         36 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    CPU family:          6
    Model:               42
    Thread(s) per core: 

I downloaded this dart-sass 

dart-sass-1.69.5-linux-arm64.tar.gz

**Comment by ntkme** [comment]
@peterPNG Your architecture is x86_64, you need to download x64 version, not arm64 version.

**Comment by peterPNG** [comment]
Thanks, Everything is ok now
