### ISSUE TITLE
Multiline in indented syntax

### ISSUE THREAD

**Issue by Eisfunke** [sass/dart-sass#280]
Over at Ruby Sass there has been an [issue](https://github.com/sass/sass/issues/216) about Multiline in indented syntax for quite some time, a [pull request](https://github.com/sass/sass/pull/2094) trying to introduce it has been closed without a merge because of the upcoming Ruby Sass deprecation in favor of Dart Sass.

Dart Sass is now here and I'm wondering whether there's any chance of restarting what was happening in that PR and maybe getting multiline into Dart Sass?

**Comment by xzyfer** [comment]
Could you please open a similar issue with sass2scss that powers indented
syntax in LibSass?

**Comment by nex3** [comment]
Yes, this is still a language feature we'd like to add. If someone wants to put together pull requests to add specs for it to [sass-spec](https://github.com/sass/sass-spec) and an implementation to Dart Sass, I'd accept them. The language feature should still be tracked in sass/sass#216, though.
