### ISSUE TITLE
Publish source maps to npm

### ISSUE THREAD

**Issue by mgol** [sass/dart-sass#281]
The [`sass` npm package](https://www.npmjs.com/package/sass) contains only four files: `package.json`, `README.md`, `sass.js` & `sass.dart.js`. The last of them includes a source map comment:
```js
//# sourceMappingURL=sass.dart.js.map
```
but the map file is not included in the package.

It'd be useful to have it if debugging the package behavior is desired.

**Comment by nex3** [comment]
Duplicate of #3.
