### ISSUE TITLE
Extending complex selectors isn’t supported (supported by ruby-sass)

### ISSUE THREAD

**Issue by binki** [sass/dart-sass#286]
`blah.scss`:
```scss
ul.asdf {
  color: green;
}
ul.bsdf {
  @extend ul.asdf;
  background: red;
}
```

```
ohnobinki@gibby ~/sass-fun $ node_modules/.bin/sass blah.scss
Error: expected selector.
  @extend ul.asdf;
            ^
  blah.scss 5:13  root stylesheet
```

Supported by sass-3.5:
```
ohnobinki@gibby ~/sass-spec $ bundle exec ~/.gem/ruby/2.3.0/bundler/gems/ruby-sass-84e552546745/bin/sass ../sass-fun/blah.scss
ul.asdf, ul.bsdf {
  color: green; }

ul.bsdf {
  background: red; }
```

Not supported by sass-4-pre:
```
ohnobinki@gibby ~/sass-spec $ bundle exec ~/.gem/ruby/2.3.0/bundler/gems/ruby-sass-883398d5ec3e/bin/sass ../sass-fun/blah.scss
Error: Can't extend ul.asdf: invalid selector
        on line 5 of ../sass-fun/blah.scss
  Use --trace for backtrace.
```

Where is the explanation of this being deprecated?

**Comment by nschonni** [comment]
The discussion for this was in https://github.com/sass/sass/issues/1599

**Comment by binki** [comment]
So dart-sass is an implementation of sass-4, it seems, and doesn’t support sass-3. I ended up using dart-sass because http://sass-lang.com/install told me that the `sass` npm package was a valid way to install sass. I guess I’ll file an issue with the website to add a warning about how the package only provides sass-4 and not sass-3.

Updating the error to not be a parsing error but to understand what feature I am attempting to use and link me to the issue would be very helpful too. Can this bug be for that?

**Comment by AlexWayfer** [comment]
@nex3, it's a bit strange:

```scss
a { 
  @extend button, .light;
}
```

```
Error: unexpected token.
		@extend button, .light;
		              ^
```

OK, let's change to `button.light`:

```
Error: compound selectors may longer be extended.
Consider `@extend button, .light` instead.
See http://bit.ly/ExtendCompound for details.

		@extend button.light;
```

Wat. Considered code returns `Error: unexpected token.`

**Comment by AlexWayfer** [comment]
I think it's a bug:

> Multiple extends can also be written using a comma-separated list of selectors. For example, @extend .error, .attention is the same as @extend .error; @extend .attention.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend
