### ISSUE TITLE
Syntax for importing CSS files

### ISSUE THREAD

**Issue by craigjennings11** [sass/dart-sass#287]
Is there a way to include basic CSS files in a SASS compilation? I've googled around and the majority advice is to use the syntax `@import "my-file"` without an extension. I found this only works using libsass, where as this dart implementation doesn't seem to work.

Some related issues I found:
https://github.com/sass/sass/issues/1094
https://github.com/sass/sass/issues/193
https://github.com/sass/libsass/pull/754 - libsass implementation of above syntax

I'm just curious if this syntax is planned to be supported in this dart implementation or it will remain an exclusive of libsass.

**Comment by nschonni** [comment]
libsass will be removing that behaviour https://github.com/sass/libsass/issues/2611

**Comment by craigjennings11** [comment]
Thanks @nschonni, I hadn't seen that issue. Is there any plan to allow for importing CSS files some other way?

**Comment by nschonni** [comment]
I think that's being discussed in https://github.com/sass/proposal.module-system

**Comment by stratboy** [comment]
@import without .css extension, will perfectly work in dart sass.
