### ISSUE TITLE
OutputStyle could be enum

### ISSUE THREAD

**Issue by indiealexh** [sass/dart-sass#289]
It seems like `OutputStyle` could be an enum, which would improve code for anything using the dart-sass library

e.g. 
```dart
enum OutputStyle {
  /// The standard CSS style, with each declaration on its own line.
  ///
  /// .sidebar {
  ///   width: 100px;
  /// }
  expanded,

  /// A CSS style that produces as few bytes of output as possible.
  ///
  /// .sidebar{width:100px}
  /// 
  compressed,
}
```

**Comment by nex3** [comment]
Dart's built-in enum feature isn't very good. It doesn't allow `toString()` to be customized, and it's not extensible at all so if you ever want to add new methods to the values there's no way to do that without introducing a breaking change. As such, it's recommended to avoid enums in general in favor of explicitly writing constant values.
