### ISSUE TITLE
CSS attribute should be within commas

### ISSUE THREAD

**Issue by FDiskas** [sass/dart-sass#30]
![gnome-shell-imgur-tdi5py](https://cloud.githubusercontent.com/assets/468006/20029825/8a09bbca-a35f-11e6-9261-64c84a8d94a8.png)

**Comment by nex3** [comment]
This is intentional; [attribute values are allowed to be identifiers](https://www.w3.org/TR/selectors4/#attribute-representation). We will (or at least should) generate quoted strings when the attribute values aren't valid identifiers.
