### ISSUE TITLE
"Unsupported operation: Illegal character in path" hides real error when using Node API on Windows

### ISSUE THREAD

**Issue by dmitrage** [sass/dart-sass#301]
Hi, this happens when imported file contains error. Tested on win 10 x64 with node 9.11.1 and npm 5.8.0

### Steps to reproduce:

1. Must be inside directory with at least 1 parent directory
```
C:\sass - not OK, will not be reproduced
C:\repro\sass - OK
```

2. Install dart-sass
```
npm i dart-sass
```

3. Create valid entry file (`index.scss`):
```scss
@import "dep";
```

4. Create dependency file (`_dep.scss`) with error content:
```
error
```

5. Ensure that CLI works (should report correct error)
```
npx dart-sass index.scss
```

6. Execute api call
```
node -e "require('dart-sass').renderSync({file: 'index.scss'})"
```

### Expected (as produced by CLI):

```
Error: expected "{".
error
     ^
  _dep.scss 1:6   root stylesheet
  index.scss 1:9  root stylesheet
```

### Actual (note: drive letter is removed from path):

```
Unsupported operation: Illegal character in path: repro\sass
```

### Tested sass versions:

- 1.0.0-beta.3 ... 1.2.1 - can be reproduced
- 1.0.0-beta.2 - works correctly
```
Error: expected "{".
  _dep.scss 1:6  root stylesheet
```
- Prior 1.0.0-beta.2 - Different errors (for example: "FormatException: null", "[object Object]")

Thanks!

**Comment by nex3** [comment]
I'll see if I can take a look at this next week. Unfortunately, I don't have a Windows machine set up for development at the moment, so it might take a bit. If someone else wants to give it a shot before then, please be my guest; I'm guessing we're accidentally treating a path as a URL somewhere in `lib/src/importer/node/implementation.dart` or the code that calls that in `lib/src/visitor/async_evaluate.dart`.

**Comment by dmitrage** [comment]
Looks like it was caused by incomplete backslash replacement in node_preamble.

So, the error is not in the dart-sass codebase, and can be reproduced by compiling this code with dart2js and prepending preamble:

```dart
import 'package:path/path.dart' as P;
main() {
    print(P.current);
}
```

When running compiled result with Node, Uri.base returns path with only first backslash escaped and then validation regexp (Uri._checkWindowsPathReservedCharacters) detects it and throws. Note: step 1 from issue description is required.

**Comment by nex3** [comment]
Good catch! There's also a bug here in Dart Sass itself: we should only ever be using our [custom context](https://github.com/sass/dart-sass/blob/e0ae8c907c032d81065579f32396111e73a69105/lib/src/util/path.dart) for the `path` package, which uses Node's notion of the current path rather than passing through URI encoding and decoding.

**Comment by dmitrage** [comment]
`exception.trace.toString()` (stack_trace package) call [here](https://github.com/sass/dart-sass/blob/master/lib/src/node.dart#L175)

Whole exception stack below. Btw, to preserve sourcemap lines, I had to change preamble to minified [here](https://github.com/sass/dart-sass/blob/master/tool/grind.dart#L122)

| | |
|-|-|
wrapException | build\sass.dart.js:4440 |
_Uri__checkWindowsPathReservedCharacters | build\sass.dart.js:12608 |
_Uri__toWindowsFilePath | build\sass.dart.js:13130 |
toFilePath$1$windows | build\sass.dart.js:12388 |
toFilePath$0 | build\sass.dart.js:12400 |
current | path-1.5.1\lib\path.dart:93 |
relative$2$from | path-1.5.1\lib\src\context.dart:62 |
relative$1 | build\sass.dart.js:15318 |
prettyUri$1 | path-1.5.1\lib\src\context.dart:1048 |
get$library | path-1.5.1\lib\path.dart:452 |
get$location | stack_trace-1.9.2\lib\src\frame.dart:113 |
dart.Trace_toString_closure0.call$1 | stack_trace-1.9.2\lib\src\trace.dart:323 |
elementAt$1 | build\sass.dart.js:2671 |
fold$2 | build\sass.dart.js:2418 |
toString$0 | stack_trace-1.9.2\lib\src\trace.dart:323 |
_wrapException | lib\src\node.dart:173 |
dart._renderSync | lib\src\node.dart:161 |

**Comment by nex3** [comment]
I believe this was fixed by https://github.com/mbullington/node_preamble.dart/pull/6.
