### ISSUE TITLE
--watch command not supported

### ISSUE THREAD

**Issue by ahmedSamra88** [sass/dart-sass#305]
i want --watch command for directory but it not supported in this way.
![screenshot 162](https://user-images.githubusercontent.com/24457188/39099171-63069a52-467e-11e8-9530-b60a40553ff9.png)

**Comment by nschonni** [comment]
Duplicate of #264

**Comment by nex3** [comment]
The `--watch` and `--update` flags aren't currently supported in Dart Sass, but they're coming soon! Keep an eye on https://github.com/sass/dart-sass/issues/264 for updates.
