### ISSUE TITLE
@import should resolve to files in the current directory first

### ISSUE THREAD

**Issue by mattdsteele** [sass/dart-sass#314]
**To reproduce**

1. Clone https://github.com/mattdsteele/dart-sass-import-bug and `npm i`
1. `node run-sass.js`
1. It should fail regarding an undefined variable
1. Edit `run-sass.js` and try requiring `node-sass` instead of `sass`, it will successfully build.

**What I think is happening**

The project's sass structure is:

```
  |   | app/app.scss

  |   | shared/bar/scss/bar/_bar.scss
  |   | shared/bar/scss/bar/_global.scss

  |   | shared/foo/scss/_foo.scss
  |   | shared/foo/scss/_global.scss
```

And `includePaths` are setup for `shared/foo/scss` and `shared/bar/scss`.

When `_bar.scss` tries to `@import 'global'`, Dart Sass is importing `shared/foo/scss/_global.scss`, rather than the `_global.scss` in the current directory. This is different behavior than node-sass, which uses the `_global` in the same directory.

I haven't tried with Ruby Sass yet, but the [reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import) makes me think `@import` should look in the current directory before searching `includePaths`.

My environment is Node 6.12.0 on Windows 10, as info.

**Comment by nex3** [comment]
This is a weird one; it only reproduces if the load path is relative. As a workaround, you can make the load path absolute.
