### ISSUE TITLE
FilesystemImporter attempts to resolve 'file.scss' as a partial first

### ISSUE THREAD

**Issue by nshahan** [sass/dart-sass#335]
If you go out of your way and write the full name of the import with an extension the implementation of `FilesystemImporter` will try to load the file as a partial first. It relies on `_tryPath()` when the import has a file extension.
https://github.com/sass/dart-sass/blob/fba35fe0dadf452ced65a610234cb998b7145353/lib/src/importer/utils.dart#L15

`_tryPath()` tries the file as a partial before trying the import as written. 
https://github.com/sass/dart-sass/blob/fba35fe0dadf452ced65a610234cb998b7145353/lib/src/importer/utils.dart#L31-L32

Is this the correct behavior?  If you have a partial file `_foo.scss` and a regular file `foo.scss` at the same location you can't ever load `foo.scss`.

**Comment by nex3** [comment]
It looks like Ruby Sass's behavior, which we should probably match, is to throw an error when imports are ambiguous (either because of partials or because of extensions). We should match that behavior in Dart Sass.
