### ISSUE TITLE
'dart.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by JacobKpr** [sass/dart-sass#336]
My sass was working just fine, and it is in my path, but now it won't run. Anytime I try to  run a sass command it just returns "'dart.exe' is not recognized as an internal or external command,
operable program or batch file."

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
