### ISSUE TITLE
Missing semicolons at the end of a line causes crash

### ISSUE THREAD

**Issue by michaelkolber** [sass/dart-sass#359]
The following CSS causes dart-sass to crash:

```scss
.nav__logo-wrapper {
    height: 80%
    overflow: hidden;
}
```

Note the missing semicolon. Here is the output:

```
Unexpected exception:
Error: expected ";".
    overflow: hidden;
            ^
  scss\stylesheet.scss 42:13  root stylesheet


package:sass/src/parse/parser.dart 603                  Parser.wrapSpanFormatException
package:sass/src/parse/stylesheet.dart 68               StylesheetParser.parse
package:sass/src/ast/sass/statement/stylesheet.dart 37  new Stylesheet.parseScss
package:sass/src/import_cache.dart 152                  ImportCache.importCanonical.<fn>
dart:collection                                         _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
package:sass/src/import_cache.dart 139                  ImportCache.importCanonical
package:sass/src/stylesheet_graph.dart 128              StylesheetGraph.reload
package:sass/src/executable/watch.dart 121              _Watcher.watch
package:sass/src/executable/watch.dart 48               watch
package:sass/src/executable.dart 55                     main
```

This is a Windows 10 installation.

**Comment by nex3** [comment]
What version of Dart Sass are you using?

**Comment by michaelkolber** [comment]
Dart Sass version 1.6.0. I'm using whatever version of Dart came with Dart Sass. Is there a way to check that?

**Comment by nex3** [comment]
That depends how you installed it. You may be able to run `dart --version`.

**Comment by nex3** [comment]
For what it's worth, I can't reproduce this with the pre-packaged 1.6.0 release.

**Comment by michaelkolber** [comment]
The output for `dart --version` is: `Dart VM version: 2.0.0-dev.62.0 (Wed Jun 13 16:50:22 2018 +0200) on "windows_x64"`

The error only occurs for me when the property is the last property for the given selector. So, a one-property block won't cause this, but a two-property block with the first property missing a semicolon will cause this.

**Comment by nex3** [comment]
I'm failing to reproduce this against your exact example, running Dart Sass 1.6.0 with Dart 2.0.0-dev.62.0.

Maybe it's a Windows-only issue somehow... can you see if you can reproduce it on a non-Windows machine, or on a Windows machine other than the one you've been testing on?

**Comment by michaelkolber** [comment]
I tried it on a different Windows 10 64-bit computer and it still happens. Steps to reproduce:

1. Create a block with at least two properties, both valid. For example,
```scss
class {
	color: black;
	background-color: white;
}
```
2. Run `sass --watch filename.scss filename.css`
3. Remove the first semicolon:
```scss
class {
	color: black
	background-color: white;
}
```
4. Sass crashes:
```
PS C:\Users\Michael\Desktop> sass --watch .\test.scss test.css
Compiled test.scss to test.css.
Sass is watching for changes. Press Ctrl-C to stop.

Unexpected exception:
Error: expected ";".
        background-color: white;
                        ^
  test.scss 3:18  root stylesheet


package:sass/src/parse/parser.dart 603                  Parser.wrapSpanFormatException
package:sass/src/parse/stylesheet.dart 67               StylesheetParser.parse
package:sass/src/ast/sass/statement/stylesheet.dart 37  new Stylesheet.parseScss
package:sass/src/import_cache.dart 152                  ImportCache.importCanonical.<fn>
dart:collection                                         _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
package:sass/src/import_cache.dart 139                  ImportCache.importCanonical
package:sass/src/stylesheet_graph.dart 128              StylesheetGraph.reload
package:sass/src/executable/watch.dart 121              _Watcher.watch
package:sass/src/executable/watch.dart 48               watch
package:sass/src/executable.dart 55                     main
```

**Comment by nex3** [comment]
Ah, that's the missing piece; it's an issue with how watch mode handles parse errors that happen after the file is first compiled.
