### ISSUE TITLE
Better support for @-moz-document

### ISSUE THREAD

**Issue by ruslang02** [sass/dart-sass#372]
Actually repeating the same issue: https://github.com/sass/libsass/issues/1401
When trying to compile https://github.com/material-components/material-components-web I am getting error:
```
Error: expected ")".
@-moz-document url-prefix("") {
                          ^
node_modules/@material/select/mdc-select.scss 64:31                     root stylesheet
node_modules/material-components-web/material-components-web.scss 38:9  
@import front/styles.scss 1:9  root stylesheet
```

Any ideas?

I use Node.js 8.9.3 accompanied with Electron v2.0.1 and sass@1.6.2 from NPM

File (that causes disaster) https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/mdc-select.scss

**Comment by xzyfer** [comment]
FWIW this feature is being removed in the next firefox release (61).
https://twitter.com/FxSiteCompat/status/1003967138057424897

**Comment by ruslang02** [comment]
It would be really nice if I could manage it somehow, but I need to save originality of the NPM package, even though I absolutely don't need that hack (Electron = Chromium)

**Comment by nex3** [comment]
@xzyfer Note that [this specific case](https://www.fxsitecompat.com/en-CA/docs/2018/moz-document-support-has-been-dropped-except-for-empty-url-prefix/) will still be supported for some time:

> An exception is the empty `url-prefix` function that has been used as a CSS hack targeting Firefox. It continues to be parsed on the Release channel to avoid breakages but will be removed in the near future once major compatibility issues are solved.
