### ISSUE TITLE
Dart Sass --watch fails on the command line

### ISSUE THREAD

**Issue by DerekCL** [sass/dart-sass#399]
**Expected Behavior**
Given I'm using dart sass on the command line inside of an npm script
When I run sass --watch sass/index.scss dist/index.css and then change my scss file
Then the sass should compile to css once after npm script and again after my change

**Actual Behavior**
Given I'm using dart sass on the command line inside of an npm script
When I run sass --watch sass/index.scss dist/index.css and then change my scss file
Then the sass compiles to css once after npm script but after my change I receive the following error

```
project_name/node_modules/sass/sass.dart.js:6421
throw H.e(P.lF(this,b.gnt(),b.gnL(),b.gnx(),null))},null,"gny",5,0,null,19],
^

NoSuchMethodError: method not found: 'call'
Receiver: Closure 'Hs'
Arguments: ["sass/index.scss"]
    at Object.e (project_name/node_modules/sass/sass.dart.js:1642:3)
    at Hs.dart.k.kj (project_name/node_modules/sass/sass.dart.js:6421:9)
    at Object.J.pj (project_name/node_modules/sass/sass.dart.js:22083:34)
    at Object.lQ (project_name/node_modules/sass/sass.dart.js:1605:10)
    at Object.tG (project_name/node_modules/sass/sass.dart.js:1616:21)
    at Object.tH (project_name/node_modules/sass/sass.dart.js:1611:10)
    at Object.fx (project_name/node_modules/sass/sass.dart.js:5706:28)
    at dart.Cb (project_name/node_modules/sass/sass.dart.js:7294:10)
    at FSWatcher.<anonymous> (project_name/node_modules/sass/sass.dart.js:7282:42)
    at emitOne (events.js:116:13)
```

**Steps to Reproduce**
1) run `npm install --save sass` in your command line
2) create some sass in sass/index.scss
3) add `sass --watch sass/index.scss dist/index.css` to your `npm start` script
3) run `npm start`
4) make a change to your sass file and save your change.

**Additional Information**
System: MacOS 10.13.5
dart-sass version: 1.9.0
node version: 8.11.1
npm version: 6.1.0

**Comment by nex3** [comment]
What's the contents of your `index.scss` file before and after you change it?

**Comment by hannahcin** [comment]
I also have the same problem.

**Comment by Amaruq** [comment]
@hannahcin You are on OS X too ? Which versions of sass, node and npm do you use ? Is sass installed globally or in local (though it doesn't seem to be the reason…) ?

**Comment by shubrhajit** [comment]
@Amaruq I'm also facing the same problem.
Sass installed globally and in mac os X version 10.13.5

**Comment by Amaruq** [comment]
@shubrhajit Well I don't pretend to have a solution, but to precise which versions are used may help to isolate the problem. I had the same problem with sass^1.8.0

**Comment by ChrisB55** [comment]
same problem sass 1.9 installed globally mac osx 10.10.5

**Comment by jmesserly** [comment]
Yeah, can take a look.

I can reproduce this. The contents of the scss file do not seem to matter (I grabbed the first example on https://sass-lang.com/guide). I'm on node v10.3.0. Going to see if I can build `sass.dart.js` with a source map and/or unminified so I can debug it.

**Comment by mechmillan** [comment]
I am having the same issue, here is some additional info:

Sass version, installed with npm install -g sass
- 1.9.0 compiled with dart2js 2.0.0-dev.67.0
- Mac OSX version 10.13.5
- Node version 10.6.0

Contents that I am trying are standard css:
```css
body {
  background: black;
}
```

**Comment by jmesserly** [comment]
thanks for the info! I have a fix almost ready for this (#402)

**Comment by DerekCL** [comment]
can confirm that the specifics of the sass file do not matter

**Comment by NetOperatorWibby** [comment]
Oh yay, this is being worked on! I wanted a sass module that didn't have dependency vulnerability issues. I guess I'll be patient and hope the fix gets merged soon!
