### ISSUE TITLE
As of 1.6.0, chokidar is required as an npm dependency

### ISSUE THREAD

**Issue by arciisine** [sass/dart-sass#409]
In the nodejs sass package, chokidar is listed as a `dependency` and not a `devDependency`.  Since `chokidar` is a fairly heavy library by package count, would it be possible to set it as a dev-time element. Or even consider moving to something like [node-watch](https://github.com/yuanchuan/node-watch) as a more light-weight alternative?

**Comment by nex3** [comment]
What concrete problem is this causing?

**Comment by arciisine** [comment]
Only longer npm install times, unnecessary disk usage.

**Comment by nex3** [comment]
Those are pretty minor problems. If someone wanted to submit a pull request to use another watcher, I guess I'd accept it as long as it passes the tests, but it's so low priority I don't think it's worth tracking until then.
