### ISSUE TITLE
Installing dart sass with homebrew. Error: No devel block is defined for sass/sass/sass

### ISSUE THREAD

**Issue by alex-page** [sass/dart-sass#414]
I noticed while installing dart-sass with homebrew using the [README.md](https://github.com/sass/dart-sass/blob/master/README.md#from-homebrew-os-x) instructions, it couldn't find the devel block. I assume the `--devel` is used for non stable code, maybe this was meant to be removed and forgotten about. This is the command I followed:
```
brew install --devel sass/sass/sass
```

Removing `--devel` worked fine for me, I am happy to update the documentation however you may intend for it to be installed with `--devel`.

**Comment by nex3** [comment]
Oh, that's a leftover from when we were pre-1.0. A patch to fix it would be much appreciated!
