### ISSUE TITLE
"kernel-service" error sent to stdout

### ISSUE THREAD

**Issue by GreenFootballs** [sass/dart-sass#421]
I installed the latest Dart Sass via Homebrew on my Mac (replacing the old Ruby Sass, which I've used for years), and at first it seemed to be working fine. But then I noticed that it was occasionally appending what looks like a kernel error message to the output of the sass command:

```
kernel-service: Calling main resulted in an error: isolate terminated by vm
```

The actual CSS code is compiled correctly, but that error message is obviously not a good thing to have in a CSS file. (If this is a real error, shouldn't it have been sent to STDERR, not STDOUT?)

Is this a known issue? I couldn't find other references to it.

**Comment by nex3** [comment]
This is a Dart VM bug. What version of Sass are you using, so we can figure out what version of Dart you're on?

**Comment by nex3** [comment]
Ah, it looks like this was already found and fixed on the Dart side: https://github.com/dart-lang/sdk/issues/32134. I believe this should be picked up in the latest release, but if not it'll be in the next one.

**Comment by GreenFootballs** [comment]
Update: I installed the latest standalone MAC OS package to test, and the bug seems to be fixed in that one.
