### ISSUE TITLE
Allow one property on same line as selector?

### ISSUE THREAD

**Issue by beastdestroyer** [sass/dart-sass#431]
Issue Type: Feature Request;
Hi there, i haven't been able to find any issues related to this so I'll put it up here. My idea is a small one, but I was wondering, would it be possible for selectors with just one property, allow them on the same line? Just like how Pug (formerly Jade) allows text on the same line after a space?

For example, instead of this:
```
p
  font-size: 16px
```
We could have this:
```
p font-size: 16px
```
This would only work with one property, but it would help save lines and make it more concise when coding. (It should also be optional, should you decide to implement it, so people can choose their style).
It could also work for things such as @for loops, or @media queries with only one property being changed?

**Comment by nex3** [comment]
For reference, feature requests for the Sass language should go in the [sass/sass](https://github.com/sass/sass) repository.
