### ISSUE TITLE
Add compact style

### ISSUE THREAD

**Issue by AlexWayfer** [sass/dart-sass#442]
Hello.

For now `dart-sass` has `expanded` (default) and `compressed` styles.

But [Ruby Sass has](https://github.com/sass/ruby-sass/blob/f8a10cd/lib/sass/exec/sass_scss.rb#L84-L87) `nested` (default), `compact`, `compressed` and `expanded`.

Thanks.

**Comment by nex3** [comment]
There are no plans to add additional output styles at this time. They add complexity to the CSS output logic, and there's not a lot of benefit to having more of a distinction than just a human-readable style (`expanded`) versus a minified style (`compressed`).

**Comment by ericmorand** [comment]
@nex3 , it's totally fair. But at one point we'll need to have some proper TypeScript typings for dart-sass. We are currently stuck with the node-sass types but the two APIs are not as identical as we first thought (see https://github.com/sass/dart-sass/issues/13#issuecomment-428346573).

**Comment by lucianmarin** [comment]
I prefer compact style for checking out and reading git diff easily.

**Comment by nektro** [comment]
deeply saddened by this news

**Comment by cooliean** [comment]
Some languages require comment for conditional compilation, which is inconvenient without Compact

**Comment by ericmorand** [comment]
@cooliean what do you mean by _some languages_?

**Comment by nektro** [comment]
`compressed` is not vcs friendly at all

**Comment by nektro** [comment]
perhaps not in your projects, but in many others it is (both are `.scss`/`.min.css`)

**Comment by ericmorand** [comment]
Well, this is not the purpose of a compiler to guarantee that you can easily track binaries in a VCS. Would you ask gcc to make sure that the built artifact can easily be tracked in a VCS?

**Comment by nex3** [comment]
If you want to preserve comments or have nicely diff-able output, expanded mode is great for that. If you want that _and_ a particular formatting style for your CSS, I recommend using PostCSS to set up that formatting yourself.
