### ISSUE TITLE
SASS Compiler not updating onSave

### ISSUE THREAD

**Issue by beastdestroyer** [sass/dart-sass#451]
First, I would like to explain briefly my development setup, just to see if it's more easily reproducible:
1. Use Visual Studio Code Insiders and Dart Sass 1.11 (The one which fixed the compile bug) 
2. Relevant Extensions: stylelint, prettier, Live Server
3. Create a HTML file, create a scss file and compile it using the command (the one I use the most) ```sass --watch ./scss/main.scss ./css/main.min.css --style=compressed --no-source-map```
4. The compiler works, but it doesn't seem to update frequently. I also had autoSave on VSCode, but even manually saving didn't update the css file. I was able to see old code in my CSS file, and it didn't update until I restarted the compiler.

I hope that you could easily reproduce it, it basically is another iteration of the previous issue. I will try to put in more info to help. 

Also try to put random SCSS code and keep your eyes on certain lines. After first compile, delete those lines and let it recompile. Looking at output, those lines will probably still be there

Using Windows 10 1803,17134.191

**Comment by tassiogoncalves** [comment]
Olá amigo, escreva em inglês.
Hello friend, write in English!

**Comment by RazorfieldSquirrel** [comment]
I'm having a similar issue. Here's my environment:

1. MacOS 10.13.6, Sublime Text  3176 & Brackets 1.13 as editors
2. DartSass 1.12.0 installed via brew install sass/sass/sass
3. Create a main.scss file that imports partials _variables.scss and _formstyle.scss thusly
`@import "variables";
@import "formstyle";`
4. Compile using `sass --watch /xxx/xxxx/css/sass:/xxx/xxxx/css/app`
5. The initial compile works great, but edits made to the partials isn't updated in the output css even by forcing a recompile

**Comment by beastdestroyer** [comment]
Yh, 1.11 fixed an issue where the compiler wouldnt work after an error, and you had to restart the compiler. This new bug now happens regardless of error

**Comment by nex3** [comment]
Can one of you create a small Git repo that contains a consistent reproduction of this issue?

**Comment by beastdestroyer** [comment]
@nex3 I have created a small repo. Apologies for not creating it sooner (if that matters). There is some important info I left in the repo's README, I'll let you read for yourself, here's the link and hope you can get it fixed!: [sass-issue-test](https://github.com/beastdestroyer/sass-issue-test)

**Comment by beastdestroyer** [comment]
@nex3 Hey there, I'd love to be able to dive into the Dart code, however I would like to spend a few more days experimenting a bit more to see if I can repro consistently, currently I use SASS with one of my projects, and use Live Server and hot reload etc, usually if it doesn't reload after I edit an SCSS file it won't reload, I'll give you an update when I feel that going into the dart code is necessary, thanks!

**Comment by beastdestroyer** [comment]
After a few days:
Nothing out of the norm/

**Comment by beastdestroyer** [comment]
After no more issues, it doesn't seem fit for a bug that even I cannot repro consistently. Closing.

**Comment by vincedubroeucq** [comment]
Hi, 
I'm experiencing the issue with dart 1.16.1.
I have to stop the watcher and start it again to have changes appear. I'm using VSCode with autosave, on a windows machine.

**Comment by bendjukastein** [comment]
I can report that this issue still exists, I am using VScode on a windows machine with autosave making localhost changes through chrome to a docker web page . It appears to possibly be an issue with the cache, as I can view my changes by simply by performing a hard reload.

**Comment by Awjin** [comment]
If a hard reload fixes the problem, this could be an issue with caching that we don't have control over. One possible workaround is to disable browser cache entirely. If this continues to be an issue, I would recommend trying to put together a reproduction for us to debug against (see #964).
