### ISSUE TITLE
Broken `@extend` with a comma-separated list of selectors

### ISSUE THREAD

**Issue by AlexWayfer** [sass/dart-sass#452]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend

> Multiple extends can also be written using a comma-separated list of selectors. For example, @extend .error, .attention is the same as @extend .error; @extend .attention.

```scss
a {
  @extend button, .light;
}
```

```
Error: unexpected token.
		@extend button, .light;
		              ^
```

**Comment by tassiogoncalves** [comment]
Please, help me, this Dart Sass version not work @extend .class1, .class2;
Necessary coding @extend .class1; @extend class2;


**The error this is:**
Sass code: @extend .light-blue, .darken-4 ;
Return: Error: unexpected token.
@extend .light-blue, .darken-4;
_____________________^

Sass code: @extend .light-blue; @extend .darken-4 ;
Compilation with success.

How to proceed? This is correct? This (@extend .class1, .class2; ) is deprecated?

**Comment by tassiogoncalves** [comment]
Thanks!
