### ISSUE TITLE
Using spaces in argument for "nth-child" causes error `Error: Expected "of".`

### ISSUE THREAD

**Issue by Naahuel** [sass/dart-sass#465]
Using `sass` (installed globally with `npm`) from the command line and with a source like this:

```
a{
  &:nth-child( 4n ) {
    display: none;
  }
}
```
Causes the error `Error: Expected "of".` Took me a long time, but after removing the spaces inside the parenthesis, it worked.

**npm --version** 6.4.0
**node --version** v10.9.0
**sass --version** 1.13.0 compiled with dart2js 2.0.0

**To reproduce:**
```
echo "a{ &:nth-child( 4n ){display:none} }" > style.scss
sass style.scss style.css
# Finishes with error
```

**To fix** (remove spaces)
```
echo "a{ &:nth-child(4n){display:none} }" > style.scss
sass style.scss style.css
echo style.css
# Finishes correctly
```

![screenshot from 2018-08-31 23-23-56](https://user-images.githubusercontent.com/1612488/44941543-3a42c280-ad76-11e8-9d43-938cfc41fa59.png)

**Comment by Naahuel** [comment]
Thanks a lot Natalie. You're the best.

**Comment by nex3** [comment]
Thank you for the clear and thorough issue report!
