### ISSUE TITLE
Was on ruby sass but now trying out dart sass

### ISSUE THREAD

**Issue by dodozhang21** [sass/dart-sass#47]
Hi, I was wondering if there exists good documentation on how to switch from ruby sass to dart sass. For example, we use compass and have multiple import path right now using ruby sass and also via grunt plugin. Is there any documentation on how to do the same using dart sass?

Thanks

**Comment by nex3** [comment]
Dart Sass isn't really complete enough yet for us to be focusing on a migration path. If community members wanted to lay the groundwork that would be rad, but for now I'm focusing on just getting the language right.
