### ISSUE TITLE
"pub global activate dart-sass" does not work

### ISSUE THREAD

**Issue by koorgoo** [sass/dart-sass#49]
```bash
$ pub global activate dart-sass
Resolving dependencies... (1.5s)
Could not find package dart-sass at https://pub.dartlang.org.
```

Environment:
```bash
$ dart --version
Dart VM version: 1.20.1 (Wed Oct 12 15:00:54 2016) on "macos_x64"
```

**Comment by zoechi** [comment]
`dart-sass` is only the GitHub repository name. The package name is `sass`
https://pub.dartlang.org/packages/sass

**Comment by koorgoo** [comment]
As of now README says:

> If you're a Dart user, you can install Dart Sass globally using `pub global
 -activate dart-sass`, which will provide a `dart-sass` executable.

Please see changes in #50.
