### ISSUE TITLE
error message when starting dart-sass

### ISSUE THREAD

**Issue by MagnusA** [sass/dart-sass#490]
I suppose that the error message is not supposed to be shown?
Also the --no-color argument does not apply on the error message.

$./dart-sass --version
-e \e[1;33mWarning\e[0;0m: The \e[1;1mdart-sass\e[0;0m executable is deprecated, use \e[1;1msass\e[0;0m instead.
1.14.1

**Comment by nex3** [comment]
This error message is intended. You should use the executable named `sass` instead.
