### ISSUE TITLE
Error: Unable to open file

### ISSUE THREAD

**Issue by tusharshuklaa** [sass/dart-sass#500]
All of my code is under a mapped drive (Z:) in Windows 10.
I have created few SCSS files like:
```
xyz.scss
abc.scss
_variables.scss
```
When I include `_variables` file in any of other scss files like `@import "_variables.scss";` and then run `sass scss/xyz.scss xyz.css`, 
it gives me error like
```
Error: Cannot open file
@import _variables.scss
```
The files are present in the folder and there is no problem with the code as well.
After i run the command and get the above mentioned error
_variables.scss gets deleted (VS Code says - deleted from disk)

I have no idea what is wrong here!!
Any suggestions?

P.S. - I'm not able to reproduce this error when I repeat these steps in a usual drive (not mapped).

**Comment by nex3** [comment]
You're using a very old Sass version. The most recent version is 1.14.3.

I'm closing this, since there's not much more I can do without the full error output, and it's likely that the issue has been fixed since 1.3.1 anyway.
