### ISSUE TITLE
Sass compilation is returning a Buffer?

### ISSUE THREAD

**Issue by Simplonium** [sass/dart-sass#505]
I'm using npm sass to compile a .scss file into .css through the JS API. Awkward as it may be, it's returning a buffer on the success callback and I have no idea how to turn it into a string.

`        sass.render({
           file: BUILD_DIR + "/game.scss"
        }, function(err, result) {
            console.log(result);
        });
`

Result is:

```
{ css: <Buffer >,
  map: null,
  stats:
   { duration: 1011,
     end: 1540028165613,
     entry: 'build/game.scss',
     includedFiles:
      [ '[censored (the correct file)]',
        '$ti': [Array] ],
     start: 1540028164602 } }
```

I looked buffers up online and this should create the correct content:

`result.css.toString("utf8")`

However logging it to the console prints nothing.

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
