### ISSUE TITLE
Seeing $color and app colors not working

### ISSUE THREAD

**Issue by erichonkanen** [sass/dart-sass#507]
Hello,

I upgraded to latest 1.14 version via ember-cli-sass and now my app colors aren't loading at all and it's mostly black and white.

When I inspect my root color definitions in console I see below. Any ideas what could be going on?

Thanks!

![image](https://user-images.githubusercontent.com/230757/47480596-c78a1c80-d7e5-11e8-80bc-3ffccf58974d.png)

sass vars looks like:
```
$colors: (
  bg-blend: hsla(hue($color-mixed), 100%, 65%, 1),
  bg-default: hsla(hue($color-mixed), 26%, 95%, 1),
  bg-default-darker: hsla(hue($color-mixed), 22%, 90%, 1),
```

**Comment by nex3** [comment]
Recent Sass implementations have changed how custom properties are parsed. See [this blog post](http://sass.logdown.com/posts/809572-sass-35-release-candidate) for details.
