### ISSUE TITLE
Error with 1.0.0-alpha.4  on Windows 

### ISSUE THREAD

**Issue by AngusFu** [sass/dart-sass#51]
On Windows CMD and GitBash, it seems path seperator often cause some error. 

Test the following code, where `./test.scss` is any given valid `scss` file in the same folder:

```
var sass = require('dart-sass');
var res = sass.renderSync({ file: './test.scss' });
console.log(res);
```

Then got: 

![image](https://cloud.githubusercontent.com/assets/8180186/20553445/c3a2a8a4-b18f-11e6-942a-952f8b8c1aec.png)

In `dart.Uri_parse`‘s body, insert a new line at the begining, `uri = uri.replace(/\\/g, '/')` will work,

So this maybe a problem to be solved.

**Comment by nex3** [comment]
This looks like it could be a bug in the glue code we use for Node.js, or possibly even in Dart itself. I may need to track down a Windows machine to test this properly.

**Comment by nschonni** [comment]
Might be a good idea to setup Appveyor for this repo to catch the Windows specific issues

**Comment by nex3** [comment]
> Might be a good idea to setup Appveyor for this repo to catch the Windows specific issues

Currently our only tests are sass-spec tests of the language itself, which aren't likely to vary from OS to OS. We should probably add some tests for the CLI(s), though.
