### ISSUE TITLE
Allow direct symlinks to dart-sass

### ISSUE THREAD

**Issue by joseluis** [sass/dart-sass#52]
Currently dart-sass doesn't work in Linux when you call it through a symlink located on a different path.

It's common practice to install a package in one place and create a symlink to the binary from a location already in `$PATH`. E.g.:

    sudo ln -sf $HOME/Downloads/dart-sass/dart-sass /usr/local/bin/sass

    $ dart-sass --version
    /usr/local/bin/sass: line 11: /usr/local/bin/src/dart: No such file or directory

In order for this to work the path resolution must be changed from:

    path=`dirname "$0"`

to:

    path="$(dirname "$(readlink -f "$0")")"

This expression correctly returns the directory of the script, and supports calling the binary directly linked through a symlink. It is posix compatible, and it has been tested with posh (Policy-compliant Ordinary SHell).

The only problem with it is that it is not compatible with Mac OS X, because apparently it doesn't support the -f flag in readlink, under normal conditions. And I can see the same script is used for Mac OS too.

So the simplest way I can see to support both cases, is to check first if the target path can be resolved, and only if it fails, use the new resolution formula. Like this:

    path=$(dirname "$0")
    if [ ! -f "$path/src/dart" ]; then
        path="$(dirname "$(readlink -f "$0")")"
    fi

**Comment by zoechi** [comment]
What about linking to `~/.pub-cache/bin/dart-sass` (after running `pub global activate`)?

**Comment by joseluis** [comment]
Ha, I didn't thought about that, since it's not officially published yet, I had to install it like this:

    pub global activate --source git https://github.com/dart-lang

And calling a symlink pointing to "$HOME/.pub-cache/bin/dart-sass", does work well.

Thanks @zoechi. It seems that the script I had to modify isn't intended for production then.

**Comment by zoechi** [comment]
It's published https://pub.dartlang.org/packages/sass but you need a proper version constraint.
The package name was previously used for another Dart SASS package and pre-release versions (1.0.0-alpha.4) are handled a bit different

**Comment by zoechi** [comment]
```
 pub global activate sass ^1.0.0-alpha.4
```

**Comment by joseluis** [comment]
That does work. But then the [README](https://github.com/sass/dart-sass#from-pub) should be updated because it currently says:

> If you're a Dart user, you can install Dart Sass globally using `pub global activate dart-sass `

**Comment by zoechi** [comment]
Already created a PR
