### ISSUE TITLE
Misleading error message for overloaded function arity

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#520]
When the wrong number of arguments are passed to a function with overloads, Dart Sass's error message sometimes claims that the function accepts fewer arguments than it actually does. For example:

```
$ sass --interactive
>> hsla(1, 2, 3, 4, 5)
   ^^^^^^^^^^^^^^^^^^^
Error: Only 1 argument allowed, but 5 were passed.
```

`hsla()` allows up to 4 arguments, so this error message is confusing and incorrect.

**Comment by DreamSpinner22** [comment]
Hey, @nex3, has this one been solved yet? I'd like to work on it, if possible. I may need some direction in doing so. Mainly, just where to find the code in the files. I see multiple color.dart files in different directories. Can you help out with this?

Thanks!

**Comment by nex3** [comment]
This is still up for grabs! I think you actually want to look at [`_AsyncEvaluator._runBuiltInCallable()`](https://github.com/sass/dart-sass/blob/6b8c168779a735087513dfb7a15902230627c843/lib/src/visitor/async_evaluate.dart#L2140-L2141) or maybe [`ArgumentDeclaration.verify()`](https://github.com/sass/dart-sass/blob/6b8c168779a735087513dfb7a15902230627c843/lib/src/ast/sass/argument_declaration.dart#L60-L97)—the problem is that there are multiple possible overloads of the function with different numbers of arguments, and we should be throwing an error for the one with the most arguments.

**Comment by Awjin** [comment]
How do we know which overloaded function to use for argument validity?

Currently with 4 args, `hsla` gets overloaded as `hsla(hue, saturation, lightness, alpha)`.
But with 1 arg it becomes `hsla(channels)`.

If we choose `hsla(hue, saturation, lightness, alpha)` we would get the desired error,

```
>> hsla(1, 2, 3, 4, 5)
   ^^^^^^^^^^^^^^^^^^^
Error: Only 1 argument allowed, but 5 were passed.
```

but we would also get the undesired

```
>> hsla()
   ^^^^^^^^^^^^^^^^^^^
Error: Missing argument $hue.  // Should be "Error: Missing argument $channels"
```

**Comment by nex3** [comment]
That's kind of the core question here, and it may come down to finding a heuristic that best matches the failure cases we know of. I think a good starting point is choosing the overload that's *closest* to the number of (positional?) arguments that were actually passed.

**Comment by Awjin** [comment]
@DreamSpinner22 don't want to steal your thunder—would you mind if I worked on this?

**Comment by DreamSpinner22** [comment]
@Awjin I do not mind you working on this. I haven't had much spare time to work on this, unfortunately. If you do figure it out before me, please let me know how because I'm still new to Dart and want to learn as much as possible.

**Comment by Awjin** [comment]
@DreamSpinner22 see the solution here: https://github.com/sass/dart-sass/pull/883/files
