### ISSUE TITLE
Quotes in CSS attribute selectors and IE11

### ISSUE THREAD

**Issue by stukalin** [sass/dart-sass#527]
Faced the following issue. Let's say we have a piece of scss:

```
.badge-pos:not([class*="--top-left"]):not([class*="--bottom-left"]):not([class*="--bottom-right"]) {
  top: 0;
  right: 0;
  transform: translate(50%, -50%);
}
```

It turns out that IE11 expects the result CSS to preserve the quotes. `dart-sass`, however, opts them out:
![image](https://user-images.githubusercontent.com/9863365/48537258-1c3f2580-e8c2-11e8-8672-fd9f0989ce83.png)

The `node-sass` doesn't seem to have the issue, switched on it for the time being.

My dart-sass version: 1.15.0

**Comment by nex3** [comment]
It looks like this issue is specific to attribute values that are identifiers that look like custom property names. I'm guessing IE11 doesn't support the latest identifier spec.
