### ISSUE TITLE
Broken CSS after switching to 1.15

### ISSUE THREAD

**Issue by hubchau** [sass/dart-sass#530]
Hi, 

This morning, our website no longer showed some SVG icons. It seems that, following an `npm install`, we unknowingly switched to sass 1.15.0 (poorly configured package.json file on our side).

After a thorough investigation, we realized the only differences between the css file generated by Sass 1.14.3 and the one generated by Sass 1.15.0 were spaces (or so it seems) inserted between a css property  and its opening curly bracket (of course, no space was inserted in the .scss file). And weirdly enough, this caused browsers (all of them) to no apply the subsequent CSS rule...

I noticed that the Changelog mentioned "Properly compile selectors that end in escaped whitespace." so I guess it's linked, but I wonder if it's an issue.

What's even weirder is that this space insertion only happened for this few lines whereas my entire .scss file as spaces between the selector and the opening curly bracket.

The scss part (nothing fancy): 

```
.navbar #paging-mode {
  background-image: url(../../shared/assets/img/toolbar/page.svg);
}
.navbar #rotate-mode {
  background-image: url(../../shared/assets/img/toolbar/3-d-rotate.svg);
}
.navbar #zoom-mode {
  background-image: url(../../shared/assets/img/toolbar/zoom.svg);
}
.navbar #wwwl-mode {
  background-image: url(../../shared/assets/img/toolbar/wwwl.svg);
}
.navbar #distance-mode {
  background-image: url(../../shared/assets/img/toolbar/segment.svg);
}
.navbar #pan-mode {
  background-image: url(../../shared/assets/img/toolbar/pan.svg);
}
``` 

And the diff between the 1.14.3 and the 1.15.0 css:
```
--- /Desktop/css-1.14.3.css
+++ /Desktop/css-1.15.css
@@ -8692,27 +8692,27 @@
   margin: auto;
 }
 
-.navbar #paging-mode {
+.navbar #paging-mode  {
   background-image: url(../../shared/assets/img/toolbar/page.svg);
 }
 
-.navbar #rotate-mode {
+.navbar #rotate-mode  {
   background-image: url(../../shared/assets/img/toolbar/3-d-rotate.svg);
 }
 
-.navbar #zoom-mode {
+.navbar #zoom-mode  {
   background-image: url(../../shared/assets/img/toolbar/zoom.svg);
 }
 
-.navbar #wwwl-mode {
+.navbar #wwwl-mode  {
   background-image: url(../../shared/assets/img/toolbar/wwwl.svg);
 }
 
-.navbar #distance-mode {
+.navbar #distance-mode  {
   background-image: url(../../shared/assets/img/toolbar/segment.svg);
 }
 
-.navbar #pan-mode {
+.navbar #pan-mode  {
   background-image: url(../../shared/assets/img/toolbar/pan.svg);
 }
```

What do you make of this? Is this a bug or am I missing something here? Could it be a special character and not a space, causing the browsers to fail on this?

Thanks a lot!

**Comment by nex3** [comment]
I can't reproduce output diffs from the input you've provided. Can you provide a git repo that reproduces the issue?

Also, what browser(s) are you seeing rendering issues on?

**Comment by hubchau** [comment]
Hi, 

Sorry for the late reply. I created a public repo to provide you with a piece of my code but unfortunately, I wasn't able to reproduce my issue in this context.

I guess you can close this issue. Sorry!
