### ISSUE TITLE
Broken CSS when minified with version >1.14.3

### ISSUE THREAD

**Issue by cdgeelen** [sass/dart-sass#532]
Hi,

When using npm sass version 1.15.0/1.15.1 (version 1.14.4 is not released on npm), our minified CSS breaks.

We have reduced this error to our import of _forms.scss of bootstrap-sass. To be more specific, [line 245](https://github.com/twbs/bootstrap-sass/blob/2dd87b0c471a6a00e5b19502dee702db54602400/assets/stylesheets/bootstrap/_forms.scss#L245). 
It appears that the \9 character is not parsed correctly in a minified version.

To illustrate, below are snippits of resulting minified CSS files:

sass version 1.15.1; margin-top last line of the CSS selector (note the trailing \ at the end, and no ;)
```
.checkbox-inline input[type=checkbox],.radio input[type=radio],.radio-inline input[type=radio]{position:absolute;margin-left:-20px;margin-top:4px \}
```

sass version 1.15.1; margin-top moved to the second-to-last line of the CSS selector (note the ; after the trailing \)
```
.checkbox-inline input[type=checkbox],.radio input[type=radio],.radio-inline input[type=radio]{position:absolute;margin-top:4px \;margin-left:-20px}
```

sass version 1.14.3; margin-top last line of the CSS selector (note the \9 remained intact, without ;)
```
.checkbox-inline input[type=checkbox],.radio input[type=radio],.radio-inline input[type=radio]{position:absolute;margin-left:-20px;margin-top:4px\9}
```

I assume this is related to #504, but I don't have enough knowledge of the code to pinpoint if this is true, and if yes, why.

**Comment by nex3** [comment]
I can't reproduce this. When I compile

```scss
.checkbox-inline input[type="checkbox"] {
  margin-top: 4px \9;
}
```

with Dart Sass 1.15.1 in compressed mode, I get

```css
.checkbox-inline input[type=checkbox]{margin-top:4px \  }
```

Note the tab character after the backslash. Are you running this through an additional CSS minifier after Sass? It's possible that that minifier isn't properly parsing the escaped tab character.
