### ISSUE TITLE
--source-map-urls=absolute ineffective

### ISSUE THREAD

**Issue by sirthias** [sass/dart-sass#575]
I'm running dart sass 1.16.1 on macOS (installed via homebrew).

The CLI option `--source-map-urls=absolute` or `--source-map-urls absolute` is ineffective for me, i.e. all source map URIs are still rendered in with relative paths, i.e. unchanged from the default.

**Comment by nex3** [comment]
Can you create an example repo with the source files you're compiling and the source maps you're getting out the other end?

**Comment by sirthias** [comment]
Thank you, @nex3, for the quick reply!

In fact, I misunderstood the `--source-map-urls` option.
I now think it works as intended and turns the elements of the `sources` array in the source map file into absolute paths.

I was looking at the `/*# sourceMappingURL=out.css.map */` comment in the actual `css` file and mistakenly assumed, that the `--source-map-urls` option would change _that_ URI to become absolute, which it doesn't.

By the way: Is the file name of the source map file guaranteed to always be the same as the `output` file name with an additional `.map` suffix?

**Comment by nex3** [comment]
> Thank you, @nex3, for the quick reply!
> 
> In fact, I misunderstood the `--source-map-urls` option.
> I now think it works as intended and turns the elements of the `sources` array in the source map file into absolute paths.
> 
> I was looking at the `/*# sourceMappingURL=out.css.map */` comment in the actual `css` file and mistakenly assumed, that the `--source-map-urls` option would change _that_ URI to become absolute, which it doesn't.

That's right. The only flag to control that URL is `--embed-source-map`, which replaces it with a `data:` URL that contains the contents of the source map inline. If you want really fine-grained control over how the source map works, you'll need to use either the Dart API or the JS API.

> By the way: Is the file name of the source map file guaranteed to always be the same as the `output` file name with an additional `.map` suffix?

Yes, as long as a source map is generated.

**Comment by sirthias** [comment]
Great! Thank you, @nex3!
