### ISSUE TITLE
Gitbash integration

### ISSUE THREAD

**Issue by AmmarAlam17** [sass/dart-sass#579]
sass is recognized by cmd in both of my systems after adding to the path but not with my git bash, I checked permission and restart bash but the results are same with both systems gitbash is updated to its new version no problem there...

Snap:
![sass](https://user-images.githubusercontent.com/33506246/51806058-09b87380-2297-11e9-885b-7a817c4d4e32.PNG)

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
