### ISSUE TITLE
color: rgb(black / 0.1);

### ISSUE THREAD

**Issue by brookjordan** [sass/dart-sass#580]
Now that we have the new color syntax working (I love it 😍):
```scss
color: rgb(0 0 0 / 0.5);
```

Would it be possible to use color variables in place of the `r`,`g`,`b` numbers, as is possible with the `rgba` function?
```scss
// allow:
color: rgb(black / 0.5);

// along with:
color: rgba(black, 0.5);
```

**Comment by nex3** [comment]
It's extremely risky to add Sass-specific behavior in places where CSS might add its own behavior down the line. In retrospect, I regret even adding the two-argument `rgba()` function--we dodged a bullet that CSS never decided to use that syntax for something different.

The syntax you're proposing would also be technically infeasible. We already have to jump through a bunch of hoops to correctly handle slash-separated *numbers* in the new syntax, and doing it with *colors* would be substantially more difficult.
