### ISSUE TITLE
@warn directive bug

### ISSUE THREAD

**Issue by oligot** [sass/dart-sass#585]
Hi :wave:,

I'm trying to switch from node-sass to dart-sass.
I only have one issue left, regarding the @warn directive: with node-sass, we can [define a function](https://github.com/sass/node-sass#functions--v300---experimental) `@warn` that will be called when a  @warn directive is encountered:
```js
sass.renderSync({
    file: 'style.scss',
    functions: {
      '@warn'(warning) {
        // Do something with warning...
        return warning;
      }
    }
});
```

This works great with node-sass, but throw an Error when switching to dart-sass.

To see the issue in action, I've created a [small repo with instructions on how to reproduce the bug](https://github.com/oligot/sass-warn-directive).

Unfortunately, I don't know dart, so I can't fix the bug myself...

**Comment by nex3** [comment]
I don't think it's accurate to describe this as a "bug". You're asking us to support a (completely undocumented) Node Sass feature.

From a design perspective, I don't think defining a function with a magic name to customize the behavior of an at-rule is the clearest or most flexible way to support the goal of controlling how Sass provides information to the user. In the Dart API, we have [a full `Logger` interface](https://pub.dartlang.org/documentation/sass/latest/sass/Logger-class.html) that provides the caller with information about the stack trace and source of the message, and that's invoked for *all* warnings (not just `@warn` rules) and optionally for `@debug` rules as well.

@xzyfer @nschonni Is this something you consider crucial to the Node Sass API? If not, I'd prefer to come up with a better-designed alternative that both Node Sass and Dart Sass can implement.

**Comment by glenn2223** [comment]
Hello,

Has there been anymore thought/progress on this? I also used this node-sass feature, in a VS Code extension, which outputs a message to the user.

I see you wanted to have this as accessible properties over a `feature` "hack". Would these properties be an array containing something similar to the `SassException` interface, like below?

```` Typescript
interface SassException extends Error {
    message: string;
    formatted: string;
    line: number;
    column: number;
    status: number;
    file: string;
}
````

**My usage**
````Typescript
data.functions = {
    // @error is handled suitably
    '@warn': function (info) {
        const lines: string[] = [];

        infoCompiler(lines, info);

        OutputWindow.Show('Warning:', lines, showOutputWindow, true); // <-- Output a message (shown based on settings)
        WindowPopout.Warn('Live Sass Compiler\n *Warning:* \n' + (lines.join('\n'))); // <-- Open popup to flag a warning has happened

        return compiler.types.Null;
    },
    '@debug': function (info) {
        const lines: string[] = [];

        infoCompiler(lines, info);

        OutputWindow.Show('Debug info:', lines, showOutputWindow, true); // <-- Output a message (shown based on settings)

        return compiler.types.Null;
    }
};
````

**Output error**
````console
Error: Invalid signature "@warn": Expected identifier.
  ╷
1 │ @warn
  │ ^
  ╵
  - 1:1  root stylesheet
````
````
{
  formatted: "Error: Invalid signature \"@warn\": Expected identifier.\n  ╷\n1 │ @warn\n  │ ^\n  ╵\n  - 1:1  root stylesheet",
  line: 1,
  column: 1,
  file: "stdin",
  status: 1,
}
````

**Comment by nex3** [comment]
If you'd like to take the reins on designing a new JS API for this, that would be amazing. We'd probably want it to look something like Dart Sass's [`Logger`](https://pub.dev/documentation/sass/latest/sass/Logger-class.html) API.

Since this is a new JS API feature, let's move it over to https://github.com/sass/sass/issues/2979 where we typically discuss JS API design.
