### ISSUE TITLE
node-sass compat: async errors for sass functions

### ISSUE THREAD

**Issue by chriseppstein** [sass/dart-sass#590]
In node-sass you return a value of type `sass.types.Error` if you want to communicate a failure that occurred during function execution back to the sass compiler. In dart-sass, there's no `sass.types.Error` constructor. According to @nex3, dart-sass expects an instance of the standard js Error object, but returning a standard error object to node-sass fails with `error in C function eyeglass-fs-info: A SassValue object was expected.`

**Comment by chriseppstein** [comment]
example code:

```js
let sassOptions = {
  "functions": {
    "raise-error($wait-time)": function(waitTime, cb) {
      setTimeout(function() {
        cb(new sass.types.Error("An Error!"));
      }, waitTime.getValue());
    }
  }
};
```

**Comment by nex3** [comment]
The hilarious thing here is that passing an `Error` to an *importer's* callback works in Node Sass, but passing a `sass.types.Error` does not.
