### ISSUE TITLE
lib-sass compat: inspect("abc") == "abc" should be true but is false

### ISSUE THREAD

**Issue by JakeChampion** [sass/dart-sass#594]
I was attempting to move a project over from node-sass to dart-sass and came across this difference in the compiled output. I've looked through the [16 behavioral differences from ruby-sass](https://github.com/sass/dart-sass#behavioral-differences-from-ruby-sass) and I think this difference in output is not due to any of those differences.
I've posted working sassmeiser test-cases and taken screenshots incase the test-cases are not working.
[dart-sass version](https://www.sassmeister.com/gist/5cb24526bfcf721045275ad0b2f32baa)
![dart-sass](https://user-images.githubusercontent.com/1569131/52718104-956e1780-2f9a-11e9-96c7-62a8573f45f0.png)
[lib-sass version](https://www.sassmeister.com/gist/c1ed7d7407664d294055e1d7718ddac7)
![lib-sass](https://user-images.githubusercontent.com/1569131/52718125-9e5ee900-2f9a-11e9-9188-df9a102b41d2.png)

**Comment by nex3** [comment]
LibSass is incorrect here. Both Ruby Sass (the old reference implementation) and Dart Sass (the new reference implementation) return an unquoted string containing U+0022 QUOTATION MARK, U+0061 LATIN SMALL LETTER A, and U+0022 QUOTATION MARK. LibSass incorrectly returns a quoted string containing only U+0061 LATIN SMALL LETTER A. I'll file an issue for this against LibSass.
