### ISSUE TITLE
CLI success output

### ISSUE THREAD

**Issue by gabrielmaldi** [sass/dart-sass#595]
When running node-sass successfully, a nice (green) message is printed to the console:

```
Rendering Complete, saving .css file...
Wrote Source Map to /Users/gabriel/file.css.map
Wrote CSS to /Users/gabriel/file.css
```

By contrast, Dart Sass produces no output on successful builds.

Is this by design? Is there an option to make Dart Sass print something like node-sass?

Sorry if this has been discussed before.

Thanks

**Comment by nex3** [comment]
Unix command-line programs have a strong convention of printing no output when they succeed, and Dart Sass (like Ruby Sass before it) follows that convention (except in `--watch` mode). I think it makes sense to continue following it.
