### ISSUE TITLE
Oddities with a proprietary property -moz-column-count in mixin when compiled

### ISSUE THREAD

**Issue by mosesfender** [sass/dart-sass#597]
Tried to do so:

@mixin columnCount($count) {
    -webkit-column-count: $count;
    -moz-column-count: $count;
    column-count: $count;
}

@mixin columnGap($gap) {
    -webkit-column-gap: $gap;
    -moz-column-gap: $gap;
    column-gap: $gap;
}

@mixin columns($count, $gap){
    @include columnCount($count);
    @include columnGap($gap);
}
…
    &__list{
        @include columns(4, 40px);
…

Out after compile:

  .popular__list {
    -webkit-column-count: 4;
    column-count: 4;
    -webkit-column-gap: 40px;
    column-gap: 40px;
…

Her skips proprietary -moz-column-count & -moz-column-gap. If made so:
…
    &__list{
        -moz-column-count: 4;
        @include columns(4, 40px);
…
then all right.

Finally, swapped:

@mixin columnCount($count) {
    -webkit-column-count: $count;
    column-count: $count;
    -moz-column-count: $count;
}

and it worked. But it should not be so. You need a "clean" property after proprietary.

**Comment by nex3** [comment]
I can't tell what's going on in your input files. Please reformat using code blocks, and include a full valid input file.
