### ISSUE TITLE
Erasing quotes enclosing a value of an attribute selector

### ISSUE THREAD

**Issue by sttk** [sass/dart-sass#598]
The `test.scss` is:

```
$ cat test.scss
div[data-a="a."] { color: red; }
div[data-a="1."] { color: blue; }
```

And the result by compiling with `sass` is as follows. By erasing the quotes of the attribute value, the first style is ineffective.

```
$ npm i sass
$ npx sass test.scss:test.css
$ cat test.css
div[data-a=a.] {
  color: red;
}

div[data-a="1."] {
  color: blue;
}

/*# sourceMappingURL=test.css.map */
```

As a reference, the result by `node-sass` is as follows. This first style is effective.

```
$ npm i node-sass
$ npx node-sass test.scss test.css
$ cat test.css
div[data-a="a."] {
  color: red; }

div[data-a="1."] {
  color: blue; }
```

**Comment by adamjcook** [comment]
I am still seeing a variation of this issue (I think) on the latest Dart Sass. Should I file a new issue with the reproduction steps?
