### ISSUE TITLE
@import from node_modules different from node-sass

### ISSUE THREAD

**Issue by tomByrer** [sass/dart-sass#615]
given: `sass src/css/video-js.scss dist/video-js.css`
& in `video-js.scss` this import does not work for dart-sass, but did in node-sass:
```sass
...
@import "node_modules/videojs-font/scss/icons";
```
Though with dart-sass, this does work:
```sass
`@import "../../node_modules/videojs-font/scss/icons";`
```

Is this [expected behavior](https://github.com/sass/dart-sass/issues/574#issuecomment-457026289) or a bug?

**Comment by nex3** [comment]
Dart Sass's command-line interface doesn't look for imports in any location that's not explicitly provided as a `--load-path` on the command line. Node Sass's CLI may behave differently.

**Comment by tomByrer** [comment]
Thanks for the info!

I tried to look that up in the docs, but was discouraged & confused by the [Ruby references](https://github.com/sass/sass-site/issues/205#issuecomment-469787757) in the [options section](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#options).

**Comment by nex3** [comment]
We're working on updating the website so hopefully these things will be easier to find!
