### ISSUE TITLE
If import URL is wrong but even if package urls are supported, dart-sass complains: "package:" URLs aren't supported on this platform.

### ISSUE THREAD

**Issue by AlexanderJohr** [sass/dart-sass#630]
I get the Error `"package:" URLs aren't supported on this platform`.

The error is resolved when the path is correct.

I ran into this issue when I renamed the package and hence the import urls needed to be updated.

dart-sass tries to import and if it didn't work and it is a package URL, it doesn't check if it was just a wrong url. It just assumes, that it is because package aren't isn't supported on that platform, even when they are.

It can be found in \visitor\evaluate.dart and \visitor\async_evaluate.dart:

https://github.com/sass/dart-sass/blob/bc5e3c4f8f220cc4f9aefa79d3d6354ffdaeffb2/lib/src/visitor/async_evaluate.dart#L854

https://github.com/sass/dart-sass/blob/bc5e3c4f8f220cc4f9aefa79d3d6354ffdaeffb2/lib/src/visitor/evaluate.dart#L854

```dart
// [...]
    try {
      if (_nodeImporter != null) {
        var stylesheet = _importLikeNode(url);
        if (stylesheet != null) return Tuple2(null, stylesheet);
      } else {
        var tuple = _importCache.import(
            Uri.parse(url), _importer, _stylesheet.span?.sourceUrl);
        if (tuple != null) return tuple;
      }
 
// AlexanderJohr: If the program reached here, the import didn't work. Could be because of wrong url or because package URLs aren't supported, but it just assumes, that it is because of package URLs not supported on the platform.
      if (url.startsWith('package:')) {
        // Special-case this error message, since it's tripped people up in the
        // past.
        throw "\"package:\" URLs aren't supported on this platform.";
      } else {
        throw "Can't find stylesheet to import.";
      }
    } on SassException catch (error) {
// [...]
```

But for now I'm not sure how to fix it myself.

**Comment by aaronlademann-wf** [comment]
I am seeing the same thing.
