### ISSUE TITLE
Error reading c:\Program Files\Common Files\*: Directory listing failed.

### ISSUE THREAD

**Issue by ghost** [sass/dart-sass#632]
[Downloaded](https://github.com/sass/dart-sass/releases/download/1.17.3/dart-sass-1.17.3-windows-x64.zip) from [here](https://github.com/sass/dart-sass/releases/tag/1.17.3), added to path, then:

```
C:\>sass C:\test.scss C:\test.css
Error reading c:\Program Files\Gemeinsame Dateien\*: Directory listing failed.

C:\>
```

Why do i get an error? And why is this software interested in whats inside my user folder?

**Comment by nex3** [comment]
I can't imagine why this is happening. What do you see when you pass `--trace` to `sass`?

**Comment by heronils** [comment]
I can not get the above output any more. The first times i ran it i just got nothing and i aborted with ctrl+c. Then i got the above message. I now re'installed' (also tried with the x32 version) and i get nothing again. I can run `C:\run\dart-sass\sass.bat --help` and get the help message (For the records, the help message shows the square symbol before the '[' in headings - encoding issue). When i run `C:\run\dart-sass\sass.bat --version` i get `1.17.3`. But `C:\run\dart-sass\sass.bat C:\test.scss C:\test.css` just does nothing, also when i append `--trace` . Im on Windows 7.

**Comment by Registrierungsgenervter** [comment]
I can not get the above output any more. The first times i ran it i just got nothing and i aborted with ctrl+c. Then i got the above message. I now re'installed' (also tried with the x32 version) and i get nothing again. I can run `C:\run\dart-sass\sass.bat --help` and get the help message (For the records, the help message shows the square symbol before the '[' in headings - encoding issue). When i run `C:\run\dart-sass\sass.bat --version` i get `1.17.3`. But `C:\run\dart-sass\sass.bat C:\test.scss C:\test.css` just does nothing, also when i append `--trace` . Im on Windows 7.

**Comment by Registrierungsgenervter** [comment]
The square symbol seems to be related to the font im using, Lucida Console. When i switch to Consolas it goes away.

**Comment by nex3** [comment]
I believe this was fixed by https://github.com/sass/dart-sass/pull/641.
