### ISSUE TITLE
Add strictness flags

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#633]
A number of users have requested the ability to opt in to stricter Sass compilation, in which code that would normally just causes a warning (especially a deprecation warning) instead produces a compile error. We should add these flags for all current deprecation warnings to the CLI and both APIs, and possibly add configuration file support so that the can be consistently configured for teams.

TypeScript's [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) provide some prior art here. I suspect we *don't* want to add a general `--strict` flag that enables all strict checks, though, since this will mean some downstream users will break when we add new deprecations.

- [x] CLI support
- [x] Dart API support
- [ ] JS API support
- [ ] Documentation

**Comment by jathak** [comment]
As part of this, there should also be an option to error on `@warn` rules.

**Comment by Ariane-B** [comment]
So when can we hope to see this? I'm guessing not soon, since the proposal doesn't seem to be entirely decided upon?

**Comment by jathak** [comment]
We have many things we want to work on and while this is one of them, we don't currently have an ETA for this. We'll add an update here when we have news to share.

**Comment by jjonescz** [comment]
> As part of this, there should also be an option to error on `@warn` rules.

Note: for failing on warnings in CI, I'm using the logger option like this (not ideal, but better than nothing):

```js
logger: process.env.CI
  ? undefined
  : {
    warn: (message: string): void => {
      throw new Error(`Warning from SASS reported: ${message}`);
    },
  },
```

**Comment by jathak** [comment]
Forgot to close this issue, but this is now fully released. You can use the [`--fatal-deprecation` flag](https://sass-lang.com/documentation/cli/dart-sass/#fatal-deprecation) on the CLI or the [`fatalDeprecations` option](https://sass-lang.com/documentation/js-api/interfaces/options/#fatalDeprecations) in the JS API to make a particular deprecation type an error, or pass in a Dart Sass version to make all deprecations active in that version errors.

There's also `--silence-deprecation`/`silenceDeprecations` to silence a particular deprecation type.

**Comment by u01jmg3** [comment]
Thanks for implementing this feature, @jathak

Is there any way to opt-in so that all deprecations are treated as fatal without knowing their ID (or the Sass version) ahead of time? I'd like my CI to fail and alert me as soon as a new deprecation warning is present in my build.

**Comment by nex3** [comment]
We intentionally chose *not* to make it easy to do that, because it would effectively make adding a new deprecation into a breaking change for a subset of our users. The goal of adding strictness flags was to make it smoother, not more painful, to add deprecations in the future.

That said, you can do this manually by passing the current Sass version to the `--fatal-deprecations` flag. In Bash:

```sh
sass --fatal-deprecations=$(sass --version) ...
```

or in the JS API:

```js
const sass = require('sass');

const sassVersion = sass.Version.parse(sass.info.split("\t")[1]);
sass.compileString('@import "other"', {fatalDeprecations: [sassVersion]});
```

**Comment by u01jmg3** [comment]
- Appreciate the info and noted the implications
- Code snippets were super helpful
- Should I be able to combine with `silenceDeprecations`? Aiming to achieve:

```js
const sass = require('sass');
const sassVersion = sass.Version.parse(sass.info.split("\t")[1]);

sass.compileString(
  '@import "other"', 
  { silenceDeprecations: ['import'], fatalDeprecations: [sassVersion] }
);
```

**Comment by nex3** [comment]
Per [the specification](https://github.com/sass/sass/blob/main/accepted/deprecations-api.md#fataldeprecations):

> If a deprecation is passed both [to `fatalDeprecations`] and to `silenceDeprecations`, a warning must be emitted, but making the deprecation fatal must take precedence.

So if you want to silence specific deprecations, you have to explicitly list all the deprecations you want to be fatal. If you're using the JS API, you can do that semi-automatically by iterating [the set of all known deprecations](https://sass-lang.com/documentation/js-api/interfaces/deprecations/).

**Comment by u01jmg3** [comment]
Thank you - I hadn't spotted that in the specification

Along the same lines of your previous snippet, I went with:

```js
const sass = require('sass');

const deprecationIds = Object.keys(sass.deprecations);
const excludedDeprecations = ['import'];
const includedDeprecations = deprecationIds.filter(id => !(new Set(excludedDeprecations)).has(id));

sass.compileString(
  '@import "other"', 
  { silenceDeprecations: excludedDeprecations, fatalDeprecations: includedDeprecations }
);
```

☮️

**Comment by rgpublic** [comment]
> We intentionally chose _not_ to make it easy to do that, because it would effectively make adding a new deprecation into a breaking change for a subset of our users. The goal of adding strictness flags was to make it smoother, not more painful, to add deprecations in the future.

IMHO this should really be easier and not use two separate SASS calls which is quite inefficient. I'm the only one administrating our compile pipeline. I know when I'm installing a new version and this intentionally means everything that's now deprecated should fail so our developers can review this. There are very legimitate applications for this. Why not letting users decide and just document/warn about the implications. I was very surprised to find that --fatal-deprecations by itself doesn't work. At least --fatal-deprecations=9.9.9 should IMHO work. The check that it a version higher than the current one isn't allowed is really a bit too chaperone-ish, I guess.

**Comment by nex3** [comment]
Again, there's a straightforward workaround if you _really_ want to opt into potentially being broken by every release:

```sh
sass --fatal-deprecations=$(sass --version | cut -d ' ' -f1) ...
```
