### ISSUE TITLE
Deprecate the dart-sass package on npm

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#645]
When we first started distributing Dart Sass on npm, we released it as [the `dart-sass` package](https://www.npmjs.com/package/dart-sass). Since we made it the official reference implementation, we've changed the primary package name to [`sass`](https://www.npmjs.com/package/sass), while continuing to release `dart-sass` alongside it. But having two packages is confusing and makes download numbers harder to track, so we should deprecate the `dart-sass` package (however that works best on npm) and eventually discontinue it.

**Comment by stof** [comment]
Looking at npmjs.com, it looks like the `dart-sass` does not get updated anymore now (last published version is 1.25.0). It would be great to mark it as deprecated with `npm deprecate` so that npm warns when using it (instead of making people think they use an uptodate version).

**Comment by nex3** [comment]
Done!
