### ISSUE TITLE
what is the current version of Dart Sass?

### ISSUE THREAD

**Issue by khaitawng** [sass/dart-sass#648]
hello,
please share me the current version of dart-sass.
**I got Sass 3.4.22 (Selective Steve). is that right?**

Thank you

**Comment by apfelbox** [comment]
Hi, did you take a look at the releases page? https://github.com/sass/dart-sass/releases

It seems however that you are using (Ruby) Sass / libsass.

**Comment by khaitawng** [comment]
> Hi, did you take a look at the releases page? https://github.com/sass/dart-sass/releases
> 
> It seems however that you are using (Ruby) Sass / libsass.

yes, checked that is Dart Sass 1.18.0 and I have installed dart sass and version is Sass 3.4.22 (Selective Steve). removed Ruby Sass already...

**Comment by nex3** [comment]
The current version of Dart Sass is 1.18.0. This is always listed on [the Sass website](https://sass-lang.com/), as well as the releases page (as @apfelbox pointed out).

3.4.22 is a Ruby Sass version. If you're still seeing it, you haven't removed Ruby Sass entirely yet.

**Comment by khaitawng** [comment]
> The current version of Dart Sass is 1.18.0. This is always listed on [the Sass website](https://sass-lang.com/), as well as the releases page (as @apfelbox pointed out).
> 
> 3.4.22 is a Ruby Sass version. If you're still seeing it, you haven't removed Ruby Sass entirely yet.

Thank you
