### ISSUE TITLE
Releases page is missing a macOS build for 1.20.0

### ISSUE THREAD

**Issue by chdiza** [sass/dart-sass#665]
The releases page of this repo has no macOS builds for 1.20.0.  Is this intentional?  If so, I'm not clear on how to install this new version of dart-sass on my macOS machines.

**Comment by chdiza** [comment]
I see that I could use `brew` to do it, but I prefer the pre-built macOS binaries.

**Comment by nex3** [comment]
Sorry for the hassle! We're updating our deployment infrastructure, and it's caused some hiccups that we're working on fixing.
