### ISSUE TITLE
Error: Getter not found 'sealed'

### ISSUE THREAD

**Issue by ZhangXector** [sass/dart-sass#671]
Today after pulling latest from dart-sass for the first time in a while, I can't get any sass to compile. When I try to even call into dart-sass to get a version (let alone doing an actual sass compile) I get the following errors on multiple files:
```
lib/src/visitor/serialize.dart:1144:2: Error: Getter not found: 'sealed'.
@sealed
 ^^^^^^
lib/src/visitor/serialize.dart:1144:2: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
@sealed
 ^
```
Here's the command I'm running:
`dart bin/sass.dart --version`
(from inside the sass directory)

I'm running Ubuntu (Budgie) 18.04, Dart 2.2.0 (latest from apt), cloned repo to pull latest dart-sass.

I started checking out previous commits and found that (149bf85) is where the issue starts for me. If I check out the previous commit, I no longer get this error. I tried searching this everywhere and can't find any other info about it. Is anyone else seeing this? I'd appreciate anyone who could shed some light on this issue. I'll try to provide any other info needed, and I apologize if it's something dumb I'm doing, but I'd love to get dart-sass updated to latest. Thank you!

**Comment by srawlins** [comment]
`sealed` comes from the [meta](https://pub.dev/packages/meta) package. dart-sass depends on 1.1.7, which is the latest, so this should be fine. You've run `pub get`?  What version of `meta` is listed in the `pubspec.lock` file after running `pub get`?

**Comment by ZhangXector** [comment]
Yep, I realized the error of my ways probably just as you were writing your response. I went back to the README to look at the steps for installation. Totally forgot about the `pub get` command. Works like a charm now! At least if someone else forgets like me, maybe a search will point them here. Thanks!
