### ISSUE TITLE
Nested Interpolated Pseudo-elements

### ISSUE THREAD

**Issue by flaviusmihaiu** [sass/dart-sass#677]
I am having some issues where nested interpolated pseudo-elements have a space between the parent and child selector. This takes place with all pseudo-elements except the first one in the list.

SCSS
```
$input-search: (
  "[type='search']"
);

$input-search-clear: (
  "::-webkit-search-cancel-button",
  "::ms-clear"
);

#{$input-search} {
    display: block;

    &#{$input-search-clear} {
        display: none;
    }
}
```

CSS
```
[type=search] {
  display: block;
}
[type=search]::-webkit-search-cancel-button, [type=search] ::ms-clear {
  display: none;
}
```

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.

**Comment by flaviusmihaiu** [comment]
I posted this here as I wasn't sure whether this was an error on my end or the way the code is compiled as theoretically I should be outputting without the space between the element and pseudo element. But thanks.
