### ISSUE TITLE
chocolatey - Can't update dart from 2.2.0 to 2.3.0 because of sass

### ISSUE THREAD

**Issue by 8lall0** [sass/dart-sass#678]
The choco package manager says that it's "unable to find a version of 'sass' that is compatible with 'dart-sdk 2.3.0'.

**Comment by nex3** [comment]
Unfortunately, due to https://github.com/dart-lang/sdk/issues/27596 Dart Sass must be run with exactly the same version of the Dart SDK that it was built with. Please be patient while we work on releasing a new version that uses Dart 2.3.0.
