### ISSUE TITLE
undefined variable in comments?

### ISSUE THREAD

**Issue by Daijobou** [sass/dart-sass#698]
I have used sass command line with ruby-sass (deprecated) and testing now dart-sass (1.20.2).

I get a error with "undefined veriable" for a comment. That complete old function is comment out:
```
/*
@mixin border-radius($value) {
	//-moz-border-radius: #{$value}px;
	//-webkit-border-radius: #{$value}px;
	border-radius: #{$value}px;
}
*/
```
And I get for line
`//-moz-border-radius: #{$value}px;`
`Error: Undefined variable.` for **$value**

Why dart-sass check syntax in comments?

**Comment by nex3** [comment]
Multi-line comments emitted to CSS, so they're allowed to contain interpolation in case you want to dynamically generate the contents of the comment. See [the documentation](https://sass-lang.com/documentation/syntax/comments) for details.

**Comment by Daijobou** [comment]
@nex3 
Thanks for share this information. You see the beginning of line is `//`, so this line is a silent comment and should not parse?
> silent comments written with // are never emitted as CSS
