### ISSUE TITLE
`includePaths` doesn't work inside of `data` template string.

### ISSUE THREAD

**Issue by syntacticsolutions** [sass/dart-sass#703]
I'm getting an error when trying to use the official sass module in place of node-sass. I'm not able to use my `includePaths` in my `data` template like I was able to in node-sass. When I run unit tests, I get the following error:

```shell     
  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  
                          ^
        Can't find stylesheet to import.
    ╷
  2 │                     @import 'test';
    │                             ^^^^^^^^^^^^^^^^^
```

Here is a link to the repo:

https://github.com/syntacticsolutions/sass-test

Here is how to reproduce:

0. `$ git clone https://github.com/syntacticsolutions/sass-test`
0. `$ cd sass-test`
0. `$ npm i`
0. `$ npm run test:unit`

Here is my loader config: 
``` javascript
{
    sass: {
        implementation: require('sass'),
        includePaths: ['./src/assets/css'],
        data: ` @import 'test';`
    }
}
```

**Comment by nex3** [comment]
I can't reproduce this using the raw Sass API:

```js
var sass = require("sass");

var result = sass.renderSync({
  data: "@import 'test'",
  includePaths: ['src/assets/css']
});

console.log(result.css.toString());
```

so it looks like the problem has something to do with [sass-loader](https://github.com/webpack-contrib/sass-loader). I suggest you open an issue in that repo.

**Comment by lujunpeng** [comment]
I also encountered the same problem, but there is no problem with node-sass.

**Comment by nex3** [comment]
@lujunpeng Can you provide a minimal reproduction using only the Sass API?

**Comment by lujunpeng** [comment]
> @lujunpeng你能使用Sass API提供最小的复制吗？

I can't provide.Only when the test will report an error, the development is normal.
