### ISSUE TITLE
no syntax check?

### ISSUE THREAD

**Issue by Daijobou** [sass/dart-sass#707]
I can write in version 1.20.2
```
.myclass {
	command: value;
}
```
or
```
.myclass {
	command: #XXXXXXXXXXXX;
}
```
Thats all "compiled" without errors.

**Comment by nex3** [comment]
Both of these are valid CSS syntax. Beyond that, Sass doesn't do any verification that the property value is valid for the given property name, because that would require a huge amount of work to stay up-to-date with the latest CSS specifications. I suggest using a linter for that.
