### ISSUE TITLE
Prefix functions

### ISSUE THREAD

**Issue by stevenvachon** [sass/dart-sass#71]
`sass-darken()` instead of `darken()`. This was supposed to make it into Sass v4, but it'd be awesome to get it in here asap.

See [sass#2078](https://github.com/sass/sass/issues/2078) for more information.

**Comment by nex3** [comment]
There are no plans to add a `sass-` prefix to these functions. We will add some sort of namespacing in Sass 4, but the design for that isn't finished and we aren't ready to start implementing it.
