### ISSUE TITLE
CLI no --check flag?

### ISSUE THREAD

**Issue by DrawnWren** [sass/dart-sass#717]
I'm trying to migrate [flycheck](https://github.com/flycheck/flycheck) from ruby-sass to dart-sass. It currently calls sass --check on file save in order to lint a file. Is there no similar output-less option for dart-sass?

**Comment by nex3** [comment]
I recommend using [stylelint-scss](https://www.npmjs.com/package/stylelint-scss) for linting. It provides a much deeper set of feedback than a Sass tool is able to.
