### ISSUE TITLE
Ember sass implementation build issue after 1.22.2 update

### ISSUE THREAD

**Issue by jsthoufeeqahamed** [sass/dart-sass#748]
After this update 1.22.2, we are facing the below issue in ember-cli-sass

Could not find the default SASS implementation. Run the default blueprint:
   `ember g ember-cli-sass`
Or install an implementation such as "node-sass" and add an implementation option. For example:
   `sassOptions: {implementation: require("node-sass")}`
Error: Could not find the default SASS implementation. Run the default blueprint:
   `ember g ember-cli-sass`
Or install an implementation such as "node-sass" and add an implementation option. For example:
   `sassOptions: {implementation: require("node-sass")}`

**Comment by nex3** [comment]
Are you sure this is an issue with Dart Sass 1.22.2? Have you verified that it *does* work if you manually install an older version of Dart Sass?

**Comment by jsthoufeeqahamed** [comment]
Yes, I manually downgraded the version of sass to 1.22.1 and I was able to solve the issue.

**Comment by nex3** [comment]
Can you provide step-by-step instructions to reproduce this from scratch?

**Comment by jsthoufeeqahamed** [comment]
I have **ember-cli-sass": "^7.0.0**  in my package.json which downloads "sass". The earlier version of 1.22.1 dint give me any errors when I give ember s, but with this update ember s/ember build throws an error with the implementation of node-sass.

Should I be amending any of ember modules to accommodate this update?

**Comment by nex3** [comment]
I really need step-by-step instructions, starting from having nothing but `npm` installed, that will reproduce this. I'm not familiar with Ember, so I can't just pop this into an existing project.

**Comment by konart** [comment]
I can confirm that there is an error with versions above 1.22.1 (at least the latest one)
```SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/safecrow-ng/20190712172804/node_modules/sass/sass.dart.js:72:17)```

**Comment by konart** [comment]
As an additional info:
this fails on Debian 3.16.36-1+deb8u2, but works on my macOS. node_modules are the same though. npm -v is 6.10.1 on both machines.

**Comment by nex3** [comment]
@konart It looks like you're experiencing a problem with [`chokidar`](https://github.com/paulmillr/chokidar). I recommend filing an issue there.
