### ISSUE TITLE
Selector function error reporting a little inconsistent?

### ISSUE THREAD

**Issue by mgreter** [sass/dart-sass#773]
Given `selector-append("foo", null)`
It reports: `Error: null is not a ...`
Previously it was `Error: $selectors: null is not a ...`

Other errors, as for `selector-append()`
Always report `Error: $selectors: At least one ...`

Might be an oversight that the variable name
is not included in those error messages?

**Comment by nex3** [comment]
The difference is that `selector-append()` takes a variable-length argument list. Including the name of that argument list doesn't really make it any clearer which argument caused the problem, so it's omitted.
