### ISSUE TITLE
Incorrect number of passed args in some errors

### ISSUE THREAD

**Issue by mgreter** [sass/dart-sass#776]
Given: `a {b: join(c, d, comma, true, false, $invalid: true)}`
Reports: `Only 4 arguments allowed, but 5 were passed.`

Upcoming LibSass: `Only 4 arguments allowed, but 6 were passed.`

IMO it's correct that six arguments are passed.
But I somewhat see why dart-sass only reports five.
Might be an oversight or was this intended?

**Comment by nex3** [comment]
I'll update this message to clarify that what matters is the number of *positional* arguments.
