### ISSUE TITLE
Multiline string

### ISSUE THREAD

**Issue by pawelkondraciuk** [sass/dart-sass#783]
Multiline strings does not work with dart-sass while working in other implementations.

*Reproduction*
Go to https://www.sassmeister.com/ and select dart-sass from options
```sass
@mixin mymixin (
  $selector: null
) {

  #{$selector} {
    &::after,
    &::before {
      width: 50%;
    }
  }
}

.my-item {
  @include mymixin(
    '.first-selector ~ &,
    .second-selector ~ &'
  );
}
```

**Comment by nex3** [comment]
Dart Sass is correct here. This multi-line string syntax was deprecated in Ruby Sass, and should be deprecated in LibSass (https://github.com/sass/libsass/issues/2841). Sass should follow [CSS's syntax for strings](https://drafts.csswg.org/css-syntax-3/#string-token-diagram), which doesn't allow raw newlines.

You can stretch a string across multiple lines by writing a `\` before the newline:

```scss
.my-item {
  @include mymixin(
    '.first-selector ~ &,\
    .second-selector ~ &'
  );
}
```

or by using `+` to concatenate multiple strings:

```scss
.my-item {
  @include mymixin(
    '.first-selector ~ &,' +
    '.second-selector ~ &'
  );
}
```
