### ISSUE TITLE
@import url starting with tilde doesn't pass through importer

### ISSUE THREAD

**Issue by 7studio** [sass/dart-sass#786]
Hi,

I encounter an issue with dart-sass and importer option from JavaScript API. 
When the url of `@import` rule starts with a tilde like `~normalize.css`, the url doesn't pass through importer.

I use Dart Sass compiler (sass@1.22.5) via gulp-sass (v4.0.2) and I don't have this issue when I switch to Node Sass (node-sass@4.12.0) compiler :/

Have I missed something  or is it a bug?

My issue is similar to the #574 but not exactly the same problem. 

Thank you for your answer.

**Comment by nex3** [comment]
Can you provide instructions to reproduce your issue with as few external dependencies as possible?

**Comment by 7studio** [comment]
Sure, this is the instruction to reproduce the issue:

1. install dependencies: `npm i gulp gulp-sass fibers sass --save-dev`
2. create `.scss` file:
    ```scss
    @import "abstracts/**/*.scss";
    @import "~normalize.css";
    @import "variables";
    @import "http://fonts.googleapis.com/css?family=Droid+Sans";
    ```
2. create `gulpfile.js`:
    ```js
    const { src, dest } = require('gulp');
    const Fiber = require('fibers');
    const sass = require('gulp-sass');

    //sass.compiler = require('sass');

    exports.default = function() {
      return src('input.scss')
        .pipe(sass({
            fiber: Fiber,
            importer: (url, prev, done) => {
                console.log(url);
                return { contents: `.TestJsApiImporter{content:"${url}"}` };
            },
        })
        .on('error', sass.logError))
        .pipe(dest('.'));
    }
    ```
4. run `gulp`

With Node Sass (default compiler with `gulp-sass`), all `@import` rules are logged and printed into `input.css` file. 

On the contrary, if you uncomment the line `sass.compiler = require('sass')`, the Dart Sass compiler logs only `abstracts/**/*.scss` and `variables`.

I hope that will help you to fix the issue or explain to me this behaviour :)

**Comment by nex3** [comment]
The difference you're seeing isn't because of the leading tilde, it's because `~normalize.css` ends in `.css`, which tells Sass to treat it as a plain CSS import (see [the Sass documentation](https://sass-lang.com/documentation/at-rules/import#plain-css-imports) for details). Node Sass is behaving incorrectly here by treating those imports as Sass imports and passing them to the importer (see https://github.com/sass/libsass/issues/2957).
