### ISSUE TITLE
Support inline-font-files?

### ISSUE THREAD

**Issue by gabrielmaldi** [sass/dart-sass#80]
This is a question/feature request.

Since Compass doesn't work with dart-sass, what would the recommended way to get fonts inlined be?
Is providing something like Compass' [inline-font-files](http://compass-style.org/reference/compass/helpers/inline-data/#inline-font-files) helper out of scope for dart-sass?
Our current build processes and git merge-drivers rely on running a single command to compile Sass, so it would be nice to be able to switch to dart-sass without having to introduce another step that inlines the fonts.

Thanks!

**Comment by nex3** [comment]
This is out of scope for the core language implementation. That's the sort of thing that should be defined as an extension function.

**Comment by gabrielmaldi** [comment]
I supposed. Is there something I can read about how to define an extension function? Or some pointers to code files and I'll try to figure it out by myself. Thanks!

**Comment by nex3** [comment]
Dart Sass doesn't support extension functions yet. #10 is tracking custom function support when compiled to JS, and I've just filed #82 to track support for them in the Dart API.
