### ISSUE TITLE
1.23.0-module.beta.1 was mistakenly released under the `latest` dist-tag

### ISSUE THREAD

**Issue by sodatea** [sass/dart-sass#818]
```
ζ npm view sass@latest version
1.23.0-module.beta.1
```

If users install dart sass via `npm install sass` and use it along with sass-loader, sass-loader's version check will fail.
https://github.com/webpack-contrib/sass-loader/blob/aa9b53b4d1c14117c4ca114a13cecb6e53b4e87a/src/getSassImplementation.js#L28-L31

**Comment by nex3** [comment]
I want to fix this, but `npm dist-tag` is giving me bogus 401 error codes. I've reached out to npm support about it.

As an aside, it's baffling to me that this is the default behavior for publishing a pre-release version of a package.

**Comment by robertIsaac** [comment]
@nex3 any update regarding this?

**Comment by nex3** [comment]
I haven't heard back from npm support about the `npm dist-tag` issue.

**Comment by vladimiry** [comment]
The half-measure: `npm deprecate sass@v1.23.0-module.beta.1 "incorrect publishing channel"`

**Comment by nex3** [comment]
Well, I don't want it to be deprecated; it's definitely a valid person I want people to be able to use. I think this will be solved when we release the next stable version, which should be soon.

**Comment by vladimiry** [comment]
Deprecation doesn't prevent someone to use the version but it would be a clear indication that there is something wrong with the version.

**Comment by robertIsaac** [comment]
> Well, I don't want it to be deprecated; it's definitely a valid person I want people to be able to use. I think this will be solved when we release the next stable version, which should be soon.

you should deprecate this version
release it again with a new versionand the correct tag (beta)

**Comment by nex3** [comment]
Why would deprecating it be better than releasing a new stable version that will take the `latest` tag?

**Comment by robertIsaac** [comment]
the time
if you will release a new stable version now then it would be perfect
but till you do so a lot of people would use a beta version as it's stable

**Comment by nex3** [comment]
It's no faster to release a new version of the beta than it is to release a new version of the stable release.

**Comment by robertIsaac** [comment]
> It's no faster to release a new version of the beta than it is to release a new version of the stable release.

i meant to release the old version again
i mean checkout the commit that was released and just build run the npm publish command

**Comment by nex3** [comment]
I'm pretty sure npm forbids re-releasing a version that's already been uploaded.

**Comment by nex3** [comment]
Once we have to bump the package version, it's not trivial to release a new version.

**Comment by robertIsaac** [comment]
> Once we have to bump the package version, it's not trivial to release a new version.

if you can explain why maybe someone can help

**Comment by nex3** [comment]
You'll either have to look at our deployment infrastructure, or just take my word for it.

Anyway, we're in the process of [releasing a new stable version](https://travis-ci.org/sass/dart-sass/builds/583850301) right now, so this is a moot point.

**Comment by robertIsaac** [comment]
> You'll either have to look at our deployment infrastructure, or just take my word for it.
> 
> Anyway, we're in the process of [releasing a new stable version](https://travis-ci.org/sass/dart-sass/builds/583850301) right now, so this is a moot point.

okay i will take your word

sorry for bothering you

**Comment by nex3** [comment]
1.22.12 has been released, so I'm closing this out.
