### ISSUE TITLE
resolve-url-loader fails with dart-sass

### ISSUE THREAD

**Issue by thasmo** [sass/dart-sass#819]
It seems that `dart-sass` behaves differently in a way which results in `resolve-url-loader` to not work properly, as mentioned in bholloway/resolve-url-loader#122. I was wondering if someone here has an idea on why this would happen.

Thanks a lot!

**Comment by nex3** [comment]
I'm not very familiar with the internals of webpack loaders. What's different about how Dart Sass is implementing [the Sass JS API](https://sass-lang.com/documentation/js-api) that's the root cause of this incompatibility?

**Comment by thasmo** [comment]
This issue has been fixed somewhere upstream as mentioned in bholloway/resolve-url-loader#122. 👍
