### ISSUE TITLE
Comments directly under selectors break output.

### ISSUE THREAD

**Issue by davetheknave** [sass/dart-sass#829]
I am using dart-sass 1.22.12 windows-x64.

When I have a comment directly under a selector, like so:

```
input
/*whatever*/
  color: red
```

The output will often omit the selector or produce garbage next to the properties. It seems like it doesn't like it when the comment isn't indented in the same way as its properties, since it behaves differently depending on whether it's indented more or less than the properties.

**Comment by nex3** [comment]
This is expected. In the indented syntax, comments are indented syntactic nodes just like everything else. Anything indented beneath a comment is considered part of that comment. Note that Ruby Sass has the same behavior here.
