### ISSUE TITLE
"# sourceMappingURL" comments takes precedence over SourceMap response headers

### ISSUE THREAD

**Issue by jprogramer** [sass/dart-sass#847]
Hi there!
I'm using sass in a JSF project and the CSS resources are not served using simple paths
At the same time, the server is serving the correct SourceMap response headers but the browser keeps following the paths in the comments instead
That's why I think that it would be helpful to have an additional possibility for the
`--source-map-urls` arg like this `--source-map-urls=none` that will cause the map files to get generated normally but without appending the corresponding path comment to the css file

**Comment by nex3** [comment]
The `--source-map-urls` comment specifically refers to the means by which the source map refers to the source file, *not* the reverse (which is what `sourceMappingURL` is for). I recommend doing a simple post-processing step, such as `sed 's~/\*#.*~~'`, if you want to remove the source map comment from the CSS file.

**Comment by jprogramer** [comment]
sure, but honestly I was hoping for an `embedded` post-processing -_-
