### ISSUE TITLE
sass.dart.js is polluting the Object constructor

### ISSUE THREAD

**Issue by jas7457** [sass/dart-sass#851]
The compiled sass.dart.js file ends up setting a value (namely, an empty object) on `Object["___dart_isolate_tags_"]`. You should never put anything on any prototypes or directly on any constructors and this causing issues with another package that I am using (`object-hash`).

Here is the code in question:
```
var tableProperty = "___dart_isolate_tags_";
var usedProperties = Object[tableProperty] || (Object[tableProperty] = Object.create( null ));
```

You can test this is a problem by:
```
var obj = {};
console.log( obj.constructor.a ); // undefined
Object['a'] = 'a'
console.log( obj.constructor.a ); // "a"
```

**Comment by nex3** [comment]
We don't control the details of the JS output that Dart produces; please file an issue against [dart-lang/sdk](/dart-lang/sdk).
