### ISSUE TITLE
--watch infinite loop

### ISSUE THREAD

**Issue by Sliverside** [sass/dart-sass#853]
hi,
i update my sass version to "1.23.0 compiled with dart2js 2.5.1" recently and my command for watch my files as un unexpected behavior.

the problem come from this : [Fix a bug where changes in .css files would be ignored in --watch mode.](https://github.com/sass/dart-sass/blob/master/CHANGELOG.md#command-line-interface)

The problem happend when the input folder and the outpout folder are the same.
When my files *.scss are compiled that create files like *.css then sass detect these new files and watch it so it's creating an infinite loop.

My command is : sass --watch .:.

my solutions are : 
- create a command with all my files (exemple : sass --watch style.scss:style.css colors.scss:color.css anything.scss:anything.css ...) but it's not efficient
- outpout my files in a diferent folder (exemple : sass --watch stylesheets:public/stylesheets) but it's changing my workflow

the changes that can be made :
- Adding the suport of globs, this is already an issue : #616
- Adding the possibility to ignore patterns (exemple : sass --watch --ignore *.css .:.)

Thank you for your time !
Sorry for my english.

**Comment by nex3** [comment]
We should just avoid treating CSS files as entrypoints when their outputs would be the same as their inputs.
