### ISSUE TITLE
Render function: Allow `file` and `data` config at the same time 

### ISSUE THREAD

**Issue by garthenweb** [sass/dart-sass#864]
I am testing the Parcel v2 beta currently, and therefore switched form node-sass to dart-sass.
To make my project compile, I need to include certain files for variables in all sass files.

I define a global config in a `.sassrc.js` where `data` with some variables is defined, Parcel merges `data` and `file` into the same config file which is passed to the render function of dart-sass.

See https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/sass/src/SassTransformer.js#L35 and https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/sass/src/SassTransformer.js#L72 for more information.

As dart-sass in this case prefers the `data` key and ignores `file`, all my css files are empty.

**Would it be possible to make dart-sass compatible to the node-sass behaviour and except both `file` and `data` config at the same time?**

I found this code which looks related to this: https://github.com/sass/dart-sass/blob/48c284b4ef22fa834cc56e40c193182146f76199/lib/src/node.dart#L97

I also implemented a small test case to ensure it is not related to parcel:

```sass
// /path/index.scss
.file { width: 100%; }
```

``` js
const render = require('sass').renderSync // using version 1.23.1

console.log(
  render({
    data: '.data { width: 100% }',
    file: '/path/index.scss',
    includePaths: ['node_modules'],
  }).css.toString(),
)
```

Output is

```css
.data {
  width: 100%;
}
```

Expected
```css 
.data {
  width: 100%;
}
.file {
  width: 100%; 
}
```

**Comment by nex3** [comment]
We'll implement this for now because we're committed to Node Sass compatibility, but I will warn you that we are planning to define a new JS API for both which will be much stricter about passing inputs which don't have clear behavior, such as this.

**Comment by nex3** [comment]
According to my tests, Dart Sass behaves the same way that Node Sass does here. In [this test repo](https://gist.github.com/nex3/e7deadba69d139013712d87262d0bcc1), running

```shellsession
$ npm install
$ node test.js
```

produces:

```css
.data {
  width: 100%; }
```

**Comment by garthenweb** [comment]
@nex3 I had another look into this and you are completely right, this is something which parcel was doing under the hood which I did not expect. Sorry for my wrong assumption and thank you for having a look into this!
