### ISSUE TITLE
placeholders not building as expected in dart-sass

### ISSUE THREAD

**Issue by MansoorBashaBellary** [sass/dart-sass#866]
I have a placeholder as below:

```
%button-common {
  color: black;
  background-color: white;
}
```

And i have my SCSS file as below:

```
.btn {
  &,
  &.btn-common {
    @extend %button-common;
  }
}
```

On building above SCSS file, i am getting below output:

```
.btn {
  color: black;
  background-color: white;
}
```

What i am expecting to be in output:

```
.btn,
.btn.btn-common {
  color: black;
  background-color: white;
}
```

Above thing was building fine in `node-sass`. On migrating to `dart-sass`, getting this weird issue.

Can someone please help me on this issue.

**Comment by nex3** [comment]
I can't reproduce this:

```shellsession
$ cat > test.scss
%button-common {x: y}

.btn {
  &,
  &.btn-common {
    @extend %button-common;
  }
}
$ sass --version
1.23.2
$ sass test.scss
.btn, .btn.btn-common {
  x: y;
}
```

**Comment by MansoorBashaBellary** [comment]
@nex3 - Thanks for quick turn around. Here is the info:

### Steps to reproduce:

1. Checkout the repo: https://github.com/MansoorBashaBellary/dart-sass-module-test
2. Do `yarn`, `yarn build`
3. Go to: `dist/main.css` file. It only has below styles:

```
.btn {
  position:relative;
  display:inline-block
  vertical-align:middle
}
```

Where as my `src/components/styles/default.scss` file has:

```
.btn {
  &,
  &.btn-submit {
    @extend %btn-common;
  }
}
```

**Comment by nex3** [comment]
It looks like this bug is triggered when the extendee is in a different module than the extender. Here's a minimal repro:

```scss
@use 'other';
.a, .a.b {@extend %c}
```

```scss
// _other.scss
%c {d: e}
```
