### ISSUE TITLE
Dashes are not considered a valid selector for selector-append

### ISSUE THREAD

**Issue by Anthony-Gaudino** [sass/dart-sass#896]
This `$var: selector-append('--', ".test");` gives the following error on `dart-sass`:
```
Error: expected selector.
  ╷
1 │ --
  │ ^
  ╵
  - 1:1  root stylesheet
  ╷
1 │ $var: selector-append('--', ".test");
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 1:7  root stylesheet on line 1 at column 7
```

The same code works fine with `LibSASS`.

This can be tested on https://www.sassmeister.com/, using the `Sass v3.5.6` option on sassmeister it also gives an error:

```
$selectors: "--" is not a valid selector: Invalid CSS after "": expected selector, was "--" for `selector-append'
```

**Comment by jathak** [comment]
This bug was fixed in #816 (released in 1.22.12). SassMeister is currently using 1.18.0, so that's why this is still broken there. Upgrading to the latest version should fix this.
