### ISSUE TITLE
Importing variables from JSON file with Webpack

### ISSUE THREAD

**Issue by ObsydianBlackKnight** [sass/dart-sass#900]
Hello,

I started using SASS today. I'm using it with Webpack and `sass-loader`.

Initially I installed `node-sass`, then I needed to import a file from another one, and decided to switch to `sass` (dart sass) after learning that `@import` is deprecated in favor of `@use` and that the latter is not available in `node-sass`.

I need to use data stored in a JSON object from SASS, to automatically generate some classes based on some JSON properties.

I couldn't find a way to import a JSON file from SASS though, and all the information I'm running into talks about `node-sass` only.

How can I achieve what I need?

I'm also open to hacks and tricks... Like writing a script that reads in the JSON file and outputs SASS code. I just couldn't find a way to do anything of the sort in a clean way with Webpack.

**Comment by jathak** [comment]
Is [this](https://github.com/pmowrer/node-sass-json-importer) the package you were using to import JSON in Node Sass? Dart Sass compiled to JS uses the same importer API as Node Sass, so it should just work (despite the package name) if you set `sass-loader`'s implementation to be Dart Sass. If it doesn't work, that's a bug in either the importer or `sass-loader`, so you should file an issue there instead.
