### ISSUE TITLE
Variable declaration problems

### ISSUE THREAD

**Issue by aschoelling** [sass/dart-sass#916]
Either my brain or the way variables are used seems to be non-functional. Given are the following, simple files:

a.scss containing 2 lines:
```
    @use "b";
    @use "c";
```

_b.scss with only 1 line:
`    $i: 1;
`
and finally _c.scss with only 1 line, too:
`    @debug $i;`

running sass a.scss gives the following error message (using dart-sass 1.24.0):

```
Error: Undefined variable.
  ╷
1 │ @debug $i;
  │        ^^
  ╵
  _c.scss 1:8  @use
  a.scss 2:1   root stylesheet
```

Declaring the variable inside the same file that uses it works, but @use inside _c.scss didn't work either.

I'm lost at this point, any ideas?

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
