### ISSUE TITLE
sourceMap issue with custom importers

### ISSUE THREAD

**Issue by wassim-k** [sass/dart-sass#922]
I've come across a peculiar issue while using source maps with a custom importer.

When running the following code, I get the this error:
> Error: PathException: Unable to find a path to "./vars.json" from "file:///d:/Code/sass-test"

```javascript
const sass = require('sass');
const fs = require('fs');

// set this flag to false to produce issue
const works = false;

const rendered = sass.renderSync({
    sourceMap: works ? true : `${process.cwd()}\\sass.map`,
    outFile: 'out.css',
    file: './test.scss',
    importer: (url) => url.endsWith('.json')
        ? {
            contents: Object.entries(JSON.parse(fs.readFileSync(url, 'utf-8')))
                .map(([name, value]) => `$${name}: ${value}`)
                .join('\n')
        }
        : null
});

const { css, map, stats } = rendered;
console.log(JSON.stringify({ css: `${css}`, map: `${map}`, stats }, undefined, 4));
```

_test.scss_
```scss
@import './vars.json';

body {
    color: $var;
}
```

_vars.json_
```json
{
    "var": "red"
}
```

Notes: 
* The error does not occur and the source maps are produced correctly if `sourceMap: true` option is used instead of `sourceMap: {string}`
* Unfortunately, I don't have much control over the options passed to sass since I'm defining my importer through webpack's `sass-loader`, which sets the following options:
```javascript
{
    sourceMap: path.join(process.cwd(), '/sass.map'),
    sourceMapRoot: process.cwd(),
    omitSourceMapUrl: true,
    sourceMapContents: true
}
```

**Comment by nex3** [comment]
It looks like this also only reproduces when `sourceMap` is absolute rather than relative. Here's a minimal reproduction:

```js
const sass = require('./build/npm/sass.dart');

sass.renderSync({
    sourceMap: `${process.cwd()}/sass.map`,
    data: "@import 'other';",
    importer: (url) => ({contents: 'x {y: z}'})
});
```
