### ISSUE TITLE
sass@1.25.1-test.1 version is marked as latest

### ISSUE THREAD

**Issue by crobinson42** [sass/dart-sass#943]
I ran `npm update` and saw this latest version is some "test" version that's published under the `latest` tag for npm? Could this be fixed and the effort that's going on for `1.25.1-test.1` be moved to a beta tag or something?

![image](https://user-images.githubusercontent.com/5973579/73202842-c3d3fc80-40f0-11ea-8de1-13cee3347d19.png)

**Comment by mashpie** [comment]
plus: a fresh `install` with `sass-loader` (ie. `vue create some-client`) raises build errors, ie.:

```sh
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Dart Sass version 1.25.1-test.1 is incompatible with ^1.3.0.
```

resolvable by manual install of `sass@1.25.0`

**Comment by nex3** [comment]
Fixed. npm's insistence on treating semantic versioning pre-releases like normal versions by default for the purpose of dist-tags never ceases to frustrate me.

**Comment by esynaps** [comment]
Still the same problem
```
$ yarn add sass
yarn add v1.19.1
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check.
 Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning " > vuetify-loader@1.4.3" has unmet peer dependency "webpack@^4.0.0".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0
.0".
warning " > vue-loader@15.9.0" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.0" has unmet peer dependency "webpack@^3.0.0 || ^4.1
.0 || ^5.0.0-0".
[4/4] Building fresh packages...

success Saved lockfile.
warning No license field
success Saved 2 new dependencies.
info Direct dependencies
└─ sass@1.25.1-test.1
info All dependencies
├─ picomatch@2.2.1
└─ sass@1.25.1-test.1
Done in 14.35s.

```

**Comment by esynaps** [comment]
I try again after executing `yarn cache clean`
This does not correct the problem

**Comment by nex3** [comment]
I think that's a bug on your end. npm shows 1.25.0 as the latest published version: https://www.npmjs.com/package/sass

**Comment by esynaps** [comment]
I agree. Until this bug disappears, manual install is still required

**Comment by mashpie** [comment]
@esynaps maybe check your yarn.lock. Maybe `1.25.1-test.1` is marked to resolve your requirements. 

A fresh install in an empty repo correctly installs latest stable:

```sh
$ yarn init -y .
yarn init v1.21.1
# [...]
success Saved package.json

$ yarn add sass
yarn add v1.21.1
info No lockfile found.
# [...] 
success Saved lockfile.
success Saved 16 new dependencies.
# [...] 
info Direct dependencies
└─ sass@1.25.0

$ yarn list sass
yarn list v1.21.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ sass@1.25.0
```

**Comment by esynaps** [comment]
Same problem in an empty folder on my side. Weird ....

![image](https://user-images.githubusercontent.com/30432290/74916022-68cab800-53c5-11ea-8518-29a969d34db2.png)

**Comment by mashpie** [comment]
One idea left: yarn version? Maybe issues with semver resolution. So maybe npm  or upgraded yarn leads to different results... sry getting out of topic for `sass`.

**Comment by esynaps** [comment]
I tried with the latest version of yarn

![image](https://user-images.githubusercontent.com/30432290/74924540-ffea3c80-53d2-11ea-8531-39874b11f256.png)
