### ISSUE TITLE
Node Version support

### ISSUE THREAD

**Issue by duncanmapes** [sass/dart-sass#95]
I see you have the engine set to >=0.10.0.  Is that the intended support, because I am having some issues with v4.x?

**Comment by nex3** [comment]
I think I looked at which versions supported the narrow slice of Node APIs we're using. What sorts of problems are you running into?

**Comment by snowblindroan** [comment]
Compiled dart-sass uses `Buffer.from()` in a couple places, which was [backported](https://github.com/nodejs/node/blob/66f09be74399b61a433a58dfe48c6fd5b9d66594/doc/changelogs/CHANGELOG_V4.md#2016-08-15-version-450-argon-lts-thealphanerd) to v4.5.0. I think dart-sass will run with 4.5.0 but haven't tested. Anything prior to that is not compatible as far as I can tell.

**Comment by srawlins** [comment]
For what its worth, the exit code tests in `test/cli_shared.dart` under node, on Linux:

* **fail** for me with **node v0.10.24** (the processes always exit 0 instead of the intended exit code) and
* **pass** for me with **node v7.10.0**.

**Comment by nex3** [comment]
Ah, it does look like `Process.exitCode` was added in v0.11.8. I'll update the version constraint accordingly.
