### ISSUE TITLE
Options to attach output files with a .min suffix in case of --watch directory

### ISSUE THREAD

**Issue by akkumar** [sass/dart-sass#953]
So - when we use a sass watcher to watch a directory, say 

`sass ---style compressed --watch inputdir:outputdir` - assuming the inputdir contains a bunch of .scss files, the output files correctly get generated in outputdir .

All the files in outputdir get generated with .css extension ( hello.scss generates hello.css ) .

But, I would prefer it to be generated with a .min.css extension though (eg: hello.scss with --style compressed should write to hello.min.css  , say ). 

Is there any way / option to specify this to happen ? looking forward to the same.

**Comment by nex3** [comment]
Sass's command-line `--watch` command is there for convenience, but for more advanced functionality than it offers we recommend instead using a fully configurable build system with its own watcher mode, such as Webpack.
