### ISSUE TITLE
sass.cmd launches a new window 

### ISSUE THREAD

**Issue by akkumar** [sass/dart-sass#954]
For one of the plugins we have, we spawn sass watchers (in nodejs) as below

```node
     import * as child from 'child_process';
     const prc = child.spawn("node_modules/.bin/sass.cmd",  ["--watch", inputDir, outputDir], {
            cwd: "C:\Program Files\RandomFolder",
            detached: true,
            stdio: 'ignore',
            shell: false,
            windowsHide: true,
        });
        prc.undef();
```

In windows, this does launch and does everything correctly but launches a separate window / console though . 

I would wish the console does not appear but rather the sass watcher runs in the background ( as it does on linux  / similar systems ).

debugging further , came across [this issue node/issues/21825](https://github.com/nodejs/node/issues/21825) . 

Apparently (one of) the conclusions seems to be that it because of the way the cmd ( `node_modules\.bin\sass.cmd` in this case ) is written that launches the console. 

no windows expert here. 

1) can you help point in this repo / source control  to where the file `node_modules/.bin.sass.cmd` is present 

2) any windows + nodejs expert can reproduce that issue and help identify why the sass watcher launches a new window/console , ( as opposed to launching it in background silently ).

**Comment by nex3** [comment]
Unfortunately, as far as I know, creating a visible window is an inherent property of spawning a batch script on Windows. If there's any way to stop it from doing so, that way must exist within the program spawning the process (that is, Node itself) rather than within the script you're spawning.
