### ISSUE TITLE
:root selector should always go at the beginning of a selector

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#969]
Currently, it's possible for Dart Sass's unification to nest the `:root` selector beneath another selector. For example, `selector-unify(":root .c .d", ".e .f")` current returns `:root .c .e .d.f, .e :root .c .d.f`, but the latter selector cannot possibly match any elements and so should be omitted.

**Comment by chriseppstein** [comment]
This is true for [`:scope`](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) as well because it's functionally equivalent to `:root` in a css file.

Also, true for `:host()` and `:host-context()` which can only match the shadow root element of a web component.
