### ISSUE TITLE
Distribute on Homebrew

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#97]
We should distribute a snapshot via Homebrew to make it easier for Mac OS users to use Dart Sass. Ideally we'd depend on [the Dart VM's Homebrew package](https://www.dartlang.org/install/mac), which probably means that we'll have to set up our own tap.

**Comment by BenSpace48** [comment]
This would be great as the instructions aren't clear at all, for me at least.

**Comment by nex3** [comment]
@BenSpace48 Which instructions?

**Comment by BenSpace48** [comment]
@nex3 How to get Dart Sass running on OSx sorry. Mainly this bit:

> Extract it, add the directory to your path, and the dart-sass executable is ready to run!

I'm pretty sure I could manage it with some Googling but it would be good to have the instructions for that in the readme, or an easier method.

**Comment by nex3** [comment]
What specifically is unclear—extracting the file? Adding a directory to your path? Running the executable?

**Comment by BenSpace48** [comment]
Adding the directory to the path, I know it's a one line change but without researching it I don't know how to do it and I suspect quite a few others are the same. Most other instructions I've used that require it usually explain how to do it.
