### ISSUE TITLE
[Suggestion] Add option that enforces Sass modules syntax

### ISSUE THREAD

**Issue by emilio-martinez** [sass/dart-sass#972]
The following suggestion could also be implemented via linting and such; however, it seems to me like a prime candidate for implementing at a library level.

I've been progressively migrating projects away from `@import` to Sass modules. The experience has been great—and even better after I tried the Sass migration tool. However, it occurs to me that kicking the habit of the old syntax may take a bit—which brings me to my suggestion:

## Optional flag: `enforceModuleSyntax`

This flag would be disabled by default. What it would do is effectively disable the pre-module syntax, e.g., `@import`, global functions/utilities, etc. to aid in the migration to adopt the newer syntax and practices. Because I know the plan is to support the newer and older syntaxes side-by-side for a while, this would allow users to opt-in to dropping the old syntax on a project-by-project basis at their convenience, potentially increasing the readiness by the time said syntax actually is dropped.

Anyway, that's it for the suggestion. I've never contributed to the Sass project, but I'm happy to take a stab at a contribution if helpful.

Thanks for the great work!

**Comment by nex3** [comment]
I think this is a better fit for a tool outside the language itself. I recommend using [stylelint-scss](https://www.npmjs.com/package/stylelint-scss); in particular, you can use stylelint's [`at-rule-blacklist`](https://github.com/stylelint/stylelint/blob/96cfb48d3485e3bdf38bcb40ecc1ec26236baed8/lib/rules/at-rule-blacklist/README.md) rule to forbid the `@import` rule.
