### ISSUE TITLE
Allow @import starting with forward / (slash)

### ISSUE THREAD

**Issue by monkeythedev** [sass/dart-sass#974]
When using with sass-loader in NodeJS this implementations throw this error "Can't find stylesheet to import" when trying to import a file like this: 
`@import "/app/src/style/modules/myModule.scss";`

I think this is a common path when using webpack.

When trying to resolve imports, after failing all currents tries you should fallback by prepending the current context path to allow this kind of import:
**example:**
When cwd is `C:\workspaces\myworkspace`
`/app/src/style/modules/myModule.scss`
should become
`C:\workspaces\myworkspace\app\src\style\modules\myModule.scss`
Only after also this fallback fails then you should throw error.

This is pretty useful with VSCode because this will allow VSCode to follow the file path with the Go To function since it will resolve the forward slash from the workspace/folder location.

![image](https://user-images.githubusercontent.com/53383860/77718497-61f61d00-6fe3-11ea-9753-5d3867082179.png)

Thank you!

**Comment by nex3** [comment]
Sass imports are URLs, and URLs have specific well-defined semantics around what a leading forward slash means. For local filesystem paths, they're [`file:` URLs](https://en.wikipedia.org/wiki/File_URI_scheme), and a leading `/` is resolved to the root of the filesystem (below even the drive letter on Windows).
