### ISSUE TITLE
Relative symbolic link to dart-sass CLI script fails to run

### ISSUE THREAD

**Issue by RayDeCampo** [sass/dart-sass#978]
I installed the dart-sass 1.26.3 tarball on CentOS 7 and then created a link to the sass script in the same directory:

```
$ cd /opt/sass/latest/dart-sass
$ sudo ln -s sass sass.bat
```

The link fails to work correctly however, because `readlink` does not return the full path.

```
$ cd ~
$ sass.bat
/opt/sass/latest/dart-sass/sass.bat: line 17: /home/rkdecampo/dart: No such file or directory
$ readlink /opt/sass/latest/dart-sass/sass.bat
sass
```

I understand that `readlink -f` is not used because of OSX, however in this case it is needed.

As a workaround I recreated the symbolic link with the full path and that works.

```
$ cd /opt/sass/latest/dart-sass
$ sudo rm sass.bat
$ sudo ln -s /opt/sass/latest/dart-sass/sass sass.bat
```

**Comment by nex3** [comment]
Dart Sass's executables are generated by [`cli_pkg`](https://github.com/google/dart_cli_pkg). Please file an issue there.

Also, it's unlikely that we'll be able to fix this on our own. If you can provide a PR that fixes it without breaking any existing use-cases, that would be very helpful.

**Comment by nex3** [comment]
Moved to https://github.com/google/dart_cli_pkg/issues/43 which was folded into https://github.com/google/dart_cli_pkg/issues/43.
