### ISSUE TITLE
Not looking for .css files

### ISSUE THREAD

**Issue by faebeee** [sass/dart-sass#985]
Hello In the current Project, we have some issues importing css files from the node_modules folder.

The docs are stating that `sass` automatically looks for the `.css` file in a path if you omit the `.css` ending on the import statement.  That is somehow not working.

![Screenshot 2020-04-22 at 15 54 50](https://user-images.githubusercontent.com/1639604/79991151-39fabc00-84b2-11ea-8dcf-50f5db31adf7.png)
![Screenshot 2020-04-22 at 15 55 07](https://user-images.githubusercontent.com/1639604/79991155-3b2be900-84b2-11ea-9cfa-a76685afba15.png)

These are the libs we are using

    "sass": "^1.26.3",
    "node-sass-import-once": "^1.2.0",
    "node-sass-json-importer": "^4.1.4",

**Comment by nex3** [comment]
We need more information in order to help you with your problem. Can you provide a minimal reproduction that uses only Dart Sass and that reproduces your problem?

**Comment by stof** [comment]
it automatically look for the `.css` file if you omit the `.css` extension and you don't have a `.scss` or `.sass` matching that import.
