### ISSUE TITLE
Release 1.26.5 missing windows and mac builds

### ISSUE THREAD

**Issue by JakeChampion** [sass/dart-sass#994]
I noticed that the previous releases have linux, windows, and mac builds and the 1.26.5 release only has linux. Do the windows and mac builds get added at a later date? I'm using a mac machine and wanted to try out the 1.26.5 release.

Thank you for your work on this project, it is really good :-)

**Comment by Awjin** [comment]
Duplicate of https://github.com/sass/dart-sass/issues/992
