### ISSUE TITLE
--embed-sources --embed-source-map combined not working

### ISSUE THREAD

**Issue by iniatse** [sass/dart-sass#997]
`sass <source> <target> --embed-sources --embed-source-map`

is not working within Chrome Version 81.0.4044.129 (Official Build) (64-bit). Within Firefox it does work.

**Comment by Awjin** [comment]
We need more information to help diagnose your problem. How is this broken? (what behavior were you expecting that no longer works?) Is there any error output? What does your input file? Which version of Sass are you using?

**Comment by iniatse** [comment]
> How is this broken? (what behavior were you expecting that no longer works?) (what behavior were you expecting that no longer works?)

I don't know if it ever worked. I expect source maps to work. I expect that I can move to the source when clicking the scss file (which should show up) within chrome. At the moment Chrome dev tools only link to the css files i.e. source maps do not work.

I expect that the source map as well as the source is embedded which seems to be the case. 

At the moment it only works in Firefox.

> Is there any error output?

No error output

> Which version of Sass are you using?

`^1.26.5`

Note: You can easily reproduce the issue by executing the command within the opening post. Source maps then do not work in chrome.

**Comment by iniatse** [comment]
I can also upload a testrepo and a video if it is not clear enough?

**Comment by Awjin** [comment]
@iniatse I'm having trouble reproducing an issue with source maps, with Chrome 81.0.4044.129. Could you provide a minimal reproduction that demonstrates the problem?

**Comment by iniatse** [comment]
[https://github.com/iniatse/dart-sass-source-maps-test](https://github.com/iniatse/dart-sass-source-maps-test)

`npm install`
`npm run dart-sass-build`
Open `index.html`

Works in chrome.

`npm install`
`npm run node-sass-build`
Open `index.html`

Does not work chrome.

I tested a bit and I found out that source maps work for the same code within a simpler directory structure.

**Comment by Awjin** [comment]
This looks like an issue with node-sass. I would recommend filing an issue in that repo: https://github.com/sass/node-sass

**Comment by iniatse** [comment]
Oops sry it's the other way around. dart-sass is not working. I edited the post.

**Comment by Awjin** [comment]
Thanks for the clarification. I'm still unable to reproduce the bug. Since the source map works in Firefox, it appears source map generation itself is not broken in Dart Sass. This might be an issue with Chrome, which I'd encourage you to ask in the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass). We try to keep this issue tracker focused on requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
